core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala
core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala

Handle ExprOp.Include correctly when inlining $project.

---

core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala
core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala
core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala

Handle implicit _id in inlineProject.

---

admin/src/main/scala/slamdata/engine/admin/admin.scala

Status is now a separate text area which is always present at the
bottom of the view, and the plan/result is now preserved when the query
is edited.

make "compile" a separate action (Fixes #542)

---

admin/src/main/scala/slamdata/engine/admin/edit.scala
core/src/main/scala/slamdata/engine/backend.scala
core/src/main/scala/slamdata/engine/backends.scala
core/src/main/scala/slamdata/engine/evaluator.scala
core/src/main/scala/slamdata/engine/physical/mongodb/evaluator.scala
core/src/main/scala/slamdata/engine/planner.scala
core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala
web/src/test/scala/slamdata/engine/api/fs.scala

- just look for “2.6.”-anything for MongoDB for now
- and push some Mongo-specific stuff into the Evaluator implementation

check backend version (Fixes #332)

---

core/src/test/scala/slamdata/engine/physical/mongodb/evaluator.scala

This should have been part of the PR with the fix for #528, but it got
stashed and forgotten.

Add a test to make sure we generate correct $where.

---

core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala
core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala
core/src/main/scala/slamdata/engine/physical/mongodb/reshape.scala
core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala
core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala
core/src/main/scala/slamdata/engine/physical/mongodb/workflowtask.scala
core/src/test/scala/slamdata/engine/physical/mongodb/optimize.scala
core/src/test/scala/slamdata/engine/physical/mongodb/pipeline.scala
core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala
core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala
core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala
it/src/test/resources/tests/concatArray.test

* Generate real arrays (rather than docs with index keys) in results,
* eliminate Reshape.Arr, and
* merge Reshape.Doc into Reshape.

Fix array generation/usage.

---

core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala

This is the Java representation for BinData(3, ...).
Also, give a slightly more comprehensible error when a value is not matched.

handle java.util.UUID when converting back from BSON (Fixes #624)

---

core/src/main/scala/slamdata/engine/physical/mongodb/util.scala

Fix an issue that surfaced after the merge for #678.

put effectful code inside Task

---

admin/src/main/scala/slamdata/engine/admin/admin.scala
admin/src/main/scala/slamdata/engine/admin/config.scala
core/src/main/scala/slamdata/engine/config/config.scala
core/src/main/scala/slamdata/engine/physical/mongodb/collection.scala
core/src/main/scala/slamdata/engine/repl/repl.scala
core/src/test/scala/slamdata/engine/config/config.scala
example-slamengine-config.json
scripts/testJar
web/src/main/scala/slamdata/engine/api/server.scala

Unified config file lookup.

---

admin/src/main/scala/slamdata/engine/admin/config.scala
admin/src/main/scala/slamdata/engine/admin/edit.scala
core/src/main/scala/slamdata/engine/backends.scala
core/src/main/scala/slamdata/engine/config/config.scala
core/src/test/scala/slamdata/engine/config/config.scala
it/src/test/scala/slamdata/engine/backendtest.scala

Fixes #684.
Improve a few error messages to give context as to where a broken config
was being loaded from, and fix our connectionUri parsing to not leak
nulls (leading to crashes in certain cases).

Improve config file handling.

---

web/src/main/scala/slamdata/engine/api/server.scala

Bind on all interfaces (i.e. 0.0.0.0)

---

web/src/main/scala/slamdata/engine/api/fs.scala

Not just the OPTIONS method. This makes the UI work when preflight
requests don't kick in (which they don't for simple GET/POST requests).
Fixes #689

Add CORS for all responses

---

scripts/startSlamEngine

Fix detection for the running server process.
Add a second param for the content path when starting the server.

tweak scripts for Jenkins

---

core/src/main/scala/slamdata/engine/fs/filesystem.scala
core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala
it/src/test/scala/slamdata/engine/fs/filesystem.scala
web/src/main/scala/slamdata/engine/api/fs.scala

Make PUT on /data/fs idempotent.

---

core/src/main/scala/slamdata/engine/physical/mongodb/collection.scala
core/src/test/scala/slamdata/engine/physical/mongodb/collection.scala

improve error message for path with no collection name

---

README.md
web/src/main/scala/slamdata/engine/api/fs.scala

Fixes #737 and fixes #738.
Both the PUT and DELETE requests were returning incorrect statuses. Also
corrected the README to state that PUT works for new resources.
And … adds MOVE.

Improve /mount/fs API.

---

web/src/main/scala/slamdata/engine/api/fs.scala

Quick fix for @garyb after a little manual testing.

use Destination header in MOVE /mount

---

build.sbt

Upgrade MongoDB driver to 3.0.2.

---

web/src/main/scala/slamdata/engine/api/server.scala

Handle any errors when trying to check System.in.

---

core/src/main/scala/slamdata/engine/backend.scala
web/src/test/scala/slamdata/engine/api/fs.scala

un-relativize paths on the way out of Backend

---

README.md
web/src/main/scala/slamdata/engine/api/fs.scala
web/src/test/scala/slamdata/engine/api/fs.scala

Check for conflicting mounts in `PUT /mount/fs`.

---

core/src/main/scala/slamdata/engine/repl/repl.scala

Capture and report PathErrors and allow the REPL to continue to handle
commands (Fixes #810).
Fix formatting for ls (Fixes #805):
- get rid of the internal junk
- hide the leading `./` on each path
- show a trailing `/` on dirs, `@` for mounts
Fix ls to always treat its argument as a directory.
Scan only the query results needed for display.

fix error handling in the REPL, and a couple of other improvements

---

web/src/main/scala/slamdata/engine/api/server.scala

...and pick one randomly if it's in use
Fixes #765.

When starting the API server, test the requested port 

---

sbt

This fetches sbt from the new archive location.

Update sbt launcher.

---

core/src/main/scala/slamdata/engine/physical/mongodb/util.scala

reduce the MongoDB driver's serverSelectionTimeout to 5 seconds

---

core/src/main/scala/slamdata/engine/repl/repl.scala

Adds a call to `Backend#checkCompatibility` to the repl startup as well as orders this and the config path validation to happen before the prompt is displayed (prior to this, you'd get a prompt and then maybe an error).
Also handles path errors and backend initialization errors in a uniform way, so both are printed to the console.

Check backend compatibility when loading the repl 

---

.travis.yml
core/src/main/scala/slamdata/engine/backend.scala
core/src/main/scala/slamdata/engine/backends.scala
core/src/main/scala/slamdata/engine/fs/path.scala
core/src/main/scala/slamdata/engine/physical/mongodb/collection.scala
core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala
core/src/test/scala/slamdata/specs2/decorators.scala
it/src/test/scala/slamdata/engine/fs/filesystem.scala
scripts/build

Also add a `.skipped` test decorator.
SD-761 #done
Review by @mossprescott, @wemrysi.

Enable deleting dbs and clusters in MongoDB.

---

web/src/main/scala/slamdata/engine/api/fs.scala
web/src/test/scala/slamdata/engine/api/fs.scala

In order to make pieces of test infrastructure more easily usable from within other contexts. In particular, I am interested in making the test infrastructure available from within the it project in order to write tests cases for bugs.

Refactor tests in web project

---

core/src/main/scala/slamdata/engine/backend.scala
core/src/main/scala/slamdata/engine/evaluator.scala
core/src/main/scala/slamdata/engine/mounter.scala
core/src/main/scala/slamdata/engine/repl/repl.scala
web/src/main/scala/slamdata/engine/api/fs.scala
web/src/main/scala/slamdata/engine/api/server.scala
web/src/test/scala/slamdata/engine/api/fs.scala

This fixes the regression introduced in #910 where the backend isn't updated when the config changes. It also includes tests that should prevent this regression in the future.

[SD-946] Fix regression where backend not updated when config changed

---

it/src/test/scala/quasar/fs/filesystem.scala

Skip db deletion tests when we can’t create/delete dbs.

---

build.sbt
project/build.properties
project/plugins.sbt
sbt

bump sbt to 0.13.9
fix duplicate resolver warning
introduce Ammonite REPL see http://lihaoyi.github.io/Ammonite/#Ammonite-REPL

misc sbt fixes

---

scripts/build

- These were being “exported” unexpectedly and breaking the local dev environment for some users

Fix export mongoDb env variables

---

core/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala
core/src/test/scala/quasar/physical/mongodb/planner.scala
core/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala
it/src/test/resources/tests/groupByArray.test

Fix grouping by array fields in MongoDB.

---

core/src/main/scala/quasar/compiler.scala
core/src/main/scala/quasar/functions.scala
core/src/main/scala/quasar/logicalplan.scala
core/src/main/scala/quasar/mra.scala
core/src/main/scala/quasar/semantics.scala
core/src/main/scala/quasar/sql/ast.scala
core/src/main/scala/quasar/sql/fixpoint.scala
core/src/main/scala/quasar/sql/package.scala
core/src/main/scala/quasar/sql/parser.scala
core/src/main/scala/quasar/std/set.scala
core/src/test/scala/quasar/backend.scala
core/src/test/scala/quasar/compiler.scala
core/src/test/scala/quasar/physical/mongodb/planner.scala
core/src/test/scala/quasar/semantics.scala
core/src/test/scala/quasar/sql/SqlParserSpec.scala

#done SD-1001, #done SD-1002
Also, fix `TransformSelect` to work on nested selects.

Separate `limit` and `offset` operators from `select`.

---

.travis.yml
README.md
build.sbt
web/build.sbt
web/src/main/scala/quasar/api/fs.scala
web/src/main/scala/quasar/api/package.scala
web/src/test/scala/quasar/api/fs.scala

- supersedes #953
- #done SD-857 (fixed via http4s update)
- preparation for SD-884

bump http4s to 0.10.1

---

web/src/main/scala/quasar/api/package.scala

SD-884: utilize http4s FileService

---

core/src/main/scala/quasar/backend.scala
core/src/main/scala/quasar/jscore/package.scala
core/src/main/scala/quasar/physical/mongodb/expression/package.scala
core/src/main/scala/quasar/physical/mongodb/package.scala
core/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala
core/src/main/scala/quasar/repl/repl.scala
core/src/main/scala/quasar/std/math.scala
core/src/main/scala/quasar/types.scala
core/src/test/scala/quasar/physical/mongodb/planner.scala
core/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala
core/src/test/scala/quasar/physical/mongodb/workflowop.scala
core/src/test/scala/quasar/std/date.scala
web/src/test/scala/quasar/api/fs.scala

There are a number of places in the code (pending tests, comments, etc.)
where we refer to issue numbers. They now refer to JIRA issues rather
than the old GitHub issues.
NB: There were three references that I couldn’t find the ticket for. I
left the GitHub numbers there in the hopes that it may help someone in
future.

Update issues referenced in code.

---

build.sbt
core/src/main/scala/quasar/backend.scala
core/src/main/scala/quasar/fp/package.scala
core/src/main/scala/quasar/physical/mongodb/planner.scala
core/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala
core/src/main/scala/quasar/physical/mongodb/workflowop.scala
it/src/main/scala/quasar/Interactive.scala
scripts/build
web/src/main/scala/quasar/api/server.scala

The `doc` task was failing and therefore `publishLocal` was failing. This fixes the `doc` failures.

SD-1068 : update scaladoc to build cleanly

---

core/build.sbt
core/src/main/scala/quasar/compiler.scala
core/src/main/scala/quasar/jscore/package.scala
core/src/main/scala/quasar/physical/mongodb/planner.scala
core/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala
core/src/main/scala/quasar/sql/parser.scala
core/src/main/scala/quasar/std/string.scala
core/src/test/scala/quasar/compiler.scala
core/src/test/scala/quasar/physical/mongodb/planner.scala
it/src/main/resources/tests/guardedExpression.test
it/src/main/resources/tests/matchCaseInsensitiveRegex.test
it/src/main/resources/tests/negatedRegex.test
it/src/main/resources/tests/projectCaseInsensitiveRegex.test

Also bump minimum scoverage req to 80%.

Implement case insensitive (and negated) regex.

---

core/src/main/scala/quasar/compiler.scala
core/src/test/scala/quasar/physical/mongodb/planner.scala

This is probably not a full fix to SD-1081, but this bug would be hit
once the other bug gets fixed.

Fix a bug in converting LIKE patterns to regexes.

---

build.sbt
core/src/main/scala/quasar/config/CoreConfig.scala
core/src/main/scala/quasar/config/FsPath.scala
core/src/main/scala/quasar/config/config.scala
core/src/main/scala/quasar/config/package.scala
core/src/main/scala/quasar/evaluator.scala
core/src/main/scala/quasar/mounter.scala
core/src/main/scala/quasar/repl/repl.scala
core/src/test/scala/quasar/config/config.scala
web/src/main/scala/quasar/api/fs.scala
web/src/main/scala/quasar/api/server.scala
web/src/main/scala/quasar/config/WebConfig.scala
web/src/test/scala/quasar/api/fs.scala
web/src/test/scala/quasar/api/server.scala
web/src/test/scala/quasar/config/config.scala

[SD-1068] preparation for external configuration extension

---

build.sbt
web/src/main/scala/quasar/api/server.scala
web/src/main/scala/quasar/config/WebConfig.scala

Warts were mistakenly removed in #975.

re-add mistakenly removed warts

---

web/src/main/scala/quasar/api/fs.scala
web/src/test/scala/quasar/api/fs.scala

SD-1151 #done
This adds two simple tests, and the simplest, quickest possible fix. It's beginning to look like making ViewConfig a subtype of MountConfig along with MongoDbConfig was a mistake, with more and more code ending up either pattern matching or inspecting paths to decide how to handle mounts. But in the interest of getting a fix in quickly, this commit makes it a bit worse. I'm going to write a "technical debt" ticket with a proposal for cleaning this up.

allow views to be nested inside other mounts

---

core/build.sbt
scripts/installMongo

A couple of quick fixes to hopefully make Travis builds more robust in the short term.

Improve build stability

---

core/src/main/scala/quasar/backend.scala

We no longer strictly require the ability to write, now that some
queries can be run in "streaming" mode.
SD-1163 #done

disable writing a temp file when checking connections

---

core/src/main/scala/quasar/fs/chroot.scala
it/src/test/scala/quasar/physical/mongodb/filesystems.scala

A couple of fixes that slipped through the last PR to the web feature

Fixes for recent PRs

---

core/src/main/scala/quasar/fs/QueryFile.scala
web/src/main/scala/quasar/api/MessageFormat.scala
web/src/main/scala/quasar/api/server.scala
web/src/main/scala/quasar/api/services/package.scala
web/src/test/scala/quasar/api/MessageFormatGen.scala
web/src/test/scala/quasar/api/services/DataServiceSpec.scala
web/src/test/scala/quasar/api/services/Fixture.scala
web/src/test/scala/quasar/api/services/ServerServiceSpec.scala
web/src/test/scala/quasar/api/zip.scala

- Just generally try and tackle as many dangling TODOs as possible

Revisit DataServiceSpec tests and add checks for server state after certain operations

---

core/src/main/scala/quasar/fs/InMemory.scala
core/src/main/scala/quasar/fs/Positive.scala
core/src/main/scala/quasar/fs/package.scala
web/src/main/scala/quasar/api/services/data.scala
web/src/main/scala/quasar/api/services/package.scala
web/src/main/scala/quasar/api/services/query.scala
web/src/test/scala/quasar/api/services/CompileAndQueryServiceSpec.scala

- Add show for Positive
- Implement response for SemanticError
- Add new test in CompileAndQuerySpec and refactor a little to get it in there nicely
- Add simple in-memory query evaluator

[SD-1177] Port over addition of offset and limit to query API

---

core/src/main/scala/quasar/Predef.scala
core/src/main/scala/quasar/errors.scala
core/src/main/scala/quasar/fp/free/Interpreter.scala
core/src/main/scala/quasar/fp/free/package.scala
core/src/main/scala/quasar/fp/package.scala
core/src/main/scala/quasar/fs/InMemory.scala
core/src/main/scala/quasar/fs/Natural.scala
core/src/main/scala/quasar/fs/Positive.scala
core/src/main/scala/quasar/fs/QueryFile.scala
core/src/main/scala/quasar/fs/WriteError.scala
core/src/main/scala/quasar/fs/chroot.scala
core/src/main/scala/quasar/fs/package.scala
core/src/main/scala/quasar/physical/mongodb/fs/queryfile.scala
core/src/main/scala/quasar/physical/mongodb/fs/readfile.scala
core/src/test/scala/quasar/codec.scala
core/src/test/scala/quasar/fs/FileSystemFixture.scala
core/src/test/scala/quasar/fs/ManageFileSpec.scala
core/src/test/scala/quasar/fs/QueryFileSpec.scala
core/src/test/scala/quasar/fs/ReadFileSpec.scala
core/src/test/scala/quasar/fs/WriteFileSpec.scala
it/src/test/scala/quasar/fs/ReadFilesSpec.scala
it/src/test/scala/quasar/fs/WriteFilesSpec.scala
it/src/test/scala/quasar/physical/mongodb/filesystems.scala

This commits brings over the general purpose improvements to core that were done in the web branch (which is currently blocked on more work that needs to be done on Free in core) so that they can be available as soon as possible for projects that depend on Quasar as a library. Also to avoid conflicts with current work on Free in master.
This commit aggregation is co-authored with @wemrysi, specifically the part on the addition of the `Explain` term to the `QueryFile` algebra.

General improvements to Free in core

---

core/src/test/scala/quasar/fs/QueryFileSpec.scala
core/src/test/scala/quasar/scalacheck/package.scala

Based on initial insight from @wemrysi 
Supersedes #1037

Improve property for descendantFiles

---

core/src/main/scala/quasar/fp/free/package.scala
core/src/test/scala/quasar/fs/FileSystemFixture.scala

* add `restrict` to `free` package
* improve return type of `FileSystemFixture`'s `segAt`

Misc improvements

---

core/src/main/scala/quasar/fs/FileSystemError.scala
core/src/main/scala/quasar/fs/InMemory.scala
core/src/main/scala/quasar/fs/ReadFile.scala
core/src/main/scala/quasar/fs/WriteFile.scala
core/src/main/scala/quasar/physical/mongodb/fs/readfile.scala
core/src/main/scala/quasar/physical/mongodb/fs/writefile.scala
it/src/test/scala/quasar/fs/ReadFilesSpec.scala
it/src/test/scala/quasar/fs/WriteFilesSpec.scala

As suggested by @jedesah, this adds some useful context to the handles which is useful both for debugging and for nicer log/error messages.

Add file path to ReadHandle and WriteHandle

---

core/src/main/scala/quasar/effect/KeyValueStore.scala
core/src/main/scala/quasar/effect/MonotonicSeq.scala
core/src/main/scala/quasar/fp/free/package.scala
core/src/main/scala/quasar/fp/package.scala
core/src/main/scala/quasar/fs/Node.scala
core/src/main/scala/quasar/fs/QueryFile.scala
core/src/main/scala/quasar/fs/Views.scala
core/src/main/scala/quasar/fs/chroot.scala
core/src/main/scala/quasar/fs/package.scala
core/src/main/scala/quasar/fs/view.scala
core/src/test/scala/quasar/fs/TraceFS.scala
core/src/test/scala/quasar/fs/ViewsSpec.scala
core/src/test/scala/quasar/fs/view.scala
it/src/test/scala/quasar/fs/FileSystemTest.scala

View interpretation for the Free architecture

---

core/src/main/scala/quasar/fs/InMemory.scala
core/src/main/scala/quasar/fs/QueryFile.scala
core/src/main/scala/quasar/fs/WriteFile.scala
core/src/main/scala/quasar/fs/chroot.scala
core/src/main/scala/quasar/physical/mongodb/fs/queryfile.scala
core/src/test/scala/quasar/fs/ManageFileSpec.scala
core/src/test/scala/quasar/fs/QueryFileSpec.scala
core/src/test/scala/quasar/fs/WriteFileSpec.scala
it/src/test/scala/quasar/fs/ManageFilesSpec.scala
it/src/test/scala/quasar/fs/WriteFilesSpec.scala
it/src/test/scala/quasar/physical/mongodb/fs/MongoDbFileSystemSpec.scala
it/src/test/scala/quasar/regression/QueryRegressionTest.scala

Add FileExists term to QueryFile algebra

---

web/src/test/scala/quasar/api/services/DataServiceSpec.scala

Currently 409 Conflict, but should possible be some kind of 200 and a
no-op. Anyway this documents the current behavior and fixes the
intermittent failure.
The diff is unfortunate here. I had to make `expectedBody` a function so that the test for moving a directory to the same path could match the error which can refer to any file in the directory.

separate tests for MOVE file/dir to same path

---

core/src/main/scala/quasar/physical/mongodb/util.scala

Fixes a bug where we weren't copying the credentials from the connection string into the settings object when creating the mongo client. We were only using the settings object in order to configure a timeout that appears to be no longer needed given that we're monitoring the connection time via a different means for this driver.
Given this, we can just switch to creating the mongo client directly from the connection string.

Create async mongo client from a ConnectionString instead of settings

---

core/src/main/scala/quasar/fs/mount/view.scala
core/src/test/scala/quasar/fs/TraceFS.scala
core/src/test/scala/quasar/fs/mount/view.scala

...which by the way are now generated by TraceFS.

in the view FS interpreter, handle PathNotFound errors from the underlying FS

---

core/src/main/scala/quasar/fs/mount/Views.scala
core/src/test/scala/quasar/fs/mount/ViewsSpec.scala

fix for reading from views with relative path references

---

core/src/main/scala/quasar/effect/Failure.scala
core/src/main/scala/quasar/fp/free/package.scala
core/src/main/scala/quasar/fs/package.scala
core/src/test/scala/quasar/fp/free/FreeCatchableSpec.scala
web/src/main/scala/quasar/api/QHttpService.scala
web/src/main/scala/quasar/api/QuasarResponse.scala
web/src/main/scala/quasar/api/ServerOps.scala
web/src/main/scala/quasar/api/ToQuasarResponse.scala
web/src/main/scala/quasar/api/package.scala
web/src/main/scala/quasar/api/services/RestApi.scala
web/src/main/scala/quasar/api/services/data.scala
web/src/main/scala/quasar/api/services/package.scala
web/src/test/scala/quasar/api/services/DataServiceSpec.scala
web/src/test/scala/quasar/api/services/RestApiSpecs.scala

* Added Catchable[Free[S, ?]] when Task :<: S
* Changed QHttpService to a be a partial function to allow for taking
advantage of Http4s fallthrough behavior

Convert data service to a QHttpService

---

CHANGELOG/3.0.4.md
version.sbt
web/src/main/scala/quasar/api/Http4sUtils.scala

Make waitForInput in Http4sUtils public

---

core/src/main/scala/quasar/sql/package.scala
core/src/main/scala/quasar/sql/parser.scala
core/src/test/scala/quasar/VariablesArbitrary.scala
core/src/test/scala/quasar/compiler.scala
core/src/test/scala/quasar/fs/mount/HierarchicalFileSystemSpec.scala
core/src/test/scala/quasar/physical/mongodb/planner.scala
core/src/test/scala/quasar/sql/ExprArbitrary.scala
core/src/test/scala/quasar/sql/SqlParserSpec.scala
it/src/main/resources/tests/aliasedFieldSortedByOriginal.test
it/src/main/resources/tests/complex-vars.test
it/src/main/resources/tests/constantAndGrouped.test
it/src/main/resources/tests/convertTimestamp.test
it/src/main/resources/tests/dateFilter.test
it/src/main/resources/tests/days.test
it/src/main/resources/tests/different-flattens.test
it/src/main/resources/tests/filterOnDate.test
it/src/main/resources/tests/filterOnOid.test
it/src/main/resources/tests/groupByExpression.test
it/src/main/resources/tests/time.test
it/src/main/resources/tests/timestampsAndIntervals.test
it/src/test/scala/quasar/ErrorConditions.scala
it/src/test/scala/quasar/physical/mongodb/fs/MongoDbFileSystemSpec.scala
it/src/test/scala/quasar/view.scala
web/src/test/scala/quasar/api/services/query/QueryFixture.scala

**NB**: This is a breaking change

Switch quoting style to SQL².

---

CHANGELOG/revision.md
build.sbt

Disable the Spark subproject.

---

CHANGELOG/revision.md
it/src/test/scala/quasar/TaskResource.scala
it/src/test/scala/quasar/TaskResourceSpec.scala
scripts/build

This adds some tests for TaskResource (the thing that was causing builds to hang), as requested the other day.
Also a couple of small adjustments to what runs in the primary and secondary Travis builds.

More build stability

---

CHANGELOG/feature.md
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/readfile.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/writefile.scala
sparkcore/src/test/scala/quasar/physical/sparkcore/fs/ReadFileSpec.scala
sparkcore/src/test/scala/quasar/physical/sparkcore/fs/WriteFileSpec.scala

Implements WriteFile for spark-local. 
Connected with https://github.com/quasar-analytics/quasar/issues/1254

WriteFile for spark-local

---

CHANGELOG/revision.md
mongodb/src/main/scala/quasar/physical/mongodb/MongoDbIO.scala

read collection size from any BsonNumber

---

CHANGELOG/revision.md
core/src/main/scala/quasar/qscript/EquiJoin.scala
core/src/main/scala/quasar/qscript/Mergeable.scala
core/src/main/scala/quasar/qscript/ProjectBucket.scala
core/src/main/scala/quasar/qscript/QScriptCore.scala
core/src/main/scala/quasar/qscript/SourcedPathable.scala
core/src/main/scala/quasar/qscript/ThetaJoin.scala
core/src/main/scala/quasar/qscript/Transform.scala
core/src/main/scala/quasar/qscript/package.scala
foundation/src/main/scala/quasar/fp/ExternallyManaged.scala

This was discussed in #1370, but I never made the change. So, here’s the change.

Add `ExternallyManaged` to replace some usages of `Unit`.

---

CHANGELOG/revision.md
core/src/main/scala/quasar/qscript/MapFunc.scala
core/src/main/scala/quasar/qscript/QScriptCore.scala
core/src/test/scala/quasar/qscript/QScript.scala

@sellout some misc qscript changes that I didn't want to lose

Qscript misc

---

CHANGELOG/feature.md
build.sbt
project/Dependencies.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/readfile.scala

Implement proper read for sparkcore where quasar will not read all content with single read, but do it in batches

Spark - Proper read

---

CHANGELOG/revision.md
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/Planner.scala

`CoreMap` is being used in `QScriptCore.Map` & `QScriptCore.Filter`

Spark - CoreMap implementation

---

CHANGELOG/revision.md
it/src/main/resources/tests/temporal/datePartsConverted.test
it/src/main/resources/tests/temporal/datePartsConvertedSimple.test
mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOpCore.scala

add missing expr-JS conversion

---

CHANGELOG/revision.md
build.sbt
connector/src/main/scala/quasar/qscript/Optimize.scala
connector/src/main/scala/quasar/qscript/package.scala
connector/src/test/scala/quasar/qscript/Optimize.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala

- Add `shiftRead` convenience function
- Add optimization for `ShiftedRead` and apply in new `shiftRead` function

Optimization for `ShiftedRead`

---

CHANGELOG/revision.md
mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala

It's just black magic. Import only what you need and certain
kinds of bugs go away for a while.

Eliminate the separate compilation diverging implicit error.

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/qscript/MapFunc.scala
marklogic/src/main/scala/quasar/physical/marklogic/ejson/EncodeXQuery.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/MarkLogicPlannerError.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/QScriptCorePlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/ejson.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/fn.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/map.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/mem.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/qscript.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/syntax.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/xdmp.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/xs.scala

* Includes support for all terms except `Undefined`, `IfUndefined` and `Guard` (`Guard` expressions are currently replaced by their `cont` expression, effectively ignoring them for now).
* Also fixes the plan for `QScriptCore.Unreferenced` to have the correct cardinality (1).

Finish MarkLogic planning of MapFunc

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/PhaseResult.scala
connector/src/main/scala/quasar/fs/FileSystemError.scala
connector/src/main/scala/quasar/fs/InMemory.scala
connector/src/main/scala/quasar/fs/QueryFile.scala
connector/src/main/scala/quasar/package.scala
foundation/src/main/scala/quasar/RenderTree.scala
foundation/src/main/scala/quasar/fp/package.scala
frontend/src/test/scala/quasar/sql/SqlParserSpec.scala
js/src/test/scala/quasar/jscore/jscore.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala
mongodb/src/main/scala/quasar/physical/mongodb/fs/queryfile.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala
mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOp3_2.scala
mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOpCore.scala
mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala
mongodb/src/test/scala/quasar/physical/mongodb/planner.scala
repl/src/main/scala/quasar/repl/Repl.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala
web/src/main/scala/quasar/api/ToApiError.scala

This also eliminates the implicit Show automatically provided by RenderTree.

Fix REPL debug output.

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/qscript/DiscoverPath.scala
connector/src/main/scala/quasar/qscript/Injectable.scala
connector/src/main/scala/quasar/qscript/MapFunc.scala
connector/src/main/scala/quasar/qscript/Optimize.scala
connector/src/main/scala/quasar/qscript/Provenance.scala
connector/src/main/scala/quasar/qscript/QScriptCore.scala
connector/src/main/scala/quasar/qscript/package.scala
connector/src/test/scala/quasar/qscript/Optimize.scala
connector/src/test/scala/quasar/qscript/QScript.scala
connector/src/test/scala/quasar/qscript/QScriptHelpers.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/package.scala
mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala

- Lower Free[MapFunc...] noise with type alias.
- Utilize FreeQS alias more places.
- More consistent definition of Injectable.

Consistent Injectable, more type aliases

---

CHANGELOG/revision.md
core/src/main/scala/quasar/fs/mount/MountConfig.scala
core/src/main/scala/quasar/fs/mount/Mounter.scala
core/src/test/scala/quasar/fs/mount/MounterSpec.scala
interface/src/main/scala/quasar/main/package.scala
web/src/test/scala/quasar/api/services/MountServiceSpec.scala

Defines a `PathStore` trait with the necessary operations, with an implementation for `KeyValueStore.

Refactor mounter

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/qscript/Optimize.scala
connector/src/main/scala/quasar/qscript/Transform.scala
connector/src/test/scala/quasar/qscript/QScript.scala

avoid theta join creation if one side is constant

---

CHANGELOG/revision.md
foundation/src/main/scala/quasar/fp/free/package.scala
marklogic/src/main/scala/quasar/physical/marklogic/xcc/ContentSourceIO.scala
mongodb/src/main/scala/quasar/physical/mongodb/MongoDbIO.scala
web/src/test/scala/quasar/api/services/DataServiceSpec.scala

And a few more polymorphic lambdas.

Trim free package object to live functions.

---

CHANGELOG/revision.md
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala

Adding some optimization to QScript.

Turn on QS optimization on sparkcore

---

CHANGELOG/revision.md
couchbase/src/main/scala/quasar/physical/couchbase/planner/QScriptCorePlanner.scala
couchbase/src/test/scala/quasar/physical/couchbase/BasicQueryEnablementSpec.scala

Addresses #1593 that came out of review for #1563.

CB: Filter

---

CHANGELOG/revision.md
couchbase/src/main/scala/quasar/physical/couchbase/fs/package.scala
it/src/test/scala/quasar/physical/mongodb/MongoDbStdLibSpec.scala

Also by way of @mossprescott:
- Favor DateTimeFormatter over toString

CB: Increase queryTimeout

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/qscript/QScriptCore.scala
connector/src/main/scala/quasar/qscript/Transform.scala
connector/src/main/scala/quasar/qscript/package.scala
connector/src/test/scala/quasar/qscript/QScript.scala

Implement DistinctBy compilation in QScript.

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/package.scala
frontend/src/main/scala/quasar/functions.scala
frontend/src/main/scala/quasar/optimizer.scala
frontend/src/test/scala/quasar/matchers.scala
js/src/main/scala/quasar/jscore/package.scala
mongodb/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala
mongodb/src/main/scala/quasar/physical/mongodb/workflow/package.scala
mongodb/src/test/scala/quasar/physical/mongodb/optimize.scala

Various cleanup.  Broken up into hopefully useful commits.

misc cleanup re aliases and matryoshka uses

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/qscript/QScriptCore.scala
connector/src/test/scala/quasar/qscript/QScript.scala

Fix merging of QScript Reduce nodes.

---

CHANGELOG/revision.md
it/src/main/resources/tests/concatArray.test
it/src/main/resources/tests/concatArrayWithLiteral.test
it/src/main/resources/tests/concatArrayWithUnknown.test
it/src/main/resources/tests/concatBetween.test
it/src/main/resources/tests/concatFieldAndConstant.test
it/src/main/resources/tests/convertFromString.test
it/src/main/resources/tests/letInSelectProjection.test
it/src/main/resources/tests/selectArrayElement.test

CB: Enable additional query integration tests

---

CHANGELOG/revision.md
couchbase/src/main/scala/quasar/physical/couchbase/common.scala
couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala
couchbase/src/main/scala/quasar/physical/couchbase/fs/readfile.scala
couchbase/src/main/scala/quasar/physical/couchbase/planner/EquiJoinPlanner.scala
couchbase/src/main/scala/quasar/physical/couchbase/planner/MapFuncPlanner.scala
couchbase/src/main/scala/quasar/physical/couchbase/planner/QScriptCorePlanner.scala
couchbase/src/main/scala/quasar/physical/couchbase/planner/ReduceFuncPlanner.scala
couchbase/src/test/scala/quasar/physical/couchbase/BasicQueryEnablementSpec.scala
it/src/main/resources/tests/boulderLikePop.test
it/src/main/resources/tests/trivialGroup.test
project/Dependencies.scala
scripts/startCouchbase

CB: Impls for ConcatMaps and Arbitrary

---

CHANGELOG/revision.md
couchbase/src/main/scala/quasar/physical/couchbase/planner/MapFuncPlanner.scala
couchbase/src/main/scala/quasar/physical/couchbase/planner/QScriptCorePlanner.scala
couchbase/src/test/scala/quasar/physical/couchbase/BasicQueryEnablementSpec.scala
it/src/main/resources/tests/largestCities.test
it/src/main/resources/tests/sortProjectLimit.test

CB: Fix Sort

---

CHANGELOG/revision.md
couchbase/src/main/scala/quasar/physical/couchbase/fs/package.scala

addresses: slamdata/slamdata#1159

CB: Handle connection refused

---

CHANGELOG/revision.md
core/src/test/scala/quasar/sql/compiler.scala
effect/src/main/scala/quasar/effect/Timing.scala
frontend/src/main/scala/quasar/data.scala
frontend/src/main/scala/quasar/std/agg.scala
frontend/src/main/scala/quasar/std/date.scala
frontend/src/test/scala/quasar/DataArbitrary.scala
frontend/src/test/scala/quasar/codec.scala
frontend/src/test/scala/quasar/sql/ExprArbitrary.scala
frontend/src/test/scala/quasar/std/AggLibSpec.scala
frontend/src/test/scala/quasar/std/StdLibSpec.scala
frontend/src/test/scala/quasar/std/date.scala
frontend/src/test/scala/quasar/std/math.scala
interface/src/test/scala/quasar/main/prettify.scala
it/src/test/scala/quasar/physical/mongodb/MongoDbStdLibSpec.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/xdmitem.scala
marklogic/src/main/scala/quasar/physical/marklogic/prisms.scala
mongodb/src/main/scala/quasar/physical/mongodb/bson.scala
mongodb/src/main/scala/quasar/physical/mongodb/bsoncodec.scala
mongodb/src/main/scala/quasar/physical/mongodb/expression/Check.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala
mongodb/src/test/scala/quasar/physical/mongodb/bson.scala
mongodb/src/test/scala/quasar/physical/mongodb/expression/spec.scala
mongodb/src/test/scala/quasar/physical/mongodb/planner.scala
project/Dependencies.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala
web/src/test/scala/quasar/api/services/DataServiceSpec.scala

Since we require java 8 now, the library serves no purpose.

Eliminate dependency on org.threeten.bp.

---

CHANGELOG/revision.md
connector/src/test/scala/quasar/qscript/QScript.scala
connector/src/test/scala/quasar/qscript/Rewrite.scala
core/src/test/scala/quasar/optimizer.scala
core/src/test/scala/quasar/sql/compiler.scala
frontend/src/main/scala/quasar/frontend/logicalplan/LogicalPlanR.scala
mongodb/src/test/scala/quasar/physical/mongodb/planner.scala
sql/src/test/scala/quasar/sql/helpers.scala

Remove implicit `Fix` embedding in tests

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/qscript/package.scala
couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala
mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala

Consolidate call sites for SimplifyJoin

---

CHANGELOG/revision.md
connector/src/main/scala/quasar/fs/QueryFile.scala
connector/src/main/scala/quasar/qscript/Coalesce.scala
connector/src/main/scala/quasar/qscript/MapFunc.scala
connector/src/main/scala/quasar/qscript/Normalizable.scala
connector/src/main/scala/quasar/qscript/Transform.scala
connector/src/main/scala/quasar/qscript/package.scala
connector/src/test/scala/quasar/qscript/QScript.scala
it/src/main/resources/tests/projectFromConcattedArray.test
it/src/main/resources/tests/projectFromConcattedArrayPrefix.test

Fix non-static array projection prefix

---

CHANGELOG/revision.md
couchbase/src/main/scala/quasar/physical/couchbase/RenderQuery.scala
couchbase/src/test/scala/quasar/physical/couchbase/BasicQueryEnablementSpec.scala

CB: Single quote strings in query rendering

---

CHANGELOG/revision.md
couchbase/src/main/scala/quasar/physical/couchbase/fs/package.scala

CB: Verify sufficient version

---

connector/src/main/scala/quasar/qscript/Mergeable.scala
connector/src/main/scala/quasar/qscript/Rewrite.scala
connector/src/main/scala/quasar/qscript/Transform.scala
connector/src/main/scala/quasar/qscript/package.scala
connector/src/test/scala/quasar/qscript/QScript.scala
connector/src/test/scala/quasar/qscript/QScriptHelpers.scala
it/src/main/resources/tests/sameFieldName.test

Fixes #1581 
Fixes #1560 
Implements basic joins in QScript.

Implement QScript joins.

---

connector/src/main/scala/quasar/config/FsPath.scala
core/src/test/scala/quasar/fs/Arbitraries.scala
foundation/src/main/scala/quasar/fp/free/Interpreter.scala

Re-add not so dead code used downstream in QAdv

---

connector/src/main/scala/quasar/qscript/Rewrite.scala
connector/src/test/scala/quasar/qscript/QScript.scala
it/src/main/resources/tests/flattenArrayLeftWithUnflattened.test
it/src/main/resources/tests/flattenArrayWithUnflattened.test
it/src/main/resources/tests/unifyFlattenedFields.test

Fixes #1783 - removes unnecessary theta join from query with flatten.

Remove extra theta join

---

project/Dependencies.scala
web/src/main/scala/quasar/api/package.scala

In order to temporarily fix issue #1852

Downgrade http4s back to `0.14.1a`

---

frontend/src/test/scala/quasar/sql/ExprArbitrary.scala

Avoid scalacheck precondition

---

.travis.yml
scripts/publishJarIfMaster

Only decrypt publish creds when available

---

connector/src/main/scala/quasar/qscript/PruneArrays.scala
connector/src/test/scala/quasar/qscript/PruneArrays.scala

Fix bug in PruneArrays so we check for entire array usage.

Fix bug in PruneArrays so we check for entire array usage.

---

connector/src/main/scala/quasar/qscript/MapFunc.scala
frontend/src/main/scala/quasar/frontend/logicalplan/LogicalPlanR.scala
frontend/src/main/scala/quasar/functions.scala

Remove `Option#get` usage.
Fixes #1927.

Remove `Option#get` usage

---

connector/src/main/scala/quasar/fs/ManageFile.scala
connector/src/main/scala/quasar/fs/QueryFile.scala
connector/src/main/scala/quasar/fs/ReadFile.scala
connector/src/main/scala/quasar/fs/WriteFile.scala
core/src/main/scala/quasar/fs/mount/Mounting.scala
core/src/test/scala/quasar/fs/mount/MountingSpec.scala
effect/src/main/scala/quasar/effect/AtomicRef.scala
effect/src/main/scala/quasar/effect/Failure.scala
effect/src/main/scala/quasar/effect/KeyValueStore.scala
effect/src/main/scala/quasar/effect/LiftedOps.scala
effect/src/main/scala/quasar/effect/MonotonicSeq.scala
effect/src/main/scala/quasar/effect/Read.scala
effect/src/main/scala/quasar/effect/Timing.scala
it/src/test/scala/quasar/physical/mongodb/fs/MongoDbFileSystemSpec.scala
repl/src/main/scala/quasar/repl/ConsoleIO.scala
web/src/main/scala/quasar/api/services/data.scala
web/src/main/scala/quasar/api/services/mount.scala

Rename `F` in `LiftedOps` to `FreeS`.

Rename F in LiftedOps to FreeS.

---

.travis.yml
it/testing.conf.example
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/package.scala

spark-local should always use "local[*]", thus the user only needs to
provide path to folder from local file system

Change spark-local connectionUri

---

it/src/main/resources/tests/likeWithConstantFoldablePattern.test

Enable integration test with LIKE and variable

---

project/Dependencies.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/package.scala

Part of https://github.com/quasar-analytics/quasar/issues/1900

Change the way spark-hdfs connectionUri is defined, add spark-cluster configs

---

build.sbt
scripts/publishJarIfMaster

Creates one more artifact: sparkcore.jar to be added to releases
Part of https://github.com/quasar-analytics/quasar/issues/1712

sparkcore.jar - new artifact in releases

---

sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/package.scala

There was a bug in how sparkUri was created. This PR fixes this bug.

Fix way master and port are fetched from URI

---

.travis.yml
couchbase/src/main/scala/quasar/physical/couchbase/fs/package.scala
scripts/build
scripts/startCouchbase

Address doc gen timeouts on Travis

---

connector/src/main/scala/quasar/qscript/MapFunc.scala
connector/src/main/scala/quasar/qscript/Merge.scala
connector/src/test/scala/quasar/qscript/QScript.scala
connector/src/test/scala/quasar/qscript/QScriptHelpers.scala
it/src/main/resources/tests/caseVariations.test

improved QScript merging through Filter and Sort

---

.travis.yml

Fixed travis script publishAndTag commands as per @drostron comment in this prior [PR](https://github.com/quasar-analytics/quasar/pull/2037).

Fix travis script publishAndTag

---

connector/src/main/scala/quasar/qscript/Optimize.scala
connector/src/main/scala/quasar/qscript/Rewrite.scala
connector/src/test/scala/quasar/qscript/Optimize.scala
connector/src/test/scala/quasar/qscript/QScriptHelpers.scala
connector/src/test/scala/quasar/qscript/Rewrite.scala
couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala
mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala

push filter before union in qscript

---

connector/src/main/scala/quasar/qscript/Rewrite.scala
connector/src/test/scala/quasar/qscript/Rewrite.scala

LeftShift cancels out static array.

---

it/src/test/scala/quasar/server/ServiceSpec.scala
web/src/main/scala/quasar/config/ServerConfig.scala
web/src/main/scala/quasar/server/CliOptions.scala
web/src/main/scala/quasar/server/Http4sUtils.scala
web/src/main/scala/quasar/server/Server.scala
web/src/main/scala/quasar/server/control.scala
web/src/main/scala/quasar/server/package.scala
web/src/test/scala/quasar/config/WebConfigArbitrary.scala
web/src/test/scala/quasar/config/WebConfigSpec.scala
web/src/test/scala/quasar/server/ControlServiceSpec.scala

To avoid non-deterministic build failures including fthomas/refined#260

Revert "A Refined Port"

---

it/testing.conf.example
project/Dependencies.scala

Knobs version updated to 4.0.30

knobs version updated

---

README.md

9.5+ required for `CREATE INDEX IF NOT EXISTS ...`

PostgreSQL version requirement

---

web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala

Disallow equal names in MetadataServiceSpec.

---

couchbase/src/main/scala/quasar/physical/couchbase/common.scala
couchbase/src/main/scala/quasar/physical/couchbase/fs/managefile.scala
couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala
couchbase/src/main/scala/quasar/physical/couchbase/fs/readfile.scala

Handle Couchbase query errors. Relates to #1621.

handle cb errors

---

couchbase/src/main/scala/quasar/physical/couchbase/RenderQuery.scala
couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala
couchbase/src/test/scala/quasar/physical/couchbase/BasicQueryEnablementSpec.scala

CB: Avoid `value` due to a CB client issue

---

interface/src/main/scala/quasar/main/config.scala
interface/src/main/scala/quasar/main/metastore.scala
interface/src/main/scala/quasar/main/package.scala
repl/src/main/scala/quasar/repl/Main.scala
web/src/main/scala/quasar/server/Server.scala

Support MetaStore without config file

---

build.sbt
mimir/src/main/scala/com/precog/mimir/Mimir.scala
project/Precog.scala

Also a bit of build tweaking required.

Mimir backend module implementation

---

scripts/afterSuccess
scripts/build
scripts/quasarPublishAndTag

afterSuccess script fixed to publish codecov data

fixed code coverage publication script

---

frontend/src/main/scala/quasar/std/agg.scala
sql/src/test/scala/quasar/sql/compiler.scala

Type `Count(Const)` as `Const(1)`.

---

interface/src/main/scala/quasar/main/metastore.scala

Halt `initUpdateMetaStore` when conf file is malformed

---

web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala

Fix MetadataServiceSpec to not generate conflicting values.

---

sparkcore/src/main/scala/quasar/physical/sparkcore/fs/EquiJoinPlanner.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/Planner.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/QScriptCorePlanner.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/ShiftedReadPlanner.scala

This is just merely refactoring `Planner.scala` into smaller files each holding one of the `Planner` instance.
Part of https://github.com/quasar-analytics/quasar/issues/1659

Refactor Planner

---

blueeyes/src/main/scala/quasar/precog/util/cache/Cache.scala
build.sbt
project/Dependencies.scala
yggdrasil/src/main/scala/quasar/yggdrasil/nihdb/NIHDBProjection.scala
yggdrasil/src/main/scala/quasar/yggdrasil/nihdb/SegmentsWrapper.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/ActorVFS.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/BlobMetadata.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/FileSystem.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/VFS.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/VFSPathUtils.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/VersionLog.scala

Include ActorVFS.

---

mimir/src/main/scala/quasar/mimir/Mimir.scala
mimir/src/main/scala/quasar/mimir/Precog.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/ActorVFS.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/SecureVFS.scala

Cake baking

---

connector/src/main/scala/quasar/connector/BackendModule.scala
interface/src/main/scala/quasar/main/package.scala
marklogic/src/main/scala/quasar/physical/marklogic/Marklogic.scala
mimir/src/main/scala/quasar/mimir/Mimir.scala
skeleton/src/main/scala/quasar/physical/skeleton/fs/Skeleton.scala

- Remove the need for connectors to handle FileSystemErrors and PhaseResults
- Remove Free from BackendModule

Backend module update

---

docker/Dockerfiles/Marklogic/MarkLogic-Dockerfile

Randomizes trying to download ML rpm to avoid failures reported in #2201. Fixes #2201.

changed marklogic rpm download to use wget with randomized download time

---

build.sbt

Fixed mimir build targets

---

blueeyes/src/main/scala/quasar/blueeyes/json/JValue.scala
build.sbt
connector/src/main/scala/quasar/connector/BackendModule.scala
mimir/src/main/scala/quasar/mimir/Mimir.scala
mimir/src/main/scala/quasar/mimir/Precog.scala
project/Dependencies.scala
repl/src/main/resources/logback.xml
web/src/main/resources/logback.xml
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/SecureVFS.scala

Implemented (in some cases, quite poorly) most of the filesystem stuff on top of mimir.  It's now possible to upload and view data, though queries still don't work (failing for a reason which is a little weird right now).  That'll come soon.
Fixes #2211

Bridging mimir into quasar

---

docker/scripts/assembleTestingConf
docker/scripts/setupContainers

setupContainers will now handle docker-machine without a default host

setupContainers handles docker-machine properly

---

frontend/src/main/scala/quasar/sql/package.scala
frontend/src/test/scala/quasar/sql/SqlParserSpec.scala

Fix sql pprint for FieldDeref with StringLiteral

---

scripts/build

This will make it easier to quickly see which test failed on Travis

Travis will only output failing tests

---

README.md
docker/scripts/initMarklogic
docker/scripts/setupContainers
marklogic/src/main/scala/quasar/physical/marklogic/MarkLogic.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/lib.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/ops.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/FunctionDecl.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/admin.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/cts.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/fn.scala

No longer rely on ML directories for filesystem operations

---

repl/src/main/scala/quasar/repl/Main.scala
web/src/main/scala/quasar/server/Server.scala

Actually unmount filesystems when exiting repl/server

---

blueeyes/src/main/scala/quasar/precog/util/cache/Cache.scala
blueeyes/src/main/scala/quasar/precog/util/utilclasses.scala
niflheim/src/main/scala/quasar/niflheim/CTypeFlags.scala
niflheim/src/main/scala/quasar/niflheim/Chef.scala
niflheim/src/main/scala/quasar/niflheim/CookedBlockFormat.scala
niflheim/src/main/scala/quasar/niflheim/NIHDBActor.scala
niflheim/src/main/scala/quasar/niflheim/SegmentFormat.scala
niflheim/src/main/scala/quasar/niflheim/V1SegmentFormat.scala
niflheim/src/main/scala/quasar/niflheim/VersionedSegmentFormat.scala
niflheim/src/main/scala/quasar/niflheim/Versioning.scala
niflheim/src/test/scala/quasar/niflheim/SegmentFormatSupport.scala
project/Precog.scala
yggdrasil/src/main/scala/quasar/yggdrasil/scheduling/ScheduleStorage.scala
yggdrasil/src/main/scala/quasar/yggdrasil/scheduling/Scheduler.scala
yggdrasil/src/main/scala/quasar/yggdrasil/scheduling/SchedulingActor.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/ActorVFS.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/SecureVFS.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/VFS.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/VersionLog.scala

Banish `PrecogUnit` to the dustbin of bad ideas

---

frontend/src/main/scala/quasar/sql/package.scala
frontend/src/test/scala/quasar/sql/SqlParserSpec.scala

Fix sql pprint for let binding

---

frontend/src/test/scala/quasar/sst/CompressionSpec.scala

Fix handling of duplicate keys in sst compression spec.

---

.gitignore
.travis.yml
docker/Dockerfiles/Marklogic/MarkLogic-Dockerfile
docker/Dockerfiles/Marklogic/MarkLogic.rpm.sha1
docker/Dockerfiles/Marklogic/getMLRpm
docker/docker-compose.yml
docker/scripts/initContainer
docker/scripts/setupContainers

Keep MarkLogic.rpm cached away in Travis and load it from cache when ML container is built.

Cache MarkLogic RPM in Travis

---

connector/src/main/scala/quasar/qscript/Transform.scala
connector/src/main/scala/quasar/qscript/package.scala
it/src/main/resources/tests/different-flattens.test
it/src/main/resources/tests/flattenGroupedObject.test
it/src/main/resources/tests/unifyFlattenedFieldsWithUnflattened.test

Check for unnested duplicate element in qscript concat.

---

frontend/src/main/scala/quasar/sql/package.scala
frontend/src/test/scala/quasar/sql/SqlParserSpec.scala

Fix sql pprint for Binop

---

README.md

add mount point json pattern description

---

connector/src/main/scala/quasar/qscript/PruneArrays.scala
connector/src/main/scala/quasar/qscript/package.scala
connector/src/test/scala/quasar/qscript/PruneArrays.scala
it/src/main/resources/tests/skipCount.test

Prune subset branch using previously computed state.

---

connector/src/main/scala/quasar/qscript/QScriptCore.scala
it/src/main/resources/tests/backendStatuses.test

Fix merging of LeftShifts with differing IdStatus.

---

frontend/src/main/scala/quasar/sst/TypeStat.scala

Resolves #2404.
Please tell me what hiedous goofs I've made :wink:.
I'm not sure if we want to call it `tag`, `type` seemed like a decent alternative too, but I thought that might be a bit odd when we have multiple things that can be considered "type" in the response.

Add tags to the EJson encoding for TypeStat

---

it/src/test/scala/quasar/physical/marklogic/qscript/MarkLogicStdLibSpec.scala
it/src/test/scala/quasar/physical/marklogic/qscript/StructuralPlannerSpec.scala
it/src/test/scala/quasar/physical/marklogic/qscript/XmlStructuralPlannerSpec.scala
marklogic/src/main/scala/quasar/physical/marklogic/MarkLogic.scala
marklogic/src/main/scala/quasar/physical/marklogic/cts/ComparisonOp.scala
marklogic/src/main/scala/quasar/physical/marklogic/cts/MatchDepth.scala
marklogic/src/main/scala/quasar/physical/marklogic/cts/Query.scala
marklogic/src/main/scala/quasar/physical/marklogic/cts/package.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/ops.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/package.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/DataPlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/MarkLogicPlannerError.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/Planner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/QScriptCorePlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/ReadFilePlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/Search.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/ShiftedReadDirPlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/ThetaJoinPlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/UnreachablePlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/package.scala
marklogic/src/main/scala/quasar/physical/marklogic/xcc/package.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/cts.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/xdmp.scala
project/Dependencies.scala

cts:query initial AST

---

web/src/main/scala/quasar/api/MessageFormat.scala
web/src/test/scala/quasar/api/services/DataServiceSpec.scala
web/src/test/scala/quasar/api/services/InvokeServiceSpec.scala

- Also remove `content-disposition` media-type extension from `Content-Type` response header as it has no meaning

Add test for content-disposition functionality on `invoke` endpoint

---

connector/src/test/scala/quasar/qscript/QScriptHelpers.scala
core/src/main/scala/quasar/metastore/package.scala
foundation/src/main/scala/quasar/contrib/pathy/package.scala
frontend/src/main/scala/quasar/sql/Statement.scala
frontend/src/main/scala/quasar/sql/package.scala
frontend/src/main/scala/quasar/sql/parser.scala
frontend/src/test/scala/quasar/sql/StatementArbitrary.scala
marklogic/src/main/scala/quasar/physical/marklogic/fs/MarkLogicConfig.scala
repl/src/main/scala/quasar/repl/Command.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/package.scala
sparkcore/src/test/scala/quasar/physical/sparkcore/fs/WriteFileSpec.scala
web/src/main/scala/quasar/api/package.scala
web/src/main/scala/quasar/api/services/data.scala
web/src/main/scala/quasar/api/services/mount.scala
web/src/main/scala/quasar/api/services/query/execute.scala
web/src/test/scala/quasar/api/services/query/ExecuteServiceSpec.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/vfs.scala

- Fixes #2430 
- Add a few more tests around importing

Queries and modules now support imports with `/../`

---

it/src/main/resources/tests/divide.test
it/src/main/resources/tests/divide0.test
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala

Fixes https://github.com/quasar-analytics/quasar/issues/2269

Fix divide by zero for spark

---

it/src/main/resources/tests/largestZips.test
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/QScriptCorePlanner.scala

Resolves https://github.com/quasar-analytics/quasar/issues/1763
Fixes https://github.com/quasar-analytics/quasar/issues/2103

Fix sorting issue in spark

---

mimir/src/main/scala/quasar/mimir/Mimir.scala

- `ShiftedRead` with `IncludeId` wasn't working (and apparently we haven't yet enabled the tests which would expose it)
- Hard coding is embarrassing.  Fixed!

Corrected a couple random issues in mimir

---

it/src/test/scala/quasar/server/ServiceSpec.scala
web/src/main/scala/quasar/api/services/metadata.scala

Additionally provides a breaking version bump missing from #2440

Leverage MountingError's ToApiError instance

---

connector/src/main/scala/quasar/qscript/ExpandMapFunc.scala
connector/src/main/scala/quasar/qscript/MapFunc.scala
connector/src/main/scala/quasar/qscript/MapFuncDerived.scala
frontend/src/main/scala/quasar/functions.scala
frontend/src/main/scala/quasar/std/math.scala
frontend/src/test/scala/quasar/std/StdLibSpec.scala
it/src/main/resources/tests/derivedFunctionCeil.test
it/src/main/resources/tests/derivedFunctionFloor.test
it/src/test/scala/quasar/physical/mimir/MimirStdLibSpec.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala
mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
sql/src/main/scala/quasar/sql/compiler.scala

Relates to #2272 (check appropriate boxes once merged)

Add floor and ceil

---

it/src/main/resources/tests/boulderPop.test
it/src/main/resources/tests/constantAndGrouped.test
it/src/main/resources/tests/fieldOrder.test
it/src/main/resources/tests/filter-vars.test
it/src/main/resources/tests/implicitGroupWithFilter.test
it/src/main/resources/tests/skipCount.test
it/src/main/resources/tests/var-relation.test
mimir/src/main/scala/quasar/mimir/Mimir.scala
mimir/src/main/scala/quasar/mimir/StdLib.scala

Implements Reduce in mimir

---

docker/scripts/initMarklogic

Attempting to address #2319. We can close that issue when we haven't seen the problem arise for a while.

Increase ML cache sizes.

---

frontend/src/test/scala/quasar/std/StdLibSpec.scala
it/src/main/resources/tests/concatBetween.test
it/src/main/resources/tests/filterWithComplexNot.test
it/src/main/resources/tests/filterWithNot.test
it/src/main/resources/tests/groupAndWildcard.test
it/src/main/resources/tests/likeWithConstantFoldablePattern.test
it/src/main/resources/tests/matchCaseInsensitiveRegex.test
it/src/main/resources/tests/matchLikeComplement.test
it/src/main/resources/tests/matchRegexPattern.test
it/src/main/resources/tests/negatedRegex.test
it/src/main/resources/tests/projectCaseInsensitiveRegex.test
it/src/test/scala/quasar/physical/mimir/MimirStdLibSpec.scala
it/src/test/scala/quasar/physical/mongodb/ExprStdLibSpec.scala
it/src/test/scala/quasar/physical/mongodb/QExprStdLibSpec.scala
it/src/test/scala/quasar/physical/mongodb/QJsStdLibSpec.scala
mimir/src/main/scala/quasar/mimir/ArrayLib.scala
mimir/src/main/scala/quasar/mimir/MapFuncCorePlanner.scala
mimir/src/main/scala/quasar/mimir/StringLib.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala

Also the implementation of `Search` was completely wrong, so I've fixed that now.  A bunch more tests have sprung to life.

Hey, more mimir stdlib!

---

it/src/main/resources/tests/basicAnalyticQuery.test
it/src/main/resources/tests/citiesByTotalPopulation.test
it/src/main/resources/tests/projectIndexFromGroup.test

Adjusts a few tests that were too pessimistic for all the MongoDB versions.

Update a few MongoDB regression test expectations to reflect reality.

---

it/src/main/resources/tests/joins/joinWithComplexCondition.test

mark mongodb_3_4 test as timeout

---

it/src/test/scala/quasar/physical/marklogic/qscript/MarkLogicStdLibSpec.scala

Restrict decDomain a bit to avoid ceil/floor to fail occasionally

---

it/src/main/resources/tests/derivedFunctionAbs.test
it/src/main/resources/tests/derivedFunctionCeil.test
it/src/main/resources/tests/derivedFunctionFloor.test
it/src/main/resources/tests/derivedFunctionTrunc.test
it/src/test/scala/quasar/physical/mongodb/ExprStdLibSpec.scala
it/src/test/scala/quasar/physical/mongodb/JsStdLibSpec.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/JsFuncHandler.scala

fix incorrect merge JsFuncHandler and FuncHandler

---

repl/src/main/scala/quasar/repl/Main.scala

The repl `Task` was not being created properly causing violated assumptions making a recent change break the Repl as the Quasar FileSystem was being shutdown right after the Repl was created. Now properly using `Task.async` constructor designed specifically for callback apis such as `AeshConsole`.

Fix Repl from crashing immediately

---

sparkcore/src/main/scala/quasar/physical/sparkcore/fs/elastic/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/package.scala

This change method signature. All four files need to be refactor in near future (https://github.com/quasar-analytics/quasar/issues/2584) but for now I need this method signature to be changed.

Refactor definition, change signature of sparkFSDef method

---

sparkcore/src/test/scala/quasar/physical/sparkcore/fs/elastic/ElasticCallSpec.scala

Approach to resolve https://github.com/quasar-analytics/quasar/issues/2598
@alissapajer : the issue (that I tried to reproduce locally and failed multiple times) seems to happen when tests are running while embedded Elastic Search is not yet properly instantiated. This PR gives it a "5 times retry", each separated by 200 mills sleep. Lets try to merge that and see if it resolves the issue on CI. What do you think?

Run healthchecks few times before running test

---

docker/scripts/setupContainers
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/elastic/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/package.scala

Fixes https://github.com/quasar-analytics/quasar/issues/2417

spark-local should return error when directory doesn't exist

---

connector/src/main/scala/quasar/fs/QueryFile.scala
connector/src/main/scala/quasar/qscript/PruneArrays.scala
connector/src/main/scala/quasar/qscript/ReplaceMapFunc.scala
connector/src/main/scala/quasar/qscript/Transform.scala
it/src/main/resources/tests/joins/nonJsJoinCondition.test
it/src/main/resources/tests/joins/symmetricNonJsJoinCondition.test

Handle shifting on both sides of a join condition.

---

.travis.yml
docker/Dockerfiles/FTP/pureftpd.passwd
docker/Dockerfiles/Spark/Spark-Dockerfile
docker/Dockerfiles/Spark/wrapper_script.sh
docker/docker-compose.yml
docker/scripts/assembleTestingConf
docker/scripts/initContainer
docker/scripts/setupContainers

Add spark connector infrastructure for integration testing. Fixes #2471, #2414, #2413, #2412, #2411, #2410.

Docker spark connectors

---

it/src/main/resources/tests/demo/nestedSelectWithReduce.test
it/src/main/resources/tests/selectCount.test
mimir/src/main/scala/quasar/mimir/Mimir.scala

Fix tests selectCount and nestedSelectWithReduce in Mimir.

Mimir equijoin fix

---

effect/src/main/scala/quasar/effect/Capture.scala
it/src/main/resources/tests/multistageFlatten.test
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/EquiJoinPlanner.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/Planner.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/QScriptCorePlanner.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/ShiftedReadPlanner.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/cassandra/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/cassandra/queryfile.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/elastic/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/elastic/queryfile.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/queryfile.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/package.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/queryfile.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala
sparkcore/src/test/scala/quasar/physical/sparkcore/fs/PlannerSpec.scala

Finally closes #1634 - it removes QueryFile.Input completely. Also in `Planner` the `Task` is replace with `Free[S,?`]

Change planner signature

---

README.md

Add missing field in example request

---

core/src/main/scala/quasar/db/Schema.scala
core/src/main/scala/quasar/db/package.scala
core/src/main/scala/quasar/metastore/MetaStore.scala
core/src/test/scala/quasar/db/DbUtil.scala
core/src/test/scala/quasar/metastore/MetaStoreAccessSpec.scala
interface/src/main/scala/quasar/main/Quasar.scala
project/Dependencies.scala

Tests pass, but problably there's more to check to ensure that these changes don't break anything. 
I need this update to keep working on #2684

Upgrade to Doobie 0.4.4

---

README.md
foundation/src/main/scala/quasar/contrib/scalaz/package.scala
it/src/test/scala/quasar/server/ServiceSpec.scala
web/src/main/scala/quasar/server/Http4sUtils.scala
web/src/main/scala/quasar/server/PortChangingServer.scala
web/src/main/scala/quasar/server/Server.scala
web/src/main/scala/quasar/server/control.scala
web/src/test/scala/quasar/server/ControlServiceSpec.scala

- Refactors the way `PortChangingServer` operates and how things are setup to simplify and optimize the code around launching the server

Fix server not stopping when the user presses `Enter`

---

frontend/src/main/scala/quasar/sql/package.scala
frontend/src/test/scala/quasar/sql/ResolveImportSpec.scala

Relative paths within function body now resolve to location of module

---

connector/src/main/scala/quasar/qscript/Transform.scala
connector/src/test/scala/quasar/qscript/QScript.scala
it/src/main/resources/tests/sortCount.test

sort single value reduction

---

build.sbt

Made web/run and repl/run fast again, because I'm awesome like that

---

build.sbt
scripts/publishJar

This should fix connector JAR pushing, which isn't currently working.  Have to see it run in Travis (in master) to be sure.

Added githubReleaseAll task

---

build.sbt
scripts/publishJar

Fix broken ghrelease stuff

---

web/src/main/scala/quasar/server/CliOptions.scala

Fixed -P/--plugins configuration for web/run

---

rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsQueryFile.scala

Correct per miss between PR build passing and merge

Update RdbmsQueryFile's ExecutePlan

---

build.sbt
project/build.properties

Rolled back SBT to 0.13.16

---

connector/src/main/scala/quasar/qscript/Transform.scala
it/src/main/resources/tests/subselectReduction.test

Fix bug in qscript reduce for consecutive reductions.

---

connector/src/main/scala/quasar/qscript/PruneArrays.scala
connector/src/main/scala/quasar/qscript/QScriptCore.scala
connector/src/main/scala/quasar/qscript/Rewrite.scala
connector/src/main/scala/quasar/qscript/Transform.scala
connector/src/main/scala/quasar/qscript/package.scala
it/src/main/resources/tests/caseWithGroup.test

Fixes https://github.com/quasar-analytics/quasar/issues/2846

Improve merging of `Reduce` in qscript

---

it/src/main/resources/tests/derivedFunctionCeil.test
it/src/main/resources/tests/derivedFunctionFloor.test
it/src/main/resources/tests/derivedFunctionTrunc.test
mimir/src/main/scala/quasar/mimir/UnaryLib.scala

Fixed broken rounding of bigdecimal values

---

it/src/main/resources/tests/unshiftAggregation.test
mimir/src/main/scala/quasar/mimir/Mimir.scala
mimir/src/main/scala/quasar/mimir/ReductionLib.scala
mimir/src/test/scala/quasar/mimir/ReductionLibSpecs.scala

Fixes #2855 
Decided to play around with a prototype implementation, and it turned out to be a lot easier than I was expecting.

Implemented UnshiftArray in mimir

---

core/src/main/scala/quasar/fs/mount/Mounter.scala
web/src/test/scala/quasar/api/services/MountServiceSpec.scala

Fix bug when moving mount to a new path contained within it's current path

---

web/src/main/scala/quasar/server/Server.scala

I found a *bug* in @djspiewak code! Achievement unlocked!

Fix check when loading plugins

---

yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala

Fixes #2909 
…sort of.  The query is still relatively slow, but it's not *horrifically* slow.  The minimized case for this, btw, is the following:
```sql
select labels[*] from quasar where labels[*]
```
That takes 71 seconds to return the empty set (on my machine).  With my fix, it's down to 11 seconds.  Once #2366 is fixed, this should drop to around 3-5 seconds at the most.

Reconfigure leftShift re-splitting to avoid repeatedly remapping the same slice

---

it/src/main/resources/tests/nestedSelectWithFilter.test

Add integration test for nested query bug.

---

connector/src/main/scala/quasar/qscript/Branches.scala
connector/src/main/scala/quasar/qscript/Rewrite.scala
connector/src/main/scala/quasar/qscript/Trans.scala
connector/src/main/scala/quasar/qscript/package.scala
mongodb/src/main/scala/quasar/physical/mongodb/MongoDbPlanner.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/assumeReadType.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/common.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/mapBeforeSort.scala

* Generalize `Branches` as `Traversal`
* Write `mapBeforeSort`  in terms of it
* Add `normalize` across branches

Generalize branches as traversal

---

build.sbt
project/Dependencies.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/SparkHdfs.scala
sparkcore/src/test/scala/quasar/physical/sparkcore/fs/hdfs/HdfsPackageSpec.scala

Fixes https://github.com/quasar-analytics/quasar/issues/2264

Add support for S3 in spark-hdfs

---

foundation/src/main/scala/quasar/contrib/matryoshka/package.scala

Implement transHyloM in quasar.contrib.matryoshka

---

web/src/main/scala/quasar/api/services/package.scala
web/src/test/scala/quasar/api/services/DataServiceSpec.scala

Fix inability to upload downloaded single zipped file. 
Fixes #2652.

add archive metadata hidden file to single zip download

---

connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala

First steps toward LP => QSU.  Hopefully the stub-ish areas are obvious.

Initial work on ReadLP

---

connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala

Depends on #3003, since I made some changes to things in that PR as well.

Helpers for manipulating QSU

---

connector/src/main/scala/quasar/qscript/TTypes.scala
connector/src/main/scala/quasar/qscript/package.scala
connector/src/main/scala/quasar/qscript/qsu/Graduate.scala
connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/QSUTTypes.scala
connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala

Depends on #3011
The initial structure for `graduate`. What's remaining is `(QSUGraph, QSUGraph) => (QSUGraph, FreeQS, FreeQS)`. This involves finding the common source `Symbol` (just by inspecting nodes/edges, not by inspecting any structure directly) and also running `graduate` manually on the not-common graphs with the common source removed (this will become the `Hole` in the `FreeQS`).

QSU students prepare for graduation

---

connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
foundation/src/main/scala/quasar/contrib/scalaz/NonEmptyListE.scala

Also there was a bug.  'Tis squashed.

LP => QSU Tests

---

connector/src/main/scala/quasar/connector/BackendModule.scala
connector/src/main/scala/quasar/qscript/package.scala
connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala
connector/src/main/scala/quasar/qscript/qsu/Graduate.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/ReifyProvenance.scala

LP to QS using QSU

---

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/Graduate.scala
connector/src/main/scala/quasar/qscript/qsu/MappableRegion.scala
connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala

Nullary and constant handling for QSU

---

core/src/main/scala/quasar/fs/mount/view.scala
core/src/test/scala/quasar/fs/mount/ViewFileSystemSpec.scala
interface/src/test/scala/quasar/main/Fixture.scala
interface/src/test/scala/quasar/main/api/ViewsAndModulesSpec.scala
web/src/test/scala/quasar/api/services/Fixture.scala
web/src/test/scala/quasar/api/services/query/ExecuteServiceSpec.scala
web/src/test/scala/quasar/api/services/query/QueryFixture.scala

Fix compilation of views containing relative imports

---

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/EliminateUnary.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/main/scala/quasar/qscript/qsu/RecognizeDistinct.scala
connector/src/test/scala/quasar/qscript/qsu/EliminateUnarySpec.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala

Collapse wasn't working, so I had to add a `Unary` node which is rewritten away immediately.  Also `LPtoQS` wasn't working at all due to `\circ` precedence.  All that is fixed.  We're very close to graduating.  Just have to get that thesis banged out…

Fixes to reading and rewriting

---

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/EliminateUnary.scala
connector/src/main/scala/quasar/qscript/qsu/Graduate.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/main/scala/quasar/qscript/qsu/RecognizeDistinct.scala
connector/src/test/scala/quasar/qscript/qsu/EliminateUnarySpec.scala
connector/src/test/scala/quasar/qscript/qsu/GraduateSpec.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala

End-to-end queries!

---

connector/src/main/scala/quasar/qscript/qsu/Graduate.scala
connector/src/test/scala/quasar/qscript/qsu/GraduateSpec.scala

Graduate distinct

---

web/src/main/scala/quasar/api/package.scala

Preserve query params upon HTTP redirect

---

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/test/scala/quasar/qscript/qsu/EliminateUnarySpec.scala

This fixes… uh, any query involving `Typecheck`.  :-P

Fixed graph revisiting when rewritten in subgraph

---

web/src/main/scala/quasar/server/Http4sUtils.scala

Enable HTTP/2

---

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/main/scala/quasar/qscript/qsu/ReifyProvenance.scala
connector/src/test/scala/quasar/qscript/qsu/EliminateUnarySpec.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala

Also moves the conversion of `Transpose` -> `LeftShift` to `ApplyProvenance`.
Fixes #3112.

Add property to QSU.Transpose indicating what to retain

---

README.md
foundation/src/main/scala/quasar/contrib/scalaz/package.scala
it/src/test/scala/quasar/server/ServiceSpec.scala
web/src/main/scala/quasar/server/Http4sUtils.scala
web/src/main/scala/quasar/server/PortChangingServer.scala
web/src/main/scala/quasar/server/Server.scala
web/src/main/scala/quasar/server/control.scala
web/src/test/scala/quasar/server/ControlServiceSpec.scala

Cherry pick the fix for server stop on enter to backport

Cherry pick fix server stop on enter

---

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala
foundation/src/main/scala/quasar/contrib/scalaz/MonadState_.scala

Fix handling of Free variables coming out of LP

---

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
foundation/src/main/scala/quasar/contrib/scalaz/MonadState_.scala
it/src/main/resources/tests/caseVariations.test
it/src/main/resources/tests/citiesByLargestZip.test
it/src/main/resources/tests/joins/groupedJoin.test
it/src/main/resources/tests/shortCities.test

Merge this one, not the others.  :-D

All my things

---

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala
connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
foundation/src/main/scala/quasar/contrib/scalaz/MonadState_.scala
it/src/main/resources/tests/caseVariations.test
it/src/main/resources/tests/caseWithGroup.test
it/src/main/resources/tests/citiesByLargestZip.test
it/src/main/resources/tests/joins/groupedJoin.test
it/src/main/resources/tests/shortCities.test

Depends on #3137 
Corrects the issue where we were attempting to project on map key `"-1"`, which doesn't make any sense.  Also I think the code is less bonkers now.

Fix remap offsets through minimization

---

connector/src/main/scala/quasar/qscript/qsu/Access.scala
connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala
connector/src/main/scala/quasar/qscript/qsu/QProv.scala
connector/src/main/scala/quasar/qscript/qsu/ReifyBuckets.scala
connector/src/test/scala/quasar/qscript/qsu/ReifyBucketsSpec.scala

[#3129] Compute the correct source for QSReduce

---

it/src/main/resources/tests/demo/nestedSelectWithReduce.test
it/src/main/resources/tests/different-flattens.test
it/src/main/resources/tests/flattenGroupedObject.test
it/src/main/resources/tests/flattenObjectLike.test
it/src/main/resources/tests/groupByFlatten.test
it/src/main/resources/tests/joins/nonJsJoinCondition.test
it/src/main/resources/tests/joins/symmetricNonJsJoinCondition.test
it/src/main/resources/tests/nestedSelectWithFilter.test
it/src/main/resources/tests/projectFieldWithFlatten.test
it/src/main/resources/tests/reduceNestedSelect.test
it/src/main/resources/tests/unifyFlattenedFields.test
it/src/main/resources/tests/unsupportedTests.test
mongodb/src/test/scala/quasar/physical/mongodb/PlannerLPSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerLogSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala

Attention @jsantos17 and @rintcius!  This will create some (hopefully trivial) merge conflicts with what you're doing.

Working unit tests in QSU

---

connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
it/src/main/resources/tests/demo/nestedSelectWithReduce.test
it/src/main/resources/tests/different-flattens.test
it/src/main/resources/tests/flattenGroupedObject.test
it/src/main/resources/tests/flattenObjectLike.test
it/src/main/resources/tests/groupByFlatten.test
it/src/main/resources/tests/joins/nonJsJoinCondition.test
it/src/main/resources/tests/joins/symmetricNonJsJoinCondition.test
it/src/main/resources/tests/nestedSelectWithFilter.test
it/src/main/resources/tests/projectFieldWithFlatten.test
it/src/main/resources/tests/reduceNestedSelect.test
it/src/main/resources/tests/unifyFlattenedFields.test
it/src/main/resources/tests/union.test
it/src/main/resources/tests/unsupportedTests.test
mongodb/src/test/scala/quasar/physical/mongodb/PlannerLPSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerLogSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala

Depends on #3149 
Spark integration tests spring to life with this change.

Implemented reading of Union nodes from LP

---

connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
it/src/main/resources/tests/caseVariations.test
it/src/main/resources/tests/caseWithGroup.test
it/src/main/resources/tests/citiesByLargestZip.test
it/src/main/resources/tests/fieldWithReduction.test
it/src/main/resources/tests/joins/selfjoinConstantOnLeft.test
it/src/main/resources/tests/joins/selfjoinWithComplexCondition.test
it/src/main/resources/tests/selectCount.test
it/src/main/resources/tests/shortCities.test
it/src/main/resources/tests/union.test

Depends on #3151 
Also filed a bunch of bugs as relevant.

Marked a bunch of mongo bugs as pending

---

connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
it/src/main/resources/tests/caseVariations.test
it/src/main/resources/tests/caseWithGroup.test
it/src/main/resources/tests/citiesByLargestZip.test
it/src/main/resources/tests/demo/nestedSelectWithReduce.test
it/src/main/resources/tests/different-flattens.test
it/src/main/resources/tests/fieldWithReduction.test
it/src/main/resources/tests/flattenGroupedObject.test
it/src/main/resources/tests/flattenObjectLike.test
it/src/main/resources/tests/groupByFlatten.test
it/src/main/resources/tests/joins/nonJsJoinCondition.test
it/src/main/resources/tests/joins/selfjoinConstantOnLeft.test
it/src/main/resources/tests/joins/selfjoinWithComplexCondition.test
it/src/main/resources/tests/joins/symmetricNonJsJoinCondition.test
it/src/main/resources/tests/nestedSelectWithFilter.test
it/src/main/resources/tests/projectFieldWithFlatten.test
it/src/main/resources/tests/reduceNestedSelect.test
it/src/main/resources/tests/selectCount.test
it/src/main/resources/tests/shortCities.test
it/src/main/resources/tests/union.test
it/src/main/resources/tests/unsupportedTests.test

Marked a bunch of tests as pending in marklogic

---

connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala
connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
it/src/main/resources/tests/caseVariations.test
it/src/main/resources/tests/caseWithGroup.test
it/src/main/resources/tests/citiesByLargestZip.test
it/src/main/resources/tests/couchbase/leftKeyJoin.test
it/src/main/resources/tests/couchbase/leftKeyJoinMultipleSelect.test
it/src/main/resources/tests/couchbase/rightKeyJoin.test
it/src/main/resources/tests/demo/nestedSelectWithReduce.test
it/src/main/resources/tests/different-flattens.test
it/src/main/resources/tests/fieldWithReduction.test
it/src/main/resources/tests/filterSkipLimitCount.test
it/src/main/resources/tests/flattenGroupedObject.test
it/src/main/resources/tests/flattenObjectLike.test
it/src/main/resources/tests/groupByFlatten.test
it/src/main/resources/tests/joins/nonJsJoinCondition.test
it/src/main/resources/tests/joins/selfjoinConstantOnLeft.test
it/src/main/resources/tests/joins/selfjoinWithComplexCondition.test
it/src/main/resources/tests/joins/symmetricNonJsJoinCondition.test
it/src/main/resources/tests/nestedSelectWithFilter.test
it/src/main/resources/tests/projectFieldWithFlatten.test
it/src/main/resources/tests/reduceNestedSelect.test
it/src/main/resources/tests/resultFile/basicAnalyticQuery.test
it/src/main/resources/tests/selectCount.test
it/src/main/resources/tests/shortCities.test
it/src/main/resources/tests/union.test
it/src/main/resources/tests/unsupportedTests.test

Depends on #3157
If everything worked out correctly, we should now have a clean build!!!!

Skip a bunch of tests in couchbase

---

.appveyor.yml

Fixes #3144
Hopefully this fixes appveyor…

Remove AppData\Local\Coursier from cache

---

connector/src/test/scala/quasar/qscript/qsu/LPtoQSSpec.scala

Added basic LPtoQSSpec

---

connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala

Part of #3021 
Nothing comes alive because queries are hitting the `ReifyBuckets` error.

Implement FreeMap extraction for DimEdit.

---

core/src/main/scala/quasar/metastore/Queries.scala
core/src/test/scala/quasar/metastore/MetaStoreAccessSpec.scala

Fix false warning about failing to load modules

---

frontend/src/main/scala/quasar/sql/SqlRelation.scala
frontend/src/main/scala/quasar/sql/package.scala
frontend/src/main/scala/quasar/sql/parser.scala
frontend/src/test/scala/quasar/sql/ExprArbitrary.scala
frontend/src/test/scala/quasar/sql/SqlParserSpec.scala
sql/src/main/scala/quasar/sql/compiler.scala
sql/src/main/scala/quasar/sql/semantics.scala

Expression relation no longer requires an alias

---

it/src/main/resources/tests/demo/nestedSelectWithReduce.test
it/src/main/resources/tests/orderByDescAsc.test
yggdrasil/src/main/scala/quasar/yggdrasil/table/BlockStoreColumnarTableModule.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/BlockSortSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/SliceSpec.scala

Fix mimir ordering in different directions. 
Fixes #3183

fix mimir sort when using order by desc and asc

---

it/src/main/resources/tests/flattenOrElseField.test
it/src/main/resources/tests/flattenOrElseFieldUnavailable.test
it/src/main/resources/tests/flattenable.data

add ITs for #2985 and #2960

---

.travis.yml

Disabled couchbase build stage

---

connector/src/main/scala/quasar/fs/InMemory.scala
core/src/main/scala/quasar/fs/mount/module/package.scala
sql/src/test/scala/quasar/sql/helpers.scala
web/src/test/scala/quasar/api/services/DataServiceSpec.scala
web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala

Fixes #3241 
- Also add some tests for `DataServiceSpec` regarding views and modules

Fix bug where `ls` misbehaves in the presence of modules

---

it/src/main/resources/tests/ifundefinedInFunction.test
it/src/main/resources/tests/joins/joinDistinct.test

Add a couple integration tests

---

it/src/main/resources/tests/postgres/stringFunctionsCase.data
it/src/main/resources/tests/postgres/stringFunctionsCase.test
it/src/main/resources/tests/postgres/stringFunctionsOther.data
it/src/main/resources/tests/postgres/stringFunctionsOther.test
rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/planner/PostgresRenderQuery.scala
rdbms/src/main/scala/quasar/physical/rdbms/planner/MapFuncCorePlanner.scala
rdbms/src/main/scala/quasar/physical/rdbms/planner/sql/SqlExpr.scala
rdbms/src/main/scala/quasar/physical/rdbms/planner/sql/SqlExprInstance.scala
rdbms/src/main/scala/quasar/physical/rdbms/planner/sql/SqlExprRenderTree.scala

Part of #3265. Provides support for basic string manipulation functions.

String manipulation for RDBMS/Postgres

---

docker/docker-compose.yml
it/src/main/resources/tests/bigdecimal.test
it/src/main/resources/tests/doubleFlatten.test
it/src/main/resources/tests/doubleFlattenWithIntervening.test
it/src/main/resources/tests/flattenArray.test
it/src/main/resources/tests/flattenNestedObject.test
it/src/main/resources/tests/flattenObject.test
it/src/main/resources/tests/tripleFlatten.test
it/src/main/resources/tests/unifyFlattenedFields.test

Update readonly mongo docker container to 3.4. 
Fixes #3224.

Bump read only mongo docker container version

---

connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala
connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala
connector/src/main/scala/quasar/qscript/qsu/minimizers/MergeReductions.scala
connector/src/main/scala/quasar/qscript/qsu/minimizers/Minimizer.scala
connector/src/main/scala/quasar/qscript/qsu/minimizers/ShiftProjectBelow.scala
connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala

Fixes #3289
This also introduces a real abstraction into `MinimizeAutoJoins` so that we have the ability to better compose these things.

Generalize autojoin minimization to apply inductively

---

scripts/publishJar
version.sbt

Fix publishing of sparkcore jars.

add sparkcore to publishJar

---

connector/src/main/scala/quasar/qscript/qsu/ReifyIdentities.scala

If a `ThetaJoin` branch carries an IV map, we need to remap value access to that side in the join condition.
Also adds a nicer error message for the unimplemented case tracked in #3114.

Remap ThetaJoin condition in ReifyIdentities.

---

docker/Dockerfiles/Marklogic/MarkLogic-Dockerfile
it/src/main/resources/tests/demo/groupedSelectOfNestedReduction.test
it/src/main/resources/tests/flattenGroupedObject.test

Fix checksum yum install failure of Marklogic.rpm.

fix checksum marklogic failure

---

rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsQueryFile.scala

This should print output like:
```
SqlExprTree:
Select
├─ selection
│  ╰─ References
│     ├─ Id(_2)
│     ╰─ Constant(Str(a))
╰─ from(_2)
╰─ SelectRow
├─ selectionInRow(_1)
│  ╰─ *
╰─ fromInRow(_0)
╰─ Table(db.foo)
Raw query:
select row_to_json(row) from (select _2.a from (select * from db.foo) _2) row
DB EXPLAIN output:
QUERY PLAN                       
--------------------------------------------------------
Seq Scan on foo  (cost=0.00..41.88 rows=2550 width=32)
```
In case there's an error on calling the DB EXPLAIN query, the last part will be
```
DB EXPLAIN output: unavailable (error description)
```

RDBMS explain support

---

it/src/main/resources/tests/demo/chained_step1.test
it/src/main/resources/tests/demo/chained_step2.test
it/src/main/resources/tests/demo/chained_step3.test
it/src/main/resources/tests/demo/chained_step4.test
it/src/main/resources/tests/demo/chained_step5.test
it/src/main/resources/tests/demo/chained_step6.test
it/src/main/resources/tests/demo/chained_step7.test
it/src/main/resources/tests/demo/games_step1.test
it/src/main/resources/tests/demo/games_step2.test
it/src/main/resources/tests/demo/games_step3.test
it/src/main/resources/tests/demo/games_step4.test

Fixes https://github.com/quasar-analytics/quasar/issues/3271

Missing 2 integration tests for working demos

---

foundation/src/test/scala/quasar/DateGenerators.scala
mongodb/src/main/scala/quasar/physical/mongodb/MongoDbPlanner.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/assumeReadType.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerQScriptSpec.scala
sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala
version.sbt
web/src/test/scala/quasar/api/services/DataServiceSpec.scala

Merge master into next-major

---

it/src/main/resources/tests/qa/s01_simple_selects/escapy_strings.data
it/src/main/resources/tests/qa/s01_simple_selects/escapy_strings.test
rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/package.scala

Added single quote escaping for RDBMS/Postgres.

---

README.md
core/src/main/scala/quasar/metastore/MetaStore.scala
core/src/main/scala/quasar/metastore/MetaStoreAccess.scala
core/src/main/scala/quasar/metastore/PathedMountConfig.scala
core/src/main/scala/quasar/metastore/Queries.scala
core/src/main/scala/quasar/metastore/Schema.scala
core/src/main/scala/quasar/metastore/package.scala
core/src/test/scala/quasar/metastore/MetaStoreAccessSpec.scala
core/src/test/scala/quasar/metastore/MetaStoreFixture.scala
interface/src/main/scala/quasar/main/MetaStoreLocation.scala
interface/src/main/scala/quasar/main/Quasar.scala
interface/src/test/scala/quasar/main/api/ApiSpec.scala
web/src/main/scala/quasar/api/services/metastore.scala
web/src/test/scala/quasar/api/services/MetastoreServiceSpec.scala

Copy metastore endpoint added.

add copy metastore endpoint

---

repl/src/main/scala/quasar/repl/Main.scala

Fix doc build with type annotation

---

core/src/main/scala/quasar/fs/mount/cache/VCache.scala
core/src/main/scala/quasar/fs/mount/cache/ViewCache.scala
core/src/main/scala/quasar/metastore/MetaStoreAccess.scala
core/src/main/scala/quasar/metastore/Queries.scala
core/src/main/scala/quasar/metastore/package.scala
core/src/test/scala/quasar/fs/cache/VCacheSpec.scala
core/src/test/scala/quasar/fs/cache/ViewCacheArbitrary.scala
core/src/test/scala/quasar/fs/mount/ViewFileSystemSpec.scala
core/src/test/scala/quasar/metastore/MetaStoreAccessSpec.scala
foundation/src/test/scala/quasar/DateGenerators.scala
interface/src/main/scala/quasar/main/ViewCacheRefresh.scala
interface/src/test/scala/quasar/main/CachingSpec.scala
web/src/main/scala/quasar/api/VCacheMiddleware.scala
web/src/main/scala/quasar/api/services/mount.scala
web/src/test/scala/quasar/api/services/DataServiceSpec.scala
web/src/test/scala/quasar/api/services/query/ExecuteServiceSpec.scala

#qz-3358 done
#qz-3359 done
(Tickets will be closed manually since we are merging to next-major.)

Update VCache date handling.

---

frontend/src/main/scala/quasar/data.scala
mongodb/src/main/scala/quasar/physical/mongodb/bsoncodec.scala

All the unit tests should now be passing except for various mongo planner specs, which will be addressed separately.

Update Bson date time codecs in next-major

---

yggdrasil/src/main/scala/quasar/yggdrasil/vfs/vfs.scala
yggdrasil/src/test/scala/quasar/yggdrasil/vfs/FreeVFSSpecs.scala

Add Mimir VFS VERSION

---

rdbms/src/main/scala/quasar/physical/rdbms/Interpreter.scala
rdbms/src/main/scala/quasar/physical/rdbms/Rdbms.scala

RDBMS: Fix connection pool leak

---

build.sbt
scripts/constants

Fix `web/assembly`

---

it/src/main/resources/tests/groupByFlatten.test

Should get the build functioning again.

Disable problematic test

---

.jvmopts
it/src/main/resources/tests/groupByFlatten.test
it/src/test/scala/quasar/regression/QueryRegressionTest.scala

By third time, I meant fourth.

Really fix the build this time

---

connector/src/main/scala/quasar/qscript/qsu/minimizers/CollapseShifts.scala
connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala
it/src/main/resources/tests/groupByFlatten.test

Sneaky bug uncovered via switching to scala 2.12, HT: @djspiewak for supplying the fix.

Restore shifts lost during coalescence

---

.travis.yml
interface/src/main/scala/quasar/main/package.scala
repl/src/main/scala/quasar/repl/Main.scala
web/src/main/scala/quasar/server/Http4sUtils.scala
web/src/main/scala/quasar/server/Server.scala

Revert enter fix

---

connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala
connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala

Only attempt to `expandSecondOrder` when none of the minimizers apply to the candidate roots.
#qz-3599 Done

Avoid aggressive expandSecondOrder in MinimizeAutoJoin

---

build.sbt
project/Dependencies.scala

Update niflheim akka version

---

build.sbt
project/build.properties

Updated to sbt 1.1

---

connector/src/main/scala/quasar/qscript/MapFunc.scala
connector/src/main/scala/quasar/qscript/MapFuncCore.scala
connector/src/main/scala/quasar/qscript/RenderQScriptDSL.scala
couchbase/src/main/scala/quasar/physical/couchbase/planner/MapFuncCorePlanner.scala
foundation/src/main/scala/quasar/DateTimeInterval.scala
foundation/src/main/scala/quasar/OffsetDate.scala
foundation/src/test/scala/quasar/DateGenerators.scala
frontend/src/main/scala/quasar/DataDateTimeExtractors.scala
frontend/src/main/scala/quasar/std/date.scala
frontend/src/test/scala/quasar/std/SimplifyStdLibSpec.scala
frontend/src/test/scala/quasar/std/StdLibSpec.scala
it/src/test/scala/quasar/physical/mimir/MimirStdLibSpec.scala
marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncCorePlanner.scala
marklogic/src/main/scala/quasar/physical/marklogic/xquery/fn.scala
marklogicIt/src/test/scala/quasar/physical/marklogic/qscript/MarkLogicStdLibSpec.scala
mimir/src/main/scala/quasar/mimir/MapFuncCorePlanner.scala
mimir/src/main/scala/quasar/mimir/TimeLib.scala

Add unit tests for datetime functions on next-major

---

connector/src/main/scala/quasar/qscript/MapFuncCore.scala
connector/src/main/scala/quasar/qscript/construction.scala
connector/src/test/scala/quasar/qscript/MapFuncCoreSpec.scala

Add StaticMapSuffix and use to generalize normalizations of map ops

---

.travis.yml

Added another workaround to travis' broken stage caching

---

mimir/src/main/scala/quasar/mimir/EquiJoinPlanner.scala
mimir/src/main/scala/quasar/mimir/Mimir.scala
mimir/src/main/scala/quasar/mimir/MimirCake.scala
mimir/src/main/scala/quasar/mimir/MimirRepr.scala
mimir/src/main/scala/quasar/mimir/QScriptCorePlanner.scala
mimir/src/main/scala/quasar/mimir/ShiftedReadPlanner.scala

Mimir reorg

---

mongodb/src/main/scala/quasar/physical/mongodb/planner/assumeReadType.scala
mongodb/src/test/resources/planner/plan_distinct_with_sum,_group,_and_orderBy.txt
mongodb/src/test/resources/planner/plan_distinct_with_sum_and_group.txt
mongodb/src/test/resources/planner/plan_expr3_with_grouping.txt
mongodb/src/test/resources/planner/plan_group_by_flattened_field.txt
mongodb/src/test/resources/planner/plan_group_by_simple_expression.txt
mongodb/src/test/resources/planner/plan_having_with_multiple_projections.txt
mongodb/src/test/resources/planner/plan_multiple_expressions_using_same_field.txt
mongodb/src/test/resources/planner/plan_non-equi_join.txt
mongodb/src/test/resources/planner/plan_simple_cross.txt
mongodb/src/test/resources/planner/plan_sum_flattened_int_arrays.txt
mongodb/src/test/resources/planner/plan_unify_flattened_fields.txt
mongodb/src/test/resources/planner/plan_unify_flattened_with_double-flattened.txt
mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/planner/assumeReadTypeSpec.scala

* Elide `assumeReadType`-guards for `Union` and `Subset`
* Also started adding property tests for `assumeReadType`
#qz-3584 Done

assumeReadType for Union and Subset

---

mongodb/src/test/scala/quasar/physical/mongodb/PlannerPropSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala

#qz-2667 done
This marks the last `notOnPar` tests with their issue number. There's one test I have left as `notOnPar` because I don't fully understand what it's trying to test.

Mark PlannerPropSpec tests pending with issue number

---

mongodb/src/main/scala/quasar/physical/mongodb/MongoDbPlanner.scala
mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOp3_4.scala
mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOpCore.scala
mongodb/src/main/scala/quasar/physical/mongodb/workflow/package.scala
mongodb/src/main/scala/quasar/physical/mongodb/workflowtask/package.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerWorkflowHelpers.scala

Add WorkflowOp3_4 with $AddFieldsF

---

mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala

#qz-1880 done
The test checks the query in the issue compile to QScript we know can be in turn be compiled into an efficient plan for Mongo.

Add test verifying we $match  before $unwind(ing)

---

mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala

Fix sql2 mongo spec expectation.

---

.travis.yml

#qz-3637 Done (maybe for reals this time)

Add preBuild before connector-specific integration tests.

---

blueeyes/src/main/java/quasar/precog/BitSet.java

I couldn't develop the benchmark dashboard without fixing this, so here it is :)

Fix BitSet#setLength loop

---

connector/src/main/scala/quasar/qscript/construction.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
connector/src/main/scala/quasar/qscript/qsu/ReifyAutoJoins.scala
connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala
connector/src/test/scala/quasar/qscript/qsu/ReifyAutoJoinsSpec.scala

Fix bug ReifyAutoJoins and add unit tests.

---

mongoIt/src/test/scala/quasar/physical/mongodb/fs/MongoDbIOSpec.scala
mongodb/src/main/scala/quasar/physical/mongodb/MongoDbIO.scala

add test capturing https://jira.mongodb.org/browse/JAVA-2779
relates to #qz-3565

add rename test

---

frontend/src/main/scala/quasar/std/string.scala
frontend/src/test/scala/quasar/std/ConstantPlanStdLibSpec.scala
frontend/src/test/scala/quasar/std/SimplifyConstantPlanStdLibSpec.scala
frontend/src/test/scala/quasar/std/StdLibSpec.scala

Fix substring simplifier

---

mongodb/src/main/scala/quasar/physical/mongodb/bsoncodec.scala

Leaving tests to CI.
Edit: Oh yeah, no CI on next-major. Doing it locally too.

Encode days in intervals as 24 hours in Mongo

---

frontend/src/main/scala/quasar/std/math.scala

Good that this was caught.
#qz-3731 Done

Subtract coherence fix

---

project/plugins.sbt
project/project/plugins.sbt

Using the feature label just so it's easier to pick out the published version.

Updated to snapshot-dependent build of sbt-slamdata

---

connector/src/main/scala/quasar/fs/QueryFile.scala
it/src/test/scala/quasar/fs/FileSystemTest.scala
it/src/test/scala/quasar/fs/ManageFilesSpec.scala
it/src/test/scala/quasar/fs/QueryFilesSpec.scala
it/src/test/scala/quasar/fs/ReadFilesSpec.scala
it/src/test/scala/quasar/fs/WriteFilesSpec.scala
it/src/test/scala/quasar/regression/QueryRegressionTest.scala
mongodb/src/main/scala/quasar/physical/mongodb/MongoDbIO.scala
mongodb/src/main/scala/quasar/physical/mongodb/fs/fsops.scala
mongodb/src/main/scala/quasar/physical/mongodb/fs/managefile.scala

Remove rmdir mvdir support from mongodb

---

connector/src/main/scala/quasar/qscript/qsu/FoldConstantReductions.scala
connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala
it/src/main/resources/tests/demo/reductionsonnull.test

I'm not sure I'm doing the right thing with providence here, hence the unused `StateT` over `QDims`. If I am, I can delete that.

Simplify some constant reductions in QSU

---

build.sbt

This makes it considerably easier to publish branch snapshots.

Tweak local settings to allow for publication of branch snapshots

---

it/src/main/resources/tests/flattenGroupedMap.test
it/src/main/resources/tests/flattenMap.test
it/src/main/resources/tests/flattenMapKeyWildcard.test
it/src/main/resources/tests/flattenMapLike.test
it/src/main/resources/tests/flattenNestedMap.test
it/src/main/resources/tests/shiftMapKeys.test
it/src/main/resources/tests/shiftMapKeysDistinctWildcard.test
it/src/main/resources/tests/shiftMapKeysNested.test
it/src/main/resources/tests/shiftMapKeysWildcard.test

Add tests for flattening and shifting map keys 
Also some renaming
Relates to #qz-3696 and #qz-3746

Add tests for flattening and shifting map keys

---

project/CachedCi.scala

This might fix hoarder for integration tests as well, now that I think about it…

Revised hoarder's Travis semantics to take our build stages into account

---

.travis.yml

There is no way I will regret this.

Increased travis_wait timeout. This is a good idea.

---

it/src/main/resources/tests/demo/nestedreductionsonnull.test
it/src/main/resources/tests/demo/reductionsonnull.test
it/src/main/resources/tests/demo/selectConcat.test
it/src/main/resources/tests/demo/timeSeriesAggregation.test
it/src/main/resources/tests/flattenMapKeyWildcard.test
it/src/main/resources/tests/flattenNestedMap.test
it/src/main/resources/tests/qa/s07_join/joinSubSelects.test
it/src/main/resources/tests/qa/s07_join/selfjoinWithComplexCondition.test
it/src/main/resources/tests/qa/s10_datetime/extract_dates.test
it/src/main/resources/tests/shiftMapKeysDistinctWildcard.test
it/src/main/resources/tests/shiftMapKeysNested.test
it/src/main/resources/tests/shiftMapKeysWildcard.test
it/src/main/resources/tests/sortProjectLimit.test
it/src/main/resources/tests/temporal/datePartsConverted.test
it/src/main/resources/tests/temporal/datePartsConvertedSimple.test
it/src/main/resources/tests/temporal/days.test
it/src/main/resources/tests/temporal/groupByMonth.test
it/src/main/resources/tests/temporal/intervalWithDay.test
it/src/main/resources/tests/temporal/simple_date_filter.test
it/src/main/resources/tests/temporal/simple_timestamp_filter.test
it/src/main/resources/tests/temporal/simple_to_timestamp_filter.test
it/src/main/resources/tests/temporal/timestampRead.test

Fix JSON format of flattenNestedMap.test

---

.travis.yml

Add travis encrypted keys for GitHub and Encryption Password.

travis encrypt github and encryption keys

---

mongoIt/src/test/scala/quasar/physical/mongodb/MongoDbStdLibSpec.scala

Fix LocalDateTime property test in mongodb std lib 

---

.travis.yml

add travis wait 30 to aws s3 cache download

---

frontend/src/test/scala/quasar/std/ConstantPlanStdLibSpec.scala
frontend/src/test/scala/quasar/std/SimplifyConstantPlanStdLibSpec.scala
frontend/src/test/scala/quasar/std/StdLibSpec.scala
marklogicIt/src/test/scala/quasar/physical/marklogic/qscript/MarkLogicStdLibSpec.scala
mongodb/src/main/scala/quasar/physical/mongodb/bson.scala
mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOpCore.scala
mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerLPSpec.scala
mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala

Improve FuncHandler

---

project/build.properties

There's apparently big improvements in file watcher latency and even build times for 1.1.5, so I thought it might be worth upgrading.

Update SBT to 1.1.5

---

api/src/main/scala/quasar/api/QueryEvaluator.scala
api/src/main/scala/quasar/api/ResourceDiscovery.scala
api/src/main/scala/quasar/api/ResourceError.scala
api/src/main/scala/quasar/api/ResourcePath.scala
api/src/test/scala/quasar/api/MockQueryEvaluator.scala
api/src/test/scala/quasar/api/ResourceNameGenerator.scala
api/src/test/scala/quasar/api/ResourcePathGenerator.scala
api/src/test/scala/quasar/api/ResourcePathSpec.scala
build.sbt
core/src/main/scala/quasar/FederatedQuery.scala
core/src/main/scala/quasar/FederatingQueryEvaluator.scala
core/src/main/scala/quasar/QueryFederation.scala
core/src/main/scala/quasar/Source.scala
core/src/main/scala/quasar/package.scala
core/src/test/scala/quasar/FederatingQueryEvaluatorSpec.scala
foundation/src/main/scala/quasar/Disposable.scala

Additional instances for
* `quasar.Disposable`
* `quasar.api.QueryEvaluator`
* `quasar.Source`
* `quasar.QueryFederation`
Depends on #3579.

Additional typeclass instances for recently introduced types

---

mimir/src/main/scala/quasar/mimir/SlamEngine.scala

#qz-3821 done
```
(v42.2.1-4442d77) 💪 $ ls
localfs/
mimir/
s3/
(v42.2.1-4442d77) 💪 $ ls localfs
bin/
boot/
...
(v42.2.1-4442d77) 💪 $ cd localfs
(v42.2.1-4442d77) 💪 $ ls
bin/
boot/
...
(v42.2.1-4442d77) 💪 $ ls bin
bash
bunzip2
...
```

List contents of both lwc and mimir

---

yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala

The previous `isEmpty` check on `ltail` and `rtail` evaluates the first effect from each, however one or both tails are then passed to one of the join handling functions, resulting in that same effect being evaluated again. This causes problems when the intermediate `Step` effects are not repeatable (like consuming bytes from a network socket).

Avoid evaluating Slices effects multiple times when performing cross-joins

---

mimir/src/main/scala/quasar/mimir/QScriptCorePlanner.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
yggdrasil/src/test/scala/quasar/yggdrasil/LeftShiftSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala

leftovers that didn't make it in #3597

Leftshift OnUndefined.Emit in SlamEngine (part 2)

---

yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala

extract some functions to make `leftshift` easier to understand

leftshift untangling

---

project/Dependencies.scala

This should make the build reproducible again.

Updated iota

---

frontend/src/test/scala/quasar/DataGenerators.scala
frontend/src/test/scala/quasar/QDataDataSpec.scala
frontend/src/test/scala/quasar/RepresentableData.scala
frontend/src/test/scala/quasar/TypeGenerators.scala
interface/src/test/scala/quasar/main/prettify.scala
project/Dependencies.scala

Also adds recursive generator for `Data` so we can generate `Data` that has nested objects/arrays.

Upgrade qdata

---

mimir/src/main/scala/quasar/mimir/ArrayLib.scala
mimir/src/main/scala/quasar/mimir/InfixLib.scala
mimir/src/main/scala/quasar/mimir/MathLib.scala
mimir/src/main/scala/quasar/mimir/ReductionLib.scala
mimir/src/main/scala/quasar/mimir/StdLib.scala
mimir/src/main/scala/quasar/mimir/StringLib.scala
mimir/src/main/scala/quasar/mimir/TimeLib.scala
mimir/src/main/scala/quasar/mimir/TypeLib.scala
yggdrasil/src/main/scala/quasar/yggdrasil/bytecode/Library.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/CFN.scala

Also delete the rest of the precog function names.

Delete the precog libs

---

mimir/src/main/scala/quasar/mimir/Precog.scala
niflheim/src/main/scala/quasar/niflheim/NIHDBActor.scala

Might as well delete stuff like this when I find it.

Delete some misc unused things

---

.travis.yml
project/CachedCi.scala
project/plugins.sbt
scripts/s3Cache

I've confirmed locally that hoarder cannot handle quasar for some reason. I'm not sure why, but it appears to be the case. Fortunately, @nicflores's S3 stuff should ensure that we're not completely bonkers on build times, but it's going to be unfortunate. The PR compilation stage will always be from scratch now. *grumble grumble grumble*

Removed hoarder

---

it/src/main/resources/tests/joins/changedTestStatusInterim.test
it/src/main/resources/tests/multitypeFlatten.test
it/src/main/resources/tests/null/nullTestExprsWithMissing.test
it/src/main/resources/tests/temporal/extract_dates.test
it/src/main/resources/tests/typeOf.test

Various improvements found during auditing ITs

various IT improvements

---

blueeyes/src/main/java/quasar/precog/BitSet.java
yggdrasil/src/main/scala/quasar/yggdrasil/Config.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ArrayColumn.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ArrayView.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/vfs.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/SliceSpec.scala

Still not sure about `ReductionLib`.

Table.fromRValuesStream cleanup

---

it/src/main/resources/tests/temporal/toDatetimeFunctionsInvalidData.test
it/src/main/resources/tests/types.data
mimir/src/main/scala/quasar/mimir/TimeLib.scala
repl/src/main/scala/quasar/repl/Evaluator.scala

Also, in repl don't exit in case a bug is hit but show the exception instead

fix NPE converting from string to date/time in mimir

---

foundation/src/main/scala/quasar/contrib/cats/stateT.scala
foundation/src/test/scala/quasar/EffectfulQSpec.scala
impl/src/main/scala/quasar/impl/storage/IndexedStore.scala
impl/src/main/scala/quasar/impl/storage/PureIndexedStore.scala
impl/src/test/scala/quasar/impl/storage/IndexedStoreSpec.scala
impl/src/test/scala/quasar/impl/storage/PureIndexedStoreSpec.scala
mimir/src/main/scala/quasar/mimir/storage/MimirIndexedStore.scala
mimir/src/main/scala/quasar/mimir/storage/StoreKey.scala
mimir/src/test/scala/quasar/mimir/storage/MimirIndexedStoreSpec.scala

Introduces the `IndexedStore` abstraction and includes an implementation backed by `mimir`.

IndexedStore

---

mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala
mimir/src/test/scala/quasar/mimir/storage/MimirPTableStoreSpec.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/VFSColumnarTableModule.scala

This should allow us to actually store prepared tables in nihdb. Note that the dependent types are a little fiddly, especially within `for`-comprehensions.

Implement ptable store

---

project/Dependencies.scala

Upgraded to specs2 4.1.2

---

impl/src/main/scala/quasar/impl/table/PreparationsManager.scala
impl/src/test/scala/quasar/impl/table/PreparationsManagerSpec.scala

A `JobManager` by any other name…

PreparationsManager

---

mimir/src/main/scala/quasar/mimir/MapFuncCorePlanner.scala
yggdrasil/src/main/scala/quasar/yggdrasil/TransSpecModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnSupport.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/SliceTransform.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/cf/Util.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/SliceSpec.scala

Unit tests are a bit lacking because I'm in a hurry but I'm relatively certain that our test coverage is sufficient via the other test suites (especially `StdLibSpec`).

Implemented IfUndefined as a primitive in mimir

---

repl/src/main/scala/quasar/repl/Command.scala
repl/src/main/scala/quasar/repl/Evaluator.scala

add NoOp command in repl and avoid escaping in regex where possible

add NoOp command in repl 

---

impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
impl/src/main/scala/quasar/impl/external/Plugin.scala

[ch939]
this should help debug version incompatibilities.

Log plugin version when loading

---

blueeyes/src/main/java/quasar/precog/BitSet.java
blueeyes/src/test/scala/quasar/precog/BitSetSpec.scala
it/src/main/resources/tests/veryHeterogeneousFlattenArrayIndexWithField.test

Assigning to both @rintcius and @alissapajer in the interest of urgency (I don't know what Rintcius' schedule looks like for the rest of the day). Either of you should feel free to merge. Any review comments made post-merge will be addressed in a follow-up PR. I'll try to address anything pre-merge as quickly as possible.
[ch994]

Fixed post-projection of sparsenByMod index when mod > 64

---

mimir/src/main/scala/quasar/mimir/evaluate/FederatedShiftedReadPlanner.scala
mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
yggdrasil/src/main/scala/quasar/yggdrasil/TableModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/package.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
yggdrasil/src/test/scala/quasar/yggdrasil/ArbitrarySValue.scala
yggdrasil/src/test/scala/quasar/yggdrasil/CogroupSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/LeftShiftSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/SampleData.scala
yggdrasil/src/test/scala/quasar/yggdrasil/TakeRangeSpecs.scala
yggdrasil/src/test/scala/quasar/yggdrasil/TestIdentities.scala
yggdrasil/src/test/scala/quasar/yggdrasil/ToArraySpecs.scala
yggdrasil/src/test/scala/quasar/yggdrasil/TransformSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/PartitionMergeSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/SampleSpec.scala

Misc fromRValues cleanup

---

impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
repl/src/main/resources/log4j.properties

Previously we warned on any, which meant we always warned.

Only warn when loading fails for all datasource kinds

---

connector/src/main/scala/quasar/connector/package.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala

catch LinkageError and raise as IncompatibleDatasourceException

---

api/src/test/scala/quasar/api/table/MockTables.scala
api/src/test/scala/quasar/api/table/MockTablesSpec.scala
api/src/test/scala/quasar/api/table/TablesSpec.scala

Expand MockTables to handle more preparation-related requests

---

yggdrasil/src/main/scala/quasar/yggdrasil/NoCsvEscape.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala

Implement tri-numeric support in renderCsv

---

repl/src/main/scala/quasar/repl/Evaluator.scala
yggdrasil/src/main/scala/quasar/yggdrasil/util/NullRemover.scala

Move NullRemover into quasar.yggdrasil.util

---

foundation/src/main/scala/quasar/contrib/scala/package.scala
mimir/src/main/scala/quasar/mimir/MapFuncCorePlanner.scala
mimir/src/main/scala/quasar/mimir/QScriptCorePlanner.scala
mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
qsu/src/main/scala/quasar/qsu/MinimizeAutoJoins.scala
qsu/src/main/scala/quasar/qsu/QScriptUniform.scala
qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala
yggdrasil/src/main/scala/quasar/yggdrasil/jdbm3/JDBMRawSortProjection.scala
yggdrasil/src/main/scala/quasar/yggdrasil/nihdb/SegmentsWrapper.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/BlockStoreColumnarTableModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/IndicesModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/SamplableTableModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/SingletonColumn.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/SliceTransform.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/cf/Util.scala
yggdrasil/src/test/scala/quasar/yggdrasil/CanonicalizeSpecs.scala
yggdrasil/src/test/scala/quasar/yggdrasil/nihdb/SegmentsWrapperSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/SliceSpec.scala

Singleton columns

---

repl/src/main/scala/quasar/repl/Evaluator.scala

in repl also handle errors that are raised in stream

---

api/src/test/scala/quasar/api/datasource/DatasourcesSpec.scala
connector/src/main/scala/quasar/connector/HeavyweightDatasourceModule.scala
connector/src/main/scala/quasar/connector/LightweightDatasourceModule.scala
impl/src/main/scala/quasar/impl/DatasourceModule.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalDatasourceModule.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceControl.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala
impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala
impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala
impl/src/test/scala/quasar/impl/datasources/MockDatasourceControl.scala

Sanitize config of secret key.

sanitize datasource config

---

mimir/src/main/scala/quasar/mimir/EquiJoinPlanner.scala
mimir/src/main/scala/quasar/mimir/QScriptCorePlanner.scala
niflheim/src/main/scala/quasar/niflheim/NIHDBActor.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/VFSColumnarTableModule.scala
yggdrasil/src/test/scala/quasar/yggdrasil/nihdb/NIHDBAkkaSetup.scala
yggdrasil/src/test/scala/quasar/yggdrasil/nihdb/SegmentsWrapperSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/VFSColumnarTableModuleSpec.scala

Verified pretty well by the integration tests (though the cartesian case is apparently never hit with large datasets; perhaps for the best).
[ch158]

Cache holes in branching nodes

---

it/src/main/resources/tests/veryHeterogeneousShiftArrayValueWithFieldOnMap.test
mimir/src/main/scala/quasar/mimir/QScriptCorePlanner.scala

Use ShiftType in mimir's evaluation of LeftShift

---

mimir/src/main/scala/quasar/mimir/ReductionLib.scala
yggdrasil/src/main/scala/quasar/yggdrasil/nihdb/NIHDBProjection.scala
yggdrasil/src/main/scala/quasar/yggdrasil/nihdb/SegmentsWrapper.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/DerefSlice.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/SliceTransform.scala
yggdrasil/src/test/scala/quasar/yggdrasil/CanonicalizeSpecs.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/BlockStoreTestSupport.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleTestSupport.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/CompactSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/SliceSpec.scala

Extract `Slice.replaceColumnImpl` so that we also replace the column impl where `Slice` is extended (ie in `SegmentsWrapper` and `DerefSlice`).
Also a couple more places to replace `new Slice` with `Slice.apply`

extract Slice.replaceColumnImpl

---

blueeyes/src/main/scala/quasar/precog/common/CValue.scala
blueeyes/src/main/scala/quasar/precog/common/QDataRValue.scala
blueeyes/src/test/scala/quasar/precog/common/CValueGenerators.scala
blueeyes/src/test/scala/quasar/precog/common/QDataRValueSpec.scala
blueeyes/src/test/scala/quasar/precog/common/RValueGenerators.scala
common/src/main/scala/quasar/common/data/Data.scala
common/src/main/scala/quasar/common/data/QDataData.scala
common/src/test/scala/quasar/common/data/DataGenerators.scala
foundation/src/test/scala/quasar/pkg/TestsPackage.scala

QData[RValue]

---

it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala

Refactor regression test runner to use portable file paths

---

frontend/src/test/scala/quasar/std/StdLibSpec.scala
mimir/src/main/scala/quasar/mimir/TimeLib.scala

fix to_timestamp for integer values which are not a Long

---

api/src/main/scala/quasar/api/table/TableError.scala
core/src/main/scala/quasar/Variables.scala
repl/src/main/scala/quasar/repl/Command.scala
repl/src/main/scala/quasar/repl/Evaluator.scala
repl/src/main/scala/quasar/repl/Main.scala
repl/src/main/scala/quasar/repl/Repl.scala

commands added:
```
table (list | ls)
table add [name] [query]
table prepare [uuid]
table (cancelPreparation | cancel) [uuid]
table (preparedData | data) [uuid]
```
[ch1852]

add table api commands to repl

---

build.sbt
common/src/main/scala/quasar/common/data/PreciseKeys.scala
connector/src/main/scala/quasar/connector/Datasource.scala
connector/src/main/scala/quasar/connector/HeavyweightDatasourceModule.scala
connector/src/main/scala/quasar/connector/LightweightDatasourceModule.scala
connector/src/main/scala/quasar/connector/datasource/HeavyweightDatasource.scala
connector/src/main/scala/quasar/connector/datasource/LightweightDatasource.scala
connector/src/test/scala/quasar/connector/DatasourceSpec.scala
foundation/src/main/scala/quasar/time/DateTimeUtil.scala
frontend/src/main/scala/quasar/frontend/data/DataCodec.scala
frontend/src/test/scala/quasar/frontend/data/DataCodecSpec.scala
impl/src/main/scala/quasar/impl/datasource/ByNeedDatasource.scala
impl/src/main/scala/quasar/impl/datasource/ConditionReportingDatasource.scala
impl/src/main/scala/quasar/impl/datasource/FailedDatasource.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalDatasource.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalDatasourceModule.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala
impl/src/main/scala/quasar/impl/parse/QDataFacade.scala
impl/src/main/scala/quasar/impl/parse/QDataPreciseFacade.scala
impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala
impl/src/test/scala/quasar/impl/parse/QDataFacadeSpec.scala
impl/src/test/scala/quasar/impl/parse/QDataPreciseFacadeSpec.scala
it/src/main/resources/tests/temporal/simple_date_filter.test
mimir/src/main/scala/quasar/mimir/evaluate/FederatedShiftedReadPlanner.scala
mimir/src/main/scala/quasar/mimir/evaluate/QueryAssociate.scala
project/Dependencies.scala
run/src/main/scala/quasar/run/ResourceRouter.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala

and other adventures.
[ch1575]

A Datasource has a QueryEvaluator rather than is one

---

mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala

add signal to track whether write in MimirPTableStore has completed

---

mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala
niflheim/src/main/scala/quasar/niflheim/NIHDBActor.scala

Assigning this to @rintcius but I'm going to merge it myself since he's out. This is a straightforward correction of the remaining blocker issue in #3801

add signal to track whether write in MimirPTableStore has completed (with closing fix)

---

connector/src/main/scala/quasar/connector/QScriptEvaluator.scala
mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
mimir/src/main/scala/quasar/mimir/package.scala
qscript/src/main/scala/quasar/qscript/package.scala

Remove some more implicits

---

it/src/main/resources/tests/real-giraffe.data
it/src/main/resources/tests/shiftRealGiraffe.test

Added an integration test for ch2113

---

yggdrasil/src/test/scala/quasar/yggdrasil/TableModuleTestSupport.scala
yggdrasil/src/test/scala/quasar/yggdrasil/TransformSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleTestSupport.scala

Enable all of ColumnarTableModuleSpec

---

qscript/src/main/scala/quasar/qscript/construction.scala

Newlines are my sunshine 🌻

---

project/Dependencies.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/SlicePlate.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/SlicePlateSpec.scala

First cut at `SlicePlate`. There probably should be a ticket for this. I forgot to make one.
Anyway, it's missing tests for hitting column limits and things, but the code which implements that is very simple. I'll come back and write tests which specifically exercise those cases. For now, this is enough to get us started.

I ask nothing more than their Slice on a Plate!

---

qsu/src/main/scala/quasar/qsu/ApplyProvenance.scala

Optimize provenance computation for Map

---

frontend/src/test/scala/quasar/ParseInstructionSpec.scala

Add some more Pivot tests

---

impl/src/test/scala/quasar/impl/table/PreparationsManagerSpec.scala

Removed flaky assertion (there's no way to do it reliably)

---

yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/SlicePlate.scala
yggdrasil/src/test/scala/quasar/yggdrasil/table/SlicePlateSpec.scala

Versioning as **feature** since it doesn't break a public API.
[ch2718]

Added support for parsing precise via SlicePlate

---

sql/src/test/scala/quasar/sql/SqlParserSpec.scala

Add sql parser specs for a couple addition cases that used to not work

---

api/src/main/scala/quasar/api/table/Tables.scala
api/src/test/scala/quasar/api/table/MockTables.scala
api/src/test/scala/quasar/api/table/TablesSpec.scala
impl/src/main/scala/quasar/impl/table/DefaultTables.scala
impl/src/test/scala/quasar/impl/table/DefaultTablesSpec.scala
run/src/main/scala/quasar/run/Quasar.scala

Live access

---

it/src/main/resources/tests/deep-giraffe-array2.data
it/src/main/resources/tests/shiftDeepGiraffeArrayDeref.test
it/src/main/resources/tests/shiftDeepGiraffeArrayDeref2.test
qscript/src/main/scala/quasar/qscript/rewrites/Optimize.scala
qscript/src/test/scala/quasar/qscript/rewrites/OptimizeSpec.scala

Implement InterpretedRead rewrites through static array derefs

---

frontend/src/test/scala/quasar/ParseInstructionSpec.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/PivotPlate.scala

Fixed issue with emiting FinishRow on a singleton vector pivot

---

mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala

compact/canonicalize in execute (after evaluation)

---

qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
qscript/src/main/scala/quasar/qscript/rewrites/Coalesce.scala
qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
qscript/src/main/scala/quasar/qscript/rewrites/Rewrite.scala
qscript/src/main/scala/quasar/qscript/rewrites/ShiftRead.scala
qscript/src/main/scala/quasar/qscript/rewrites/SimplifyJoin.scala
qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala
qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
qsu/src/main/scala/quasar/qsu/MinimizeAutoJoins.scala
qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala

This reverts commit 3df0d9f613f1bc4fef0aeecd82bda2ddee2c205c, reversing
changes made to cb500fe88d7f4da7973d5f320274f094c1fe5a7d.

Revert "82.0.7: No more Normalizable"

---

qscript/src/test/scala/quasar/qscript/provenance/DimensionsGenerator.scala

Reduce the size of generated Dimensions in tests.

---

it/src/test/scala/quasar/regression/QScriptCount.scala
it/src/test/scala/quasar/regression/QScriptRegressionSpec.scala
it/src/test/scala/quasar/regression/RegressionQScriptEvaluator.scala
it/src/test/scala/quasar/regression/RegressionQueryEvaulator.scala

Add QScript regression test

---

impl/src/main/scala/quasar/impl/datasource/local/EvaluableLocalDatasource.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalParsedDatasource.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalParsedDatasourceModule.scala
impl/src/main/scala/quasar/impl/datasource/local/package.scala
impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
impl/src/test/scala/quasar/impl/datasource/local/LocalDatasourceSpec.scala
it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala
repl/src/main/scala/quasar/repl/Main.scala
run/src/main/scala/quasar/run/Quasar.scala

Add LocalParsedDatasource

---

project/Dependencies.scala

Add woodstox as a dep as a quick and dirty way to get azure working

---

impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala

Mark test as flaky

---

ejson/src/main/scala/quasar/ejson/QDataEJson.scala
ejson/src/main/scala/quasar/ejson/TemporalKeys.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala
impl/src/main/scala/quasar/impl/schema/QDataCompressedSst.scala
impl/src/main/scala/quasar/impl/schema/SstConfig.scala
impl/src/main/scala/quasar/impl/schema/SstSchema.scala
impl/src/main/scala/quasar/impl/schema/package.scala
impl/src/test/scala/quasar/impl/schema/ProgressiveSstSpec.scala
impl/src/test/scala/quasar/impl/schema/QDataCompressedSstSpec.scala
sst/src/main/scala/quasar/sst/compression.scala
sst/src/main/scala/quasar/sst/strings.scala
sst/src/test/scala/quasar/sst/CompressionSpec.scala
sst/src/test/scala/quasar/sst/StringsSpec.scala

Compress SSTs during construction

---

qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
qscript/src/main/scala/quasar/qscript/rewrites/Rewrite.scala
qscript/src/main/scala/quasar/qscript/rewrites/ThetaToEquiJoin.scala
qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala
qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
qscript/src/test/scala/quasar/qscript/rewrites/ThetaToEquiJoinSpec.scala

Tests for normalizing static projections

---

connector/src/main/scala/quasar/connector/QScriptEvaluator.scala
it/src/test/scala/quasar/regression/RegressionQScriptEvaluator.scala
mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala
qscript/src/main/scala/quasar/qscript/TTypes.scala
qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
qscript/src/main/scala/quasar/qscript/rewrites/Rewrite.scala
qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala
qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
qsu/src/main/scala/quasar/qsu/QSUTTypes.scala

Does not change the rewrites that are applied or how they are applied.

Clean up the types in qscript rewrites

---

qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala
qsu/src/main/scala/quasar/qsu/MinimizeAutoJoins.scala
qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala

Frees qsu from a dependency on `Normalizable`.

Move freeMF to MapFuncCore

---

build.sbt
foundation/src/main/scala/quasar/Disposable.scala
foundation/src/main/scala/quasar/contrib/fs2/convert.scala
foundation/src/main/scala/quasar/contrib/scalaz/MonadError_.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala
repl/src/main/scala/quasar/repl/Evaluator.scala
repl/src/main/scala/quasar/repl/Main.scala
repl/src/main/scala/quasar/repl/Repl.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala

A bunch of changes cleaning up `repl`, trying to make things better, trying to find the memory leak and essentially just failing.

Repl cleanup and things

---

build.sbt
it/src/test/scala/quasar/physical/mimir/MimirCompressedEvaluationSpec.scala
it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala
mimir/src/main/scala/quasar/mimir/evaluate/MimirQueryFederation.scala
mimir/src/main/scala/quasar/mimir/evaluate/QuasarImpl.scala
mimir/src/main/scala/quasar/mimir/evaluate/ResourceRouter.scala
mimir/src/main/scala/quasar/mimir/evaluate/optics.scala
repl/src/main/scala/quasar/repl/Command.scala
repl/src/main/scala/quasar/repl/Evaluator.scala
repl/src/main/scala/quasar/repl/Main.scala
repl/src/main/scala/quasar/repl/Repl.scala
run/src/main/scala/quasar/run/Quasar.scala
run/src/main/scala/quasar/run/QuasarError.scala
run/src/main/scala/quasar/run/implicits.scala
yggdrasil/src/main/scala/quasar/yggdrasil/vfs/ResourceError.scala

Eliminate Quasar's dependency on mimir

---

blueeyes/src/main/java/quasar/precog/BitSet.java
blueeyes/src/main/scala/quasar/precog/util/BitSetUtil.scala
blueeyes/src/test/scala/quasar/precog/BitSetSpec.scala
yggdrasil/src/main/scala/quasar/yggdrasil/table/Column.scala

This should fix the memory leak reported by @alissapajer

Implemented BitSet#clearFrom to allow for _length adjustment

---

.appveyor.yml
.travis.yml
build.sbt
foundation/src/test/scala/quasar/QuasarSpecification.scala
project/plugins.sbt

We don't need to generate assembly jars

---

connector/src/main/scala/quasar/connector/datasource/SingletonDatasource.scala
connector/src/test/scala/quasar/connector/datasource/SingletonDatasourceSpec.scala

Not sure what label to set here

made singletondatasource using resourcepath

---

frontend/src/main/scala/quasar/ParseInstruction.scala
frontend/src/test/scala/quasar/ParseInstructionSpec.scala
impl/src/main/scala/quasar/impl/evaluate/RValueParseInstructionInterpreter.scala
impl/src/test/scala/quasar/impl/evaluate/RValueParseInstructionSpec.scala
qscript/src/main/scala/quasar/qscript/rewrites/RewritePushdown.scala
qscript/src/test/scala/quasar/qscript/rewrites/RewritePushdownSpec.scala

Change pivot parse instruction from multi to single

---

common/src/main/scala/quasar/common/CPath.scala
frontend/src/main/scala/quasar/ParseInstruction.scala
frontend/src/test/scala/quasar/JsonSpec.scala
frontend/src/test/scala/quasar/ParseInstructionSpec.scala
impl/src/main/scala/quasar/impl/evaluate/RValueParseInstructionInterpreter.scala
impl/src/test/scala/quasar/impl/evaluate/RValueParseInstructionSpec.scala

Add impl of RValue Cartesian interpretation and tests

---

run/src/test/scala/quasar/QScriptRegressionSpec.scala

Add qscript regression tests for provenance bug ch2068

---

build.sbt

Updated to shims 1.7

---

frontend/src/test/scala/quasar/std/StdLibSpec.scala

Add test cases for multi line searching to StdLibSpec

---

scripts/quasarPublishAndTag

Depends on https://github.com/slamdata/thoth/pull/2

Added thoth autobump

---

impl/src/main/scala/quasar/impl/evaluate/RValueParseInstructionInterpreter.scala
impl/src/test/scala/quasar/impl/evaluate/RValueCartesianSpec.scala
impl/src/test/scala/quasar/impl/evaluate/RValueParseInstructionSpec.scala

parallel RValue Cartesian interpreter

---

impl/src/main/scala/quasar/impl/evaluate/RValueParseInstructionInterpreter.scala
impl/src/test/scala/quasar/impl/evaluate/RValueCartesianSpec.scala
impl/src/test/scala/quasar/impl/evaluate/RValueParseInstructionSpec.scala

Incremenal RValue parse instruction interpreter

---

api/src/main/scala/quasar/api/table/TableError.scala
api/src/main/scala/quasar/api/table/Tables.scala
api/src/test/scala/quasar/api/table/MockTables.scala
api/src/test/scala/quasar/api/table/TablesSpec.scala
impl/src/main/scala/quasar/impl/table/DefaultTables.scala

Ensure unique names when replacing a table

---

impl/src/main/scala/quasar/impl/schema/ProgressiveSst.scala

Don't compress SST in map-size chunks

---

qscript/src/main/scala/quasar/qscript/provenance/Dimensions.scala
qscript/src/main/scala/quasar/qscript/provenance/Prov.scala
qscript/src/test/scala/quasar/qscript/provenance/ProvSpec.scala
qsu/src/main/scala/quasar/qsu/ApplyProvenance.scala
qsu/src/test/scala/quasar/qsu/ApplyProvenanceSpec.scala

Fix Map provenance computation when expression involves unions

---

.gitignore
frontend/src/test/scala/quasar/ScalarStageSpec.scala
impl/src/test/scala/quasar/impl/evaluate/RValueScalarStagesInterpreterSpec.scala

`ScalarStagesSpec` pending-configurable per spec and per implementation

---

common/src/main/scala/quasar/common/data/RValue.scala
common/src/test/scala/quasar/common/data/RValueSpec.scala
frontend/src/test/scala/quasar/ScalarStageSpec.scala
impl/src/main/scala/quasar/impl/evaluate/RValueScalarStagesInterpreter.scala
impl/src/test/scala/quasar/impl/evaluate/RValueScalarStagesInterpreterSpec.scala

scalar stages undefined tests + rvalue interpreter undefined handling fix

---

frontend/src/test/scala/quasar/ScalarStageSpec.scala

[ch6060]
This surfaces `undefined`-preservation bugs in `MaskPlate`, `PivotPlate`, and `ProjectPlate`.

Add cartesian tests for nested pivots

---

frontend/src/test/scala/quasar/ScalarStageSpec.scala
impl/src/main/scala/quasar/impl/evaluate/RValueScalarStagesInterpreter.scala
impl/src/test/scala/quasar/impl/evaluate/RValueScalarStagesInterpreterSpec.scala

No tests in it yet; just getting it in place.

Add FullSpec in ScalarStageSpec

---

api/src/main/scala/quasar/api/table/ColumnType.scala

I need this to improve `MaskPlate`

Added ordinal to ColumnType

---

scripts/quasarPublishAndTag

Added autobump for slamdata/benchmarks

---

project/Versions.scala

…due to binary compatibility breakage: https://twitter.com/djspiewak/status/1127418890009530368

Apparently we really have to be at this higher version

---

impl/src/main/scala/quasar/impl/datasource/local/EvaluableLocalDatasource.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalDatasourceModule.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalDestination.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalDestinationModule.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalParsedDatasourceModule.scala
impl/src/main/scala/quasar/impl/datasource/local/package.scala
impl/src/test/scala/quasar/impl/datasource/local/LocalDatasourceSpec.scala

Ensure LocalDatasource paths are confined to config dir

---

common/src/main/scala/quasar/common/data/QDataRValue.scala
common/src/main/scala/quasar/common/data/RValue.scala
common/src/test/scala/quasar/common/data/CValueGenerators.scala
common/src/test/scala/quasar/common/data/RCValueGenerators.scala
impl/src/main/scala/quasar/impl/evaluate/RValueScalarStagesInterpreter.scala

Binary RValue

---

connector/src/test/scala/quasar/connector/DatasourceSpec.scala
impl/src/main/scala/quasar/impl/datasource/local/package.scala

Recover from InvalidPathException when resolving ResourcePath

---

api/src/main/scala/quasar/api/table/TableColumn.scala
api/src/main/scala/quasar/api/table/TableRef.scala
connector/src/main/scala/quasar/connector/ResultType.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalDestination.scala
impl/src/test/scala/quasar/impl/destinations/MockDestination.scala

Use quasar.api.table.TableColumn instead of custom type in destination API

---

api/src/main/scala/quasar/api/datasource/Datasources.scala
api/src/test/scala/quasar/api/datasource/DatasourcesSpec.scala
api/src/test/scala/quasar/api/datasource/MockDatasources.scala
api/src/test/scala/quasar/api/datasource/MockDatasourcesSpec.scala
impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala
run/src/main/scala/quasar/run/Quasar.scala

add new schema method to Datasources

---

scripts/quasarPublishAndTag

To be merged after https://github.com/slamdata/scion/pull/33 lands

Add autobump for scion

---

api/src/main/scala/quasar/api/datasource/DatasourceError.scala
api/src/test/scala/quasar/api/datasource/DatasourcesSpec.scala
run/src/main/scala/quasar/run/QuasarError.scala

Evict scalaz from DatasourceError due to NPEs

---

qsu/src/main/scala/quasar/qsu/minimizers/MergeCartoix.scala
qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala

Fixes identity index numbering and switches to using `NameGenerator` as a source of intermediate cartoix names.

More robust naming and reindexing in simplifyJoin

---

scripts/quasarPublishAndTag

Depends on https://github.com/slamdata/quasar-destination-thoughtspot/pull/1

Added autobump for thoughtspot destination

---

api/src/main/scala/quasar/api/push/ResultRender.scala
impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala

Add row limiting to ResultRender

---

api/src/main/scala/quasar/api/push/PushMeta.scala
api/src/main/scala/quasar/api/push/Status.scala
impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala

Include destination push information in push status

---

api/src/main/scala/quasar/api/destination/ResultSink.scala
api/src/main/scala/quasar/api/push/ResultRender.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalDestination.scala
impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
impl/src/test/scala/quasar/impl/destinations/MockDestination.scala
impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala

Make CSV header rendering optional for destinations

---

core/src/main/scala/quasar/compile/Compiler.scala
frontend/src/main/scala/quasar/std/date.scala
frontend/src/test/scala/quasar/std/StdLibSpec.scala
qscript/src/main/scala/quasar/qscript/MapFunc.scala
qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
qscript/src/main/scala/quasar/qscript/construction.scala

Support ToLocal and ToOffset

---

foundation/src/main/scala/quasar/contrib/argonaut/JsonCodecs.scala
foundation/src/main/scala/quasar/contrib/pathy/package.scala

real codecs are nice

---

build.sbt
connector/src/main/scala/quasar/connector/QueryResult.scala
impl/src/main/scala/quasar/impl/parsing/ResultParser.scala
impl/src/test/scala/quasar/impl/datasource/local/LocalDatasourceSpec.scala

Add QueryResult.Stateful

---

impl/src/test/scala/quasar/impl/storage/TimestampedStoreSpec.scala

added updates stream test

---

impl/src/main/scala/quasar/impl/datasource/local/LocalStatefulDatasource.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalStatefulDatasourceModule.scala
impl/src/main/scala/quasar/impl/datasource/local/LocalStatefulPlate.scala
impl/src/main/scala/quasar/impl/datasource/local/package.scala
impl/src/test/scala/quasar/impl/datasource/local/LocalDatasourceSpec.scala

Implement a LocalStatefulDatasource

---

impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala

Datasource read error propagation

---

qsu/src/main/scala/quasar/qsu/CoalesceSquashedMappable.scala
qsu/src/main/scala/quasar/qsu/LPtoQS.scala
qsu/src/test/scala/quasar/qsu/CoalesceSquashedMappableSpec.scala

Coalesce and normalize squashed mappable regions

---

frontend/src/test/scala/quasar/ScalarStageSpec.scala

add scalar stage spec for undefineds on both sides

---

scripts/quasarPublishAndTag

Autobump quasar-destination-snowflake

---

api/src/main/scala/quasar/api/push/PushMeta.scala
api/src/main/scala/quasar/api/push/ResultPush.scala
api/src/main/scala/quasar/api/push/ResultPushError.scala
impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
run/src/main/scala/quasar/run/Quasar.scala

A more destination-centric ResultPush

---

impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala

Should resolve the flakiness we're seeing in this suite on travis.

Refactor DefaultResultPushSpec to be more resilient to execution speed

---

scripts/quasarPublishAndTag

Autobump Avalanche

---

project/Versions.scala
project/build.properties

Scala steward updates

---

impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala

Thanks for finding it! 
Some tabulation are changed to mimic tabulation in `DefaultDestinations`

atMostRenamed in getMDS

---

impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala

remove printlns

---

impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
run/src/main/scala/quasar/run/Quasar.scala

managedDatasourceOf added to DefaultDatasources

---

build.sbt
impl/src/main/scala/quasar/impl/IndexedSemaphore.scala
impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
impl/src/main/scala/quasar/impl/destinations/DefaultDestinations.scala

[ch10631] 
Checked the problem with pushing all samples with following snapshots: 
* quasar -- 157.0.1-740b2c5
* sdbe -- 45.0.5-37e5fea

indexed semaphore for datasource and destination initialization

---

scripts/quasarPublishAndTag

Autobump Redshift

---

impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala

Fixes a race-condition where, due to how a push job's initial status was set after the job was submitted to the job manager, if the job failed or succeeded after submission but before the initial status was set, the success/failure was not reflected in the status.
[ch10816]

Fix race-condition in result push regarding initial status updates

---

impl/src/main/scala/quasar/impl/destinations/DefaultDestinations.scala
impl/src/test/scala/quasar/impl/destinations/DefaultDestinationsSpec.scala

Only allocate destination when not already in cache

---

impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala

[ch11108]
This is similar to #4586 but for datasources.

Only allocate datasource when not already in cache

---

connector/src/main/scala/quasar/connector/datasource/BatchLoader.scala

Found myself needing these while working on datasource plugins.

Additional combinators and instances for BatchLoader

---

connector/src/main/scala/quasar/connector/render/RenderConfig.scala

Configurable boolean format when rendering csv

---

README.md
connector/src/main/scala/quasar/connector/datasource/HeavyweightDatasourceModule.scala
connector/src/main/scala/quasar/connector/datasource/LightweightDatasourceModule.scala
impl/src/main/scala/quasar/impl/DatasourceModule.scala
impl/src/main/scala/quasar/impl/local/LocalConfig.scala
impl/src/main/scala/quasar/impl/local/LocalDatasourceModule.scala
impl/src/main/scala/quasar/impl/local/LocalParsedDatasourceModule.scala
impl/src/main/scala/quasar/impl/local/LocalStatefulDatasourceModule.scala
impl/src/test/scala/quasar/impl/datasources/DatasourceModulesSpec.scala
impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala

Add config migration to DatasourceModule

---

api/src/main/scala/quasar/api/DataPathSegment.scala
api/src/main/scala/quasar/api/package.scala
api/src/main/scala/quasar/api/push/package.scala
impl/src/test/scala/quasar/impl/evaluate/QueryFederatorSpec.scala
impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala

Enable referring to all fields/ids in offset paths

---

build.sbt
foundation/src/main/scala/quasar/fp/Injectable.scala
foundation/src/test/scala/quasar/QuasarSpecification.scala
impl/src/main/scala/quasar/impl/evaluate/RValueScalarStagesInterpreter.scala
project/plugins.sbt

I re-enabled scaladocs because there were only a couple of fixes, and they were trivial. Also included, showtimes should be running again.

Publish test sources and scaladocs

---

impl/src/main/scala/quasar/impl/datasource/AggregatingDatasource.scala

don't rerun prefixedChildPaths stream in aggregate

---

connector/src/main/scala/quasar/connector/DataEvent.scala
connector/src/main/scala/quasar/connector/destination/ResultSink.scala
connector/src/main/scala/quasar/connector/render/ResultRender.scala
impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala
impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala

Support for non-CSV UpsertSink

---

connector/src/main/scala/quasar/connector/datasource/HeavyweightDatasourceModule.scala
connector/src/main/scala/quasar/connector/datasource/LightweightDatasourceModule.scala
impl/src/main/scala/quasar/impl/DatasourceModule.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceModules.scala
impl/src/main/scala/quasar/impl/local/LocalDatasourceModule.scala
impl/src/main/scala/quasar/impl/local/LocalParsedDatasourceModule.scala
impl/src/main/scala/quasar/impl/local/LocalStatefulDatasourceModule.scala
impl/src/test/scala/quasar/impl/datasources/DatasourceModulesSpec.scala
impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala

[ch12195] 
🛑 Because ds-url and sdbe should be reviewed too (other dependencies are basically: add `from: Long, to: Long`)

Migrate config/v1

---

impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala

Due to how cancellation is currently implemented for `ResultPush`, there can be situations where we receive an event from the underlying `JobManager` that doesn't relate to any active pushes. Previously these events were ignored, now they'll be logged to give more visibility when debugging/monitoring.

Log JobManager events ignored by ResultPush

---

connector/src/main/scala/quasar/connector/datasource/MapBasedDatasource.scala

Adds a variant of `MapBasedDatasource` that supports seek loads.

Add a seek variant of MapBasedDatasource

---

core/src/main/scala/quasar/compile/Compiler.scala
frontend/src/main/scala/quasar/std/date.scala
frontend/src/test/scala/quasar/std/StdLibSpec.scala
qscript/src/main/scala/quasar/qscript/MapFunc.scala
qscript/src/main/scala/quasar/qscript/MapFuncCore.scala
qscript/src/main/scala/quasar/qscript/construction.scala

Requires https://github.com/precog/mimir/pull/1070

Add now_utc

---

.versions.json
impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala

Adapt to change in fs2-job

---

api/src/main/scala/quasar/api/push/ResultPush.scala
connector/src/main/scala/quasar/connector/destination/Destination.scala
impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala

Destination default selected type

---

connector/src/main/scala/quasar/connector/Expires.scala
connector/src/main/scala/quasar/connector/ExternalCredentials.scala

Model expiring Temporary ExternalCredentials

---

connector/src/main/scala/quasar/connector/datasource/DatasourceModule.scala
connector/src/main/scala/quasar/connector/destination/DestinationModule.scala
connector/src/main/scala/quasar/connector/package.scala
impl/src/main/scala/quasar/impl/Quasar.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceModules.scala
impl/src/main/scala/quasar/impl/destinations/DestinationModules.scala
impl/src/main/scala/quasar/impl/local/LocalDatasourceModule.scala
impl/src/main/scala/quasar/impl/local/LocalDestinationModule.scala
impl/src/main/scala/quasar/impl/local/LocalParsedDatasourceModule.scala
impl/src/main/scala/quasar/impl/local/LocalStatefulDatasourceModule.scala
impl/src/test/scala/quasar/impl/datasources/DatasourceModulesSpec.scala
impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala
impl/src/test/scala/quasar/impl/destinations/DefaultDestinationsSpec.scala
impl/src/test/scala/quasar/impl/destinations/DestinationsModulesSpec.scala
impl/src/test/scala/quasar/impl/destinations/MockDestination.scala

As per title.
Let me know if I'm following the process etc right. 
Next I'll start PRing destination fixes before this is merged as per Juan's advice.
[ch13272]

Auth on DestinationModule

---

impl/src/main/scala/quasar/impl/Quasar.scala
impl/src/main/scala/quasar/impl/datasources/DatasourceModules.scala
impl/src/main/scala/quasar/impl/datasources/middleware/PathDecodingMiddleware.scala

Needed for https://github.com/precog/quasar-plugin-oracle/issues/9

Path decoding middleware

---

api/src/main/scala/quasar/api/push/OffsetKey.scala
api/src/test/scala/quasar/api/push/OffsetKeyGenerators.scala
impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala

Part of https://github.com/precog/quasar-plugin-sql-server/issues/96

Temporal offset/v1

---

impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala

Fixed DefaultResultPush
