precog/quasar

core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/test/scala/slamdata/engine/physical/mongodb/optimize.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala
=> Don’t inline $project into $group when it changes the semantics.

.travis.yml, build.sbt
Some dependency was forcing this on us anyway and slowing down builds,
so might as well upgrade.
=> Upgrade to Scala 2.11.4.

core/src/main/scala/slamdata/engine/sql/ast.scala, core/src/main/scala/slamdata/engine/sql/parser.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/sql/SqlParserSpec.scala
- generate larger queries, and more of them
- shrink failing examples
Also, fix unparsing for `like`.
=> make pending test fail consistently

core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, it/src/test/resources/tests/constantAndGrouped.test
Fixes the most important cases related to #524, but not less useful cases like
`select min(1) …` and `select lower(‘ABC’) …`.
=> concat constant value with grouped expression

core/src/main/scala/slamdata/engine/physical/mongodb/findquery.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/evaluator.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala, it/src/test/resources/tests/filterOnContains.test, it/src/test/scala/slamdata/engine/regression.scala
`where field in <constant array>` and `where <constant> in field` are
both normal selectors now, rather than requiring `$where` (which is only
used for `where field1 in field2` now).
Some other changes required to implement this:
* distingish `Selector.Eq` from `Selector.Literal` – both used to
generate the same selector, but `Eq` is now for the (undocumented)
`$eq` comparator, which is needed for `$elemMatch`;
* `Selector.ElemMatch` now takes `Selector \/ SimpleCondition` rather
than just `Selector`, which is at least _closer_ to its true type; and
* regression test failures now print out the actual result to make it
easier to see what went wrong.
=> Implement `In` for SelectorPhase.

core/build.sbt, scripts/build
scoverage collects coverage data in the project where the source
resides, regardless of which project’s test is running when it occurs.
That means we were formerly collecting coverage data for a portion of
the tests from the other projects (mainly `it`), non-deterministically.
How much coverage was reported just depended on how many of the `it`
tests happened to have already run at the moment that the `core` tests
finished and the report got generated.
Running `core` last means that all the other projects’ coverage data
has already been collected by the time the report is run, which should
give consistent results, and also ensure that the greatest amount of
coverage is included (win!)
Since we now get coverage for the `it` tests, removed the exclusion for
the MongoDB evaluator.
=> report consistent and complete coverage when running all tests

admin/src/main/scala/slamdata/engine/admin/admin.scala, it/src/test/resources/tests/unicode.data
Previously was using the default encoding, which could fail depending on the
user's locale.
Hopefully this will resolve #568, but we'll need to get confirmation from the
field.
Also add dialog titles and default file names to clarify file types.
=> Always use UTF-8 for export files

core/src/main/scala/slamdata/engine/semantics.scala, core/src/main/scala/slamdata/engine/std/string.scala, core/src/main/scala/slamdata/engine/types.scala, core/src/test/scala/slamdata/engine/TypeGen.scala, core/src/test/scala/slamdata/engine/compiler.scala, core/src/test/scala/slamdata/engine/types.scala
This turned out be a very small bug in the typing of the query, and
a very long expedition into the shortcomings of `Type.typecheck`.
I ended fixing a couple of things and writing up the rest as a separate 
defect.
=> Include default case when checking type of Switch and Match (Fixes #565)

core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala, it/src/test/resources/tests/projectFieldWithFlatten.test
Fixes #488.
* Add [`$SimpleFlatMap`][†], which takes an expression (that hopefully
evaluates to an array or object) and a function that is called on each
entry in that array or object;
* add `coalesce`/`finalize` cases for `$Simple*Map` (`coalesce` combines
adjacent `$Simple*Map`s, `finalize` merges `$Simple*Map`s into
adjacent `$[Flat]Map`s);
* convert `$Unwind.flatmapop` to use [`$SimpleFlatMap`][‡]; and
* fix `toCollectionBuilder(FlatteningBuilder(Object))` to return the
entire object, not just the flattened field and to pass the `base`
through rather than always using `$$ROOT`.
[†]: I wanted to just replace `$FlatMap`, but since we still have
non-simple `$Map`, `coalesce`/`finalize` can create non-simple
`$FlatMap`s, even though we never create one directly.
[‡]: This change is …
=> Fix object-flattening ($flatMap) merging.

core/src/main/scala/slamdata/engine/javascript/jscore.scala, core/src/main/scala/slamdata/engine/physical/mongodb/exprop.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, it/src/test/resources/tests/groupByFlatten.test
Fixes #590.
Also,
* implement `substring` in JS,
* improve handling of filter when some fields are $$ROOT (used to not be
able to hit this spot),
* `simplify` JsCore in more places, and
* identify more case that don’t need undefined checks.
=> Postpone merging src and keys in GroupBuilder.

core/src/main/scala/slamdata/engine/repl/repl.scala
We do our own variable substitution, so don't need Aesh's weird `export` feature, which captures `$`s.
=> disable Aesh's "export" feature (Fixes #473)

core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/std/relations.scala, core/src/test/scala/slamdata/engine/compiler.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/std/relations.scala, it/src/test/resources/tests/joinWithReversedCondition.test
Fixes #585.
We now notice if the join condition looks like `right.field = left.field`
and then swap the sides for MongoDB. This also fixes an issue where
certain join conditions got mangled. EG, `left.parents[0].sha = right.sha`
would be treated as `left.sha = right.sha`. We now handle that correctly.
Also, eliminate the evil `asExprOp`.
=> Swap left/right parts of join condition when necessary.

core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, it/src/test/resources/tests/groupedJoin.test
Adds a new SpliceBuilder for objects with partially-unknown structure.
This builds on the fix for #587 – that made those precise queries pass,
but minor changes to them could result in other failures. This gives a
more robust solution.
It also finally eliminates the need for `WorkflowBuilder.merge` to ever
fall back to `Workflow.merge` (although `Workflow.merge` still has a
call site elsewhere, so it’s still not quite dead).
=> Improve handling of object splicing.

core/src/main/scala/slamdata/engine/javascript/javascript.scala, core/src/main/scala/slamdata/engine/javascript/jscore.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/test/scala/slamdata/engine/javascript/jscore.scala
Use "unsafe" Js conversion in JsMacro's toString and RenderTree
instance. This makes the physical plan a lot easier to read.
You can still see the actual generated JS in the "Mongo" plan.
Fix a bug where single-character names weren't recognized as
simple names, so you would see things like `_["x"]`instead of
`_.x`.
=> Improve rendering of JsMacros

core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala
Fixes the particular query reported in #603, but not many other equally simple queries.
=> match groups followed by shape-preserving ops

core/src/main/scala/slamdata/engine/data.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/types.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala
The intent here was to improve coverage a bit, but I found various
things along the way that maybe didn’t help with that goal. I’ll list
the changes in the order of the GitHub diff to make it easier to review
them.
* Move `Planner.convertConstant` to `Data.toJs` and implement all
cases (no more errors);
* remove State from `projectIndex` result;
* eliminate some unused error types;
* remove now-dead `chainBuilder`;
* fix array expr rewriting when converting to `CollectionBuilder`;
* don’t error when concatted objects have conflicting keys;
* fix reversed concatting of arrays;
* add statically-known case (and tests for it) to `projectIndex`;
* eliminate `HavingRoot` and generalizes the `$sort; $project` case in
`distinctBy`’s `findSortKeys`;
* rename the parameters to typecheck;
* modify …
=> A number of small unrelated changes.

core/src/main/scala/slamdata/engine/physical/mongodb/evaluator.scala
I don't know why some installations of MongoDB 2.6.5 would be OK with this and not @radbradman's, but we were passing an array of DBObject here, where a BasicDBList seems to be more the norm, which would neatly explain the ClassCastException seen in #616.
In any case, using `Bson.repr` is a better way of constructing this object, and eliminates an ugly occurrence of `Any`.
=> use Bson.repr to construct aggregation commands

core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, it/src/test/resources/tests/flattenGroupedObject.test, it/src/test/resources/tests/projectIndexFromGroup.test, it/src/test/resources/tests/projectIndexFromGroupWithFilter.test
Fixes #620.
`projectIndex` was not passing operations through GroupBuilder or
ShapePreservingBuilder, creating broken physical plans for the former
and overly-complicated ones for the latter.
Also
* make `expr1` total by allowing `ExprBuilder(ExprBuilder(…))` in the
case of an expr that has no JS representation on top of a JS expr,
* use `mapExpr` more consistently in the planner, rather than calling
expr1 directly,
* add a `projectField` case for JS expr that avoids stacked
ExprBuilders (this showed up after fixing the `projectIndex` case for
SPBs), and
* tighten up the GroupBuilder pass-though on flattenObject, since
previously it could ruin plans.
Finally, add an integration test for the GroupBuilder fix, since the
results were previously incorrect, but only a planner test for the …
=> Fix projecting an index on a field in a group.

core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, it/src/test/resources/tests/concatFieldAndConstant.test, it/src/test/resources/tests/flattenArray.test, scripts/importTestData
* ArrayBuilders weren’t rewriting refs correctly when converting to
Workflow, fixed that and added a test to cover it;
* fixed a test that used the wrong copy of a collection; and
* have `importTestData` try remaining collections if one fails.
=> Some small things I noticed working on other issues.

core/src/main/scala/slamdata/engine/javascript/jscore.scala, core/src/main/scala/slamdata/engine/physical/mongodb/exprop.scala, core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/test/scala/slamdata/engine/javascript/jscore.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala, it/src/test/resources/tests/wildcardWithExtraProjections.test
Added a primitive `Splice` expression to JsCore, which encapsulates the
JavaScript machinery as a pure computation. This allows splicing to be
handled by SimpleMap. Also implemented the missing cases in objectConcat
for SpliceBuilders.
That resulted in Simple(Flat)Maps showing up in more places, including after
the unwinds introduced by joins, exposing the fact that successive
SimpleFlatMap ops were not composed in a sensible way. The simplest fix was
extending SimpleFlatMap to handle a list of flattened values. Since
a SimpleFlatMap with an empty list of flattened fields is equivalent to
SimpleMap, just went for it and collapsed the two ops into one, with a
potentially empty list of fields to be flattened.
The new SimpleMap is not as clean and, well, simple, as the old SimpleMap,
but …
=> handle splicing in objectConcat (fixes #497)

core/src/main/scala/slamdata/engine/sql/ast.scala, core/src/main/scala/slamdata/engine/sql/parser.scala, core/src/test/scala/slamdata/engine/sql/SqlParserSpec.scala, core/src/test/scala/slamdata/engine/sql/SqlQueries.scala
Parsing fixes:
1. Accept parens around joins.
2. Allow arbitrary expressions inside `[]` and `{}`.
3. Parse numeric literals with exponents.
4. Rip out half-implemented
EXTRACT syntax.
Rendering:
1. Always surround joins with parens.
2. Escape single quotes in string
constants.
3. Quote identifiers as needed and escape double quotes in them.
This means `day` and `hour`, etc. are no longer keywords, at least until we
decide to support the awful EXTRACT syntax (see #210).
There were some parsing tests that included EXTRACT, which I just modified to
use `date_part`. As long as we have an equivalent that works, I didn't see any
point in preserving a test for the syntax we've never supported in the
compiler.
=> Fix AST rendering (many cases) and parsing (a few) (fixes #430)

build.sbt, core/src/main/scala/slamdata/engine/codec.scala, core/src/main/scala/slamdata/engine/data.scala, core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala, core/src/main/scala/slamdata/engine/physical/mongodb/bsoncodec.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, core/src/test/scala/slamdata/engine/codec.scala, core/src/test/scala/slamdata/engine/compiler.scala, core/src/test/scala/slamdata/engine/physical/mongodb/bson.scala, core/src/test/scala/slamdata/engine/physical/mongodb/bsoncodec.scala, core/src/test/scala/slamdata/engine/semantics.scala, core/src/test/scala/slamdata/engine/types.scala
This seemed the simplest, most practical approach. It protects slamdata from any unexpected values we might find in MongoDB, while not propagating complex error handling (i.e. functorization). I'm happy with this approach, at least for now, because although it might be nice to record the error that occurred and where, realistically I don't think we would do anything with that detail at this point.
There's a new value in each of Bson and Data which stands in for any unrepresentable value coming from the backend. Because the value can appear anywhere, it allows the rest of the structure of any result to be preserved even when some fields contain values we can't use.
Wrote a scalacheck generator for Bson values, and a number of tests of the reversibility of translation. This also turned up a …
=> translate unrepresentable Bson/Data to new NA value (fixes #627)

core/build.sbt, core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/data.scala, core/src/main/scala/slamdata/engine/javascript/jscore.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/main/scala/slamdata/engine/semantics.scala, core/src/main/scala/slamdata/engine/sql/ast.scala, core/src/main/scala/slamdata/engine/sql/parser.scala, core/src/main/scala/slamdata/engine/std/structural.scala, core/src/test/scala/slamdata/engine/javascript/jscore.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/sql/SqlParserSpec.scala, core/src/test/scala/slamdata/engine/std/math.scala, core/src/test/scala/slamdata/engine/std/structural.scala, core/src/test/scala/slamdata/engine/types.scala, it/src/test/resources/tests/concatArray.test, it/src/test/resources/tests/concatArrayWithUnknown.test
Add `ArraySpliceBuilder` and cases in `arrayConcat` to handle it. Some
wrangling of types and names in WorkflowBuilder to make this work out. This
fixes a previously pending integration test.
Add `JsCore.SpliceArrays` (and `Splice` becomes `SpliceObjects`).
Add SQL syntax for array constants with `[ ]`, and a `||` operator that works
on both arrays and strings. The operator must be typed to either Str or an
array type during type-checking, so that the compiler can translate it to
either (string) Concat or ArrayConcat. Note: type-checking doesn't push the
inferred type up and down in some cases; see pending test referring to #637.
Other minor stuff:
Add a (pending) missing test and a fix a broken existing test for math.Add.
Fix the type of empty array constants to be recognizable as an …
=> array splicing, and `||` and `[]` syntax for arrays and strings (fixes #600)

build.sbt, core/src/main/scala/slamdata/engine/analysis/fixplate.scala, core/src/main/scala/slamdata/engine/fp/package.scala, core/src/main/scala/slamdata/engine/functions.scala, core/src/main/scala/slamdata/engine/logicalplan.scala, core/src/main/scala/slamdata/engine/mra.scala, core/src/main/scala/slamdata/engine/optimizer.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/std/structural.scala, core/src/test/scala/slamdata/engine/analysis/fixplate.scala, core/src/test/scala/slamdata/engine/logicalplan.scala
* Simplify some of the fixplate morphisms and
* use kind-projector to make type lambdas somewhat closer to readable.
A couple things I’m not happy with:
* `IntRenderTree` – I wanted to make a lower-priority ShowRenderTree
that would give us a RenderTree instance for anything that had a Show
instance, but I kept getting diverging implicits, so I punted and
created the one case we needed.
* `EqualFNT` (and `ShowFNT`) – this converts `EqualF` instances into
`NaturalTransformation`s (which we need to make `Cofree`’s `Equal`
instance work). This is much like our `EqualEqualF`, except that it
doesn’t deal with subtypes. I was hoping to get rid of `EqualF` and
use NTs directly, but getting something like `FF[A] <: F[A]` into the
NT stymies me.
=> Switching from Attr/CoAttr to Cofree/Free.

README.md, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Inspired by @ilndinesh's PR (#583).
Runs the planner and simply returns the last phase's result.
Also added tests for POST to the `/query/fs` path, which seemed to be missing.
=> API for compiling a query without executing it

core/src/main/scala/slamdata/engine/sql/parser.scala, core/src/test/scala/slamdata/engine/sql/SqlParserSpec.scala
=> Parse SQL numeric literals as Long, not Int.

core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/functions.scala, core/src/main/scala/slamdata/engine/logicalplan.scala, core/src/main/scala/slamdata/engine/mra.scala, core/src/main/scala/slamdata/engine/optimizer.scala, core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/main/scala/slamdata/engine/planner.scala, core/src/test/scala/slamdata/engine/logicalplan.scala, core/src/test/scala/slamdata/engine/optimizer.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala
* Make unfixed `LogicalPlan` classes public and rename them with an `F` suffix,
* destroy `LogicalPlan.fold`, so it doesn’t shadow `Foldable.fold`,
* remove `unapply` and `Attr` from fixed `LogicalPlan` objects,
* expose a few `WorkflowOp` functions as F-algebras,
* make `Optimizer.simplify` handle shadowed variables properly (and expose as an
F-algebra), and
* reduce code base by 140 lines.
=> A few steps toward using functors more directly.

.gitignore, core/src/main/scala/slamdata/engine/physical/mongodb/exprop.scala, core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala, core/src/main/scala/slamdata/engine/physical/mongodb/reshape.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/test/scala/slamdata/engine/physical/mongodb/pipeline.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala, it/src/test/resources/tests/filterByJsWithOnlyReducing.test, it/src/test/resources/tests/groupAndFilterWithNoUnreduced.test, it/src/test/resources/tests/sortByJS.test
There were a handful of situations where values were lost along the way 
as queries were planned, generating dangling references in the final plan.
The property-based planner tests now detect this error for all the queries we 
generate, and we now generate queries with sorting.
Specifically (and there are new regression tests for each of these):
1. Sorting by a JS expression with filtering present (fixes #651)
2. Implicit grouping, with only reduced projections, with filtering by JS
3. Explicit grouping, with only reduced projections, and filtering present
Along the way, a bunch of things got improved:
Fixed `ExprOp.toJs` to *not* translate `Include`; there's not enough information 
in the op, so it needs special handling by the caller.
`optimize` now removes unused fields in `SimpleMap`, …
=> eradicate dangling references

core/src/main/scala/slamdata/engine/analysis/fixplate.scala, core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/fp/EnvT.scala, core/src/main/scala/slamdata/engine/javascript/jscore.scala, core/src/main/scala/slamdata/engine/logicalplan.scala, core/src/main/scala/slamdata/engine/optimizer.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/main/scala/slamdata/engine/std/structural.scala, core/src/test/scala/slamdata/engine/analysis/fixplate.scala, core/src/test/scala/slamdata/engine/compiler.scala, core/src/test/scala/slamdata/engine/optimizer.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala, it/src/test/resources/tests/doubleFlatten.test, it/src/test/resources/tests/orderedWildcardWithProjection.test, it/src/test/resources/tests/shortCities.test, it/src/test/resources/tests/sortWildcardOnExpression.test
Fixes #310.
* Add a DeleteField function to the stdlib,
* have the compiler generate the simplest plan, then provide a fold to
convert deletes to projections for backends to use as an optional
pass;
* provide a jsLibrary for Workflow that automatically includes
referenced functions in mapReduce scope;
* move EnvT to the fp package;
* get rid of unzipF in favor of using the Unzip type class;
* fix a bug in boundPara where it ignored bindings;
* add a pending test that flattens a flattened object; and
* add a missing data source to a test.
=> Delete synthesized fields.

admin/src/main/scala/slamdata/engine/admin/edit.scala, build.sbt, core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala, core/src/main/scala/slamdata/engine/physical/mongodb/bsoncodec.scala, core/src/main/scala/slamdata/engine/physical/mongodb/evaluator.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, core/src/main/scala/slamdata/engine/physical/mongodb/util.scala, core/src/test/scala/slamdata/engine/physical/mongodb/bson.scala, it/src/test/resources/tests/undefinedJsInExpr.test
Fixes #658.
Some of the deets:
* `eval` is gone – not exposed through the 3.0 API, so *shrug*;
* the new driver returns `BsonUndefined` for undefined value, which
exists (but is deprecated) in the BSON spec, so I replaced `Bson.NA`
with it and mapped `Bson.Undefined` to `Data.NA`; and
* disabled Java logging, because the new driver logs random stuff.
=> Upgrade to Mongo Java driver 3.0.

core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/sql/ast.scala, it/src/test/resources/tests/orderJoinByAlias.test
Fixes #640.
Also, fix ambiguous relation error so it doesn’t say “no table”.
=> Make aliases available when compiling sort keys.

core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/errors.scala, core/src/main/scala/slamdata/engine/semantics.scala, core/src/main/scala/slamdata/engine/sql/ast.scala, core/src/main/scala/slamdata/engine/sql/parser.scala, core/src/main/scala/slamdata/engine/variables.scala, core/src/test/scala/slamdata/engine/backend.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/semantics.scala, core/src/test/scala/slamdata/engine/sql/SqlParserSpec.scala
Simplify some structure and eliminate mutual recursion. Actually making
it a functor will require major changes to semantics.scala and
compiler.scala, so … holding off on that.
* Combine `Proj.Anon` and `Proj.Named` (the alias is handled with
`Option[String]`);
* generalize `SubqueryRelationAST` to `ExprRelationAST`; and
* merge `SelectStmt` and `Subselect` into `Select` (which is an `Expr`).
Consequently, we now use `expr` as the primary parser, rather than
`select`. This means that `1 + 2` could be parsed at the top level, but
neither our admin tool nor REPL currently allow this.
=> Prepare the SQL AST for functorization.

core/src/main/scala/slamdata/engine/physical/mongodb/util.scala
Something changed in the 3.0 driver, and our previous approach no longer works.
Explicitly setting the level for `org.mongodb` does the trick.
=> disable info-level logging from MongoDB (fixes #678)

core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, it/src/test/scala/slamdata/engine/fs/filesystem.scala, it/src/test/scala/slamdata/engine/regression.scala
Fixes #693.
* If src and dst are the same, it’s a NOP;
* if dst exists (and isn’t the same as src), fail; and
* modify regression tests so they don’t all try to write to the same
output collection (since it would now require adding a deletion step).
=> Fix some `fs.move` cases.

core/build.sbt, core/src/main/scala/slamdata/engine/analysis/Analysis.scala, core/src/main/scala/slamdata/engine/analysis/AnnotatedTree.scala, core/src/main/scala/slamdata/engine/analysis/Tree.scala, core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/config/config.scala, core/src/main/scala/slamdata/engine/debug.scala, core/src/main/scala/slamdata/engine/fp/package.scala, core/src/main/scala/slamdata/engine/physical/mongodb/evaluator.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/main/scala/slamdata/engine/semantics.scala, core/src/main/scala/slamdata/engine/sql/parser.scala, core/src/main/scala/slamdata/engine/types.scala, core/src/main/scala/slamdata/engine/variables.scala, it/src/test/scala/slamdata/engine/backendtest.scala, it/src/test/scala/slamdata/engine/fs/filesystem.scala, it/src/test/scala/slamdata/engine/regression.scala
Enable wartremover's check for non-Unit-returning expressions used in statement position. Add a function `ignore` to make the discarding of values explicit when we need to do it.
Also enabled scalac's warning for discarded values, which catches where you produce any value at all but `Unit` is expected, so scalac says, "great", and just tosses the value.
Both of those only in the `core` project, and wartremover only in `compile` (not `test`), because specs2.mutable and swing both break these rules by their nature.
=> Enable warnings for non-Unit-returning statements

README.md, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #644.
This supports using any of
* application/ldjson,
* application/x-ldjson, or
* application/json;boundary=NL
as a media type, along with an optional “mode=precise” (or
“mode=readable”) extension to specify which codec to use.
The response always has a Content-Type header with the value
“application/ldjson;mode=readable” (or “precise”, if the client
requested it).
=> Let the client specify if they want precise JSON.

core/src/main/scala/slamdata/engine/analysis/AnnotatedTree.scala, core/src/main/scala/slamdata/engine/analysis/fixplate.scala, core/src/main/scala/slamdata/engine/debug.scala, core/src/main/scala/slamdata/engine/errors.scala, core/src/main/scala/slamdata/engine/fp/package.scala, core/src/main/scala/slamdata/engine/functions.scala, core/src/main/scala/slamdata/engine/javascript/javascript.scala, core/src/main/scala/slamdata/engine/javascript/jscore.scala, core/src/main/scala/slamdata/engine/logicalplan.scala, core/src/main/scala/slamdata/engine/physical/mongodb/collection.scala, core/src/main/scala/slamdata/engine/physical/mongodb/exprop.scala, core/src/main/scala/slamdata/engine/physical/mongodb/findquery.scala, core/src/main/scala/slamdata/engine/physical/mongodb/reshape.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowtask.scala, core/src/main/scala/slamdata/engine/semantics.scala, core/src/main/scala/slamdata/engine/sql/ast.scala, core/src/main/scala/slamdata/engine/types.scala, core/src/test/scala/slamdata/engine/analysis/fixplate.scala, core/src/test/scala/slamdata/engine/debug.scala, web/src/test/scala/slamdata/engine/api/fs.scala
1. Make `nodeType` the first parameter, and
2. reverse the order of the list, so shared structure can be shared.
3. Make `label` optional, reflecting its
use.
This corrects the mistake of putting the nodeType at the end, simply because
it was added later, and makes it clearer that the label isn't required.
Actually, it would make sense for nodeType to be `NonEmptyList`, but that
would be painful, and it's easy enough to provide some default in case it's
empty, since it's just being turned into a label string.
=> clean up the RenderedTree type

core/src/main/scala/slamdata/engine/repl/repl.scala
This works if you're sitting at the keyboard and hit ^D, but for some
reason does not trap EOF when commands are piped into stdin.
=> trap ^D and exit the REPL (fixes #446)

core/src/main/scala/slamdata/engine/debug.scala, core/src/main/scala/slamdata/engine/physical/mongodb/exprop.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/std/date.scala, core/src/test/scala/slamdata/engine/debug.scala, core/src/test/scala/slamdata/engine/physical/mongodb/exprop.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, it/src/test/resources/tests/convertTimestamp.test, it/src/test/resources/tests/dateFilter.test, it/src/test/resources/tests/days.data, it/src/test/resources/tests/days.test, it/src/test/resources/tests/filterOnDate.test, it/src/test/resources/tests/time.test, it/src/test/resources/tests/timestampsAndIntervals.test
Compiles to an exprop adding the value to the constant 1970-01-01. However,
since that doesn't work in JavaScript, that pattern is detected and translated
to `new Date(_)` when it ends up being part of a map op.
Also fixed `RenderTree.diff` which was producing very confusing labels.
=> TO_TIMESTAMP function for converting epoch time to timestamp (fixes #703)

.travis.yml, it/src/test/resources/tests/LocationCount.test, it/src/test/resources/tests/filterOnOid.test, it/src/test/resources/tests/idNotAliased.test, it/src/test/resources/tests/null/nullTestExprsWithMissing.test, it/src/test/resources/tests/servlet.test, it/src/test/resources/tests/simpleProjectWithOneRenamed.test, it/src/test/resources/tests/tripleFlatten.test, it/src/test/scala/slamdata/engine/backendtest.scala, scripts/build, scripts/installMongo
There are now two backends configured for the regression tests. By default,
mongodb_2_6 points to the mongolab instance, and mongodb_3_0 is disabled. When
running in Travis, each version is downloaded and installed locally, running
on separate ports.
If you've been running against a local instance, just update your env variable
from `SLAMDATA_MONGODB` to `SLAMDATA_MONGODB_2_6`.
=> test against multiple mongodb versions in travis (currently 2.6.9 and 3.0.3)

build.sbt, core/src/main/scala/slamdata/engine/fs/path.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, core/src/main/scala/slamdata/engine/physical/mongodb/mapreduce.scala, it/src/test/scala/slamdata/engine/fs/filesystem.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Update http4s dependency to 0.7, and update lens construction for Monocle 1.1.0.
Pass paths through as is, now that http4s preserves trailing slashes.
Treat the destination for MOVE as a directory path if the source is a
directory path.
Fix `Path.fileOf`, which was always producing a non-relative path (like
`/foo`), which makes no sense. Of course, no one was calling it.
Do something reasonable in GET /metadata with non-dir path (return 200 with
an empty object in the body).
Add a test for the error that occurs when you try to move a file on top of
an existing file.
Note: it would be great to have unit tests for the API doing the right
effects, but that's challenging given that those effects are hidden inside
Task[Unit]. I don't want to mock the filesystem statefully, so I'm settling
for …
=> various fixes related to MOVE (fixes #711)

README.md, admin/src/main/scala/slamdata/engine/admin/config.scala, build.sbt, core/src/main/scala/slamdata/engine/config/config.scala, core/src/main/scala/slamdata/engine/repl/repl.scala, scripts/autoPublish, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/server.scala, web/src/test/scala/slamdata/engine/api/fs.scala
This serves up URIs under /slamdata relative to the location of the jar. It
also redirects / to /slamdata (assuming no other service matches
the path).
This also adds command-line options to the server (primarily to be able
to choose whether or not starting the server opens a client in the
browser). This meant changing the config file from being the first
argument to being passed with `--config`. I also add a `--port` option
just for convenience.
=> Add a static file service.

README.md, core/src/main/scala/slamdata/engine/errors.scala, core/src/main/scala/slamdata/engine/std/date.scala, core/src/test/scala/slamdata/engine/std/date.scala
Year/month don't work, so:
- correct the documentation for the conversion Func
- improve the resulting error's message
- add a note to README.md
- some tests for the current state of things
See #717 and #718.
=> better communication about INTERVAL formats

README.md, admin/src/main/scala/slamdata/engine/admin/admin.scala, core/src/main/scala/slamdata/engine/repl/prettify.scala, core/src/test/scala/slamdata/engine/repl/prettify.scala, web/build.sbt, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Uses the first `n` results (currently 1000) to identify columns, so that the
entire data set is never loaded into memory at once. Uses the same formatting
of values as the REPL and the Admin tool's CSV output.
Because the wrangling of Process was the only tricky bit here, I included a
test that effects are properly sequenced (and executed only once!)
Also fixed a couple of bugs:
- the REPL would give an error if every result object was `{}`
- `Data.Set` was not formatted properly in tabular output.
=> Produce CSV output with "Accept: text/csv" header (first part of #645)

README.md, core/build.sbt, core/src/main/scala/slamdata/engine/config/config.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/server.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Adds two new services – one for configuring mount points, and one for
the port.
Fixes #182.
There is some … non-FP code in server.scala. I’m happy if anyone can push it toward more FP.
=> Add an API to manage the engine config.

core/src/main/scala/slamdata/engine/analysis/fixplate.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, it/src/test/resources/tests/different-flattens.test, it/src/test/resources/tests/user_comments.data
Fixes #721.
We now annotate the WorkflowBuilder with branch lengths before
merging. This gives us a bit more info when making merge
decisions. Currently we only make use of it when merging flattens on
different fields, which fixes this particular issue.
**NB**: The indentation in `merge` has changed, so it’s a bit noisy. The
relevant bit is in the
```scala
case (
FlatteningBuilderF(src0, typ0, field0),
FlatteningBuilderF(src1, typ1, field1)) =>
```
case.
=> A step toward merging leaves-first.

web/src/main/scala/slamdata/engine/api/server.scala
This was breaking starting the app on Macs with a name like “SlamData 2.0.0”.
=> Decode the JAR path so we handle paths with spaces.

README.md, admin/src/main/scala/slamdata/engine/admin/config.scala, core/src/main/scala/slamdata/engine/fp/package.scala, core/src/main/scala/slamdata/engine/repl/prettify.scala, core/src/test/scala/slamdata/engine/codec.scala, core/src/test/scala/slamdata/engine/repl/prettify.scala, web/src/main/scala/slamdata/engine/api/csv.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/csv.scala, web/src/test/scala/slamdata/engine/api/fs.scala
See #645, which this fixes except for the requirement to handle crazy "CSV"-like formats.
Regularized REPL/CSV output to match the Readable encoding (by actually using it), with all JSON values turned into strings.
Handle `Content-Type: text/csv` on PUT/POST to `/data/fs`. Parse headers and reconstruct document structure from them, such that exported and re-imported CSV should reproduce the original documents. Mal-formed headers and empty cells are mostly just ignored.
Fix `unzipDisj` to *not* reverse the lists.
In the API tests, keep track of actions performed, effectfully :-(, so it's now possible to verify parsing of uploaded data.
=> accept uploaded (standard) CSV

web/src/main/scala/slamdata/engine/api/server.scala
Fixes a problem where we don’t get `System.in` on Windows when run as a
GUI app.
=> Make sure stdin is open before calling `available`.

core/src/main/scala/slamdata/engine/variables.scala, core/src/test/scala/slamdata/engine/variables.scala
Fixes #750.
Previously would only match if the expected type was exactly one of the 
primitive types. Now will coerce if the expected type `contains` the type of
the parsed value. That's important in the common case where what's expected is
`Int | Dec`, for example.
=> coerce variables to any compatible type

core/src/main/scala/slamdata/engine/fs/filesystem.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, it/src/test/scala/slamdata/engine/fs/filesystem.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #751.
Note: offset can be zero (indeed, that's a common offset), but limit cannot
(because there's no point in requesting zero results, and because MongoDB
wants to interpret that value as "no limit", naturally).
Check in the API so we can show a nice error message, and check in the
filesystem because the MongoDB driver doesn't handle this gracefully.
Always use a negative limit value, which gives the driver a hint that we won't
request additional results.
Also added an integration test for proper skip/limit behavior of the MongoDB
cursor.
=> In the API and the MongoDB Filesystem, validate that offset >= 0 and limit > 0

core/src/main/scala/slamdata/engine/config/config.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/server.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #758.
Static validation for MongoDbConfig that just attempts to parse the connection
URI.
Fix our parser to reject URIs with extra slashes, to match MongoDBs behavior.
Note: we may want two parsers at some point; one to decipher user-entered
URIs, which is lenient, and another to validate URIs from the API, which is
strict. We would regularize user-entered URIs so that they pass the strict
parser before saving them.
Small-scale conversion in the API to `EitherT[Task, RequestError, A]` to deal
with this one case.
Expose the raw services and separately a mapping from paths to the same
services wrapped in our common middleware.
New middleware to deal with failure in `Task`, returning a 500 with the
description wrapped in Json. This fixes the annoying default behavior of
http4s, which …
=> validate MongoDB connection URI before updating config

README.md, admin/src/main/scala/slamdata/engine/admin/config.scala, admin/src/main/scala/slamdata/engine/admin/edit.scala, core/src/main/scala/slamdata/engine/config/config.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/package.scala, web/src/main/scala/slamdata/engine/api/server.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #739.
Enforce a consistent interpretation of paths for mounts. MongoDB mounts should
always use a directory path, and in the API those paths always have a trailing
slash.
Test coverage for all requests to /mount, and several small fixes:
- make DELETE idempotent
- use X-File-Name in POST
- use application/json Content-Type
- fix response text in a couple of cases
In the admin UI, always add the trailing slash.
=> regularize and validate of paths in the /mount API

core/src/main/scala/slamdata/engine/backend.scala, core/src/main/scala/slamdata/engine/fs/path.scala, web/src/test/scala/slamdata/engine/api/fs.scala
This is a fix (but not the one we want) for #781.
This handles the paths correctly (with more tests), but as #781
describes, we really want a new mount at each node. So, not closing that
ticket yet.
=> Fix various issues with mount paths.

core/src/main/scala/slamdata/engine/fp/package.scala, core/src/main/scala/slamdata/engine/repl/prettify.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #782.
Includes an ugly back-port of `unconsOption` from scalaz-stream/master.
=> consume first chunk of scan, handle errors, then stream the rest

web/src/main/scala/slamdata/engine/api/server.scala
Failing to open the browser should not cause the server to fail. Instead
we now send a message to stderr acknowledging the error and providing
the URL for the user to use.
This doesn’t fix the underlying issue in #797, but it does at least
allow users to continue working when this fails.
=> Handle any error when trying to open the browser.

it/src/test/scala/slamdata/engine/backendtest.scala, it/src/test/scala/slamdata/engine/fs/filesystem.scala, it/src/test/scala/slamdata/engine/regression.scala
Refactoring put this effectful code into Task, and then we never
bothered to run the task.
Also some cleanup to make the effectful-ness more obvious.
=> restore cleanup of temp files after integration tests

core/src/main/scala/slamdata/engine/backend.scala, core/src/main/scala/slamdata/engine/backends.scala, core/src/main/scala/slamdata/engine/fs/path.scala, core/src/main/scala/slamdata/engine/mounter.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, core/src/test/scala/slamdata/engine/fs/path.scala, it/src/test/scala/slamdata/engine/fs/filesystem.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #781, fixes #785, and fixes #788.
* removed `Path.contains`
* centralized normalization of paths
* error on conflicting paths
* add tests for conflicting configs and metadata issues.
=> Convert NestedBackend into single steps.

README.md, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/package.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Providing two more of the items in the checklist in #763:
1. Handle `disposition` in the Accept header, returning it as `Content-Disposition` in the response.
2. Accept headers in `request-headers` query param on any request.
Also move the middleware to the package object, where it's easier to test.
=> two more API features related to formatting

core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/semantics.scala, core/src/main/scala/slamdata/engine/sql/ast.scala, core/src/main/scala/slamdata/engine/sql/parser.scala, core/src/main/scala/slamdata/engine/std/relations.scala, core/src/main/scala/slamdata/engine/variables.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/sql/SqlParserSpec.scala, core/src/test/scala/slamdata/engine/std/relations.scala, core/src/test/scala/slamdata/engine/variables.scala, it/src/test/resources/tests/fieldOrder.test, it/src/test/resources/tests/wildcardWithMultipleConstants.test
Fixes #608 and fixes #704.
Also, convert NullLiteral from a class to an object and add some tests
to improve coverage.
=> Ensure constant projections don’t ignore the size of the input set.

core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, it/src/test/resources/tests/caseWithGroup.test, it/src/test/resources/tests/groupByExpression.test
Fixes #807.
The general `WorkflowBuilder.expr` has never been handled as well as
`expr1` and `expr2`. This finally corrects that and unifies all three
functions.
Also, fixed a bad integration test that expected the previous behavior.
=> Fix combination of 3-arg exprs and grouping.

README.md, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/zip.scala, web/src/test/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/zip.scala
Fixes #763 (the last checklist item).
Wraps Java's ZipOutputStream so that it can be used to transform the bytes of
a scalaz-stream Process.
This is all a bit tricky to test without writing the corresponding wrapping
for ZipInputStream, which I did not do. Instead, it tests some small data sets
for their exact contents, and tests some large data sets for performance,
without trying to do both at once.
Includes a simple test at the API level of the zipped content-type and
disposition, which required implementing `ls` properly in the test stub. Also
changed the expected behavior of `GET /metadata` with a non-existent directory
to match that implementation.
=> zip up directories for downloading

README.md, core/src/main/scala/slamdata/engine/fs/path.scala, core/src/main/scala/slamdata/engine/repl/repl.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/package.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Every error case now has a test that asserts that the response:
1. is in JSON format (with the right content type)
2. contains a field `error` 
3. with the expected error message
This uncovered *many* cases where errors were in plain text, or did not have a
properly formatted `error` message, or were being trapped in the wrong place,
or had an unnecessary stack trace.
Also fixed handling of parse errors in the API and the REPL (a recent
regression).
Eliminated curly quotes in responses, because they don't render right in
specs2 output.
=> consistently return errors in JSON (fixes #757)

core/src/main/scala/slamdata/engine/backend.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, core/src/main/scala/slamdata/engine/repl/repl.scala, it/src/test/scala/slamdata/engine/fs/filesystem.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fix a bug where, whenever a query was run without a specified output path, it
would actually be executed twice, and then only the second temporary result
would be deleted after the result was returned to the client. This meant that
GET queries were taking twice as long as they should, and were leaking one
copy of their results.
Fix another bug where a query would fail if the specified ouput collection
already existed, and leave behind the temporary result (which fixes #821).
Moved code to recursively list files from the web layer to `Backend.lsAll`.
Related fixes in the REPL:
- implement `env`
- fix parsing and handling of paths for the `[path] := select ...` command
=> fix temporary collection leaks

build.sbt, web/build.sbt, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/package.scala, web/src/main/scala/slamdata/engine/api/server.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #833.
The timeout is now a parameter when running the server, which is hard-coded to
infinity for real life, and set to 1 second in tests.
This required switching to the Blaze backend (probably a good thing anyway),
because of a bug in the Jetty backend that we were using (see
http4s/http4s#336). That required a workaround for the bug in the Blaze
backend that was the reason we went with the Jetty backend in the first place
(see http4s/http4s#337).
Disabled our `FailSafe` middleware, which was only necessary due to another
bug in the Jetty backend (see http4s/http4s#338).
Moved the http4s dependencies to the web sub-project, and bumped the version
to 0.8.3 for good measure.
=> use infinite idleTimeout in the API server

core/src/main/scala/slamdata/engine/physical/mongodb/collection.scala, core/src/test/scala/slamdata/engine/physical/mongodb/collection.scala
Fixes #760 and fixes #818.
Commonly-used reserved characters are mapped to less-common, unreserved chars:
(space -> `+`, `.` -> `~`), and everything else is mapped to a name prefixed
with `$`.
=> Encode reserved characters in database names

core/src/main/scala/slamdata/engine/compiler.scala, core/src/test/scala/slamdata/engine/compiler.scala, it/src/test/resources/tests/caseVariations.test
Fixes #815.
We were trying to compile an Expr that wasn't part of the original AST, so had
no annotations. This is the easy fix: just use the LogicalPlan equivalent
directly.
Really, `attr` should be partial, so it could fail if you ask for the
annotation for some unknown node. As it is, it has to be unsafe. But really
we'd rather use fixplate probably, so I'm not going there right now.
=> fix exception in compiler with un-annotated Expr

it/src/test/scala/slamdata/engine/regression.scala
Hoping it will improve performance in mongolab, which imposes a quota
which we may be nearing.
=> delete result collections along the way

core/src/main/scala/slamdata/engine/backends.scala, core/src/main/scala/slamdata/engine/physical/mongodb/evaluator.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/main/scala/slamdata/engine/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/evaluator.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala, it/src/test/resources/tests/fieldOrder.test, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes a case where we would invariably push `$$ROOT` if there was a single
simple field alongside an aggregate function (fixes #831). This is a one-line
fix in `objectConcat`.
Capture several steps within the Planner as PhaseResults to aid debugging:
- `Logical Plan (projections preferred)`: the rewritten LP actually used in
the planner
- `Workflow Builder`: speaks for itself
- `Workflow (raw)`: before any optimizations are applied
- `Workflow (finished)`: after reordering ops and deleting unused fields, but
before "crystallization" (see below)
The PhaseResult logged as `Physical Plan` now better represents what is
actually executed, because it shows inlining and shape-adjustments that are
done in `crystallize`.
Rename `Workflow.finalize` to `crystallize` to avoid clashing with the method …
=> Don't push $$ROOT as a rule.

project/plugins.sbt
These also eliminates a duplicate resolver warning we’ve been getting for a while.
=> Delete our explicit sbt-plugin resolver.

core/src/main/scala/slamdata/engine/analysis/fixplate.scala, core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/errors.scala, core/src/main/scala/slamdata/engine/logicalplan.scala, core/src/main/scala/slamdata/engine/mra.scala, core/src/main/scala/slamdata/engine/optimizer.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/compiler.scala, core/src/test/scala/slamdata/engine/logicalplan.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, it/src/test/resources/tests/joinWithMultipleConditions.test, it/src/test/scala/slamdata/engine/backendtest.scala
Fixes #847.
The compiler is simplified to merely compile the JoinRelation clause,
while there is a new (optional) LP phase to “align” the
condition (previously done by the compiler). And then the mongo planner
separates the list of expressions for the left and right sides of the join.
Also,
* add `cataM`,
* “fix” lpParaZygoHistoM to match other zygoHisto constructions, and
* change the default it config to use mongodb_3_0.
=> Generalize LP.Join to take an arbitrary condition.

web/build.sbt, web/src/test/scala/slamdata/engine/api/zip.scala
Hopefully fixing the intermittent failure where the zip files differed
in one or two bits, but the contents were identical.
=> compare unzipped contents, not zipped bits

core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/fp/EnvT.scala, core/src/main/scala/slamdata/engine/fp/package.scala, core/src/main/scala/slamdata/engine/functions.scala, core/src/main/scala/slamdata/engine/javascript/javascript.scala, core/src/main/scala/slamdata/engine/logicalplan.scala, core/src/main/scala/slamdata/engine/mra.scala, core/src/main/scala/slamdata/engine/optimizer.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/semantics.scala, core/src/main/scala/slamdata/engine/std/set.scala, core/src/main/scala/slamdata/engine/std/structural.scala, core/src/test/scala/slamdata/engine/analysis/fixplate.scala, core/src/test/scala/slamdata/engine/compiler.scala, core/src/test/scala/slamdata/engine/logicalplan.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala
Now that we handle arbitrary conditions, Join doesn’t need any special
handling, so it’s simpler to handle it as functions.
Also, `Cross` is just an `InnerJoin` where the condition is constantly
`true`, so that’s how it’s implemented now.
Finally, add some fp package coverage:
* Add a simple `gpara` test,
* delete some dead code, and
* fix a bug in EnvT uncovered by the new coverage.
=> Convert Joins from an LP node to a Func.

core/src/main/scala/slamdata/engine/backend.scala, core/src/main/scala/slamdata/engine/config/config.scala, core/src/main/scala/slamdata/engine/evaluator.scala, core/src/main/scala/slamdata/engine/physical/mongodb/evaluator.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, core/src/test/scala/slamdata/engine/config/config.scala, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/server.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #863.
Call `Backend.test` from the API before saving a new mount (previously it was
used only by the now defunct admin UI).
Make that test somewhat more robust by also writing a temp file so that it
fails in a read-only configuraiton.
Capture additional errors from MongoDB in our error types. Unfortunately, much
of the interesting information is available only in the message strings of the
MongoDB exceptions, so for now that's just captured and wrapped.
Also, went back to the simpler server setup for the bulk of the API tests. The
server restarting code path is now used only by the one test the depends on it
(and tests it), while the rest use the simpler, single-threaded setup.
Hopefully this will resolve the flakiness we've seen in Jenkins and elsewhere.
=> In the API, test connection to new mount before saving

build.sbt, core/src/main/scala/slamdata/engine/config/FsPath.scala, core/src/main/scala/slamdata/engine/config/OS.scala, core/src/main/scala/slamdata/engine/config/config.scala, core/src/main/scala/slamdata/engine/repl/repl.scala, core/src/test/scala/slamdata/engine/config/FsPath.scala, core/src/test/scala/slamdata/engine/config/config.scala, web/src/main/scala/slamdata/engine/api/server.scala
Integrates `pathy.Path` into the server config, replacing `String` paths with typesafe versions.
Introduces `FsPath` to encapsulate paths that may be in a volume (e.g. `c:\foo\bar`, `\\c\foo\bar`). I'm not sure if this is something we'd want to extend pathy with or if it lies outside the scope of that library. The library is advertised and dealing with filesystem paths, so in that sense it might belong, though there are other kinds of paths, like URIs, which pathy could be used for and also have a scheme prefix, similar to windows volumes.
Also, the system currently makes the assumption that any paths provided via the `LOCALAPPDATA` environment variable or the `user.home` JVM property are absolute, let me know if this is a poor assumption.
Fixes #858.
=> Refactor server config to use typesafe paths

core/src/main/scala/slamdata/engine/config/FsPath.scala, core/src/main/scala/slamdata/engine/config/config.scala, core/src/test/scala/slamdata/engine/config/config.scala
Fixes #879.
Requires updated pathy.
=> handle home directory without trailing slash on posix/mac

core/src/main/scala/slamdata/engine/physical/mongodb/bson.scala, core/src/main/scala/slamdata/engine/physical/mongodb/expression/package.scala, core/src/main/scala/slamdata/engine/physical/mongodb/findquery.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/bson.scala, core/src/test/scala/slamdata/engine/physical/mongodb/findquery.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, it/src/test/resources/tests/filterWithComplexNot.test, it/src/test/resources/tests/filterWithNot.test
Fixes #418.
Add `negate` method on Selector with unit tests.
Also rewrite `not(eq(...))` as `$ne`, because `$eq` isn't a thing and `$not`
requires an operator, and switch to the 3.0 driver's new BsonRegularExpression
wrapper, since `$not: { $regex: "..."}` isn't allowed.
=> implement Not in the selector phase

core/src/main/scala/slamdata/engine/compiler.scala, core/src/main/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/std/agg.scala, core/src/test/scala/slamdata/engine/compiler.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, it/src/test/resources/tests/aliasedFieldSortedByOriginal.test, it/src/test/resources/tests/boulderLikePop.test, it/src/test/resources/tests/citiesByTotalPopulation.test, it/src/test/resources/tests/groupByExpression.test, it/src/test/resources/tests/groupByFlatten.test, it/src/test/resources/tests/groupedJoin.test, it/src/test/resources/tests/largestCities.test, it/src/test/resources/tests/projectIndexFromGroup.test, it/src/test/resources/tests/projectIndexFromGroupWithFilter.test, it/src/test/resources/tests/statesByShortestFirstCity.test, it/src/test/resources/tests/zipsByCityLength.test
Fixes #459.
New Func `Arbitrary`, to select a single value from a set. Translated to $first for MongoDB.
During compilation, keep track of the compiled form of each grouping key, and then when any of them occurs in a projection (even embedded in a larger expression), wrap with `Arbitrary(...)` to simulate SQL semantics.
Handle an additional case in objectConcat that arises from the new shape.
Update query generator to avoid generating anything that would (correctly) lead to a plan with two consecutive group ops, because that pattern is flagged as a common characteristic of busted plans.
Update integration test queries to remove DISTINCT where it's no longer needed.
=> Project a single value for any expression appearing in the group keys

build.sbt, core/src/main/scala/slamdata/engine/physical/mongodb/optimize/optimize.scala, core/src/main/scala/slamdata/engine/physical/mongodb/reshape.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowop.scala, core/src/main/scala/slamdata/engine/physical/mongodb/workflowtask.scala, core/src/test/scala/slamdata/engine/physical/mongodb/optimize.scala, core/src/test/scala/slamdata/engine/physical/mongodb/pipeline.scala, core/src/test/scala/slamdata/engine/physical/mongodb/planner.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowbuilder.scala, core/src/test/scala/slamdata/engine/physical/mongodb/workflowop.scala
Expression tends to be the “default” state, and so we’ve been doing
things like `.map(_.swap)` and `.fold(Some(_), None)`. This eliminates
that extra hoop to jump through.
The three types changed are `WorkflowBuilder.Expr`,
`WorkflowBuilder.GroupValue`, and `Reshape.Shape`.
Also, update Scala to 2.11.7 (some dependency was forcing it anyway) and
add a missing `SpliceBuilder` case to `WorkflowBuilder.objectConcat`.
=> Put Expression on the right of various disjunctions.

it/src/test/scala/slamdata/engine/fs/filesystem.scala, web/build.sbt, web/src/test/scala/slamdata/engine/api/fs.scala
Fixes #886 (now known as SD-888), a stack overflow when reading several
thousand rows via the API with gzip encoding.
The bug was fixed in http4s, which is updated here. This commit adds
integration tests of the backend and of the API implementation, showing that
each is capable of emitting a 100k rows result set.
=> update to http4s 0.8.6

build.sbt
6.1-M6 was being evicted by sbt anyway and producing an annoying warning message
=> Upgrade Argonaut from 6.1-M6 to 6.1

core/src/main/scala/slamdata/engine/evaluator.scala, core/src/main/scala/slamdata/engine/physical/mongodb/evaluator.scala
Adds a human-readable name field to `Evaluator` which is used to identify the evaluator in error messages.
Resolves [SD-908](https://slamdata.atlassian.net/browse/SD-908).
=> Human-readable name for Evaluators

core/src/main/scala/slamdata/console.scala, core/src/main/scala/slamdata/fp/package.scala, scripts/testJar, web/src/main/scala/slamdata/engine/api/fs.scala, web/src/main/scala/slamdata/engine/api/server.scala, web/src/test/scala/slamdata/engine/api/fs.scala
Changes the behavior of `FileSystemApi` to only restart the api server when the port number is changed. For mounting changes, a local cache of the configuration is updated (in a `TaskRef`) after writing the updated config to disk.
The server main is also refactored in terms of `scalaz.stream.Process` which makes running + restarting uniform and allows us to test restarting the server deterministically.
=> [SD-876] Only restart api server when port number changed

scripts/startSlamEngine
A recent PR slightly modified the output of the server on startup, which caused the `startSlamEngine` script's success check to begin failing with a false-negative. This fixes the immediate issue to make jenkins happy.
In general, it'd be nice to come up with a more robust way of detecting success as the current method is a bit brittle. I didn't see an expedient way of DRYing up `testJar` and `startSlamEngine` whilst keeping `startSlamEngine` independent of the rest of the scripts (I assumed it should remain independent, but if it is ok that it depends on being in the scripts dir, then we could dry things up a bit by having the two share success criteria).
=> Update the start script's success check

core/src/main/scala/slamdata/engine/backend.scala, core/src/main/scala/slamdata/engine/physical/mongodb/filesystem.scala, it/src/test/scala/slamdata/engine/fs/filesystem.scala
Implementation of scan contained some bizarre wizardry that I believe is worthwhile to document and test. Update comment that was out of date.
=> Document and test behavior of Backend.scan

README.md
A couple references to SlamData slipped through, this renames them to Quasar.
=> Rename the remaining references to SlamData in the README

build.sbt, core/src/main/scala/quasar/backend.scala, it/src/test/scala/quasar/Interactive.scala, it/src/test/scala/quasar/backendtest.scala
- Add test classes of web project to it (integration) classpath
- Add convenience methods used by tests as conceivably sripts one day
- Create constants for MongoDB names
=> Add infrastructure required in order concisely write integration tests

core/src/main/scala/quasar/backend.scala, core/src/main/scala/quasar/physical/mongodb/filesystem.scala, it/src/test/scala/quasar/backendtest.scala, it/src/test/scala/quasar/fs/filesystem.scala, it/src/test/scala/quasar/regression.scala, scripts/build
This removes `Backend#defaultPath` which had dubious semantics and was only used in tests. Test usage was replaced with the ability to explicitly specify the prefix path for test backends via an environment variable, defaulting to `/quasar-test/` when unspecified.
=> Remove `Backend#defaultPath`

scripts/importTestData
MongoDB can be used without credentials, this makes this script take advantage of that.
Authored with @wemrysi
=> Make importTestData script more flexible

core/src/main/scala/quasar/backend.scala, core/src/main/scala/quasar/backends.scala, core/src/main/scala/quasar/evaluator.scala, core/src/main/scala/quasar/mounter.scala, core/src/main/scala/quasar/physical/mongodb/evaluator.scala, core/src/main/scala/quasar/physical/mongodb/filesystem.scala, core/src/main/scala/quasar/physical/mongodb/util.scala, core/src/main/scala/quasar/repl/repl.scala, it/src/test/scala/quasar/backendtest.scala, web/src/test/scala/quasar/api/fs.scala
For certain operations in the MongoDB backend (like checking the `mongod` version) and when faced with a query that doesn't read from a path, we need to be able to supply a database in order to proceed. Previously, we used the authentication db from the mongo connection URI for this, but this doesn't work when using mongo without authentication (or if the user doesn't have permission to write to the authentication db).
This removes the restriction by attempting to find a database the user has access to when needed. For checking the version, we just attempt the `buildinfo` command on the databases the user has access to until one works and error otherwise. For the case when we need a database for temp collections, we try and find the first one that we can create a collection in, again …
=> [SD-895] Don't require auth db in mongo connection string

core/src/main/scala/quasar/config/config.scala, core/src/test/scala/quasar/config/config.scala, scripts/testJar
Removes another instance of "SlamData" that slipped by, the name of the parent dir of the config file.
=> Remove 'SlamData' from the configuration file path

core/src/main/scala/quasar/config/config.scala, core/src/main/scala/quasar/physical/mongodb/util.scala, core/src/test/scala/quasar/config/config.scala, web/src/main/scala/quasar/api/fs.scala, web/src/test/scala/quasar/api/fs.scala
MongoDBConfig now accepts a mongo.StringConnection instead of a String and no longer requires it to be validated as it is now safe by construction.
=> Improve typesafety of MongoDbConfig

core/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, core/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala, core/src/test/scala/quasar/std/set.scala
Since `GroupBuilder` started holding separate `WorkflowBuilder`s for its
keys, maintaining a `GroupId` created with the original set of keys is
no longer necessary. We still generate the ID in `render` to make it
easy to eyeball groups that should align.
Also removed a no-longer-used `merge` case.
=> Remove GroupId.

core/src/main/scala/quasar/compiler.scala, core/src/main/scala/quasar/sql/parser.scala, core/src/test/scala/quasar/compiler.scala, core/src/test/scala/quasar/sql/SqlParserSpec.scala
* A better error when faced with an unbound SQL var,
* avoid wrapping/unwrapping a string in `parse`/`parseExpr`,
* a test to show that we can parse `primary_expr` at the top level.
This doesn’t fix any issues, but hopefully provides some clarity on
SD-1044 and SD-1046.
=> A few improvments on the SQL side.

web/src/test/scala/quasar/api/fs.scala
SD-1052 #done 
Intermittent failure turned out to be caused by the relatively short timeout we were using in tests, and the bizarre retry behavior of the dispatch client. Simply increasing the timeout to a few seconds makes it go away.
=> In API tests, increase timeout to 5 seconds.

core/src/main/scala/quasar/compiler.scala, core/src/main/scala/quasar/logicalplan.scala, core/src/main/scala/quasar/semantics.scala, core/src/main/scala/quasar/sql/package.scala, core/src/main/scala/quasar/std/structural.scala, core/src/test/scala/quasar/compiler.scala
* Use `testLogicalPlanCompile` and `equalToPlan` consistently in
compiler tests,
* clean up some Compiler code, and
* clean up some LogicalPlan code.
=> Cleanup in prep for SQL² changes.

core/src/main/scala/quasar/RenderTree.scala, core/src/main/scala/quasar/compiler.scala, core/src/main/scala/quasar/functions.scala, core/src/main/scala/quasar/jscore/package.scala, core/src/main/scala/quasar/optimizer.scala, core/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala, core/src/main/scala/quasar/physical/mongodb/planner.scala, core/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, core/src/main/scala/quasar/physical/mongodb/workflowop.scala, core/src/main/scala/quasar/planner.scala, core/src/main/scala/quasar/recursionschemes/FunctorT.scala, core/src/main/scala/quasar/recursionschemes/Recursive.scala, core/src/main/scala/quasar/recursionschemes/TraverseT.scala, core/src/main/scala/quasar/recursionschemes/package.scala, core/src/main/scala/quasar/std/library.scala, core/src/main/scala/quasar/std/relations.scala, core/src/main/scala/quasar/std/set.scala, core/src/main/scala/quasar/std/string.scala, core/src/main/scala/quasar/std/structural.scala, core/src/test/scala/quasar/compiler.scala, core/src/test/scala/quasar/helpers.scala, core/src/test/scala/quasar/matchers.scala, core/src/test/scala/quasar/optimizer.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala, core/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala, core/src/test/scala/quasar/recursionschemes/spec.scala
This makes the compiler tests more robust to compiler changes. On failure, we
display both the normalized diff and the original (un-normalized)
result.
`TraverseT` (and `FunctorT`) is a generalization of
`Recursive with Corecursive` providing `traverse` (and `map`) for types
that can’t implement one of `Recursive` or `Corecursive` (EG, `Free` and `Cofree`).
Transformations have been moved from the `Recursive` type class to the
new type classes, and some existing algebras have been generalized from
`Fix` to `T[_[_]]`.
=> Introduce FunctorT and TraverseT.

core/src/main/scala/quasar/physical/mongodb/planner.scala, core/src/main/scala/quasar/sql/package.scala, core/src/main/scala/quasar/sql/parser.scala, core/src/test/scala/quasar/compiler.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala, it/src/main/resources/tests/multilineLike.test
* Treat all regexes as multiline (SD-1100 #done),
* change default LIKE escape char from none to `\\`, and
* add `~~` and `!~~` as aliases for `LIKE` and `NOT LIKE`.
=> Various LIKE fixes.

core/src/test/scala/quasar/compiler.scala, it/src/test/scala/quasar/view.scala
Two tests were marked pending and their assertions were broken; one was just wrong and the other had become out-dated since last week.
This commit provides the proof that getting rid of AnnotatedTree fixed SD-1101.
=> enable pending tests for sub-select scoping with views

core/src/main/scala/quasar/repl/repl.scala
A temporary fix in anticipation of bigger changes coming soon.
=> fix sequencing of the REPL's prompt with ls ouput

README.md, core/src/main/scala/quasar/backend.scala, core/src/main/scala/quasar/config/config.scala, core/src/main/scala/quasar/mounter.scala, web/src/main/scala/quasar/api/fs.scala, web/src/test/scala/quasar/api/fs.scala
- construct the ViewBackend wrapping the regular filesystem and interpreting all requests involving views
- allow views to be created through the API
- update the README with details on view configuration and affected APIs
This completes SD-976 and SD-977.
=> Enable view creation and interpretation

README.md, core/src/main/scala/quasar/backend.scala, core/src/main/scala/quasar/physical/mongodb/filesystem.scala, core/src/main/scala/quasar/repl/repl.scala, it/src/test/scala/quasar/InteractiveTest.scala, it/src/test/scala/quasar/fs/filesystem.scala, it/src/test/scala/quasar/view.scala, web/src/main/scala/quasar/api/fs.scala, web/src/test/scala/quasar/api/fs.scala
SD-978 #done
This allows a client to identify views as both a kind of mount and a kind of file.
Also fixed the listing of directories which are mounts but also contain overlayed views, and where a view appears at the same path as an actual file.
=> Split /metadata's "type" field into "type" and "mount".

web/src/main/scala/quasar/api/fs.scala, web/src/test/scala/quasar/api/fs.scala
Was empty, now has valid JSON with `{ "error": "There is no file/directory at path ..."}`
Note: this fixes only the request which was changed to a 404 in a recent commit. A quick search shows several other occurrences of `NotFound()` which we might want to address, probably in our existing "improve error messages" ticket ([SD-824](https://slamdata.atlassian.net/browse/SD-824)).
=> fix /metadata 404 response body

core/src/main/scala/quasar/backend.scala, it/src/test/scala/quasar/view.scala
SD-1165 #done
When the ViewBackend is created, it normalizes all paths in every view
query so that they can be composed with each other. Previously, this
normalization ignored absolute paths, leaving us with a mixture of
absolute and relative paths, and if an absolute path happened to refer
to another view, it would not be properly expanded when it came time to
evaluate the (outer) view's query.
Now all paths in view queries are converted to absolute, just to make
it easier to understand/explain. The locations of the views themselves
are still stored as relative and interpreted relative to '/', just
because that's how the Backend trait works. That means the fix here is
really just to convert paths in queries to relative when doing the view
lookup.
=> fix handling of views containing absolute paths

core/src/main/scala/quasar/fs/InMemory.scala, core/src/main/scala/quasar/fs/QueryFile.scala, core/src/main/scala/quasar/fs/chroot.scala, core/src/main/scala/quasar/physical/mongodb/fs/queryfile.scala, web/src/main/scala/quasar/api/server.scala, web/src/main/scala/quasar/api/services/query.scala, web/src/test/scala/quasar/api/services/CompileAndQueryServiceSpec.scala
Makes some minor modifications to the `Explain` constructor and adds the implementation for MongoDB.
An output file is added to the `Explain` constructor as, in this PR, there is no support for streaming queries and it seemed to make sense to handle this in one spot rather than have each backend have to do it. Note that the client API does not require an output file as either the first one from the LP is used or a placeholder is used.
=> [SD-1146] Implement Explain for MongoDB interpreter

core/src/main/scala/quasar/sql/parser.scala, core/src/main/scala/quasar/std/array.scala, core/src/main/scala/quasar/std/set.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala
Progress toward SD-1045.
* Parse `()` as an empty set,
* constant-fold `x IN ()` to `false`, and
* don’t accept arrays for `IN`.
This doesn’t solve the final problem of single-element sets, which would be easy with SD-1078 fixed.
=> Improvements to handling set literals.

core/src/test/scala/quasar/physical/mongodb/collection.scala
Scalacheck tests for creating a Collection from a pathy path were
occasionally failing due to scalacheck not being able to generate enough
inputs satisfying the test constraints, this reformulates the test to hopefully reduce the likelyhood
of this happening.
=> Attempt to make Collection test less volatile

core/src/main/scala/quasar/physical/mongodb/planner.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala, it/src/main/resources/tests/longCitiesWithLength.test, it/src/main/resources/tests/statesByShortestFirstCity.test, it/src/main/resources/tests/zipsByCityLength.test
Both `Length` and `Count` are defined to return Int, but we’ve just been
using the native JS numbers. This uses Mongo’s `NumberLong` to make sure
the results are integers.
=> Have Mongo’s JS return Ints when appropriate.

core/src/main/scala/quasar/fp/free/Interpreter.scala, core/src/main/scala/quasar/fs/InMemory.scala, core/src/main/scala/quasar/fs/QueryFile.scala, core/src/test/scala/quasar/fs/FileSystemFixture.scala, core/src/test/scala/quasar/fs/QueryFileSpec.scala, core/src/test/scala/quasar/fs/WriteFileSpec.scala, web/src/main/scala/quasar/api/services/package.scala, web/src/test/scala/quasar/api/services/CompileAndQueryServiceSpec.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala
- InMemState now has pre-canned responses for queries
- other minor improvements
- Remove scaladoc links in Interpreter causing doc generation failures
- Various fixes in CompileAndQueryServiceSpec in order to make all tests pass
=> Fix test failures in CompileAndQueryServiceSpec

README.md, web/src/main/scala/quasar/api/fs.scala, web/src/test/scala/quasar/api/fs.scala
SD-1150 #done
`GET /query` requests now accept `offset`, `limit`, and `var.` parameters, and `POST` now expects variables to have the `var.` prefix as well.
**Note:** this is a breaking API change. Clients need to be updated to prefix variable names when calling `POST /query`.
Also implemented variables in `/compile` (it was already mentioned in the README, but apparently never implemented).
Tests for all of the above that actually inspect the resulting plans.
=> handle variables, offset, and limit in GET /query

core/src/main/scala/quasar/sql/parser.scala, core/src/test/scala/quasar/sql/SqlParserSpec.scala
SD-1169 #done
Formerly, the parser would always attempt to parse a parenthesized
expression as a set literal, then fail when it turned out to contain
only one expression, and then re-parse it as a single expression. So it
was O(2^n) for certain patterns, including the way the pretty printer
renders long sequences of "or".
A simple fix is just to parse once and then decide based on the number
of sub-expressions whether to parse to SetLiteral or just an expression.
Three new tests (which pass before the fix) just verify the expected
behavior for 0-, 1-, and 2-element parenthesized expressions, and one
new test is the query from the bug report, which used to take at least
many minutes to parse, and now takes well under a second.
=> avoid excessive backtracking when parsing deeply-nested parens

web/src/test/scala/quasar/api/fs.scala
This fixes the compile on master.
Obviously, it's not safe to merge without rebasing, but github said it was fine, so I got lazy. Not sure why this additional import is now necessary, but it certainly fixes the compile.
=> import Fix._

README.md, build.sbt, core/src/main/scala/quasar/backend.scala, core/src/main/scala/quasar/config/config.scala, core/src/main/scala/quasar/evaluator.scala, core/src/main/scala/quasar/mounter.scala, core/src/main/scala/quasar/package.scala, core/src/main/scala/quasar/planner.scala, core/src/main/scala/quasar/sql/package.scala, core/src/main/scala/quasar/variables.scala, core/src/test/scala/quasar/config/config.scala, it/src/test/scala/quasar/view.scala, project/CustomKeys.scala, web/build.sbt, web/src/test/scala/quasar/api/fs.scala
SD-1143 #done
Accept variable bindings in the connectionUri for a view mount. These are parsed out to a Variables map in ViewConfig (so they can be re-serialied later), and substituted into the view query when it is mounted. Unbound variables lead to errors 1) when a view mount is added through the API and 2) whenever a view query is evaluated through Backend's methods.
A few new bits and pieces:
- Yet another error wrapper to embed CompilationError in EnvironmentError.
- A convenience `substVars()` which doesn't need type annotations, since it's now being used in a third place.
- Replace `rewriteRelations()` with `rewriteRelationsM()`.
=> handle variable bindings in views

build.sbt, core/src/main/scala/quasar/EnvironmentError.scala, core/src/main/scala/quasar/NameGenerator.scala, core/src/main/scala/quasar/fp/package.scala, core/src/main/scala/quasar/fp/prism.scala, core/src/main/scala/quasar/mount/ConnectionUri.scala, core/src/main/scala/quasar/mount/FileSystemType.scala, core/src/main/scala/quasar/mount/MapMounter.scala, core/src/main/scala/quasar/mount/MountConfig.scala, core/src/main/scala/quasar/mount/Mounting.scala, core/src/main/scala/quasar/mount/MountingError.scala, core/src/main/scala/quasar/mount/package.scala, core/src/main/scala/quasar/physical/mongodb/MongoDbIOWorkflowExecutor.scala, core/src/main/scala/quasar/physical/mongodb/WorkflowExecutor.scala, core/src/test/scala/quasar/mount/MapMounterSpec.scala, core/src/test/scala/quasar/mount/MountingSpec.scala
Adds a `Mounting` algebra describing the operations of managing filesystem mounts. A spec is included, implemented in terms of the algebra that describes how an interpreter of the algebra must behave.
A single interpreter is also defined, that maintains mount state in memory, allowing effectful mounting via a callback function.
=> [SD-1170] Mounting algebra

core/src/main/scala/quasar/RenderTree.scala, core/src/main/scala/quasar/compiler.scala, core/src/main/scala/quasar/config/config.scala, core/src/main/scala/quasar/fp/package.scala, core/src/main/scala/quasar/logicalplan.scala, core/src/main/scala/quasar/optimizer.scala, core/src/main/scala/quasar/package.scala, core/src/main/scala/quasar/physical/mongodb/planner.scala, core/src/main/scala/quasar/physical/mongodb/selector.scala, core/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, core/src/main/scala/quasar/physical/mongodb/workflowop.scala, core/src/main/scala/quasar/planner.scala, core/src/main/scala/quasar/recursionschemes/Fix.scala, core/src/main/scala/quasar/recursionschemes/Recursive.scala, core/src/main/scala/quasar/recursionschemes/TraverseT.scala, core/src/main/scala/quasar/recursionschemes/package.scala, core/src/test/scala/quasar/compiler.scala, core/src/test/scala/quasar/helpers.scala, core/src/test/scala/quasar/logicalplan.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala, core/src/test/scala/quasar/recursionschemes/spec.scala, it/src/main/resources/tests/crossJoin.test, it/src/main/resources/tests/crossJoinWithOneSidedConditions.test, web/src/main/scala/quasar/api/server.scala, web/src/test/scala/quasar/api/fs.scala
Includes a handful of small fixes, and then the main event:
Rewrite InnerJoin/Filter sequences, putting conditions before, in, or after the join.
The idea is to identify all filtering associated with an inner join in the source plan, breaking down all components into four categories:
- conditions referring to only the left or only the right source, which can be moved ahead of the join (SD-910)
- conditions referring to both sources using `=`, which can be rewritten into the join (SD-1063)
- all others, which have to be done after the join
This is implemented in a new rewriteCrossJoins fold, which uses boundParaM (which is new). Because the new fold introduces new temp names which made it difficult for tests to compare plans, names are now rewritten to a compact sequence starting with …
=> Optimize apparent cross joins

core/src/main/scala/quasar/physical/mongodb/MongoDbIO.scala, core/src/main/scala/quasar/physical/mongodb/MongoDbIOWorkflowExecutor.scala, core/src/main/scala/quasar/physical/mongodb/MongoWrapper.scala, core/src/main/scala/quasar/physical/mongodb/bson.scala, core/src/main/scala/quasar/physical/mongodb/evaluator.scala, core/src/main/scala/quasar/physical/mongodb/filesystem.scala, core/src/main/scala/quasar/physical/mongodb/fs/readfile.scala, core/src/main/scala/quasar/physical/mongodb/fs/writefile.scala, core/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala, core/src/main/scala/quasar/physical/mongodb/selector.scala, core/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, core/src/main/scala/quasar/physical/mongodb/workflowop.scala, core/src/test/scala/quasar/physical/mongodb/bson.scala, core/src/test/scala/quasar/physical/mongodb/evaluator.scala, core/src/test/scala/quasar/physical/mongodb/expression/spec.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala, core/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala, core/src/test/scala/quasar/physical/mongodb/workflowop.scala, it/src/main/resources/tests/filteredDistinct.test, it/src/main/resources/tests/singleFieldDistinct.test
SD-956 #done
A few other changes done to support this:
* Replaced the `java.lang.Object` BSON representation with the new
`BsonValue` one added in the 3.0 driver. This is a bit more principled
and gets rid of a few places where we had to suppress WartRemover
warnings.
* Implemented `org.bson.conversions.Bson` for our Bson type, which
eliminates some cases where we previously had to explicitly convert to
BsonDocument.
* Modified `Workflow.distinct` to distinct in a way that can be
optimized by `simplifyGroupƒ`, which also makes it easier to match in
the evaluator.
Otherwise, this follows the same form as the `find()` and `count()`
implementations.
=> Implement streaming distinct() on MongoDB.

core/src/main/scala/quasar/effect/Failure.scala, core/src/main/scala/quasar/effect/KeyValueStore.scala, core/src/main/scala/quasar/effect/LiftedOps.scala, core/src/main/scala/quasar/effect/MonotonicSeq.scala, core/src/main/scala/quasar/effect/package.scala, core/src/main/scala/quasar/fs/ManageFile.scala, core/src/main/scala/quasar/fs/QueryFile.scala, core/src/main/scala/quasar/fs/ReadFile.scala, core/src/main/scala/quasar/fs/WriteFile.scala, core/src/main/scala/quasar/mount/Mounting.scala
Adds algebras for three new, generic, effects: monotonic numeric sequence source, key-value store and failure, mostly extracted from @mossprescott's work in #1040. This is just to make the new algebras available to others and avoid blocking on that PR.
=> Additional effect algebras

build.sbt
The dependency was missing. Also updated the start command for the
current version.
I'm sure this was working at one point, but I could not find the dependency anywhere in the history. I find it useful occasionally, so here's a fix that also brings it up to the current version.
=> fix ammonite shell

core/src/main/scala/quasar/fs/ManageFile.scala, core/src/main/scala/quasar/fs/QueryFile.scala, core/src/main/scala/quasar/fs/ReadFile.scala, core/src/main/scala/quasar/fs/Views.scala, core/src/main/scala/quasar/fs/WriteFile.scala, core/src/main/scala/quasar/fs/view.scala, core/src/test/scala/quasar/fs/TraceFS.scala, core/src/test/scala/quasar/fs/view.scala
Note: this is based on @jedesah's PR to fix the build. Will rebase on master as soon as that's merged, just to be safe.
After burning a bunch of time trying to get RenderTree to work with the quantified type we were using for `Trace`, I realized it gets a lot simpler if we just render *before* accumulating the values in Writer, so here's an implementation of that, plus some slight improvements to the view tests following on JR's addition.
=> Readable TraceFS logs

core/src/main/scala/quasar/effect/AtomicRef.scala, core/src/main/scala/quasar/effect/Failure.scala, core/src/main/scala/quasar/effect/KeyValueStore.scala, core/src/main/scala/quasar/effect/MonotonicSeq.scala, core/src/test/scala/quasar/fs/mount/FileSystemMounterSpec.scala, core/src/test/scala/quasar/fs/mount/HierarchicalFileSystemSpec.scala, core/src/test/scala/quasar/fs/mount/ViewMounterSpec.scala, core/src/test/scala/quasar/fs/mount/view.scala, it/src/test/scala/quasar/fs/FileSystemTest.scala, it/src/test/scala/quasar/regression/package.scala
Instead of the default interpreters for effects in `quasar.effect` interpreting into specific monads, we can use the "mtl" classes, like `MonadState` and `MonadError`, where possible for more generality.
=> Refactor effect interpreters to use MTL classes when available

core/src/main/scala/quasar/fs/InMemory.scala, core/src/main/scala/quasar/fs/mount/Mounting.scala, core/src/main/scala/quasar/fs/mount/MountingError.scala, core/src/main/scala/quasar/fs/mount/package.scala, core/src/test/scala/quasar/fs/mount/MountingSpec.scala, web/src/main/scala/quasar/api/package.scala, web/src/main/scala/quasar/api/server.scala, web/src/main/scala/quasar/api/services/RestApi.scala, web/src/main/scala/quasar/api/services/data.scala, web/src/main/scala/quasar/api/services/mount.scala, web/src/main/scala/quasar/api/services/package.scala, web/src/main/scala/quasar/api/services/query.scala, web/src/test/scala/quasar/api/services/CompileAndQueryServiceSpec.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala, web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala, web/src/test/scala/quasar/api/services/RestApiSpecs.scala
See SD-1142
In `Mounting.Ops.mount`, return errors that result from the ambiguity in that method's argument in a separate error type (PathTypeMismatch), so that MountingErrors will only represent errors from actually interpreting the algebra.
New common stuff:
- `errorResponse()` to format simple error messages in the expected JSON syntax.
- Use that in generating responses for FileSystemError and PathError2.
- `requiredHeader()` to extract headers in a convenient EitherT.
- `resandbox()` for the previously duplicated code to fix up the type of `Abs` paths parsed by the services.
Renamed FileName to XFileName to hopefully reduce confusion and to avoid collisions.
=> Implement the /mount API given a `Mounting ~> Task`

core/src/main/scala/quasar/config/writeConfig.scala, core/src/main/scala/quasar/effect/AtomicRef.scala, core/src/main/scala/quasar/effect/KeyValueStore.scala, core/src/main/scala/quasar/fp/package.scala, web/src/main/scala/quasar/api/ServerOps.scala
Part of SD-1184.
Includes a couple of new generic interpreters for AtomicRef and KeyValueStore, a little bit of code to stack them up for use in the web services, and slightly more involved initialization of the server to set up the inital mounts and then persist changes made after that.
=> Interpret the mount store by reading/writing the config state

core/src/main/scala/quasar/physical/mongodb/collection.scala, core/src/test/scala/quasar/physical/mongodb/collection.scala, web/src/main/scala/quasar/api/package.scala, web/src/test/scala/quasar/api/AsPathSpec.scala, web/src/test/scala/quasar/api/PathUtils.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala
Really not happy about all the silly filtering this requires in the tests but didn't want to make this wait for a fix in pathy. On the other hand, switching the escape char for DB's has hardly any fallout.
With this in place, I can add folders at the DB-level, through the API, with names like `Untitled Folder.slam` and `foo/bar.slam`:
```
> show databases
...
Untitled+Folder~slam  0.078GB
admin                 0.078GB
foo%divbar~slam       0.078GB
quasar-test           0.453GB
```
=> Path encoding/escaping issues

core/src/main/scala/quasar/backend.scala, core/src/main/scala/quasar/compiler.scala, core/src/main/scala/quasar/planner.scala, core/src/main/scala/quasar/repl/repl.scala, core/src/main/scala/quasar/semantics.scala, core/src/main/scala/quasar/sql/ast.scala, core/src/main/scala/quasar/sql/fixpoint.scala, core/src/main/scala/quasar/sql/package.scala, core/src/main/scala/quasar/sql/parser.scala, core/src/main/scala/quasar/std/set.scala, core/src/main/scala/quasar/std/structural.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala
Previously, the REPL only recognized expressions that began with
`select`, however, the parser has long been able to handle expressions
like `4 + 3`, etc. that don’t use `select`. This gets rid of the
`Unknown` REPL command, and tries to treat anything that doesn’t match
some other pattern as an expression.
This also adds literal map/object syntax to the parser & SQL AST (part
of SD-990), short-circuits Constant LPs before calling the backend
planner, and fixes a few other issues I ran into when testing the REPL:
* `select 4 + 3 offset 1` would parse incorrectly as `select (4 + 3 offset 1)`,
* flattening didn’t constant fold when it could, and
* `Take`/`Drop`/`MakeArray`/`MakeObject` didn’t operate on Data.Set correctly.
=> Allow arbitrary expressions in the REPL.

CHANGELOG/3.0.1.md, version.sbt
This time *not* using `sbt release`, just for giggles.
=> Releasing 3.0.1

project/Dependencies.scala
Other than staying current, the main reason for upgrading is the
potential performance benefits for `Free`, given the `fastFlatMap`
optimization backported in 7.1.7.
See https://github.com/scalaz/scalaz/pull/1085
=> Update scalaz to 7.1.7

example-quasar-config.json
- It gets used as part of our test suite that runs on Travis and it is too flaky. Hardcode to localhost instead.
=> Remove use of mongolabs in sample config file

web/src/main/scala/quasar/api/Http4sUtils.scala, web/src/main/scala/quasar/api/ServerOps.scala, web/src/main/scala/quasar/api/services/RestApi.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala, web/src/test/scala/quasar/api/services/RestApiSpecs.scala, web/src/test/scala/quasar/api/services/ServerServiceSpec.scala
By "finalization" I mean the collapsing of the various individual api services into a single service that routes requests via the path and adds our standard middleware, feel free to suggest a better name for this.
* Separates choice of what to finalize from finalization itself
* Move api mounting out of the server, update ServerBlueprint
* Take advantage of composition to construct default middleware
Most of these changes are to make existing "server" functionality easier to reuse in quasar-advanced.
I think there is more we could do to this end, but I didn't want to risk disrupting too much before the 2.5 release. For example, I'm not sure we need the `Prefix` middleware we're currently using and could instead use `org.http4s.server.Router`, but wasn't sure if we had anything that …
=> Refactor how "finalization" of qservices is done

core/src/main/scala/quasar/functions.scala, core/src/main/scala/quasar/optimizer.scala, core/src/main/scala/quasar/physical/mongodb/planner.scala, core/src/main/scala/quasar/std/library.scala, core/src/main/scala/quasar/std/math.scala, core/src/main/scala/quasar/std/relations.scala, core/src/main/scala/quasar/std/set.scala, core/src/main/scala/quasar/std/string.scala, core/src/main/scala/quasar/std/structural.scala, core/src/test/scala/quasar/matchers.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala, it/src/main/resources/tests/inBareElement.test, it/src/main/resources/tests/singleElementSet.test
SD-1344 #done
In SQL²/MRA,  a value and a single-element set have the same
semantics. This makes that happen for the `IN` operator, which has been
a long-standing problem for the frontend.
=> Fix handling of `IN` for single-element sets.

core/src/main/scala/quasar/sql/parser.scala, it/src/main/resources/tests/delete.test
This is an expression, not a statement – it simply returns a new set
that’s a subset of the original set.
=> Implement the `delete` expression.

CHANGELOG/4.0.1.md, core/src/main/scala/quasar/physical/mongodb/WorkflowExecutionError.scala, version.sbt, web/src/main/scala/quasar/api/ServerOps.scala, web/src/main/scala/quasar/api/ToQuasarResponse.scala
As part of the translation to the free architecture, we handled some `Failure` effects via `Task.fail`, this caused a few classes of errors to always result in 500 responses.
This fixes the problem by properly interpreting these errors into `QuasarResponse`s.
Unfortunately this happens when constructing the final interpreters in `main` and thus there is no test coverage currently. We'll need tests for the server process itself to check that the effects are being evaluated as expected.
Authored with @mossprescott
=> Fix bug where failure effects were being handled via Task.fail

CHANGELOG/4.0.2.md, core/src/main/scala/quasar/fp/package.scala, core/src/main/scala/quasar/fp/process.scala, version.sbt, web/src/main/scala/quasar/api/QuasarResponse.scala, web/src/test/scala/quasar/api/QuasarResponseSpec.scala
Fixes an issue where when a `QuasarResponse` body `Process` emits some output before the first effect and/or has other `Await` cases before the first "real" effect (like those introduced by many process1 combinators) _and_ the first `F` effect fails, the resulting response becomes a `200 OK` and then drops the connection.
More concretely, this manifested when retrieving a view-backed file via the `/data/fs` endpoint in `application/json` format where the view query resulted in an error. In this case, a `[\n` is prepended to the output stream which also has process1 "effects" due to `intersperse`-ing characters between the values in the response.
Kudos to @mossprescott who actually figured out the problem and authored the solution with me.
This is related to SD-1367, but I'm not sure if it …
=> [SD-1367] Fix issue where certain error conditions would respond with 200 and then drop connection

CHANGELOG/4.0.3.md, version.sbt, web/src/main/scala/quasar/api/services/query/compile.scala, web/src/main/scala/quasar/api/services/query/execute.scala, web/src/test/scala/quasar/api/PathUtils.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala, web/src/test/scala/quasar/api/services/query/QueryFixture.scala, web/src/test/scala/quasar/api/services/query/QueryServiceSpec.scala
Fixes SD-1364
Pass file/dir path through to the queryPlanner, which will reject file paths as required, and added a test to verify the resulting error message.
Also moved the `pathUri` utility function that properly escapes paths for use in request URIs to PathUtil where it can be used in any test.
=> Improve the error message when a file path is supplied to the /query service

CHANGELOG/4.0.6.md, core/src/main/scala/quasar/PhaseResult.scala, core/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala, core/src/main/scala/quasar/physical/mongodb/workflowop.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala, core/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala, core/src/test/scala/quasar/physical/mongodb/workflowop.scala, version.sbt
Fixes SD-1403
Two cases were being silently dropped:
1. "dangling" references, where a project op referred to a name that was simply missing from the previous shape.
2. references where the referenced expresion was not a trival name _and_ the reference reached down into the named object. In particular, the case we were hitting is when the first projection does a type check on `$$ROOT` (i.e. `"__tmp0": $cond(..., $$ROOT, undefined)`) and then the second reaches in with something like `"__tmp3": "$__tmp0.city"`.
Both cases are now treated as non-inlinable and the two projections are left as is. That makes the dangling reference easier to spot and debug (and it will be caught in property-based tests). In the second case, it seems prudent to preserve the two projections because attempting to …
=> fix inlining of $project ops

CHANGELOG/4.1.1.md, core/src/test/scala/quasar/fp/numeric/NumericArbitrary.scala, core/src/test/scala/quasar/fp/numeric/SafeIntForVectorArbitrary.scala, it/src/test/scala/quasar/fs/ReadFilesSpec.scala, project/Dependencies.scala, version.sbt, web/src/test/scala/quasar/api/services/DataServiceSpec.scala
- Fix bug in `Choose` instance of `SafeIntForVector`
- Add custom generators for discrete refined numerical values
- fix error in specification of "scan with offset k and limit j takes j data, starting from k" in ReadFilesSpec
- use custom generators in specs
=> Improve reliability of arbitrary generation of refined values

CHANGELOG/4.1.2.md, core/src/main/scala/quasar/fs/InMemory.scala, core/src/main/scala/quasar/logicalplan.scala, core/src/main/scala/quasar/optimizer.scala, core/src/test/scala/quasar/compiler.scala, core/src/test/scala/quasar/logicalplan.scala, core/src/test/scala/quasar/physical/mongodb/planner.scala, version.sbt, web/src/test/scala/quasar/api/services/query/ExecuteServiceSpec.scala
A little more normalization of the incoming plan was sufficient to get the existing rewriting to recognize the additional case mentioned in SD-1418.
Specifically, we now "hoist" Lets that appear in the arguments of Invoke and Typecheck. Note: this is safe only if there is no possibility of introducing spurious shadowing, which we arrange for by first normalizing the names (which ensures they are all unique). Therefore this PR adds a couple of additional rewrites to `optimize`, and also makes the rewrites even more sensitive to being applied in the correct sequence.
The fallout was surprisingly modest:
- only 6 compiler tests needed to be updated for Lets moving around
- only 1 planner test needed updating. See my comment on the commit.
=> Push filtering ahead of joins that already have conditions

CHANGELOG/revision.md, core/src/main/scala/quasar/fs/mount/FileSystemDef.scala, core/src/main/scala/quasar/fs/mount/FileSystemMountHandler.scala, core/src/main/scala/quasar/fs/mount/MountRequestHandler.scala, core/src/test/scala/quasar/fs/mount/FileSystemDefSpec.scala
Now the monoid will only choose an alternate def if the first could not handle the arguments whereas previously we would try another if the first _did_ handle the arguments and failed.
=> Refactor FileSystemDef monoid to not forget errors

CHANGELOG/revision.md, build.sbt, core/src/test/scala/quasar/compiler.scala, core/src/test/scala/quasar/semantics.scala, core/src/test/scala/quasar/specs2/decorators.scala, core/src/test/scala/quasar/std/math.scala, core/src/test/scala/quasar/std/relations.scala, core/src/test/scala/quasar/std/set.scala, core/src/test/scala/quasar/types.scala, foundation/src/test/scala/quasar/QuasarSpecification.scala, foundation/src/test/scala/quasar/decorators.scala, it/src/test/scala/quasar/regression/QueryRegressionTest.scala, mongodb/src/test/scala/quasar/physical/mongodb/pipeline.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala, mongodb/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala
This also makes skipping pending tests automatic for QuasarSpecification. We were previously using it inconsistently.
=> Skip pending regression tests

CHANGELOG/revision.md, project/Dependencies.scala
Binary compatibility issues: specs 3.8.4 is built against
scalacheck 1.13.1 but we must use 1.12.5. Eric was kind enough
to publish a 3.8.4-against-1.12.5 artifact.
=> Update specs to compatible version.

CHANGELOG/revision.md, it/src/test/scala/quasar/TaskResource.scala
This should turn "no output for 10 minutes" into an immediate failure with a record of the cause. We had a simple bug in the handling of those connection failures during the construction of interpreters for regression tests.
I'll move this to "in review" as soon as I get confirmation from Travis.
=> fix hang in regression tests when connection failure occurs

CHANGELOG/revision.md, build.sbt
This simple change seems to eliminate "connection timeout" failures (which until recently were hangs).
However, the cost is steep: roughly 20 minutes longer to run build #1 in Travis (just over an hour vs about 40 minutes, in my most recent comparison). The times for the other 3 builds seem to be affected very little.
I'm submitting this to get a build everyone can look at, and also to raise the question of whether this is yet bad enough to consider this fix.
=> disable parallel execution for it tests in Travis

CHANGELOG/feature.md, mongodb/src/main/scala/quasar/physical/mongodb/JoinHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala, mongodb/src/main/scala/quasar/physical/mongodb/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowop.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowtask/package.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala
Pull `join` out of WorkflowBuilder, and implement a pair of `JoinHandler`s with different requirements on the workflow type. If the plan's structure does not conform to the very simple pattern, then we fall back to map-reduce as before.
@jdegoes: This commit does not include any checking of the collections `$lookup` is applied to, so it will fail if the sources are in different databases, or if the collection being merged _in_ is sharded. These checks to prevent runtime errors are the next thing on my list. If you would rather not merge this code in a state where certain queries can fail, I will add that to this PR before it is merged. Otherwise, this is certainly useful as a demonstration of the benefit of `$lookup`.
A simple example joining the 29k-document `zips` dataset to itself runs …
=> [#1284] Support for simple joins with $lookup on MongoDB 3.2 and later

CHANGELOG/revision.md, it/src/test/scala/quasar/server/ServiceSpec.scala
- run the "servers" process which actually shuts down the server after
the "shutdown" effect is run
- also shutting down the client instance
- this reduces the number of leaked threads to a single pool (from one
pool per example)
=> clean up http4s thread pools after tests run

CHANGELOG/revision.md, README.md, build.sbt, project/Dependencies.scala, project/plugins.sbt, scripts/build, scripts/constants, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/ReadFileSpec.scala
Also reenables the sparkcore project, but disables the offending readfile spec until we can get a handle on the resource leaks.
=> Switch to sbt-assembly for artifact packaging

CHANGELOG/revision.md, foundation/src/test/scala/quasar/QuasarSpecification.scala, it/src/test/scala/quasar/fs/FileSystemTest.scala, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/ReadFileSpec.scala
Stop running a specification on failure. Right now we don't
have the sort of test suite where there is useful information
to be found beyond the first failure.
Show all test timings.
=> Change some test options.

CHANGELOG/revision.md, mongodb/src/main/scala/quasar/physical/mongodb/WorkflowExecutor.scala, mongodb/src/test/scala/quasar/physical/mongodb/JavaScriptWorkflowExecutionSpec.scala
Fixes #1376.
When a simple `select count(*) from foo` is executed in the REPL, or saved as a view and then read with offset/limit parameters, `limit` and/or `offset` clauses are effectively added before the query is executed. Because the query always produces a single result, those clauses have no effect, but they were not being recognized when the query was executed, and so quasar was doing `aggregate` rather than `count`, which is potentially much slower. This commit just recognizes that pattern and disregards any skip/limit after a count operation, as long as they wouldn't affect the single result.
=> Efficient execution of simple counts with appended limit/skip ops

CHANGELOG/revision.md, core/src/main/scala/quasar/logicalplan.scala, core/src/main/scala/quasar/sql/package.scala, foundation/src/main/scala/quasar/RenderTree.scala, mongodb/src/main/scala/quasar/physical/mongodb/JoinHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/Crystallized.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOp3_2.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowtask/ast.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala
This is a first step for #1364, handling joins where one source is a trivial read and the other source is a pipeline without filtering. Notably this allows a simple 3-way join to run in `aggregate`, which is pretty impressive:
```
$ select a.foo, b.bar, c.baz from abc as a join abc as b on b.a_id = a._id join abc as c on c.b_id = b._id
MongoDB
db.abc.aggregate(
[
{ "$match": { "_id": { "$ne": null } } },
{ "$project": { "left": "$$ROOT" } },
{
"$lookup": {
"from": "abc",
"localField": "left._id",
"foreignField": "a_id",
"as": "right"
}
},
{ "$unwind": "$right" },
{ "$match": { "right._id": { "$ne": null } } },
{ "$project": { "left": "$$ROOT" } },
{
"$lookup": {
"from": "abc",
"localField": "left.right._id",
"foreignField": "b_id",
"as": "right"
}
},
{ "$unwind": "$right" },
{ "$limit": …
```
=> Handle join with arbitrary expression on one side of the condition

CHANGELOG/revision.md, it/src/main/resources/tests/joins/joinSubSelects.test, js/src/main/scala/quasar/jscore/jsfn.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/package.scala, mongodb/src/test/scala/quasar/physical/mongodb/workflowop.scala
Fixes #1371.
One was related to applying InputFinders to the wrong nodes. The other was blindly re-writing `$Map` ops even if they where trying to alter the key; a side-effect of that fix is more comprehensible JS for the resulting finalizer fns.
With this, we can now handle some very fancy-looking and perhaps even useful queries, such as the one in the new regression test.
@sellout: assigning this to you mostly so you can be aware of the bugs that appeared here, because there are probably more of them lurking in this code and I'm sure you have ideas about how we can improve it down the road.
@drostron: feel free to have a look. You saw all of these changes but I cleaned up the code a lot since we were looking at it.
=> Two fixes related to joining sub-selects

CHANGELOG/revision.md, build.sbt, effect/src/main/scala/quasar/errors.scala, foundation/src/main/scala/quasar/Predef.scala, foundation/src/test/scala/quasar/TypelevelSpec.scala, mongodb/src/main/scala/quasar/physical/mongodb/fs/package.scala, project/build.properties, web/src/main/scala/quasar/api/package.scala
The immediate consequence is the elimination of si2712fix-plugin.
A subsequent commit will exploit type literals and singleton inference
to eliminate the currently extensive reliance on shapeless's Nat.
The apparently unrelated change to move the convertError object
outside of the Errors object is actually necessary for things to
work with the typelevel options. This is life with the scala
compiler: any change at all is likely to alter the profile of
when types get forced, and you never know how it will materialize.
In fact it's very encouraging that only the one change was needed.
=> Use typelevel compiler.

CHANGELOG/revision.md, core/src/main/scala/quasar/qscript/MapFunc.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala
Happy to do the same thing for more of them. Some of them it didn't feel like it was worth the effort to name cuz they were really obvious. Of course, these ones were obvious enough since I was able to guess them from the name of the function, although I wouldn't be surprised if I got one or two of them wrong. Others (like `Between` and `Coalesce`) I wasn't able to guess so it would probably be a good idea to give them names actually 😄 .
=> Improve the names of parameters to some `MapFuncs`

CHANGELOG/revision.md, web/src/main/scala/quasar/api/package.scala, web/src/test/scala/quasar/api/UriPathCodecSpec.scala
There is a bug in http4s where %xx sequences are rendered
upper case if the xx characters might be hex digits. But it's
not clear why we're using NIH URI facilities in any case.
=> Use java's builtin facilities for URI encoding.

CHANGELOG/revision.md, core/src/main/scala/quasar/fs/mount/package.scala, core/src/main/scala/quasar/fs/package.scala, foundation/src/main/scala/quasar/fp/coproduct.scala, it/src/test/scala/quasar/ViewReadQueryRegressionSpec.scala, it/src/test/scala/quasar/physical/filesystems.scala, main/src/main/scala/quasar/main/package.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/package.scala, postgresql/src/main/scala/quasar/physical/postgresql/fs/package.scala, repl/src/main/scala/quasar/repl/Main.scala, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/ReadFileSpec.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala, web/src/test/scala/quasar/api/services/RestApiSpecs.scala
It's pretty modest machinery, but does wonders for readability. I understand there was once something along these lines and that there were performance issues. I think it likely it was the same bug being reported in [SI-8801](https://issues.scala-lang.org/browse/SI-8801) which is fixed in scala 2.11.6+.
=> Coproduct syntax.

CHANGELOG/revision.md, core/src/main/scala/quasar/qscript/ShiftRead.scala, core/src/test/scala/quasar/qscript/ShiftReadSpec.scala
To resolve the proper implicit, needed to add a “dummy” type parameter
to the `Aux` alias.
=> Fix ineffectual `ShiftRead` transformation.

CHANGELOG/revision.md, web/src/main/scala/quasar/api/package.scala, web/src/test/scala/quasar/api/UriPathCodecSpec.scala
The jre native encoder translates ' ' into '+' which, although
legal, is not what we want or expect. I discovered this through
a test failure.
=> Fix corner case in URI encoding.

CHANGELOG/revision.md, core/src/main/scala/quasar/fs/QueryFile.scala, core/src/main/scala/quasar/fs/package.scala, core/src/main/scala/quasar/qscript/ConvertPath.scala, core/src/main/scala/quasar/qscript/Optimize.scala, core/src/main/scala/quasar/qscript/StaticPath.scala, core/src/test/scala/quasar/fs/QueryFileSpec.scala, core/src/test/scala/quasar/qscript/QScriptHelpers.scala, foundation/src/main/scala/quasar/fp/eitherT.scala, it/src/test/scala/quasar/physical/mongodb/fs/MongoDbFileSystemSpec.scala, it/src/test/scala/quasar/regression/QueryRegressionTest.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, repl/src/main/scala/quasar/repl/Repl.scala
Replaces the explicit choices of `WriterT[?[_], PhaseResults, ?]` and `EitherT[?[_], FileSystemError, ?]` in `QueryFile.convertToQScript` with their equivalent "mtl" class. Also does the same in `ConvertPath`.
This expresses the required capabilities more directly, trading data types for constraints, and makes them easier to use with other transformer stacks (or algebraic effects) that satisfy the constraints.
=> Replace transformers with mtl classes in `convertToQScript` and `ConvertPath`

CHANGELOG/revision.md, build.sbt
Disables the `AutomateHeaderPlugin` config for the `marklogic-validation` project until a the exclusion support for `sbt-header` is released.
This will prevent the `XMLChar.java` file from continually showing as modified via the on-compile header updates.
=> Disable sbt-header plugin for marklogic-validation until exclusion is available

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/Transform.scala
This bug would affect any query that autojoins 3 sources, for example, any query with a `Guard` node.
This PR now produces correct (though not yet fully optimized) qscript for the query `select foo from bar`.
=> Fix bug in autojoin3.

CHANGELOG/revision.md, build.sbt, connector/src/main/scala/quasar/fs/QueryFile.scala, connector/src/main/scala/quasar/fs/WriteFile.scala
SBT normally limits tasks overall to the reported number of processors/cores. Come to find out, that number is 32(!) when running in Travis.
Since we believe Travis only uses 1-2 CPUs worth of processor time, resetting the parallel task limit to 2 should preserve any actual parallelism while reducing memory footprint and thrashing.
Running on another branch, this change made the `doc` task complete reliably. It's less clear what it does to the build time.
=> Limit concurrent tasks in Travis to 2

CHANGELOG/feature.md, foundation/src/main/scala/quasar/fp/package.scala, foundation/src/main/scala/quasar/fp/tree/package.scala, frontend/src/test/scala/quasar/std/StdLibSpec.scala, it/src/main/resources/tests/temporal/time.test, it/src/test/scala/quasar/physical/mongodb/ExprStdLibSpec.scala, mongodb/src/main/scala/quasar/physical/mongodb/accumulator/accumop.scala, mongodb/src/main/scala/quasar/physical/mongodb/accumulator/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/execution.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/fs/queryfile.scala, mongodb/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/InputFinder.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/JoinHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/main/scala/quasar/physical/mongodb/reshape.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowtask/package.scala, mongodb/src/test/scala/quasar/physical/mongodb/JavaScriptWorkflowExecutionSpec.scala, mongodb/src/test/scala/quasar/physical/mongodb/optimize.scala, mongodb/src/test/scala/quasar/physical/mongodb/pipeline.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala, mongodb/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala, mongodb/src/test/scala/quasar/physical/mongodb/workflowop.scala
Closes #1310.
The upshot here is just that `time_of_day` can now be evaluated in the aggregation pipeline. More interestingly, this lays the groundwork for the 3.2 ops to be generated as well.
=> Generate new operators in MongoDB 3.0

CHANGELOG/revision.md, it/src/main/resources/tests/letInSelectProjection.test, it/src/main/resources/tests/literalReductionWithNegative.test, it/src/test/scala/quasar/TestConfig.scala, it/src/test/scala/quasar/regression/QueryRegressionTest.scala
Instead of eagerly loading all regression test data at suite start, this PR changes the behavior to load test data on-demand, if it is missing. This makes it nicer when running a subset of the regression suite as only the required data is loaded.
=> Lazily load regression test data

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/QScriptCore.scala
The dramatic impact of this change means we should immediately
investigate the other especially slow-to-compile files for
similar opportunities. Every call to freeTransCata is a likely
candidate, but not only those.
=> Cut time to compile QScriptCore from 155 seconds to 20 seconds.

CHANGELOG/revision.md, connector/src/test/scala/quasar/fs/FileSystemFixture.scala, connector/src/test/scala/quasar/scalacheck/package.scala, core/src/test/scala/quasar/fs/mount/MountingsConfigArbitrary.scala, frontend/src/test/scala/quasar/VariablesArbitrary.scala, interface/src/test/scala/quasar/config/CoreConfigSpec.scala
A random failure occurred in a build of #1474.
As far as I can tell, this was very unlikely to happen just because `minTestsOk` was set so low that we were only testing small inputs, except when we got very lucky.
It was easy to reproduce by increasing that param, but the results were impossible to analyze because they were simply huge. After limiting the size in the generator, I've run thousands of tests without a failure, and we're certainly testing non-trivial configs of several mounts and variables, based on printing some of them out.
=> fix a flaky test of Config encoding

CHANGELOG/revision.md, core/src/main/scala/quasar/fs/mount/Mounter.scala, core/src/test/scala/quasar/fs/mount/MountingSpec.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala
This is the first, simpler, part of the fix for #1448, cleaning up when a mount is deleted so that no strange directory is left behind containing only the views.
Wanted to get this merged since this is the part that impacts the frontend most directly. Another PR will follow with the change to move nested views when a mounts is `MOVE`d. That change will be  a bit more involved because it will require a new term in the `Mounting` algebra.
=> delete nested views when a mount is deleted

CHANGELOG/revision.md, mongodb/src/main/scala/quasar/physical/mongodb/execution.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/JoinHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowtask/package.scala, mongodb/src/test/scala/quasar/physical/mongodb/JavaScriptWorkflowExecutionSpec.scala, mongodb/src/test/scala/quasar/physical/mongodb/expression/spec.scala, mongodb/src/test/scala/quasar/physical/mongodb/optimize.scala, mongodb/src/test/scala/quasar/physical/mongodb/pipeline.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala, mongodb/src/test/scala/quasar/physical/mongodb/workflowbuilder.scala, mongodb/src/test/scala/quasar/physical/mongodb/workflowop.scala
The value ExprOpCoreF.fixpoint[Fix, ExprOp] was being created
from 17 distinct call sites.
=> Centralize creation of common value.

CHANGELOG/revision.md, mongodb/src/main/scala/quasar/physical/mongodb/MongoDbIO.scala
Ran into this when preparing for the 3.1 demo. No idea why I didn't see it previously using the same version of MongoDB.
=> decode MongoDB index with Double instead of Integer

CHANGELOG/revision.md, connector/src/main/scala/quasar/fs/QueryFile.scala, connector/src/main/scala/quasar/qscript/Coalesce.scala, connector/src/main/scala/quasar/qscript/DiscoverPath.scala, connector/src/main/scala/quasar/qscript/EquiJoin.scala, connector/src/main/scala/quasar/qscript/Mergeable.scala, connector/src/main/scala/quasar/qscript/Optimize.scala, connector/src/main/scala/quasar/qscript/ProjectBucket.scala, connector/src/main/scala/quasar/qscript/Provenance.scala, connector/src/main/scala/quasar/qscript/QScriptCore.scala, connector/src/main/scala/quasar/qscript/ThetaJoin.scala, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/test/scala/quasar/qscript/Optimize.scala, connector/src/test/scala/quasar/qscript/QScript.scala, foundation/src/main/scala/quasar/fp/package.scala
Also,
- have Coalesce push Take/Drop later, rather than earlier
- add an `optimize` transformation to finalize QScript (which pulls Take/Drop earlier)
- implement Mergable for ProjectBucket
- fix conversions of Take and Drop from LP
=> Eliminate the elusive ThetaJoin.

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/Optimize.scala, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/test/scala/quasar/qscript/QScript.scala
Many more ThetaJoins are avoided in QScript with this.
This is based on #1514.
=> Avoid creating unnecessary autojoins.

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/MapFunc.scala, connector/src/main/scala/quasar/qscript/Transform.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
Take/Drop would lose the location of the result, but now they don’t.
Also some cleanup of EJson pattern-matching, QScript merging, and
Mongo-QScript undefined.
=> Fix a bug in Take/Drop.

CHANGELOG/revision.md, connector/src/main/scala/quasar/fs/QueryFile.scala, connector/src/main/scala/quasar/qscript/Coalesce.scala, connector/src/main/scala/quasar/qscript/Optimize.scala, connector/src/main/scala/quasar/qscript/ShiftRead.scala, connector/src/main/scala/quasar/qscript/TTypes.scala, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/test/scala/quasar/qscript/Optimize.scala, connector/src/test/scala/quasar/qscript/QScript.scala
Sometimes we would throw away necessary information for finding the
result of a QScript node. We now apply it properly.
This also has some other improvements to simplifying `ShiftedRead` nodes
and normalization in general.
=> Fix handling of “result” pointers.

CHANGELOG/revision.md, repl/src/main/scala/quasar/repl/Command.scala, repl/src/main/scala/quasar/repl/Repl.scala
Keeping it pretty simple, this just uses `FileSystemQueries.explainQuery` and the same code used to print the phase log as is used when running queries in the REPL:
```
💪 $ explain select a from foo
Typechecked:
Invoke(SQUASH)
╰─ Invoke(MAKE_OBJECT)
├─ Str("a")
╰─ Let('__check0)
├─ Read(/foo)
╰─ Typecheck(Obj(Map(),Some(Top)))
├─ Free('__check0)
├─ ObjectProject('__check0["a"])
╰─ Constant(NA)
Quasar error: File not found: /foo
💪 $ explain select city from `local/quasar-test/zips`
MongoDB:
db.zips.find({ "city": true });
💪 $ explain select city from `localqs/quasar-test/zips`
Quasar error: ProjectField(Fix(Coproduct(\/-(Coproduct(\/-($varF(DocVar(Name(ROOT),None))))))),Fix(Coproduct(\/-(Coproduct(\/-($literalF(Text(city)))))))) (of class quasar.qscript.MapFuncs$ProjectField)
💪 $ debug=2 …
```
=> implement `explain` in the REPL

CHANGELOG/feature.md, connector/src/main/scala/quasar/qscript/MapFunc.scala, core/src/test/scala/quasar/sql/compiler.scala, frontend/src/main/scala/quasar/SemanticError.scala, frontend/src/main/scala/quasar/std/date.scala, frontend/src/main/scala/quasar/std/math.scala, frontend/src/test/scala/quasar/std/SimplifyStdLibSpec.scala, frontend/src/test/scala/quasar/std/StdLibSpec.scala, frontend/src/test/scala/quasar/std/math.scala, it/src/main/resources/tests/temporal/datePartsConverted.test, it/src/test/scala/quasar/physical/mongodb/ExprStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/JsStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/MongoDbDomain.scala, it/src/test/scala/quasar/physical/mongodb/MongoDbStdLibSpec.scala, js/src/main/scala/quasar/jscore/fixpoint.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MarkLogicPlannerError.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/javascript/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/JsFuncHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala, sql/src/main/scala/quasar/sql/compiler.scala
First part of #1311.
Adds fairly complete tests for `date`, `math`, and `relation` to `StdLibSpec`, and includes all of the fallout from seeing how broken things were.
Breaks out the `Extract` function into a distinct LP Func and QS MapFunc for each field.
Pulls out JavaScript compilation for both MongoDB planners into common code.
If there was a clean way to break this into 3 or so PRs, I would have, but it seemed sensible to start with the tests and so this is what I ended up with.
=> Tests for date, math, and relations, and fixes for JavaScript

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/Coalesce.scala, connector/src/main/scala/quasar/qscript/DiscoverPath.scala, connector/src/main/scala/quasar/qscript/EquiJoin.scala, connector/src/main/scala/quasar/qscript/Optimize.scala, connector/src/main/scala/quasar/qscript/QScriptCore.scala, connector/src/main/scala/quasar/qscript/SelectionOp.scala, connector/src/main/scala/quasar/qscript/ShiftRead.scala, connector/src/main/scala/quasar/qscript/SimplifyJoin.scala, connector/src/main/scala/quasar/qscript/TTypes.scala, connector/src/main/scala/quasar/qscript/ThetaJoin.scala, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/test/scala/quasar/qscript/QScript.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/QScriptCorePlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/Planner.scala
- complete implementation for Mergable\[*Join\] (avoids autojoins after a join)
- fix a bug where we included the provenance in the join condition
- fix join combine func to use the result pointers
Also,
- combine `Take`/`Drop` into `Subset` (and add `Sample` case)
- fix handling of `ProjectField` in Mongo-QScript planner
- handle `ShiftedRead`’s `IncludeId` in Mongo-QScript planner
- fix `Reduce`’s repairFunc handling in Mongo-QScript planner
- normalize Mongo-specific QScript
=> Many improvements to QScript joins.

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/test/scala/quasar/qscript/QScript.scala
This makes progress toward #1411 - we no longer get the "unsupported ordering function" error. But the QScript generated is still too complex. It doesn't contain any `ThetaJoin`s, but it does appear to still have the provenance information stored in the QScript.
=> order by constant

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/Coalesce.scala, connector/src/main/scala/quasar/qscript/EquiJoin.scala, connector/src/main/scala/quasar/qscript/Normalizable.scala, connector/src/main/scala/quasar/qscript/ProjectBucket.scala, connector/src/main/scala/quasar/qscript/QScriptCore.scala, connector/src/main/scala/quasar/qscript/TTypes.scala, connector/src/main/scala/quasar/qscript/ThetaJoin.scala
This currently fails to compile with the following errors:
```
[error] /Users/greg/Documents/SlamData/quasar/connector/src/main/scala/quasar/qscript/Coalesce.scala:205: can't existentially abstract over parameterized type F
[error]     new Coalesce[QScriptCore] {
[error]     ^
[error] /Users/greg/Documents/SlamData/quasar/connector/src/main/scala/quasar/qscript/Coalesce.scala:362: can't existentially abstract over parameterized type F
[error]     new Coalesce[ProjectBucket] {
[error]     ^
[error] /Users/greg/Documents/SlamData/quasar/connector/src/main/scala/quasar/qscript/Coalesce.scala:398: can't existentially abstract over parameterized type F
[error]     new Coalesce[ThetaJoin] {
[error]     ^
[error] /Users/greg/Documents/SlamData/quasar/connector/src/main/scala/quasar/qscript/Coales …
```
=> Refactor Coalesce and Normalizable.

CHANGELOG/revision.md, connector/src/main/scala/quasar/fs/QueryFile.scala, connector/src/main/scala/quasar/qscript/Coalesce.scala, connector/src/main/scala/quasar/qscript/MapFunc.scala, connector/src/main/scala/quasar/qscript/QScriptCore.scala, connector/src/main/scala/quasar/qscript/Rewrite.scala, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/test/scala/quasar/qscript/QScript.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
This is a bunch of small fixes to QScript motivated by one of two things
1. the included changes to the Mongo-QScript connector or
2. a simplification in the way we handle Constants in qscript.Transform.
The latter exposed a number of places we weren’t properly dealing with
the value pointer in the annotation. Basically, that change broke a
number of tests (when it should have been semantically equivalent), and
the subsequent fixes were needed to make them pass again. In general, I
also took advantage of the value pointer more often, to simplify some
Transform cases and avoid creating intermediate Map nodes.
In the Mongo-QScript connector, we now identify arrays and maps with
statically-known indices/keys to take advantage of ArrayBuilder and
DocBuilder.
=> A collection of QScript fixes.

CHANGELOG/revision.md, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/CoreMapStdLibSpec.scala
This runs all the tests, skipping the Extract functions and the tests for `Power` since the implementation is limited to small values. 
Other than that, it found only a few small problems which are fixed here.
I tried to factor out the parts that should be common to QScript/MapFunc implementations, and included a few TODO comments about how that might work.
=> Run StdLib tests on sparkcore's MapFunc implementation

CHANGELOG/revision.md, connector/src/main/scala/quasar/fs/QueryFile.scala, connector/src/main/scala/quasar/qscript/Provenance.scala, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/test/scala/quasar/qscript/QScript.scala, connector/src/test/scala/quasar/qscript/QScriptHelpers.scala, frontend/src/main/scala/quasar/logicalplan.scala, frontend/src/main/scala/quasar/types.scala
Previously we reified _all_ of provenance into QScript, however much of
it is static and is only required during compilation. So we now only
reify the dynamic portion required for bucketing, autojoin, etc. Which
simplifies queries greatly.
This also fixes #1558 and #1559 (tests that were pending). And also
improves both typechecker error messages and QScript phase results.
=> Simplify runtime Provenance representation.

CHANGELOG/revision.md, it/src/main/resources/tests/concatArrayWithLiteral.test, it/src/main/resources/tests/concatBetween.test, it/src/main/resources/tests/concatFieldAndConstant.test, it/src/main/resources/tests/convertFromString.test, it/src/main/resources/tests/countDistinct.test, it/src/main/resources/tests/singleFieldDistinct.test, it/src/main/resources/tests/temporal/dateFilter.test, it/src/main/resources/tests/temporal/datePartsConvertedSimple.test, it/src/main/resources/tests/temporal/days.test, it/src/main/resources/tests/temporal/invalidDateFilter.test, it/src/main/resources/tests/trivial.test, it/src/main/resources/tests/wildcardWithMultipleConstants.test, marklogic/src/main/scala/quasar/physical/marklogic/fs/xdmitem.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/ejson.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/expr.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/package.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/qscript.scala, project/Dependencies.scala
When constructing new `Array`s or `Map`s, adds the appropriate `ejson:type` attribute so that values are properly deserialized to types other than `String`.
Also a couple other fixes, making `Data` decoding a bit more accepting, fixing an issue with how sort direction was rendered and left shift for arrays.
Enables another set of regression tests that pass due to the aforementioned improvements with the same caveats of explicit field aliases. One test is also enabled for MarkLogic and marked as pending for Mongo due to the presence of the `value` field (as including the field is not the correct behavior, as I understand it). If this is contentious, I can a) revert it or b) add another test that is skipped by all but Mongo and includes the `value` field.
Fixes #1575.
=> Attribute new constructs with their EJSON type

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/test/scala/quasar/qscript/QScript.scala, core/src/test/scala/quasar/sql/compiler.scala, frontend/src/main/scala/quasar/optimizer.scala, frontend/src/main/scala/quasar/sql/JoinDir.scala, frontend/src/main/scala/quasar/std/set.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/JoinHandler.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/PlannerSpec.scala
The first step toward #1556, which eliminates the hard-coded "left" and "right" fields in join access.
In order to complete that ticket, it will be useful to easily see all the places "left" and "right" are actually used.
=> Containment of "left" and "right" sides in LogicalPlan.

CHANGELOG/revision.md, it/src/main/resources/tests/temporal/datePartsConverted.test, it/src/test/scala/quasar/physical/mongodb/ExprStdLibSpec.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOp3_2.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/JoinHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala
This produces a much more comprehensible error than the one the refers to JS phase.
With that in hand, it was possible to debug and enable a more comprehensive `date_part` regression test that had been pending.
=> Report errors from the workflow phase

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/EquiJoin.scala, connector/src/main/scala/quasar/qscript/MapFunc.scala, connector/src/main/scala/quasar/qscript/ProjectBucket.scala, connector/src/main/scala/quasar/qscript/QScriptCore.scala, connector/src/main/scala/quasar/qscript/ThetaJoin.scala, foundation/src/main/scala/quasar/RenderTree.scala, foundation/src/main/scala/quasar/RenderTreeT.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
This makes the sources of Join and Union nodes comprehensible (see upcoming comment).
Introduces `RenderTreeT`, which the join types use to get ahold of instances for types involving `QScriptTotal`. There is also still the oddball requirement of a `Show[T[EJson]]`, which could be eliminated by implementing `Delay[RenderTree, EJson]`, but that seems like a job for another day.
I'd like to collapse ProjectIndex and ProjectField nodes for readability (as we do in LogicalPlan), but it's going to be either tricky or a big hack, since it involves seeing through the rendering of both `T` and `EJson`.
=> expand FreeQS nodes when rendering QScript trees

CHANGELOG/revision.md, connector/src/main/scala/quasar/fs/InMemory.scala, core/src/test/scala/quasar/fs/mount/ViewFileSystemSpec.scala, core/src/test/scala/quasar/optimizer.scala, foundation/src/test/scala/quasar/matchers.scala, frontend/src/main/scala/quasar/frontend/logicalplan/LogicalPlan.scala, frontend/src/test/scala/quasar/frontend/logicalplan/LogicalPlanSpecs.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala, sql/src/main/scala/quasar/sql/compiler.scala
Closes #1677 . Sort of. So I didn't get to go quite as far with this PR as I wanted. The goal was to delete the `override def equals` method on ` logicalplan.Invoke`, but because of the pervasive use of `==` in external dependencies and scalac, this was not possible. But this PR _does_ rely on the `scalaz.Equal` for `LogicalPlan` more than before, so it's an improvement.
=> Use Equal for LogicalPlan in as many places as possible.

CHANGELOG/revision.md, it/src/main/resources/tests/letBinding.test, marklogic/src/main/scala/quasar/physical/marklogic/fs/ops.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/QScriptCorePlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/ShiftedReadPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/ThetaJoinPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/package.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/BindingClause.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/EncodeXQuery.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/FunctionDecl.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/QNameGenerator.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/XQuery.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/ejson.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/expr.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/package.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/qscript.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/syntax.scala
Implements basic fusion for FLWOR expressions in the MarkLogic planner and converts `ShiftedRead` plan from a function call to a FLWOR expression in order to benefit from fusion.
The fusion implemented relies on contextual information within the planner and isn't completely general, though it could be made so once we have a complete fixpoint AST for XQuery.
Fusion for `ThetaJoin` branches sharing a non-trivial common src isn't implemented here, but is tracked in #1690.
Closes #1625
=> Basic XQuery FLWOR expression fusion for MarkLogic Planner

CHANGELOG/revision.md, it/src/main/resources/tests/complex-vars.test, it/src/main/resources/tests/filterByJsWithOnlyReducing.test, it/src/main/resources/tests/flattenArray.test, it/src/main/resources/tests/jsWithNonJsFilter.test, it/src/main/resources/tests/letBindingSelect.test, it/src/main/resources/tests/manySimpleProjections.test, it/src/main/resources/tests/matchRegexPatternWithExpressions.test, it/src/main/resources/tests/null/toFromString.test, it/src/main/resources/tests/sortByJS.test, it/src/main/resources/tests/temporal/convertTimestamp.test, it/src/main/resources/tests/zipsByCityLength.test, it/src/test/scala/quasar/regression/QueryRegressionTest.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/xdmitem.scala, marklogic/src/main/scala/quasar/physical/marklogic/prisms.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/QScriptCorePlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/EncodeXQuery.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/ejson.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/expr.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/qscript.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/xs.scala
Adds type casts based on the `ejson:type` attribute of elements to the MarkLogic planner where they would be beneficial (operands to various operators, sort keys, etc) resulting in another handful of passing regression tests.
Also improves `Constant` planning by using the `EJson => Data` algebra and unifies date/time result parsing for XQuery literals and elements with the corresponding `ejson:type` attribute.
Closes #1504.
=> Add casting to MarkLogic planner where beneficial

CHANGELOG/revision.md, frontend/src/main/scala/quasar/std/structural.scala, frontend/src/test/scala/quasar/std/StdLibSpec.scala, frontend/src/test/scala/quasar/std/structural.scala, it/src/main/resources/tests/mongodb/wildcardWithExtraProjections.test, it/src/main/resources/tests/wildcardWithExtraProjections.test, it/src/test/scala/quasar/physical/marklogic/MarkLogicStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/ExprStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/JsStdLibSpec.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/DefaultCollationDecl.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/Prolog.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/ejson.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/fn.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/qscript.scala, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/CoreMapStdLibSpec.scala
Fixes array concat to work with strings and arrays in MarkLogic. Also enables all the `StdLibSpec`s for MarkLogic and adds a few new ones exercising `ArrayConcat`.
In the process, also relaxed various array operations to work on any XML element by not requiring child elements to have a particular name.
Fixes #1503.
=> Fix MarkLogic array concatenation and enable all MapFunc tests

CHANGELOG/revision.md, connector/src/main/scala/quasar/planner.scala, connector/src/main/scala/quasar/qscript/Transform.scala, core/src/main/scala/quasar/fs/mount/view.scala, couchbase/src/main/scala/quasar/physical/couchbase/common.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/package.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/QScriptCorePlanner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/UnreachablePlanner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/common.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/package.scala, it/src/test/scala/quasar/physical/mongodb/ExprStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/JsStdLibSpec.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/xcc/SessionIO.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/qscript.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/xdmp.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/Planner.scala, web/src/main/scala/quasar/api/ToApiError.scala
Pretty prints the logged XQuery plans for MarkLogic, making it much easier to visually inspect them. Also has the benefit of catching MarkLogic planner syntax bugs prior to execution.
=> Pretty print MarkLogic XQuery plans

CHANGELOG/revision.md, it/src/test/scala/quasar/physical/marklogic/xquery/EJsonLibSpec.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/ejson.scala
It is common in XML for an element to have multiple child elements with the same name, when such an element is projected in a query the result should be an array of all the matching elements. This adds support to the MarkLogic planner to support this behavior.
Fixes #1706.
=> [1706] Make an array when a projection results in multiple items.

CHANGELOG/revision.md, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/PlannerSpec.scala
I did this to get the tests to pass on my Linux machine. Presumably the different jmv was causing the results to be returned in a different order. Now, the tests are agnostic to order.
=> Spark `PlannerSpec` tests are now more robust

CHANGELOG/revision.md, it/src/main/resources/tests/filterOnFieldComparison.test
This test is failing somewhat consistently. It's filed in issue #1752
=> Skip failing couchbase integration test.

CHANGELOG/revision.md, connector/src/main/scala/quasar/qscript/Provenance.scala, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/test/scala/quasar/qscript/QScript.scala, it/src/main/resources/tests/guardedExpression.test
There should be some integration tests that can be enabled with this fix. I'd like to see what happens when integration is run - not sure if tests will come to life (they're pending) or if I need to go in there and turn them on (they're skipped) or if I need to add some integration tests (the necessary ones don't exist yet). 
In any case, a good example query of what now comes to life is: `select distinct(city) from zips order by pop`. That query requires actually using the reified bucketing information in order to compute the sorting buckets. (There is just one bucket, but we have to give that information to the backend!)
=> Fix nested array deref bug.

CHANGELOG/revision.md, README.md, connector/src/main/scala/quasar/fs/QueryFile.scala, couchbase/src/main/scala/quasar/physical/couchbase/common.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/managefile.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala, it/src/test/scala/quasar/BackendCapability.scala, it/src/test/scala/quasar/BackendRef.scala, it/src/test/scala/quasar/ResultFileQueryRegressionSpec.scala, it/src/test/scala/quasar/StreamingQueryRegressionSpec.scala, it/src/test/scala/quasar/TestConfig.scala, it/src/test/scala/quasar/fs/FileSystemTest.scala, it/src/test/scala/quasar/fs/FileSystemUT.scala, it/src/test/scala/quasar/fs/ManageFilesSpec.scala, it/src/test/scala/quasar/fs/QueryFilesSpec.scala, it/src/test/scala/quasar/fs/WriteFilesSpec.scala, it/src/test/scala/quasar/physical/couchbase/CouchbaseStdLibSpec.scala, it/src/test/scala/quasar/physical/marklogic/MarkLogicStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/MongoDbStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/fs/MongoDbFileSystemSpec.scala, it/src/test/scala/quasar/physical/mongodb/fs/MongoDbSpec.scala, it/src/test/scala/quasar/regression/QueryRegressionTest.scala, it/src/test/scala/quasar/server/ServiceSpec.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala
This doesn't seem to ever have been specified, so I've added a test to `QueryFilesSpec` that does so, essentially codifying the existing MongoDB connector behavior.
SlamData currently expects this behavior (for the cache card, which is how I discovered it), so if we want to change it we should probably do so in a breaking release.
Fixes #1759.
=> [1759] Executing a query should overwrite an existing file in MarkLogic

CHANGELOG/feature.md, connector/src/main/scala/quasar/qscript/MapFunc.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/MapFuncPlanner.scala, frontend/src/main/scala/quasar/std/structural.scala, frontend/src/test/scala/quasar/std/StdLibSpec.scala, it/src/test/scala/quasar/physical/marklogic/xquery/EJsonLibSpec.scala, it/src/test/scala/quasar/physical/marklogic/xquery/QScriptLibSpec.scala, it/src/test/scala/quasar/physical/marklogic/xquery/XQuerySpec.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/ejson.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/fn.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/qscript.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala, sql/src/main/scala/quasar/sql/compiler.scala
The `META` function returns any metadata associated with the argument or `Undefined` otherwise.
Implementations for Couchbase (via the `meta()` function) and MarkLogic are included, MongoDB and Spark didn't seem to have an obvious (to me) implementation (@sellout @rabbitonweb feel free to suggest one).
I've added tests for the MarkLogic implementation but testing this in general via `StdLibSpec` requires `EJson` in `LogicalPlan` as we don't have a way to represent metadata in our `Data` type.
Closes #1717.
Closes #1701.
=> [1717] Add a META function providing access to any metadata associated with a value

CHANGELOG/revision.md, it/src/main/resources/tests/filterOnFieldComparison.test
Recent changes appear to have addressed the intermittent failure seen against `filterOnFieldComparison.test`.
Fixes: #1752
=> CB: Reenable filterOnFieldComparison

CHANGELOG/revision.md, it/src/main/resources/tests/filterOnFieldComparison.test
`filterOnFieldComparison.test` is still failing intermittently on Travis due to result set order. Specifying ordering currently results in sizable N1QL that leads to cbq-engine slows. That should be addressed by #1784 and then `filterOnFieldComparison.test` can be reenabled against CB.
#1752 is reopened.
=> CB: Revert "Reenable filterOnFieldComparison"

CHANGELOG/feature.md, frontend/src/main/scala/quasar/sql/package.scala, frontend/src/main/scala/quasar/sql/parser.scala, frontend/src/test/scala/quasar/sql/SqlParserSpec.scala, mongodb/src/main/scala/quasar/physical/mongodb/bson.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/Check.scala, mongodb/src/test/scala/quasar/physical/mongodb/bson.scala
Fixes #1837
Also fixes a bug where we could error in `bson.Timestamp.fromInstant` .
=> Allow variables with quoted names like :`start time`

CHANGELOG/feature.md, build.sbt, common/src/main/scala/quasar/common/PrimaryType.scala, connector/src/main/scala/quasar/qscript/MapFunc.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/MapFuncPlanner.scala, frontend/src/main/scala/quasar/std/identity.scala, frontend/src/main/scala/quasar/types.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MarkLogicPlannerError.scala, mongodb/src/main/scala/quasar/physical/mongodb/bson.scala, mongodb/src/main/scala/quasar/physical/mongodb/bsoncodec.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/Check.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/javascript/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/test/scala/quasar/physical/mongodb/bson.scala, mongodb/src/test/scala/quasar/physical/mongodb/expression/spec.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala, project/plugins.sbt, sql/src/main/scala/quasar/sql/compiler.scala, web/src/test/scala/quasar/api/services/query/ExecuteServiceSpec.scala
- Add a `TypeOf` operation (not a fix for #1802 yet, because it doesn’t implement it for any connector)
- adds a new PrimaryType type that reflects the simpler notion of type used with “patterns” as we go forward (and also the notion of types used by `TypeOf`)
- use the sbt-travisci plugin
- convert `Bson.Date` to use a `Long` instead of `Instant` (since `Instant` encodes more values than `Bson.Date`)
=> Allow users to compare types of values.

web/src/main/resources/log4j.properties
=> Add `log4j.properties` file to remove warning message when starting web server

couchbase/src/main/scala/quasar/physical/couchbase/N1QL.scala, couchbase/src/main/scala/quasar/physical/couchbase/N1QLRenderTreeInstance.scala, couchbase/src/main/scala/quasar/physical/couchbase/N1QLTraverseInstance.scala, couchbase/src/main/scala/quasar/physical/couchbase/RenderQuery.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/MapFuncPlanner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/QScriptCorePlanner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/ShiftedReadPlanner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/package.scala, couchbase/src/test/scala/quasar/physical/couchbase/N1QLSpec.scala, it/src/main/resources/tests/filterOnFieldComparison.test, it/src/test/scala/quasar/physical/couchbase/CouchbaseStdLibSpec.scala
When possible collapse inlining within `ConcatArrays` for improved CB query engine performance due to reduced query size. `order by` is added to the query in `filterOnFieldComparison.test` to avoid related intermittent failures seen on Travis.
Fixes #1752
=> CB: Collapse inlining within ConcatArrays

README.md, connector/src/main/scala/quasar/fs/WriteError.scala, connector/src/main/scala/quasar/qscript/MapFunc.scala, couchbase/src/main/scala/quasar/physical/couchbase/RenderQuery.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/writefile.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/MapFuncPlanner.scala, frontend/src/main/scala/quasar/codec.scala, frontend/src/main/scala/quasar/types.scala, frontend/src/test/scala/quasar/codec.scala, frontend/src/test/scala/quasar/types.scala, interface/src/main/scala/quasar/main/prettify.scala, it/src/main/resources/tests/mongodb/temporal/time.test, it/src/main/resources/tests/temporal/time.test, it/src/main/resources/tests/typeOf.test, it/src/main/resources/tests/undefinedJsInExpr.test, it/src/test/scala/quasar/regression/PredicateSpec.scala, it/src/test/scala/quasar/regression/QueryRegressionTest.scala, mongodb/src/main/scala/quasar/physical/mongodb/bsoncodec.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/FuncHandler.scala, postgresql/src/main/scala/quasar/physical/postgresql/fs/writefile.scala, repl/src/main/scala/quasar/repl/Repl.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/queryfile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/writefile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/queryfile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/writefile.scala, web/src/main/scala/quasar/api/MessageFormat.scala, web/src/main/scala/quasar/api/ToApiError.scala
Fixes #1802
Also eliminates undefined values from result sets. (This misbehaves
slightly in a couple tests, where results that _should_ be an empty
object are eliminated, but this is better than returning bad results to
a user.)
=> Implement TypeOf for MongoDB.

connector/src/main/scala/quasar/qscript/PruneArrays.scala, connector/src/test/scala/quasar/qscript/PruneArrays.scala, connector/src/test/scala/quasar/qscript/QScriptHelpers.scala
Prunes arrays in QScript `LeftShift`.
Fixes #1851
=> array pruning for LeftShift

README.md, foundation/src/main/scala/quasar/contrib/pathy/package.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/MarkLogicConfig.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/package.scala, marklogic/src/test/scala/quasar/physical/marklogic/fs/MarkLogicConfigSpec.scala
Allows for specifying a physical path in the MarkLogic server when describing a mount to serve as the root directory for that mount, all operations and queries will be scoped within the specified directory.
Closes #1766.
=> Support specifying a root directory for a MarkLogic mount

it/src/main/resources/tests/union.test, marklogic/src/main/scala/quasar/physical/marklogic/qscript/QScriptCorePlanner.scala
Arguments to the XQuery `union` operator weren't being grouped properly which could lead to ambiguity in certain cases, wrapping them in a sequence solved the issue.
=> Fix MarkLogic 'union' implementation.

project/Dependencies.scala
With Matryoshka 0.16.4 we get RecursiveT to be serializable, which fixes
Spark issues. See https://github.com/slamdata/matryoshka/pull/57 for details
=> Update matryoshka-core to 0.16.4

web/src/main/scala/quasar/api/MessageFormat.scala, web/src/main/scala/quasar/api/package.scala, web/src/main/scala/quasar/api/services/RestApi.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala
In lieu of crafting a PR to support RFC 5987 in http4s this is a quick workaround due to the ASAP nature of the originating issue.
Fixes: #1861
=> Handle non-ascii in disposition's filename

mongodb/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/JoinHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala
Fixes #1895
Previously this optimization happened in Workflow, which meant that expressions
could be irreversibly converted to JS even though it was unnecessary for the
optimized form.
Also includes some formatting clean-up.
=> Eliminate unused expressions in WorkflowBuilder.

connector/src/main/scala/quasar/fs/QueryFile.scala, connector/src/main/scala/quasar/qscript/Coalesce.scala, connector/src/main/scala/quasar/qscript/EquiJoin.scala, connector/src/main/scala/quasar/qscript/MapFunc.scala, connector/src/main/scala/quasar/qscript/Merge.scala, connector/src/main/scala/quasar/qscript/Normalizable.scala, connector/src/main/scala/quasar/qscript/ProjectBucket.scala, connector/src/main/scala/quasar/qscript/Provenance.scala, connector/src/main/scala/quasar/qscript/PruneArrays.scala, connector/src/main/scala/quasar/qscript/QScriptCore.scala, connector/src/main/scala/quasar/qscript/Rewrite.scala, connector/src/main/scala/quasar/qscript/ThetaJoin.scala, connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/main/scala/quasar/qscript/package.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala, ejson/src/main/scala/quasar/ejson/EJson.scala, ejson/src/main/scala/quasar/ejson/jsonParser.scala, ejson/src/main/scala/quasar/ejson/package.scala, ejson/src/test/scala/quasar/ejson/EJsonArbitrary.scala, foundation/src/main/scala/quasar/contrib/matryoshka/OrderT.scala, foundation/src/main/scala/quasar/contrib/matryoshka/package.scala, foundation/src/test/scala/quasar/pkg/TestsPackage.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
Adds `OrderT` and `Delay[Order, Common|Obj|Extension]` instances. Also extracts `EJson` arbitrary instances from the `EJson` tests so they can be used elsewhere.
=> Add Order instances for EJson.

connector/src/main/scala/quasar/qscript/Coalesce.scala, connector/src/main/scala/quasar/qscript/Rewrite.scala, connector/src/main/scala/quasar/qscript/package.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala, it/src/main/resources/tests/couchbase/leftKeyJoinMultipleSelect.test, it/src/main/resources/tests/joins/multipleSelectJoin.test, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala
Improves `QScript` generation performance by consistently calling `normalizeF` after each coalescing.
Fixes #1950
=> Improve QScript performance

connector/src/main/scala/quasar/qscript/MapFunc.scala, connector/src/main/scala/quasar/qscript/QScriptCore.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/EquiJoinPlanner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/QScriptCorePlanner.scala, ejson/src/main/scala/quasar/contrib/argonaut/package.scala, ejson/src/main/scala/quasar/ejson/EJson.scala, foundation/src/main/scala/quasar/fp/package.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOp3_0.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOp3_2.scala, mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/optimize/optimize.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/JoinHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOp3_2.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/WorkflowOpCore.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflow/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowtask/package.scala, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala, mongodb/src/test/scala/quasar/physical/mongodb/plannerQScript.scala, mongodb/src/test/scala/quasar/physical/mongodb/workflowop.scala
This eliminates a ton of `unapply` methods on various functors that are intended to project a component of a Coproduct. This is now provided directly by the `Inject` instance.
There are still 16(?) unapply methods in the MongoDB connector. These are a bit more entrenched, so aren't being removed in this PR. All other `unapply`s in this style have been removed.
=> Take advantage of Scalaz's Inject#unapply.

.travis.yml
Update slack notification key for travis. The old travis integration disappeared so I made a new one.
=> Update slack notification key for travis.

connector/src/main/scala/quasar/qscript/unicoalesce.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala
This is the first step towards a more general backend abstraction.  It enables inference of the coalesces used by backends based on the qscript they declare support for.
Fixes #1978
=> Unicoalescense

.travis.yml, scripts/quasarPublishAndTag
Ideally sbt-slamdata would offer dependents a way to specify a publish predicate in some fashion. This is a quick interim solution until we spend time on the matter within sbt-slamdata.
=> Constrain publish to Travis job 1

connector/src/main/scala/quasar/qscript/PruneArrays.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/test/scala/quasar/qscript/PruneArrays.scala, connector/src/test/scala/quasar/qscript/QScript.scala, connector/src/test/scala/quasar/qscript/QScriptHelpers.scala
If the left and/or right branch of a qscript join is a `LeftShift` with a `combine` func that is an array, then in some cases we can rewrite the array produced by that `LeftShift`, namely when only some (but not all) elements of that array are used in the join condition and join combine.
Closes #1794
=> Basic join branch array pruning

connector/src/main/scala/quasar/qscript/unirewrite.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala, marklogic/src/main/scala/quasar/physical/marklogic/fs/queryfile.scala, mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala
Last step on the way to a unified backend abstraction!  This does for rewrites what we already did for coalescence.  With this change, all of the connectors have a syntactically-unified way of getting a specifically-typed qscript, given a logical plan.
=> Unified rewrites

connector/src/main/scala/quasar/qscript/MapFunc.scala, connector/src/main/scala/quasar/qscript/Rewrite.scala, connector/src/main/scala/quasar/qscript/analysis/package.scala, connector/src/test/scala/quasar/qscript/analysis/CardinalitySpec.scala, mongodb/src/main/scala/quasar/physical/mongodb/workflowbuilder.scala, project/Dependencies.scala
Part of https://github.com/quasar-analytics/quasar/issues/1716
It changes the signature of `pathCard` to close values over some `M`.
For `zygoM` matryoshka was upgraded to `0.18.3`
Commit `cf56d33` will be reverted once https://github.com/slamdata/matryoshka/pull/78 is merged to matryoshka
=> Path card sign change

docker/scripts/assembleTestingConf
Enable travis matrix build `mongodb_3_2` to now also test qscript queries.
=> Enable ability to test qscript queries in mongo 3.2

docker/Dockerfiles/Marklogic/MarkLogic-Dockerfile
Cur timeout value in Dockerfile increased to allow for Marklogic rpm download.
=> increase curl timeout to download ML rpm in dockerfile

README.md
Quasar README update with instructions on creating containerized backend datastores using the scripts located in docker/scripts.
=> Update Quasar readme with integration testing instructions

ejson/src/main/scala/quasar/ejson/JsonCodec.scala, ejson/src/main/scala/quasar/ejson/package.scala, ejson/src/test/scala/quasar/ejson/EJson.scala, ejson/src/test/scala/quasar/ejson/EJsonArbitrary.scala, ejson/src/test/scala/quasar/ejson/JsonCodecSpec.scala, foundation/src/main/scala/quasar/contrib/matryoshka/package.scala, foundation/src/test/scala/quasar/contrib/matryoshka/CorecursiveArbitrary.scala, foundation/src/test/scala/quasar/contrib/matryoshka/arbitrary.scala, foundation/src/test/scala/quasar/pkg/TestsPackage.scala
Implements the `Json` encoding for `EJson` described in #2066.
I had to pull in the `Arbitrary` machinery for corecursive types from `matryoshka` as it still depends on a snapshot version of `scalacheck`. Once we're able to upgrade to the latest `matryoshka`, we can get rid of it.
Closes #2066.
=> Json codec for EJson

project/Dependencies.scala, web/src/main/scala/quasar/api/package.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala, web/src/test/scala/quasar/api/services/Fixture.scala, web/src/test/scala/quasar/api/services/query/ExecuteServiceSpec.scala
- Upgrade `jawn` to version `0.10.4`
- Decouple `quasar` from `sbt-slamdata`'s version of `http4s`
- Remove code that worked around a `jawn` bug
=> Upgrade to `http4s` version `0.15.9a`

it/src/main/resources/tests/largestZips.test
Enable `largestZips.test` for couchbase; it was already fixed, likely by #1694.
=> Enable largestZips.test for couchbase.

sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/Planner.scala, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/PlannerSpec.scala
`BigDecimal`s will come with `MathContext.UNLIMMITED` after being parsed from string. 
Details in #2150.
Fixes https://github.com/quasar-analytics/quasar/issues/2150
=> Fix ArithmeticException in Spark

sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/queryfile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/queryfile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala
Input methods should be more generic for the spark based connectors to 'inject' different effects to it as needed. This changes is needed for `spark-cassandra` and `spark-elastic`
=> Change signature of QueryFile.Input to return Free instead of Task

marklogic/src/main/scala/quasar/physical/marklogic/qscript/DataPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/MapFuncPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/StructuralPlanner.scala, marklogic/src/main/scala/quasar/physical/marklogic/qscript/lib.scala, marklogic/src/main/scala/quasar/physical/marklogic/xquery/fn.scala
Previously we were handling temporal coercion in relation operators due to some tests that were comparing dates and timestamps. They turned out to be incorrect and were corrected in #1843 and thus the behavior is no longer needed in MarkLogic.
=> Remove temporal coercion from MarkLogic relation operators

README.md, couchbase/src/main/scala/quasar/physical/couchbase/common.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/managefile.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/package.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/readfile.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/writefile.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/EquiJoinPlanner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/Planner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/QScriptCorePlanner.scala, couchbase/src/main/scala/quasar/physical/couchbase/planner/ShiftedReadFilePlanner.scala, couchbase/src/test/scala/quasar/physical/couchbase/BasicQueryEnablementSpec.scala, docker/scripts/assembleTestingConf, docker/scripts/initCouchbase, it/src/main/resources/tests/couchbase/leftKeyJoin.test, it/src/main/resources/tests/couchbase/leftKeyJoinMultipleSelect.test, it/src/main/resources/tests/couchbase/rightKeyJoin.test, it/src/test/scala/quasar/physical/couchbase/CouchbaseStdLibSpec.scala, it/testing.conf.example
Fixes: #1740
This PR changes the couchbase connection URI format in two ways:
a) bucket name needs to be specified after `couchbase://<host>[:<port>]/`
b) a document type needs to be specified using `docTypeKey`
In addition, a Quasar couchbase mount now maps directly to a couchbase bucket.
=> CB: bucket per mount mapping

connector/src/main/scala/quasar/fs/InMemory.scala, connector/src/main/scala/quasar/fs/WriteFile.scala, connector/src/test/scala/quasar/fs/FileSystemFixture.scala, connector/src/test/scala/quasar/fs/WriteFileSpec.scala
=> Avoid obscuring write errors when attempting to cleanup nonexistent temp file

core/src/main/scala/quasar/fs/mount/MountConfig.scala, frontend/src/main/scala/quasar/sql/parser.scala
It would appear, one needs to always call `normalize` after parsing SQL. This was not being done when parsing statements when loading a module mount.
=> Fix improper parsing of modules statement blobs

core/src/main/scala/quasar/package.scala, project/Dependencies.scala
This replaces the `???` operator with something which provides the following two features:
- Type inference based on call site
- Line information
For example:
```
scala> val x: Int = ???
scala.NotImplementedError: unimplemented value of type Int at <console>:14
at quasar.package$.$qmark$qmark$qmark(package.scala:110)
... 42 elided
scala> def x[A]: List[A] = ???
x: [A]=> List[A]
scala> x[String]
scala.NotImplementedError: unimplemented value of type scala.List[A] at <console>:14
at quasar.package$.$qmark$qmark$qmark(package.scala:110)
at .x(<console>:14)
... 42 elided
```
It's much more interesting if you do it in an actual file, since you'll get the filename instead of `<console>`, but you get the idea.  Had to bring in scalactic for the `Position` macro (thanks, @bvenners!).
This should …
=> Vastly superior ??? operator

mimir/src/main/scala/quasar/mimir/DepFn1.scala, mimir/src/main/scala/quasar/mimir/Mimir.scala, mimir/src/main/scala/quasar/mimir/Precog.scala
This PR was originally designed to make `Precog` unloadable.  It does that, but there appears to be a strange bug with the filesystem handlers (@wemrysi ??) where the `close` effect is not being run.  More research into this is needed.
In the meantime, the cake is dynamic now, so we're in better shape even without unloading.
Fixes #2290
=> Un-static the Precog cake

it/src/main/resources/tests/basicAnalyticQuery.test, it/src/main/resources/tests/caseVariations.test, it/src/main/resources/tests/caseWithGroup.test, it/src/main/resources/tests/citiesByLargestZip.test, it/src/main/resources/tests/citiesByTotalPopulation.test, it/src/main/resources/tests/demo/nestedSelectWithReduce.test, it/src/main/resources/tests/filterWithComplexNot.test, it/src/main/resources/tests/flattenArrayLeftWithUnflattened.test, it/src/main/resources/tests/flattenArrayWithUnflattened.test, it/src/main/resources/tests/flattenGroupedObject.test, it/src/main/resources/tests/groupByFlatten.test, it/src/main/resources/tests/largestCities.test, it/src/main/resources/tests/locationCount.test, it/src/main/resources/tests/multistageFlatten.test, it/src/main/resources/tests/multitypeFlatten.test, it/src/main/resources/tests/null/nullTestExprs.test, it/src/main/resources/tests/null/nullTestExprsWithMissing.test, it/src/main/resources/tests/projectFieldWithFlatten.test, it/src/main/resources/tests/projectIndexWithObjectFlatten.test, it/src/main/resources/tests/servlet.test, it/src/main/resources/tests/shortCities.test, it/src/main/resources/tests/skipCount.test, it/src/main/resources/tests/statesByShortestFirstCity.test, it/src/main/resources/tests/temporal/time.test, it/src/main/resources/tests/temporal/timestampsAndIntervals.test, it/src/main/resources/tests/unifyFlattenedFields.test, it/src/main/resources/tests/unifyFlattenedFieldsWithMultipleUses.test, it/src/main/resources/tests/unifyFlattenedFieldsWithUnflattened.test, it/src/main/resources/tests/union.test
Adds a note about why a test is skipped if it is indeed still skipped.
Also note that all `mimir` tests that require loaded data are skipped. After we enable loading we will en masse change these over to `pending`.
=> Use pending instead of skip whenever possible in integration tests.

connector/src/main/scala/quasar/qscript/Transform.scala, connector/src/test/scala/quasar/qscript/QScript.scala, it/src/main/resources/tests/flattenArrayLeftWithUnflattened.test, it/src/main/resources/tests/projectIndexWithObjectFlatten.test, it/src/main/resources/tests/selectCount.test, it/src/main/resources/tests/unifyFlattenedFieldsWithUnflattened.test
This avoids indirect access to constant values, which is something we can hopefully promise to connectors – that constants never have to be dereferenced.
The Mongo tests that are fixed by this is somewhat accidental. First, we can’t do `ProjectField` or `MakeMap` in Mongo expressions if the name of the field isn’t a constant string, which means we fall back to JS. And the old code _should_ work in JS, but isn’t currently supported (because it involves reaching outside our pure subset of JS, since you can only add dynamic field names with mutation 😭).
=> Don’t create an autojoin when one side is a constant.

core/src/main/scala/quasar/fs/mount/MountConfig.scala, frontend/src/main/scala/quasar/sql/ScopedExpr.scala, frontend/src/main/scala/quasar/sql/Statement.scala, frontend/src/main/scala/quasar/sql/package.scala, frontend/src/test/scala/quasar/sql/ExprArbitrary.scala, frontend/src/test/scala/quasar/sql/SqlParserSpec.scala, frontend/src/test/scala/quasar/sql/StatementArbitrary.scala
Incorrect pretty printing of module mounts was making them invalid and unable to be mounted.
- Fix pretty printing of import statements
- First off the `posicCodec.printPath` was not being called yielding completely bogus Sql^2
- Secondly backticks need to be espcaped
- Generator for `Statement` was changed to produce only alpha characters in import paths for now in order for the round-trip to work
- Add instances of `Shrink` for `Fix[Sql]` and `Statement[Fix[Sql]]`
- remove unnecessary call to `makeTables(Nil)` in tests (since it's already being called in the parser)
- Add a space in pretty printing between arguments of a function
- Add tests for module round-trip and specific backtick situation
- Fix small bug in function `_qq`
=> Fix pretty printing of modules

foundation/src/main/scala/quasar/contrib/scala/package.scala, web/src/main/scala/quasar/api/services/metadata.scala, web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala
=> `metadata` endpoint now supports `offset` and `limit`

it/src/main/resources/tests/distinctStar.test
This test has been failing a lot recently.
I don't like skipping tests that sometimes pass because that means the test isn't ever being run and so a bug could be introduced, but we also cannot have a couchbase build that fails so frequently.
=> Skip distinctStar test for CB because it is flaky.

it/src/main/resources/tests/cars2.data, it/src/main/resources/tests/joins/fullOuterEquiJoin.test, it/src/main/resources/tests/joins/innerEquiJoin.test, it/src/main/resources/tests/joins/innerEquiJoinLarge.test, it/src/main/resources/tests/joins/leftOuterEquiJoin.test, it/src/main/resources/tests/joins/rightOuterEquiJoin.test
The previous outer join integration tests had incorrect expected results. This fixes the results as well as uses a different dataset for the queries so that we can fully tested the "outerness" of the joins.
The tests pass in old mongo and spark. They do not pass in mimir or marklogic.
=> Fix up outer join integration tests.

it/src/main/resources/tests/filterOnFieldComparison.test, it/src/main/resources/tests/joins/orderJoinByAlias.test, it/src/main/resources/tests/largestZips.test, mimir/src/main/scala/quasar/mimir/Mimir.scala
Depends on #2516 and #2517 
Fixes #2518 
Implements sorting without bucketing.  The implementation obviously depends on the `Table#sort` function being stable.  Fortunately, it is!  So we're good.  A couple tests that *should* have sprung to life… have not.  So that's annoying.  Also there's a weird bug in `pendingIgnoreFieldOrder`.  Not sure what's up with that.
Anyway, the tests that should have sprung to life seem to be sorting on the wrong thing.  The `FreeMap` is getting translated correctly, and we're passing it along to `Table#sort` correctly, so what's probably happening here is a bug in either JDBM3 or in `BlockStoreColumnarTable`.  Hard to tell which.  Will require further investigating.
=> Implements Sort in mimir

it/src/main/resources/tests/filterOnFieldComparison.test, it/src/main/resources/tests/groupAndFilterWithNoUnreduced.test, it/src/main/resources/tests/joins/orderJoinByAlias.test, it/src/main/resources/tests/largestZips.test, mimir/src/main/scala/quasar/mimir/Mimir.scala
Depends on #2519, which itself depends on #2516 and #2517
Fixes #1991 
Fixes #1990 
Fixes #2266 
Bucketing turned out to be way easier than expected.  Basically, `partitionMerge` does exactly what we want.  Note for future: we should eliminate `groupByN` and simplify the implementation into `sort`, since we don't actually need its full generality (grouping in SQL^2 is considerably weaker than in Quirrel).  We have to explicitly sort on the bucket key, similar to the issue we have equijoin, but this should be made much nicer with #2485.
=> Implement bucketed sorting and reduction in mimir

connector/src/main/scala/quasar/qscript/DiscoverPath.scala, repl/src/main/scala/quasar/repl/Command.scala, repl/src/main/scala/quasar/repl/DebugLevel.scala, repl/src/main/scala/quasar/repl/Repl.scala
Differs from `explain` in that `compile` does not require a backend, useful for debugging LP -> QScript issues.
=> Add a 'compile' command to the repl

connector/src/main/scala/quasar/qscript/PruneArrays.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/test/scala/quasar/qscript/PruneArrays.scala, connector/src/test/scala/quasar/qscript/QScript.scala
Updates `PruneArrays` to elide singleton arrays, referring to the sole element directly instead.
=> Elide singleton arrays during pruning

it/src/main/resources/tests/basicAnalyticQuery.test, it/src/main/resources/tests/filterSkipLimitCount.test, it/src/main/resources/tests/skipCount.test, mimir/src/main/scala/quasar/mimir/Mimir.scala, yggdrasil/src/main/scala/quasar/yggdrasil/TableModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
Fixes #2506
Depends on #2557 
Affects #2542
Now we have a nice and sane `drop` and `take`, both of which run quite quickly and have the properties you would want.
=> Reimplement and replace Table#takeRange

blueeyes/src/main/scala/quasar/blueeyes/Perf.scala, it/src/main/resources/tests/trivialGroup.test
Increase `maxSliceSize` and `smallSliceSize` values in `yggConfig`. Fixes #2521.
=> Speed up mimir flatten tests 

sparkcore/src/main/scala/quasar/physical/sparkcore/fs/SparkConnectorDetails.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/elastic/package.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/elastic/queryfile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/package.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/queryfile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/readfile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/package.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/queryfile.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala
This is first PR to https://github.com/quasar-analytics/quasar/issues/1634
Here we try to eliminate `queryfile.Input` / `fileExists` method and replace it with algebra (SparkConnectorDetails) to which connectors have to provide interpreter.
Before I continue with any other functions from `queryfile.Input` I want to have this reviewed - confirmation that my approach is the right one.
=> Spark details algebra - queryfile.Input / def fileExists

connector/src/main/scala/quasar/qscript/Coalesce.scala, connector/src/main/scala/quasar/qscript/MapFuncCore.scala, connector/src/main/scala/quasar/qscript/Normalizable.scala, connector/src/main/scala/quasar/qscript/Provenance.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/test/scala/quasar/qscript/QScriptHelpers.scala, connector/src/test/scala/quasar/qscript/Rewrite.scala, it/src/main/resources/tests/different-flattens.test, it/src/main/resources/tests/union.test
Improves or fixes the following in QScript
* Avoids the use of universal equality in `MapFuncCore.extractGuards`.
* When guards are extracted from a `ThetaJoin` condition into a filter, they are also elided from the combiner.
* Fixed duplicate detection in `concat`.
* Improved equality for `Provenance.Both` by eliding `Nada` and comparing a tree of `Both`s as sets instead of structurally.
=> A handful of QScript fixes/improvements

web/src/main/scala/quasar/api/zip.scala
Avoid compressing files containing current directory path. Fixes #2587.
=> trim current directory from file paths before zipping

mimir/src/main/scala/quasar/mimir/Mimir.scala, yggdrasil/src/main/scala/quasar/yggdrasil/FNModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/TransSpecModule.scala, yggdrasil/src/test/scala/quasar/yggdrasil/TransSpecModuleSpec.scala
Keeps track of the current sort order in Mimir to avoid sorting the same data the same way repeatedly.
=> [Fix #2485] Keep track of sort order in Mimir Repr

it/src/main/resources/tests/flattenGroupedObject.test, it/src/main/resources/tests/groupByArray.test, it/src/main/resources/tests/unsupportedTests.test, mimir/src/main/scala/quasar/mimir/Mimir.scala, yggdrasil/src/main/scala/quasar/yggdrasil/TableModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala
Fixes #2656
This is a really big fix, because the web frontend relies on queries of this form to determine whether or not it should show results.  So very frequently, even when the query itself would run, the subquery form would not, meaning that the frontend would just not display results (e.g. [here](https://github.com/slamdata/slamdata/issues/2099)).
I'm assigning @alissapajer to review this, both because she knows the `Reduce` stuff better than anyone else, and also because this has a notable impact on mimir in next-major, where `ReduceIndex` is encoded differently.  Specifically, there is a TODO comment on next-major which can be eliminated and implemented from this work.
=> Subquery grouped count

connector/src/main/scala/quasar/qscript/ReplaceMapFunc.scala, connector/src/main/scala/quasar/qscript/Transform.scala, it/src/main/resources/tests/joins/nonJsJoinCondition.test
Fixes #2110 
Handles the case when a join condition compiles into a `LeftShift`.
=> Support left shifting on one side of a join condition.

it/src/main/resources/tests/citiesByLargestZip.test
I don't know why this integration test expectation got changed. This is the commit it got changed in https://github.com/quasar-analytics/quasar/commit/518dc93b61b337da23bbbd35237d60ec7578325e. SQL semantics along with the other integration tests confirm that the new expectation (which is also the expectation on master) is the one we want.
=> Enable distinct test with correct expectation.

frontend/src/test/scala/quasar/std/StdLibSpec.scala, it/src/main/resources/tests/filterComplement.test, it/src/main/resources/tests/filterMembership.test, it/src/main/resources/tests/filterOnContains.test, it/src/test/scala/quasar/physical/marklogic/qscript/MarkLogicStdLibSpec.scala, it/src/test/scala/quasar/physical/mimir/MimirStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/ExprStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/JsStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/QExprStdLibSpec.scala, it/src/test/scala/quasar/physical/mongodb/QJsStdLibSpec.scala, mimir/src/main/scala/quasar/mimir/MapFuncCorePlanner.scala, yggdrasil/src/main/scala/quasar/yggdrasil/TransSpecModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/ArrayColumn.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/SliceTransform.scala, yggdrasil/src/test/scala/quasar/yggdrasil/TransformSpec.scala, yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala
Fixes #2669 
I had to add `Within` as a first-class `TransSpec`, since it is effectively performing `Equals` repeatedly over each array index.  Since it just delegates to `equalsImpl`, there really isn't a lot of code here.  The trickiest bit is just figuring out which things to materialize and what they look like after you're done.
=> Implement Within function in Mimir

web/src/main/scala/quasar/server/PortChangingServer.scala
Fixes #2693
Like I said, we need to be very very careful of this sort of stuff.  The `fork` here was doing exactly nothing, since it was keeping the action sequenced onto the main pool, resulting in eating a thread.  The fact that this is only failing with Mongo 2.6 is also suspicious, and suggests that the mongo driver is using blocking IO and we're not thread shifting it.  We need to take a hard look at how all of this stuff is working right now, because it's tremendously easy for us to paint ourselves into terrible corners without realizing it except in specific circumstances.
=> Moved blocking console read off of the main(!!) thread pool

it/src/main/resources/tests/orderedWildcardWithProjection.test, it/src/main/resources/tests/sortWildcardOnExpression.test, it/src/test/scala/quasar/physical/sparkcore/SparkStdLibSpec.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/CoreMap.scala
Fixes #2691 
Fixes deleting a nonexistent field in spark. Previously if a field was nonexistent the result would be undefined. Now if a field is nonexistent, the original object is returned.
=> Fixes spark `DeleteField` bug

connector/src/main/scala/quasar/qscript/Rewrite.scala, it/src/main/resources/tests/demo/timeSeriesAggregation.test
Fixes #2571 
Fixes #2531
In `compactReduction` we were not remapping the indices of new reducers found according to how many reducers had previously been duplicates.
=> Fix bug in compactReduction where we didn't shift indices properly.

frontend/src/main/scala/quasar/sql/package.scala, it/src/main/resources/tests/unifyFlattenedFieldsWithUnflattened.test, sql/src/main/scala/quasar/sql/semantics.scala
This fixes an issue in the `projectSortKeys` analysis where projecting and sorting by the same flattened value would unnecessarily result in a synthetic sort key. 
Fixes #2712.
=> Avoid synthetic sort key for flattened field appearing in projection

sql/src/test/scala/quasar/sql/compiler.scala
SQL^2 compiler test ensuring ordering by a projected flattened field doesn't use a synthetic sort key.
Should have been included in #2714, but I forgot. Thanks @alissapajer for pointing this out!
=> Add a test to ensure #2712 doesn't regress

README.md, core/src/main/scala/quasar/db/DbConnectionConfig.scala, web/src/main/scala/quasar/api/services/metastore.scala, web/src/test/scala/quasar/api/services/MetastoreServiceSpec.scala
Fixes an issue that was reported in Slamdata Backend
=> Metastore endpoint now obscures postgres password on GET request

it/src/main/resources/tests/joins/crossJoinWithOneSidedConditions.test, mimir/src/main/scala/quasar/mimir/MapFuncCorePlanner.scala
Row-level equality is a very expensive check for columnar stores like mimir.  It's an order of magnitude *less* expensive when one side or the other of the equality is a simple constant.
Fixes #2675
=> Special-case equality on literals

yggdrasil/src/main/scala/quasar/yggdrasil/vfs/POSIX.scala, yggdrasil/src/main/scala/quasar/yggdrasil/vfs/POSIXOp.scala, yggdrasil/src/main/scala/quasar/yggdrasil/vfs/RealPOSIX.scala, yggdrasil/src/test/scala/quasar/yggdrasil/vfs/FreeVFSSpecs.scala, yggdrasil/src/test/scala/quasar/yggdrasil/vfs/VersionLogSpecs.scala
Fixes #2765 (I believe…)
Windows was failing because creating symlinks on windows… fails.  So now we handle those errors and return `false`, which the VFS in turn ignores because it doesn't really care whether or not the symlink is *actually* created.
=> Handle errors in linking a bit more gracefully

docker/docker-compose.yml
Enables the `ephemeralForTest` storage engine for MongoDB 3.2+ to speed up regression tests.
Locally, this reduced the time to run the regression suite by about 40%.
=> Use the 'ephemeralForTest' storage engine for MongoDB 3.2+

repl/src/main/scala/quasar/repl/Main.scala
Updates the repl prompt to include the version:
```
(v24.0.7) 💪 $
```
feel free to bikeshed away on the format.
=> Include the quasar version in the repl prompt

web/src/main/scala/quasar/api/services/package.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala
Unzipping a file produces a file with suffix equal to the data format requested. Fixes #2144.
=> fix unzipped file suffix

project/build.properties
`~` is dysfunctional with sbt version 1.0.2. Pressing enter does not return the sbt prompt, every 10 seconds it returns success as if changes were made, and we get `[error] Caused by: java.io.IOException: error=23, Too many open files in system`.
`~` is also dysfunctional with sbt version 1.0.1:
```
[error] Error occurred obtaining files to watch.  Terminating continuous execution...
[error] java.lang.NullPointerException
```
So we will use 1.0.0.
=> Use sbt version 1.0.0.

.travis.yml
Mongo 2.6 and 3.0 are no longer officially supported by SlamData.  Translation: we no longer CI them.
=> Removed mongo 2.6 and 3.0 builds

connector/src/main/scala/quasar/connector/BackendModule.scala, connector/src/main/scala/quasar/connector/DefaultAnalyzeModule.scala, connector/src/main/scala/quasar/fs/Analyze.scala, couchbase/src/main/scala/quasar/physical/couchbase/Couchbase.scala, marklogic/src/main/scala/quasar/physical/marklogic/MarkLogic.scala, mimir/src/main/scala/quasar/mimir/Mimir.scala, mongodb/src/main/scala/quasar/physical/mongodb/MongoDb.scala, rdbms/src/main/scala/quasar/physical/rdbms/Rdbms.scala, skeleton/src/main/scala/quasar/physical/skeleton/fs/Skeleton.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/sparkcore.scala
This fixes https://github.com/quasar-analytics/quasar/issues/2213
In general we provide proper implementation for `  private final def analyzeInterpreter: Analyze ~> Configured` in `BackendModule`.
Connectors should provide two methods:
```
def CardinalityQSM: Cardinality[QSM[Fix, ?]]
def CostQSM: Cost[QSM[Fix, ?]]
```
For both `Cost` and `Cardinality` there are "generic", default implementations available (under `Cost._` and `Cardinality._`) that connectors can used - and this is what they actually do right now. But at some point they should provide their own implementation (especially for the `Cost` typeclass as it can take more connecotr specific information into consideration)
There is also a method called `pathCard` that provides default implementation to calculate `APath` …
=> Backend module qanalysis

sbt.bat
Fixes #2815 
Fixes #2819 
I can now checkout and build quasar on windows and the only dependency is the JDK.  The `sbt.bat` script will bootstrap and run SBT, similar to how the `sbt` script does.  We should be able to use this when we setup AppVeyor (to address #2799).
=> Working windows build

README.md, connector/src/main/scala/quasar/connector/BackendModule.scala, connector/src/main/scala/quasar/fs/Empty.scala, connector/src/main/scala/quasar/fs/FileSystemError.scala, connector/src/main/scala/quasar/fs/InMemory.scala, connector/src/main/scala/quasar/fs/ManageFile.scala, connector/src/main/scala/quasar/fs/transformPaths.scala, core/src/main/scala/quasar/fs/mount/hierarchical.scala, core/src/main/scala/quasar/fs/mount/nonFsMounts.scala, core/src/test/scala/quasar/fs/TraceFS.scala, core/src/test/scala/quasar/fs/mount/ViewFileSystemSpec.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/managefile.scala, it/src/test/scala/quasar/fs/ManageFilesSpec.scala, marklogic/src/main/scala/quasar/physical/marklogic/MarkLogic.scala, mimir/src/main/scala/quasar/mimir/Mimir.scala, mongodb/src/main/scala/quasar/physical/mongodb/MongoDb.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsManageFile.scala, skeleton/src/main/scala/quasar/physical/skeleton/fs/Skeleton.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/sparkcore.scala, web/src/main/scala/quasar/api/ToApiError.scala, web/src/main/scala/quasar/api/services/data.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala
Fixes #2393.
This PR itself does not actually add any useful user-facing functionality because none of the connectors support copying and nor does the views and modules interpreters just yet (There is an implementation for `InMemoryFS` thought so that the web layer can be tested! 😄 ). That said I wanted to open a PR now so that my work doesn't drift as I focus on other things as well as to allow the parallel work of any connector that wants to support copy (i.e. mimir as well as views and modules seem like the important candidates).
I do need to add a section to the README documenting the new HTTP verb before this gets merged though (mostly a reminder for myself) and I am sure there will be a few revisions on the implementation after you guys review it.
=> Add Copy operation to Filesystem

interface/src/main/scala/quasar/main/BackendConfig.scala, interface/src/main/scala/quasar/main/package.scala, it/src/test/scala/quasar/TestConfig.scala, web/src/main/scala/quasar/server/Server.scala
Fixes #2813 
Fixes #2797
Obviously using `File` directly is not great, but I think it's more or less justified here since a) the Pathy representation of the same data is clunky due to sandboxing, and b) the previous pipeline was `File` -> `APath` -> `File`, with `APath` not serving any useful purpose (now we just have `File`).
=> Converted BackendConfig to use File rather than Path

foundation/src/main/scala/quasar/fp/process.scala, web/src/main/scala/quasar/api/QHttpService.scala, web/src/main/scala/quasar/api/QResponse.scala, web/src/main/scala/quasar/api/services/analyze/schema.scala, web/src/main/scala/quasar/api/services/data.scala, web/src/main/scala/quasar/api/services/invoke.scala, web/src/main/scala/quasar/api/services/metadata.scala, web/src/main/scala/quasar/api/services/metastore.scala, web/src/main/scala/quasar/api/services/mount.scala, web/src/main/scala/quasar/api/services/package.scala, web/src/main/scala/quasar/api/services/query/analysis.scala, web/src/main/scala/quasar/api/services/query/compile.scala, web/src/main/scala/quasar/api/services/query/execute.scala, web/src/test/scala/quasar/api/QHttpServiceSpec.scala
Unbeknownst to us streaming in Quasar has been broken for quite a while. The implementation of `stepUntil` was to blame\.
Also reworks the "guarding" of streams to be more pinpointed and easier to work with
=> Fix streaming of responses

it/src/main/resources/tests/jobs_jobinfo.data, it/src/main/resources/tests/locationCount.test
Fixes #2494 
The test query and test expectations for `locationCount.test` were both incorrect.
=> Enable `locationCount.test` for most connectors.

.travis.yml
Without `failtrace` enabled, the console sometimes prints too little information about a failed test, since only the test name is printed along with a single line number reference.
Usually this is enough information, but in the case of `StdLibSpec`, each connector delegates to that specification, and the line number in the test failure references the individual connector spec, not `StdLibSpec`, which is not enough information to know which test failed if there are multiple tests with the same name. (For example, we have a case for "any doubles" for many different mathematical operations.)
See https://github.com/quasar-analytics/quasar/issues/2923 for an example.
=> Include failtrace for specs2 console output in travis.

.appveyor.yml, README.md, it/src/test/scala/quasar/server/ServiceSpec.scala, mongoIt/src/test/scala/quasar/physical/mongodb/fs/MongoDbFileSystemSpec.scala, niflheim/src/main/scala/quasar/niflheim/RawLoader.scala, sbt.bat
Fixes #2799 
Fixes #2900
Fixes #2899 
Fixes a few issues with the Windows `sbt.bat` script and also fixes a couple random bugs that Windows quirks uncovered.  This PR primarily configures AppVeyor to compile, unit test and run the Mimir integration tests.  Caching is enabled along similar rules as Travis.  Both master and backport/ branches will be built, in addition to PRs.
Right now, it seems like fully-cached builds take around 28 minutes, while entirely uncached builds take just over an hour.  No build should be *entirely* uncached, since coursier stuff should be kept around, but it's worth keeping it in mind.  AppVeyor's build limit is 60 minutes, after which the job will be killed.  We're discussing options with them now.
Additionally, and this is the more constraining bit, AppVeyor …
=> AppVeyor Configuration

project/Dependencies.scala
There were a few important fixes released in these past few releases that we probably want to have in the release.
=> Upgrade `http4s` to `0.16.5a` (latest on `0.16.x` series)

frontend/src/main/scala/quasar/frontend/logicalplan/LogicalPlanR.scala, frontend/src/main/scala/quasar/std/date.scala, frontend/src/main/scala/quasar/std/identity.scala, frontend/src/main/scala/quasar/std/structural.scala
Low priority. Noticed this during datetime shift, a bunch of functions have untypers which do calculation on constant values and they actually cannot be called at runtime. Removed them and documented how the typechecker works and why they can't be called.
=> Remove dead code in untypers, add a comment explaining the typechecker

.travis.yml, build.sbt
The `sparkcore.jar` publication is a bit of a hack.  We should do better in future when we have more time.
=> Fixed spark jar publication (both sparkless and plugin jars)

connector/src/main/scala/quasar/qscript/MapFuncCore.scala, it/src/main/resources/tests/filterWithDisjunctionAndGuards.test, mongodb/src/test/resources/planner/plan_filter_on_date.txt, mongodb/src/test/scala/quasar/physical/mongodb/planner.scala
Pulling guards out of `or` expressions has the effect of requiring all the guards in the expression to pass before the `or` is evaluated whereas we'd rather evaluate each operand to the `or` independently, guards and all.
This is necessary for the search card functionality in SlamData to work (see slamdata/slamdata#2367) as well as other queries involving guards in filter disjunctions.
=> Avoid extracting guards from OR expressions.

it/src/test/scala/quasar/physical/mimir/MimirStdLibSpec.scala
Just noticed this on the way through. `MimirStdLibSpec` always executed test queries twice, changing this repeatably shaves around 600 ms off test suite run time, which I suppose means setup time and specs2 are taking a good fraction.
=> Stop MimirStdLibSpec executing tests twice

connector/src/main/scala/quasar/qscript/construction.scala, couchbase/src/main/scala/quasar/physical/couchbase/Couchbase.scala, couchbase/src/main/scala/quasar/physical/couchbase/package.scala, ejson/src/main/scala/quasar/ejson/package.scala, marklogic/src/main/scala/quasar/physical/marklogic/MarkLogic.scala, marklogic/src/main/scala/quasar/physical/marklogic/package.scala, mimir/src/main/scala/quasar/mimir/Mimir.scala, mimir/src/main/scala/quasar/mimir/package.scala, mongodb/src/main/scala/quasar/physical/mongodb/MongoDb.scala, mongodb/src/main/scala/quasar/physical/mongodb/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/package.scala, rdbms/src/main/scala/quasar/physical/rdbms/Rdbms.scala, rdbms/src/main/scala/quasar/physical/rdbms/package.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/cassandra/SparkCassandra.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/elastic/SparkElastic.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/SparkHdfs.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/local/SparkLocal.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/package.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/sparkcore.scala
Designed for use in app code and in tests. Instantiate a `Dsl` and a `Func`, or (more likely, for tests) just use `makeDefaults` to get a `Dsl` for your `FreeQS` analogue and your `Fix[QST]` analogue as well as a `Func` for your `T[_[_]]`.
Edit: See `ExprOpCoreF.fixpoint` for a *very* similar DSL for Mongo plans.
Fixes #2989
=> QScript/EJson construction DSL

connector/src/main/scala/quasar/qscript/package.scala, connector/src/main/scala/quasar/qscript/qsu/Graduate.scala, connector/src/main/scala/quasar/qscript/qsu/IntersectGraphs.scala, connector/src/main/scala/quasar/qscript/qsu/QProv.scala, foundation/src/main/scala/quasar/fp/package.scala
Completes implementation of `graduate`, except for `Nullary` and `Distinct`.
In particular implements
```scala
def mergeSources(left: QSUGraph, right: QSUGraph): (QSUGraph, FreeQS, FreeQS)
```
=> QSU Graduation

connector/src/main/scala/quasar/qscript/provenance/Dimension.scala, connector/src/main/scala/quasar/qscript/provenance/ProvF.scala, connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/MappableRegion.scala, connector/src/main/scala/quasar/qscript/qsu/QProv.scala, connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala, connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala, connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala, connector/src/main/scala/quasar/qscript/qsu/package.scala, foundation/src/main/scala/quasar/contrib/scalaz/MonadState_.scala
Adds a function to compute provenance for `QSUGraph` and remove `DimEdit` nodes in the process. Also provides `MappableRegion` which attempts to express as much of a graph as possible in terms of `MapFunc`.
=> ApplyProvenance and MappableRegion for QSU

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala, connector/src/main/scala/quasar/qscript/qsu/Graduate.scala, connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyProvenance.scala
`AutoJoin` of size 2 defaults to `ThetaJoin`. `AutoJoin` of greater sizes not yet supported.
`LPReduce` requires an adjusted impl of [`reifiedIdArray`](https://github.com/wemrysi/quasar/blob/wip/proper-prov/connector/src/main/scala/quasar/qscript/QProv.scala#L68) to compute its `buckets`.
=> Initial work on provenance reification for autojoin, transpose, reduce.

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala, connector/src/main/scala/quasar/qscript/qsu/Graduate.scala, connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala, connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala, connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala, connector/src/test/scala/quasar/qscript/qsu/GraduateSpec.scala, connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
Also renamed `UniformSort` to `QSSort` and `Sort` to `LPSort` to be consistent with our other naming.
=> More `graduate` specifications

README.md, web/src/main/scala/quasar/api/services/data.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala
Just wanted to document this somewhat surprising (IMHO) behavior and perhaps call attention to it if we want to change it.
Personally, I would go with a 404 `NotFound` response in that case but perhaps this was designed this way initially for a particular reason.
At the very least we should document it I think, but if enough people think we should change it to 404 `NotFound`, then I can go ahead and do that too
Fixes #3038
=> Fix `data` endpoint to return 404 Notfound if file does not exist

connector/src/main/scala/quasar/qscript/ExpandMapFunc.scala, ejson/src/main/scala/quasar/ejson/Common.scala, ejson/src/main/scala/quasar/ejson/EJson.scala, ejson/src/main/scala/quasar/ejson/EncodeEJson.scala, ejson/src/main/scala/quasar/ejson/EncodeEJsonK.scala, ejson/src/main/scala/quasar/ejson/Extension.scala, ejson/src/main/scala/quasar/ejson/Fixed.scala, ejson/src/main/scala/quasar/ejson/JsonCodec.scala, ejson/src/main/scala/quasar/ejson/Obj.scala, ejson/src/main/scala/quasar/ejson/SizedType.scala, ejson/src/main/scala/quasar/ejson/Type.scala, ejson/src/main/scala/quasar/ejson/TypeTag.scala, ejson/src/main/scala/quasar/ejson/optics.scala, ejson/src/main/scala/quasar/ejson/package.scala, ejson/src/test/scala/quasar/ejson/EJson.scala, ejson/src/test/scala/quasar/ejson/JsonCodecSpec.scala, foundation/src/main/scala/quasar/contrib/matryoshka/package.scala, frontend/src/main/scala/quasar/sst/StructuralType.scala, frontend/src/main/scala/quasar/sst/TypeStat.scala, frontend/src/main/scala/quasar/tpe/TypeF.scala, frontend/src/test/scala/quasar/sst/CompressionSpec.scala, frontend/src/test/scala/quasar/sst/StructuralTypeSpec.scala, frontend/src/test/scala/quasar/tpe/TypeFSpec.scala, interface/src/test/scala/quasar/main/ExtractSchemaSpec.scala, it/src/test/scala/quasar/regression/QueryRegressionTest.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/StaticHandler.scala, mongodb/src/test/scala/quasar/physical/mongodb/PlannerQScriptSpec.scala
Improves the optics story for EJson by
1. Moving types and type-specific optics out of the package object and into their own respective files, making them easier to find and easier to import a la carte.
2. Adding fixpoint prisms, based on component prisms, allowing for convenient, compositional construction and pattern matching for values having `EJson` as their pattern-functor.
=> Organize and extend optics for EJson

connector/src/main/scala/quasar/qscript/JoinSide.scala, connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/Graduate.scala, connector/src/main/scala/quasar/qscript/qsu/MappableRegion.scala, connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala, connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala, connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/package.scala, connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala
Depends on #3067 
Closes #3066 
Handles the case where we need to turn an `AutoJoin3` into nested `ThetaJoin`s because we have failed to eliminate any of the joins.
Also, this needs tests.
=> AutoJoin3 handling in ReifyProvenance

connector/src/main/scala/quasar/fs/FileSystemError.scala, connector/src/main/scala/quasar/fs/PhysicalError.scala, connector/src/main/scala/quasar/fs/ReadFile.scala, core/src/main/scala/quasar/fs/mount/Mounting.scala, core/src/main/scala/quasar/fs/mount/MountingError.scala, core/src/main/scala/quasar/fs/mount/module/Module.scala, core/src/main/scala/quasar/package.scala, effect/src/main/scala/quasar/effect/Failure.scala, foundation/src/main/scala/quasar/QuasarError.scala, foundation/src/main/scala/quasar/contrib/scalaz/eitherT.scala, interface/src/main/scala/quasar/main/Quasar.scala, interface/src/main/scala/quasar/main/QuasarAPIImpl.scala, interface/src/main/scala/quasar/main/package.scala, interface/src/test/scala/quasar/main/api/ApiSpec.scala
- Add `QuasarAPIImpl` with the intention of eventually aggregating the entire "top-level" Quasar programmatic API
- Make all Quasar errors a subclass of `QuasarError`
- Add `interpWithErrs` to Quasar to provide a better programmatic API
- Add `initMimirOnly` to have a no argument constructor for `Quasar` for the simplest case
=> Add some tests in `ApiSpec` to validate how querying views behaves

rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/PostgresDescribeTable.scala
This code should correctly check whether a schema exists. Previous implementation wasn't working for some cases, causing problems with integration tests.
=> Postgres: Fix checking if schema exists

it/src/test/scala/quasar/fs/ManageFilesSpec.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/hdfs/SparkHdfs.scala
=> Fix "Removing folders when .trash does not exist stopped working on spark-hdfs"

build.sbt
Required for downstream consumption — slamdata/slamdata-backend#280
=> Publish interface tests

connector/src/main/scala/quasar/qscript/construction.scala, connector/src/test/scala/quasar/qscript/MapFuncStdLibTestRunner.scala, connector/src/test/scala/quasar/qscript/Optimize.scala, connector/src/test/scala/quasar/qscript/PreferProjectionSpec.scala, connector/src/test/scala/quasar/qscript/PruneArrays.scala, connector/src/test/scala/quasar/qscript/QScript.scala, connector/src/test/scala/quasar/qscript/QScriptHelpers.scala, connector/src/test/scala/quasar/qscript/RenderQScriptDSLSpec.scala, connector/src/test/scala/quasar/qscript/Rewrite.scala, connector/src/test/scala/quasar/qscript/ShiftReadSpec.scala, connector/src/test/scala/quasar/qscript/analysis/CardinalitySpec.scala, connector/src/test/scala/quasar/qscript/analysis/DeepShapeSpec.scala, connector/src/test/scala/quasar/qscript/analysis/OutlineSpec.scala, couchbase/src/test/scala/quasar/physical/couchbase/BasicQueryEnablementSpec.scala, marklogic/src/test/scala/quasar/physical/marklogic/qscript/FilterPlannerSpec.scala, marklogic/src/test/scala/quasar/physical/marklogic/qscript/ProjectPathSpec.scala, marklogic/src/test/scala/quasar/physical/marklogic/qscript/RewriteNullSpec.scala, mongodb/src/test/scala/quasar/physical/mongodb/PlannerQScriptSpec.scala, sparkcore/src/test/scala/quasar/physical/sparkcore/fs/PlannerSpec.scala
Also reduced the use of tuples in `mkDefaults` because it makes the pretty printer more fragile.
=> Rewrite tests to use QScript DSL

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala, connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala, connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala, connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala, foundation/src/main/scala/quasar/contrib/scalaz/MonadState_.scala
Depends on #3131
I had to turn off second-order minimization for now.  So we're no longer doing Filter => Cond rewriting.  This was because the rewrite is currently done in the wrong place, and is over-aggressive (it happens even when it's unnecessary).  I think I have a decent idea how to restore it, but I'm putting that off for the moment.
=> Corrected invalid freemaps generated by MinimizeAutoJoins

it/src/test/scala/quasar/fs/WriteFilesSpec.scala, project/Dependencies.scala, rdbms/src/main/scala/quasar/physical/rdbms/Interpreter.scala, rdbms/src/main/scala/quasar/physical/rdbms/Rdbms.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsCreate.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsDescribeTable.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsInsert.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsWriteFile.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/Postgres.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/PostgresCreate.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/PostgresDescribeTable.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/PostgresInsert.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/PostgresScanTable.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/package.scala, rdbms/src/main/scala/quasar/physical/rdbms/model/DataFormatter.scala, rdbms/src/main/scala/quasar/physical/rdbms/model/TableModel.scala, rdbms/src/main/scala/quasar/physical/rdbms/model/TypeMapper.scala, rdbms/src/main/scala/quasar/physical/rdbms/model/package.scala, rdbms/src/test/scala/quasar/physical/rdbms/model/TableModelTest.scala
This PR brings a notion of `Table Model`. We now don't store everything in single-json-column tables, but we try to determine the best column types to represent data. `RdbmsWriteFile` scans the incoming `Vector[Data]` and incrementally creates columns. For simple elements like `Data.Int`, `Data.String` etc. we create appropriate DB fields. For nested `Data.Obj`, arrays and such, we use a `jsonb` column.
More details available here: https://docs.google.com/document/d/1loSdaInrdMaFg08EHqaLa2oxWP6wZziN2-uzLenJCuA/edit?usp=sharing
More column type <-> quasar data type mappings will be added later.
=> RDBMS table model

core/src/test/scala/quasar/fs/mount/MountConfigSpec.scala, frontend/src/main/scala/quasar/sql/ParsingError.scala, frontend/src/main/scala/quasar/sql/Statement.scala, frontend/src/main/scala/quasar/sql/package.scala, frontend/src/test/scala/quasar/sql/SqlParserSpec.scala, frontend/src/test/scala/quasar/sql/StatementArbitrary.scala, frontend/src/test/scala/quasar/sql/StatementSpec.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala
Fixes #3027 
- escape function param names that need to be escaped
- Add round-trip test for modules
- Add test to make sure we parse function with escaped param names properly
- Rename `_qq` to `escape`
- Add `Equal` instance to `ParsingError`
- Add convenience `pprintF` on `Statement` for common use case
=> Serialize module SQL properly so it can be parsed again

rdbms/src/main/scala/quasar/physical/rdbms/model/TableModel.scala, rdbms/src/test/scala/quasar/physical/rdbms/model/TableModelTest.scala
The issue was caused by multiple `ColumnDesc` with the same column name present in a `TableModel`.
=> Fix #3162: Add regular equals and hashCode to ColumnDesc

interface/src/main/scala/quasar/main/MetaStoreLocation.scala, web/src/test/scala/quasar/api/services/MetastoreServiceSpec.scala
Also:
- Remove logic in metastore to always initialize a in-memory metastore
- Add more descriptive failure message for "persistence" test
=> Add a test to `MetastoreServiceSpec` for attempting to change to an uninitialized metastore

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala, connector/src/main/scala/quasar/qscript/qsu/package.scala, connector/src/test/scala/quasar/qscript/qsu/ApplyProvenanceSpec.scala, foundation/src/main/scala/quasar/contrib/scalaz/MonadState_.scala, it/src/main/resources/tests/nestedSelectWithFilter.test
Updates how symbol rewrites are applied in `ApplyProvenance` to be correct in the presence of nested `DimEdit`s. 
Fixes #3145.
Fixes #3182.
=> [#3145] Fix how rewrites are applied during ApplyProvenance

interface/src/main/scala/quasar/main/package.scala
Isolated compilation of `RestApi.coreServices[CoreEffIORW]` went from ~130s down
to ~40s on a 2015 macbook pro
=> Switch CoreEffIORW from CoM to expanded Coproducts

mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala
Comment out tracking in PlannerSpec for now, so qscript devs won't have to deal with regenerating.  We can reenable once we are on polyrepo.
=> comment out tracking in PlannerSpec for now

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/EliminateUnary.scala, connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala, connector/src/main/scala/quasar/qscript/qsu/Graduate.scala, connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala, connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala, connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala, connector/src/main/scala/quasar/qscript/qsu/RecognizeDistinct.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyAutoJoins.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyBuckets.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyIdentities.scala, connector/src/main/scala/quasar/qscript/qsu/RewriteGroupByArrays.scala, connector/src/main/scala/quasar/qscript/qsu/package.scala, connector/src/test/scala/quasar/qscript/qsu/ApplyProvenanceSpec.scala, connector/src/test/scala/quasar/qscript/qsu/EliminateUnarySpec.scala, connector/src/test/scala/quasar/qscript/qsu/GraduateSpec.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala, connector/src/test/scala/quasar/qscript/qsu/ReadLPSpec.scala, connector/src/test/scala/quasar/qscript/qsu/ReifyBucketsSpec.scala, connector/src/test/scala/quasar/qscript/qsu/RewriteGroupByArraysSpec.scala
Some minor refactoring to avoid publicly exposing the implementation classes for QSU rewrites as well as tagging any internal errors they produce with the name of the rewrite to make them easier to identify.
=> Encapsulate and standardize QSU rewrite application

mongodb/src/test/resources/planner/plan_unaggregated_field_when_grouping,_second_case.txt, mongodb/src/test/resources/planner/plan_unify_flattened_fields.txt, mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala
Went through the `pendingUntilFixed` tests and tests that were commented out in `PlannerSpec`. Some tests now don't error anymore and are now using `trackPending`. The ones that still error are tracked now by `trackPending(Err|Throw)`.
=> track plans that are erroring

connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala, it/src/main/resources/tests/demo/conditional_input_step2.test, it/src/main/resources/tests/demo/geo_markers_step1.test, mimir/src/main/scala/quasar/mimir/MapFuncCorePlanner.scala
We can now eliminate autojoins even in cases where common sources are being obscured by filters.  We do this by rewriting the `Filter` to a `Cond` within the autojoin heritage (we don't eliminate the node, obviously, so other descendants will continue to see it as a `Filter`).  This optimization applies recursively and can open the door to other collapsing.
I wish we had a `Scan` `MapFunc`; if we had that, I could do something similar with `Subset`.
=> Reimplemented Filter => Cond rewrite to apply more conservatively

connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala, connector/src/test/scala/quasar/qscript/qsu/ExtractFreeMapSpec.scala, it/src/main/resources/tests/sortKeyFlatten.test
Part of #3021
Provide support for nonmappable sort keys.
Add tests for `ExtractFreeMap`.
=> Nonmappable sort keys

it/src/main/resources/tests/groupBySimpleExpression.test, it/src/main/resources/tests/subqueryGroupBy.test, it/src/main/resources/tests/unsupportedTests.test, mimir/src/main/scala/quasar/mimir/Mimir.scala
Affects #3272
As mentioned on the issue, I'm guessing mongo has a similar problem.
=> Fixed mistaken assumption about group keys always being array-wrapped

ejson/src/main/scala/quasar/contrib/argonaut/package.scala, it/src/test/scala/quasar/regression/Predicate.scala
I call this PR "Reversed Batman" because it is PR that we both deserve and need
With this change we get nice diff of RenderedTrees between expected
and actual.
Previously, if test was failing you got this:
```
[error] x olympic_search_step1 [./demo/olympic_search_step1.test] (10 seconds, 86 ms)
[error]  ; {"city":"Turin","event":"15km mass start","year":2006,"country":"NOR","sport":"Biathlon","discipline":"Biathlon","type":"Bronze","gender":"M"} does not match {"city":"Turin","event":"15km mass start2","year":2006,"country":"NOR","sport":"Biathlon","discipline":"Biathlon","type":"Bronze","gender":"M"} (file:1)
```
and now you get this
```
[error] x olympic_search_step1 [./demo/olympic_search_step1.test] (11 seconds, 937 ms)
[error]  ; Actual result does not match expected value. 
[error] …
```
=> Tests Diff (aka Reversed Batman)

mongodb/src/test/resources/planner/plan_3-way_right_equi-join_(map-reduce).txt, mongodb/src/test/resources/planner/plan_non-equi_join.txt, mongodb/src/test/resources/planner/plan_simple_cross.txt, mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala, mongodb/src/test/scala/quasar/physical/mongodb/PlannerWorkflowHelpers.scala
Migrate join queries in mongo PlannerSpec to test against pipeline ops instead of an exact workflow
Closes #3209
=> migrate join queries in mongo PlannerSpec

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/Graduate.scala, connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala, connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyIdentities.scala, connector/src/test/scala/quasar/qscript/qsu/GraduateSpec.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala, connector/src/test/scala/quasar/qscript/qsu/ReifyBucketsSpec.scala
Example:
```sql
select a[*] + b from foo
```
This is pretty narrowly tailored, but it does address part of #3222
=> Minimize autojoins in dimensional 1-2 cases

connector/src/main/scala/quasar/qscript/MapFuncCore.scala, connector/src/main/scala/quasar/qscript/provenance/Dimension.scala, connector/src/main/scala/quasar/qscript/provenance/Prov.scala, connector/src/main/scala/quasar/qscript/qsu/Access.scala, connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala, connector/src/main/scala/quasar/qscript/qsu/Graduate.scala, connector/src/main/scala/quasar/qscript/qsu/IdAccess.scala, connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala, connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala, connector/src/main/scala/quasar/qscript/qsu/QAuth.scala, connector/src/main/scala/quasar/qscript/qsu/QProv.scala, connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala, connector/src/main/scala/quasar/qscript/qsu/QSUTTypes.scala, connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala, connector/src/main/scala/quasar/qscript/qsu/References.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyAutoJoins.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyBuckets.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyIdentities.scala, connector/src/main/scala/quasar/qscript/qsu/package.scala, connector/src/test/scala/quasar/qscript/qsu/ApplyProvenanceSpec.scala, connector/src/test/scala/quasar/qscript/qsu/GraduateSpec.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala, connector/src/test/scala/quasar/qscript/qsu/ReifyBucketsSpec.scala, it/src/main/resources/tests/demo/groupedSelectOfNestedReduction.test, it/src/main/resources/tests/demo/nestedSelectWithReduce.test, it/src/main/resources/tests/different-flattens.test, it/src/main/resources/tests/flattenGroupedObject.test, it/src/main/resources/tests/multistageFlatten.test, it/src/main/resources/tests/multitypeFlatten.test
Group keys are now first-class identities along side shift ids and reducer buckets. This allows them to be properly reified when referenced in an autojoin.
Fixes #3170.
Fixes #3252.
=> QSU Group Key Reification

connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala, connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala, connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/MergeReductions.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/Minimizer.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/ShiftProjectBelow.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala
This generalizes #3287 to arbitrary nestings (e.g. `a[*][*] + b`).  Depends on #3297.  Affects #3222.  This PR is actually just the single `HEAD` commit.
Assigning to @wemrysi.  Can you take a close look at the way that I'm rewriting root at the end of the shift chains?  Which is to say, lines 141 and 190.  Note that `updateGraph` calls `withName`, updates dimensions, and then returns that node.
=> Generalized dimensional coalescence to arbitrarily-nested shifts

connector/src/main/scala/quasar/qscript/rewrites/Coalesce.scala, connector/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
Updates `Coalesce` for `ShiftedRead` to apply when nested in a `LeftShift`.
Fixes #3237.
=> Eliminate IncludeId from ShiftedRead inside LeftShift.

connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala
=> ApplyProvenance applies MultiLeftShift rotations in the same order as ExpandShifts

core/src/test/scala/quasar/fs/mount/HierarchicalFileSystemSpec.scala, it/src/test/scala/quasar/TestConfig.scala, it/src/test/scala/quasar/fs/QueryFilesSpec.scala, it/testing.conf.example, web/src/test/scala/quasar/api/services/MetadataServiceSpec.scala, yggdrasil/src/main/scala/quasar/yggdrasil/vfs/vfs.scala
Fix #2473
- Add test for `HierarchicalFS` to make sure it handles the root of a mount properly
- Remove `pending` from "root dir" test for connectors
- Fix `externalFileSystems` to provide "non-chrooted" interpreters to it tests
- Fix `testBackendConfig` to avoid crashing when there are no external connectors to test
- Add `mimir` to `testing.conf.example`
=> Fix Mimir returning `NotFound` on root if empty

mongodb/src/main/scala/quasar/physical/mongodb/MongoDbPlanner.scala, mongodb/src/test/scala/quasar/physical/mongodb/PlannerQScriptSpec.scala, mongodb/src/test/scala/quasar/physical/mongodb/PlannerSpec.scala
This is a second implementation that allows for parts of the `LeftShift`'s `repair` function to be planned in `mapReduce` while planning the rest of the `repair` in aggregation. I expected some more tests to become green.
=> Improve LeftShift Mongo plans

it/src/main/resources/tests/nullableDistinct.test, it/src/main/resources/tests/nullable_distinct.data, mongodb/src/main/scala/quasar/physical/mongodb/JavaScriptWorkflowExecutor.scala, mongodb/src/main/scala/quasar/physical/mongodb/MongoDbIOWorkflowExecutor.scala, mongodb/src/test/scala/quasar/physical/mongodb/JavaScriptWorkflowExecutionSpec.scala
Fixes an issue where `null` values in the results of a `db.collection.distinct(...)` query would throw an exception.
=> Allow 'null' values in MongoDB distinct results

it/src/main/resources/tests/qa/s01_simple_selects/select_single_field.test
This is an unresolved issue on PostgreSQL. When we select a single field (without alias), it will be projected into a column anyway, because all results are represented as rows and columns. We need to figure out if we can detect such cases in the planner and use some magic json keys (apparently MongoDB planner went through similiar issue).
=> Disable test for PostgreSQL

rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/PostgresCreate.scala
There are problems with calling `CREATE SCHEMA IF EXISTS` concurrently. Since schemas represent directories, such situation often happens in integration tests which try to create parent `__regression` directories multiple times.
This fix solves the problem by adding an explicit lock on the system `pg_namespace` table.
The lock is released automatically when transaction ends.
Reference: https://stackoverflow.com/questions/29900845/create-schema-if-not-exists-raises-duplicate-key-error
=> PostgreSQL: Allow creating schemas concurrently

rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/planner/PostgresRenderQuery.scala, rdbms/src/main/scala/quasar/physical/rdbms/planner/MapFuncCorePlanner.scala, rdbms/src/main/scala/quasar/physical/rdbms/planner/sql/SqlExpr.scala, rdbms/src/main/scala/quasar/physical/rdbms/planner/sql/SqlExprInstance.scala, rdbms/src/main/scala/quasar/physical/rdbms/planner/sql/SqlExprRenderTree.scala
All `like` expressions were translated to `when (true) ... else .... end`. To avoid `when (true)` and `when (false)`, such cases are now handled independently in the planner proper.
This optimization is not intended to increase performance, just readability of initial DB queries when debugging.
=> RDBMS: Optimize Search for const conditions

effect/src/main/scala/quasar/effect/ScopeExecution.scala, effect/src/main/scala/quasar/effect/TimingScope.scala, interface/src/main/scala/quasar/main/Caching.scala, it/src/test/scala/quasar/server/ServiceSpec.scala, repl/src/main/scala/quasar/repl/Command.scala, repl/src/main/scala/quasar/repl/Main.scala, repl/src/main/scala/quasar/repl/Repl.scala, web/src/main/scala/quasar/api/services/RestApi.scala, web/src/main/scala/quasar/api/services/query/execute.scala, web/src/main/scala/quasar/server/CliOptions.scala, web/src/main/scala/quasar/server/Server.scala, web/src/test/scala/quasar/api/services/RestApiSpecs.scala, web/src/test/scala/quasar/api/services/VCacheFixture.scala, web/src/test/scala/quasar/api/services/query/ExecuteServiceSpec.scala, web/src/test/scala/quasar/api/services/query/QueryFixture.scala
First pass on benchmarking infrastructure.
1. All queries have an associated "execution identifier", a pair of an integer which increments on every query and a start `Instant` (timestamp).
2. All queries have a set of "timing scopes" like "full query execution pipeline" and "parse SQL" which are pairs of start and end timestamps with identifiers attached. Adding a timing scope is as simple as a call into a type class wrapping some part of the query. There need to be a *lot* more of these; we haven't even separated query planning from query execution yet.
3. There's a "timing repository" containing a map from execution identifiers to maps containing all of the execution's timing scopes. It's size-limited, and drops the oldest executions when it goes over the size specified (with age …
=> Generate ExecutionIDs, record and dump basic timing information (fixes qz-3343)

it/src/main/resources/tests/qa/s06_union/columns_self_union.test, it/src/main/resources/tests/qa/s06_union/self_union.test, it/src/main/resources/tests/qa/s06_union/simple_union.test, rdbms/src/main/scala/quasar/physical/rdbms/fs/postgres/planner/PostgresRenderQuery.scala
Avoid the `ignoreResultOrder` flag by using explicit ordering.
=> minor updates to union tests

README.md, interface/src/main/scala/quasar/main/MetaStoreLocation.scala, version.sbt
Return a better error message when copy fails.
=> Fix metastore copy error

connector/src/main/scala/quasar/qscript/qsu/minimizers/CollapseShifts.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala
Increases the state tracking in the `CollapseShifts` core fold to allow static tracking of available map indices, avoiding the need to do a dynamic `ConcatMaps`.  Attn @jsantos17 
#qz-3576 done
=> Eliminate dynamic ConcatMaps in LeftShift repair

connector/src/main/scala/quasar/qscript/qsu/ExpandShifts.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/CollapseShifts.scala, connector/src/test/scala/quasar/qscript/qsu/ExpandShiftsSpec.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala
Depends on #3383 
Avoids a dynamic map construction in `ExpandShifts`.  There still may be a dynamic `ConcatMaps` coming out of `ReifyIdentities`, but I haven't seen it in the wild yet.
=> Ensure static map concatenation in ExpandShifts

connector/src/main/scala/quasar/fs/mount/BackendDef.scala
Provide suggestion that perhaps a required plugin is not enabled. This is after both Doug and Nic (which are both "power-users" were initially confused at what could be the problem)
=> Improve warning message when failing to load filesystem mount

effect/src/main/scala/quasar/effect/ScopeExecution.scala, effect/src/main/scala/quasar/effect/TimingScope.scala, interface/src/main/scala/quasar/main/Caching.scala, it/src/test/scala/quasar/server/ServiceSpec.scala, repl/src/main/scala/quasar/repl/Command.scala, repl/src/main/scala/quasar/repl/Main.scala, repl/src/main/scala/quasar/repl/Repl.scala, repl/src/main/scala/quasar/repl/TimingFormat.scala, web/src/main/scala/quasar/api/services/RestApi.scala, web/src/main/scala/quasar/api/services/query/execute.scala, web/src/main/scala/quasar/server/CliOptions.scala, web/src/main/scala/quasar/server/Server.scala, web/src/test/scala/quasar/api/services/RestApiSpecs.scala, web/src/test/scala/quasar/api/services/VCacheFixture.scala, web/src/test/scala/quasar/api/services/query/ExecuteServiceSpec.scala, web/src/test/scala/quasar/api/services/query/QueryFixture.scala
Makes the REPL friendly to automation by allowing us to turn off the default timing information and not print results, so we don't have to filter it out in a script running the REPL. Also makes the "readable" timing info more readable.
Depends on #3348.
=> Automation friendliness

connector/src/main/scala/quasar/qscript/QScriptCore.scala
#qz-3341 done
My mistake. Mongo's implementation for `Union` is correct. It's only the comment that's wrong.
=> Update incorrect comment on how Union should be implemented by connectors

connector/src/main/scala/quasar/qscript/MapFuncCore.scala, connector/src/main/scala/quasar/qscript/package.scala, connector/src/main/scala/quasar/qscript/rewrites/ExtractFiltering.scala, connector/src/main/scala/quasar/qscript/rewrites/Normalizable.scala, connector/src/test/scala/quasar/qscript/rewrites/ExtractFilteringSpec.scala, it/src/main/resources/tests/filteredFlatten.test
Extends the extracting of "filtering" conditional expressions (where one branch is `Undefined`) to `Cond` in addition to `Guard`.
=> Extract "filtering" Cond expressions in addition to Guards

connector/src/main/scala/quasar/qscript/qsu/ExpandShifts.scala, connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala, connector/src/main/scala/quasar/qscript/qsu/MinimizeAutoJoins.scala, connector/src/main/scala/quasar/qscript/qsu/QSUGraph.scala, connector/src/main/scala/quasar/qscript/qsu/QSUTTypes.scala, connector/src/main/scala/quasar/qscript/qsu/ReadLP.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyBuckets.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyIdentities.scala, connector/src/main/scala/quasar/qscript/qsu/RewriteGroupByArrays.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/CollapseShifts.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/MergeReductions.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/Minimizer.scala, connector/src/main/scala/quasar/qscript/qsu/package.scala, connector/src/test/scala/quasar/qscript/qsu/ExpandShiftsSpec.scala
Avoids direct manipulation of vertices and ensures identical structure will have identical names.
=> Update ExtractFreeMap and ReifyBuckets to use withName

frontend/src/main/scala/quasar/std/library.scala, frontend/src/main/scala/quasar/std/string.scala
I tried to use matchers in `StdLibTypeCoherenceSpec`, but it looks like matchers cannot use scalacheck and the fragments need to be explicit and that means it would take at least five (maybe six) times as many LOC as it does now. We'll have to do with the test names.
Did manage to avoid compiling the regex twice in the success case, though.
=> Prevent Search from erroring in simplifier with invalid regex

build.sbt
With this change (in addition to the already-merged scalaz 7.2.18 PR), the launcher works!
=> Exclude typelevel's scala-library

mongodb/src/main/scala/quasar/physical/mongodb/JavaScriptWorkflowExecutor.scala, mongodb/src/main/scala/quasar/physical/mongodb/MongoDbIOWorkflowExecutor.scala, mongodb/src/main/scala/quasar/physical/mongodb/WorkflowExecutor.scala
=> extend aggregate $out allowing to write to collections in other db's

connector/src/main/scala/quasar/qscript/MapFuncCore.scala, connector/src/main/scala/quasar/qscript/qsu/ExtractFreeMap.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyBuckets.scala, connector/src/main/scala/quasar/qscript/qsu/UnifyTargets.scala, connector/src/test/scala/quasar/qscript/qsu/ExtractFreeMapSpec.scala, connector/src/test/scala/quasar/qscript/qsu/ReifyBucketsSpec.scala, it/src/main/resources/tests/havingWithMultipleProjections.test, it/src/main/resources/tests/subselectDistinctWhere.test, it/src/main/resources/tests/subselectWhere.test
When building functions for various constructs (filter predicates, sort keys, group keys, reducer expressions), when we run into an operation that cannot be expressed as a function, we're forced to create an autojoin. However, there may be operations prior to the problematic one that _can_ be expressed as a function, this PR ensures those operations are extracted as a function prior to autojoining.
#qz-3320 Done
#qz-3331 Done
=> Greedily extract mappable regions prior to autojoining

rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsQueryFile.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsReadFile.scala
When using `.attempt(ex => emit(readFailed(...))`, our stream emits a `Left[FileSystemError]`, but this causes problems with database connections. Apparently this swallows the exception, which doesn't go through standard handling, which leaves a leaking connection and freezes integration tests after saturating the connection pool.
Letting the stream crash in a standard way fixes the problem with leaking connections, but I suppose it's not the right way to fail here, because we would prefer to get the `FileSystemError` wrapped in `Backend`?
Could someone confirm this and eventually offer a solution for correct handling?
=> Redefine RDBMS error handling

frontend/src/main/scala/quasar/sql/parser.scala, frontend/src/test/scala/quasar/sql/SqlParserSpec.scala
Corrects an issue when parsing join conditions where sub-queries weren't required to be enclosed in parentheses, causing subsequent terms from the outer query to be incorrectly considered part of the join condition.
#qz-3635 Done.
=> [qz-3635] Correct parsing of join conditions

connector/src/main/scala/quasar/qscript/qsu/MappableRegion.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/CollapseShifts.scala, connector/src/test/scala/quasar/qscript/qsu/MinimizeAutoJoinsSpec.scala, it/src/main/resources/tests/groupByFlatten.test
Improves `ConsecutiveLeftShift` handling to see through mappable regions, allowing shifts to be aligned correctly in the general case.  Doesn't handle `Cond` rewriting yet (might never; depends on needs).  This unveils other pre-existing bugs within shift handling, necessitating the disabling of `groupByFlatten`.
#qz-3611 Done
=> Mappable shift coalescence

connector/src/main/scala/quasar/qscript/construction.scala, connector/src/main/scala/quasar/qscript/qsu/ApplyProvenance.scala, connector/src/main/scala/quasar/qscript/qsu/Graduate.scala, connector/src/main/scala/quasar/qscript/qsu/LPtoQS.scala, connector/src/main/scala/quasar/qscript/qsu/QScriptUniform.scala, connector/src/main/scala/quasar/qscript/qsu/ReifyIdentities.scala, connector/src/main/scala/quasar/qscript/qsu/ResolveOwnIdentities.scala, connector/src/main/scala/quasar/qscript/qsu/minimizers/CollapseShifts.scala, connector/src/test/scala/quasar/qscript/qsu/ResolveOwnIdentitiesSpec.scala, it/src/main/resources/tests/multilevelFlatten.test, it/src/main/resources/tests/multistageFlatten.test
Corrects an issue where we were incorrectly rewriting access to identities in `LeftShift`.
#qz-3647 Done.
=> Correct identity/value access when reifying shift ids

connector/src/main/scala/quasar/qscript/MapFuncCore.scala, connector/src/main/scala/quasar/qscript/rewrites/DedupeGuards.scala, connector/src/main/scala/quasar/qscript/rewrites/ExtractFiltering.scala, connector/src/main/scala/quasar/qscript/rewrites/Normalizable.scala, connector/src/test/scala/quasar/qscript/MapFuncCoreSpec.scala, mongodb/src/test/resources/planner/plan_filter_on_date.txt, mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala
Adds a `DedupeGuards` rewrite for `FreeMap`s that elides any guards in the continuation of a guard that were evaluated in the predicate of the guard, including any nested guards.
#qz-3613 Done.
#qz-3575 Done.
=> [qz-3613, qz-3188] Elide superfluous guards in a guarded expression.

frontend/src/main/scala/quasar/frontend/logicalplan/LogicalPlanR.scala, it/src/main/resources/tests/multilevelFlatten.test
Runtime guards were only being ensured for the inputs to `FlattenArray` and `FlattenMap`, this extends them to also cover indices/keys and the corresponding `Shift` variants.
#qz-3659 Done.
=> Ensure guards are created for all nested Array/Map inflations.

frontend/src/main/scala/quasar/sql/parser.scala, frontend/src/test/scala/quasar/sql/ExprArbitrary.scala, frontend/src/test/scala/quasar/sql/SqlParserSpec.scala, it/src/main/resources/tests/havingWithMultipleProjections.test, mongodb/src/test/scala/quasar/physical/mongodb/PlannerSql2ExactSpec.scala, sql/src/test/scala/quasar/sql/compiler.scala
#qz-3692 Done
The single integration test we have that uses `having` (`havingWithMultipleProjections.test`) is already pending, with a note to qz-3686.
=> Error `having` in sql parser.

mimir/src/main/scala/quasar/mimir/Mimir.scala
I did this by accident from the runner and that was *very* odd. @djspiewak says this is never a valid thing to do in general.
=> Disallow mounting mimir on relative paths

ejson/src/main/scala/quasar/ejson/DecodeEJson.scala, ejson/src/main/scala/quasar/ejson/DecodeEJsonK.scala, ejson/src/main/scala/quasar/ejson/Decoded.scala, ejson/src/main/scala/quasar/ejson/EJson.scala, ejson/src/main/scala/quasar/ejson/Extension.scala, ejson/src/main/scala/quasar/ejson/Fixed.scala, ejson/src/main/scala/quasar/ejson/TypeTag.scala, ejson/src/main/scala/quasar/ejson/implicits.scala, ejson/src/main/scala/quasar/ejson/optics.scala, ejson/src/test/scala/quasar/ejson/EJson.scala, foundation/src/main/scala/quasar/RenderedTree.scala, foundation/src/main/scala/quasar/fp/numeric/SampleStats.scala, frontend/src/main/scala/quasar/sst/StructuralType.scala, frontend/src/main/scala/quasar/sst/Tagged.scala, frontend/src/main/scala/quasar/sst/TypeStat.scala, frontend/src/main/scala/quasar/tpe/TypeF.scala, frontend/src/test/scala/quasar/sst/StructuralTypeSpec.scala, frontend/src/test/scala/quasar/sst/TypeStatSpec.scala, frontend/src/test/scala/quasar/sst/TypedEJson.scala, frontend/src/test/scala/quasar/tpe/TypeFSpec.scala
Adds `DecodeEJson` and `DecodeEJsonK` typeclasses for decoding values from `EJson` along with instances for types that had already defined an `EncodeEJson` instance.
=> Typeclasses for decoding EJson

core/src/main/scala/quasar/fs/mount/cache/ViewCache.scala, core/src/main/scala/quasar/metastore/Queries.scala, web/src/main/scala/quasar/api/services/mount.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala
Problem was that when updating a cached view `view_cache.last_update` was still filled with a value from the old entry, whereas `view_cache.refresh_after` was set to a value in the future calculated from `maxAge`. This meant that when checking for `staleCachedViews` (based on the query `SELECT *
FROM view_cache WHERE last_update IS NULL OR ($now > refresh_after)`) these entries were not going to be repaired until somewhere in the future (i.e. a broken cache for this period). They must be repaired immediately instead.
The fix sets `view_cache.refresh_after` to `now` when creating or updating the cache and simplifies the `staleCachedViews`check by stopping to look at `last_update` in the query.
#qz-3694 Done
#qz-3695 Done
=> Fix PUTting existing cached view

project/plugins.sbt, project/project/plugins.sbt
This PR is a part of overall migration to bintray.
Here, the sbt-slamdata plugin dependency was bumped.
On next release quasar should be published to bintray repo "slamdata-inc/maven-public", and hopefully synchronzied with maven (this part is not tested as it requires sonatype credentials).
Note that before creating this PR I prepared packages on bintray manually:
I used sbt task `bintrayEnsureBintrayPackageExists`
I removed redundant packages it created (this task also creates packages for modules that will not be published)
For each such package I requested linking it to jCenter. It is required for sync with maven central
Those steps will be required when for example a new module is introduced. It is also required for any project that is published via the sbt-slamdata plugin. In case …
=> Bump sbt-slamdata plugin to enable bintray publishing

mongodb/src/main/scala/quasar/physical/mongodb/MongoDbPlanner.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/JsFuncHandler.scala, mongodb/src/main/scala/quasar/physical/mongodb/planner/common.scala
Refactor `JsFuncHandler` to be an `AlgebraM`. This allows:
* Code to move from `MongoDbPlanner` to `JsFuncHandler`
* `JsFuncHandler.mapFuncDerived` to be defined in terms of `ExpandMapFunc.expand`
* `MongoDbPlanner.handleSpecial` and `MongoDbPlanner.handleCommon` to be merged together
* deduplicate code (that was formerly duplicated in `MongoDbPlanner` and `JsFuncHandler`)
Part of #qz-3330
=> JsFuncHandler as AlgebraM

interface/src/main/scala/quasar/main/Quasar.scala, interface/src/main/scala/quasar/main/logging.scala, interface/src/main/scala/quasar/main/package.scala, repl/src/main/resources/log4j.properties, web/src/main/resources/log4j.properties, web/src/main/scala/quasar/api/FailedResponse.scala, web/src/main/scala/quasar/api/QHttpService.scala, web/src/main/scala/quasar/api/QResponse.scala, web/src/main/scala/quasar/api/package.scala, web/src/main/scala/quasar/api/services/RestApi.scala, web/src/main/scala/quasar/server/Server.scala, web/src/main/scala/quasar/server/package.scala, web/src/test/scala/quasar/api/QHttpServiceSpec.scala, web/src/test/scala/quasar/api/services/DataServiceSpec.scala, web/src/test/scala/quasar/api/services/Fixture.scala, web/src/test/scala/quasar/api/services/MetastoreServiceSpec.scala, web/src/test/scala/quasar/api/services/MountServiceSpec.scala, web/src/test/scala/quasar/api/services/RestApiSpecs.scala, web/src/test/scala/quasar/api/services/VCacheFixture.scala, web/src/test/scala/quasar/api/services/analyze/SchemaServiceSpec.scala
Improves the logging story in Quasar by logging unhandled critical errors and making exception information available to be logged when an error occurs in the middle of streaming an HTTP response body.
#qz-3715 Done.
=> Log critical Quasar errors and unhandled connector exceptions

frontend/src/main/scala/quasar/codec.scala, frontend/src/main/scala/quasar/std/date.scala, frontend/src/test/scala/quasar/codec.scala
It also supports mixed-mode data structures (i.e. arrays/objects which contain *both* the old format and the new).  Now that I think about it, that's probably not actually necessary, but it's still cool.  😁
=> Restored support for decoding (but not encoding!) old precise

it/src/main/resources/tests/temporal/simple_date_filter.test, it/src/main/resources/tests/temporal/simple_timestamp_filter.test, it/src/main/resources/tests/temporal/simple_to_timestamp_filter.test
add test cases for date, timestamp and to_timestamp filters
This is #3501 adapted for next-major
Relates to #sdbe-314, #sdbe-315, #sdbe-316
=> add test cases for date, timestamp and to_timestamp filters (next-major)

frontend/src/main/scala/quasar/codec.scala, frontend/src/main/scala/quasar/std/string.scala, frontend/src/test/scala/quasar/codec.scala, frontend/src/test/scala/quasar/std/StdLibSpec.scala, mongodb/src/main/scala/quasar/physical/mongodb/bsoncodec.scala
Did you know there's *nine* digits for sub-second precision in the default formatter? Neither did I.
I hope there are no unfortunate consequences of using a different `toFormatter` overload than is used in the JDK (the one they use is package-private).
=> Always format times verbosely, use Time#toString more often

build.sbt, interface/src/main/scala/quasar/main/BackendConfig.scala, interface/src/main/scala/quasar/main/package.scala, web/src/main/scala/quasar/server/Server.scala
This PR prepares quasar to work with new installers. Note that when it is merged installers PR also has to be merged. It won't be possible to build valid installers with old installer scripts and this version of quasar, because plugin resolution behavior changes. 
This attribute was originally only added to fat jar, now it is added to thin jars as well. It was done in order to allow quasar to resolve plugin main classes from thin jars, that will replace fat jars.
The previous behavior of `--plugins/-P` option was to find all fat jars in specified directory with Backend-Module attributes and load them.
Now this option behaves differently. It looks for files with .plugin extension. Those should be json files looking like this:
```
{
"main_jar": …
```
=> New plugin loading

core/src/main/scala/quasar/fs/mount/MountType.scala, core/src/main/scala/quasar/fs/mount/Mounter.scala, core/src/main/scala/quasar/fs/mount/module/package.scala, core/src/main/scala/quasar/metastore/MetaStoreAccess.scala, core/src/main/scala/quasar/metastore/MetaStoreMounter.scala, core/src/main/scala/quasar/metastore/Queries.scala, core/src/test/scala/quasar/fs/mount/module/ModuleFileSystemSpec.scala
A couple of performance improvements related to accessing mount metadata
1. Improve the metastore implementation of `havingPrefix` to only require a single query instead of N+1.
2. Avoid loading all mounts on every read in the module filesystem, instead just check parents until a mount is found.
Also corrects error generating behavior for writes to a module.
#qz-3732 Done
=> Improve performance when accessing mount metadata

it/src/test/scala/quasar/fs/FileSystemTest.scala, it/src/test/scala/quasar/fs/ManageFilesSpec.scala
Replaces the `unsupported` matcher with a declarative function that marks the result as `skipped` if it raises an unsupported error.
=> Minor filesystem test updates

it/src/test/scala/quasar/fs/QueryFilesSpec.scala, it/src/test/scala/quasar/fs/ReadFilesSpec.scala
These are all passing locally and do not run slowly (at least not more slowly than other tests in the suite).
=> Enable mimir fs tests

README.md, datagen/src/main/scala/quasar/datagen/dist.scala, datagen/src/main/scala/quasar/datagen/generate.scala, datagen/src/test/scala/quasar/datagen/GenerateSpec.scala, ejson/src/main/scala/quasar/ejson/DecodeEJson.scala, ejson/src/main/scala/quasar/ejson/EJson.scala, ejson/src/test/scala/quasar/ejson/DecodeEjsonSpec.scala, frontend/src/main/scala/quasar/sst/ExtractPrimary.scala, frontend/src/main/scala/quasar/sst/StructuralType.scala, frontend/src/main/scala/quasar/sst/TypeStat.scala, frontend/src/main/scala/quasar/sst/compression.scala, frontend/src/main/scala/quasar/sst/package.scala, frontend/src/main/scala/quasar/sst/strings.scala, frontend/src/main/scala/quasar/tpe/SimpleType.scala, frontend/src/main/scala/quasar/tpe/normalization.scala, frontend/src/main/scala/quasar/tpe/package.scala, frontend/src/test/scala/quasar/sst/CompressionSpec.scala, frontend/src/test/scala/quasar/sst/StringsSpec.scala, frontend/src/test/scala/quasar/sst/TypeStatArbitrary.scala, frontend/src/test/scala/quasar/sst/TypeStatSpec.scala, frontend/src/test/scala/quasar/tpe/TypeFSpec.scala, interface/src/main/scala/quasar/main/analysis.scala, interface/src/test/scala/quasar/main/ExtractSchemaSpec.scala, web/src/main/scala/quasar/api/services/analyze/schema.scala, web/src/test/scala/quasar/api/services/analyze/SchemaServiceSpec.scala
Extends the structural treatment of strings in SSTs to widen strings shorter than `stringMaxLength` to an array of their characters allowing the preservation of positional character distributions. This enables SSTs to capture much of the structure that may be embedded in a string (i.e. SSNs, phone numbers, UUIDs, temporal, etc).
#qz-3719 Done.
=> Capture character distribution within strings in SSTs

web/src/main/resources/log4j.properties, web/src/main/scala/quasar/api/Destination.scala, web/src/main/scala/quasar/api/HeaderParam.scala, web/src/main/scala/quasar/api/Prefix.scala, web/src/main/scala/quasar/api/RFC5987ContentDispositionRender.scala, web/src/main/scala/quasar/api/RequestLogging.scala, web/src/main/scala/quasar/api/XFileName.scala, web/src/main/scala/quasar/api/package.scala, web/src/main/scala/quasar/api/services/RestApi.scala
Adds a `RequestLogging` middleware for http4s and enables it by default to log HTTP request lines.
#sdbe-325 Done
=> Enable logging of HTTP request lines by default

connector/src/main/scala/quasar/connector/BackendModule.scala, connector/src/main/scala/quasar/fs/Empty.scala, connector/src/main/scala/quasar/fs/InMemory.scala, connector/src/main/scala/quasar/fs/ManageFile.scala, connector/src/main/scala/quasar/fs/TempFilePrefix.scala, connector/src/main/scala/quasar/fs/TmpFile.scala, connector/src/main/scala/quasar/fs/WriteFile.scala, connector/src/main/scala/quasar/fs/package.scala, connector/src/main/scala/quasar/fs/transformPaths.scala, core/src/main/scala/quasar/fs/mount/cache/VCache.scala, core/src/main/scala/quasar/fs/mount/hierarchical.scala, core/src/main/scala/quasar/fs/mount/nonFsMounts.scala, core/src/test/scala/quasar/fs/TraceFS.scala, couchbase/src/main/scala/quasar/physical/couchbase/fs/managefile.scala, interface/src/main/scala/quasar/main/ViewCacheRefresh.scala, it/src/test/scala/quasar/ResultFileQueryRegressionSpec.scala, it/src/test/scala/quasar/fs/ManageFilesSpec.scala, marklogic/src/main/scala/quasar/physical/marklogic/MarkLogic.scala, mimir/src/main/scala/quasar/mimir/SlamDB.scala, mongoIt/src/test/scala/quasar/physical/mongodb/fs/MongoDbFileSystemSpec.scala, mongodb/src/main/scala/quasar/physical/mongodb/MongoDb.scala, mongodb/src/main/scala/quasar/physical/mongodb/fs/managefile.scala, mongodb/src/main/scala/quasar/physical/mongodb/fs/package.scala, rdbms/src/main/scala/quasar/physical/rdbms/fs/RdbmsManageFile.scala, skeleton/src/main/scala/quasar/physical/skeleton/fs/Skeleton.scala, sparkcore/src/main/scala/quasar/physical/sparkcore/fs/sparkcore.scala, web/src/main/scala/quasar/api/services/mount.scala
The template of cache data files is now `cache_<viewFileName>_<connectorSpecificId>`, e.g for mongo it is now `cache_<viewFileName>_<salt>_<seqnr>`
#qz-3747 Done
=> rename cache data files

it/src/main/resources/tests/demo/nestedreductionsonnull.test, it/src/main/resources/tests/flattenNestedMap.test
I found these by running `find . -name '*.test' ! -exec jq 42 -c -r {} \; -print` from `it/src/main/tests/` and ignoring the `parse error: Invalid string: control characters from U+0000 through U+001F must be escaped` errors, which appear to be spurious.
=> Fixed invalid json in tests

frontend/src/test/scala/quasar/sst/CompressionSpec.scala
Fixes a flaky SST compression test that had incorrect expectations when certain combinations of SSTs and EJson involving metadata was generated. This was actually irrelevant to the feature under test so it was removed.
=> Correct and simplify SST compression spec expectation.

build.sbt, project/plugins.sbt, project/project/plugins.sbt, scripts/quasarPublishAndTag
This PR depends on https://github.com/slamdata/slamdata-backend/pull/325 and https://github.com/slamdata/sbt-slamdata/pull/46
plugin version needs to be bumped to a real one once it is released.
=> Implement auto PR to bump sdbe on release

.travis.yml, scripts/s3Cache
Use travis build numbers as the directory names in s3 bucket.
Use cleanup stage during master build to delete really old caches lingering in s3 bucket.
=> use build numbers instead of pr numbers 

qscript/src/main/scala/quasar/qscript/QScriptCore.scala, qscript/src/main/scala/quasar/qscript/RecFreeS.scala
I had these changes sitting on a local branch.
I added a `Leaf` constructor for `RecFreeS` to allow bindings like `Let(LeftSide, someFreeMap)`.
=> Fix letIn and add a real Show instance for RecFreeS

project/Precog.scala
We were never actually putting the jar at that path; instead we manage the jar:
```
"org.apache.jdbm" %  "jdbm" % "3.0-alpha5"
```
=> Remove unmanaged jar path for jdbm snapshot

api/src/main/scala/quasar/api/ResourceDiscovery.scala, api/src/main/scala/quasar/api/ResourceError.scala, api/src/main/scala/quasar/api/ResourcePath.scala, api/src/test/scala/quasar/api/MockQueryEvaluator.scala, api/src/test/scala/quasar/api/ResourceNameGenerator.scala, api/src/test/scala/quasar/api/ResourcePathGenerator.scala, api/src/test/scala/quasar/api/ResourcePathSpec.scala, build.sbt, core/src/main/scala/quasar/FederatedQuery.scala, core/src/main/scala/quasar/FederatingQueryEvaluator.scala, core/src/main/scala/quasar/QueryFederation.scala, core/src/main/scala/quasar/Source.scala, core/src/main/scala/quasar/package.scala, core/src/test/scala/quasar/FederatingQueryEvaluatorSpec.scala
Adds a `QueryEvaluator` capable of executing queries over multiple sources. Handles the routing of operations to sources and ensuring all sources referenced in a query exist.
The actual work of executing a `FederatedQuery` is left up to an instance of `QueryFederation`, to eventually be implemented for `mimir`.
=> FederatingQueryEvaluator

build.sbt, project/Dependencies.scala, project/Precog.scala, project/plugins.sbt
We were having problems with Iota's build configuration overriding ours. This is why publication was failing in master. Unfortunately, this means we have to go back to a non-reproducible build until Iota [publishes a new version](https://github.com/frees-io/iota/issues/220) (which will likely be 0.3.8).
=> Revert "Replaced snapshot dependency with stable github dependency

api/src/main/scala/quasar/api/QueryEvaluator.scala, api/src/main/scala/quasar/api/ResourceDiscovery.scala, api/src/test/scala/quasar/api/MockQueryEvaluator.scala, api/src/test/scala/quasar/api/MockResourceDiscoverySpec.scala, api/src/test/scala/quasar/api/ResourceDiscoverySpec.scala, connector/src/main/scala/quasar/connector/DataSource.scala, connector/src/main/scala/quasar/connector/HeavyweightDataSourceModule.scala, connector/src/main/scala/quasar/connector/LightweightDataSourceModule.scala, connector/src/main/scala/quasar/connector/datasource/HeavyweightDataSource.scala, connector/src/main/scala/quasar/connector/datasource/LightweightDataSource.scala, core/src/main/scala/quasar/evaluate/FederatingQueryEvaluator.scala, core/src/test/scala/quasar/evaluate/FederatingQueryEvaluatorSpec.scala
Abstracts over the return type of `ResourceDiscovery#{children, descendants}`, simplifying the interface and allowing us to specialize to `fs2.Stream` in datasource modules, allowing more efficient implementations than the strict data structures permitted.
=> More flexible resource discovery types

project/Dependencies.scala
We need 6.2.2 over in slamdata-backend and apparently it isn't binary compatible with 6.2 (turns out making implicit ops classes into value classes introduces binary incompatibilities).
=> Update argonaut to 6.2.2

api/src/test/scala/quasar/api/MockDataSourcesSpec.scala
This test was previously coincidentally triggering the specs2 SOE ch270, so it was disabled. That bug turned out to be a bug in specs2 itself, so I'd like to try enabling this test again.
If it triggers the SOE maybe we can leave this PR open until the specs2 fix is merged, just so we don't forget about this test.
=> Enable MockDataSourcesSpec

impl/src/main/scala/quasar/impl/table/PreparationsManager.scala, impl/src/test/scala/quasar/impl/table/PreparationsManagerSpec.scala
The test had a weird race condition reordering which could cause the test to spuriously fail. Fixed with a latch. Also found an unrelated bug which could cause cancelation to fail if it happened *exactly* at the moment where a preparation goes from pending to started.
[ch750]
=> Fixed flaky test in PreparationsManagerSpec

yggdrasilPerf/src/main/scala/quasar/yggdrasil/perf/ToRValuesBenchmark.scala
Actually very interesting results, which are so interesting I can't help but think that either the benchmark is broken, or `toRValue` is kind of broken.
```
Benchmark                                  (vectorLength)  Mode  Cnt    Score    Error  Units
ToRValuesBenchmarkVector.arraysToRValues                5  avgt    5    0.146 ±  0.008  ms/op
ToRValuesBenchmarkVector.arraysToRValues               20  avgt    5    0.300 ±  0.006  ms/op
ToRValuesBenchmarkVector.arraysToRValues               80  avgt    5    1.508 ±  0.035  ms/op
ToRValuesBenchmarkVector.arraysToRValues              320  avgt    5   18.392 ±  0.093  ms/op
ToRValuesBenchmarkVector.arraysToRValues             1280  avgt    5  326.650 ± 11.335  ms/op
ToRValuesBenchmarkVector.objectsToRValues               5  avgt    5    0.156 …
```
=> Add toRValue benchmarks

yggdrasilPerf/src/main/scala/quasar/yggdrasil/perf/LeftShiftBenchmark.scala, yggdrasilPerf/src/main/scala/quasar/yggdrasil/perf/SliceTools.scala
See https://gist.github.com/rintcius/9552dc741a547e9e5b60a7d37a1a6f10 for preliminary results (I can run with more iterations tomorrow if #3730 is ready then).
Overall the fixes in #3730 improve leftshift performance considerably. Exception is `scalarOrUndefined` - this became quite a lot slower.
=> Leftshift benchmark

build.sbt
Ideally we'd be publishing `testkit`s instead of publishing tests. This is tech debt we are okay with accruing for now.
=> Publish tests for all projects

foundation/src/main/scala/quasar/contrib/cats/effect/package.scala, it/src/test/scala/quasar/physical/mimir/MimirStdLibSpec.scala, mimir/src/main/scala/quasar/mimir/Precog.scala, mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala, yggdrasil/src/main/scala/quasar/yggdrasil/nihdb/NIHDBProjection.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/VFSColumnarTableModule.scala
This turned out to be quite easy to knock off. General rule: whenever we're touching `ExecutionContext`-involved code, try to keep pushing it towards the boundaries. Ultimately, we want to create these things when we create `Quasar` and thread them all the way through. We're using `global` in quite a few places right now, which is definitely not ideal, though not an urgent thing to fix.
[ch591]
=> Corrected future-derived IO continuations remaining on wrong pool

mimir/src/main/scala/quasar/mimir/storage/storage/MimirPTableStore.scala, niflheim/src/main/scala/quasar/niflheim/Chef.scala, niflheim/src/main/scala/quasar/niflheim/NIHDBActor.scala, yggdrasil/src/main/scala/quasar/yggdrasil/nihdb/SegmentsWrapper.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/ArrayColumn.scala, yggdrasil/src/test/scala/quasar/yggdrasil/nihdb/SegmentsWrapperSpec.scala
This gives us, among other things, type preservation in preparation results. It should also be orders of magnitude faster.
This relies on the new API, `NIHDB.insertSegmentsVerified`. This API is, in isolation, safe, but you cannot mix it with `NIHDB.insert` or `insertVerified`. If you mix the two, you'll end up losing uncooked data in the append logs. If we need mixing, we can add it down the line, it's just more complicated than what I wanted to deal with right now.
[ch1331]
=> Persist slices in bulk in NIHDB (bypassing JValue)

yggdrasil/src/main/scala/quasar/yggdrasil/table/Column.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
Just got reminded about this while refactoring the columns map, but like to create as a separate PR. 
We discussed this change earlier as part of another PR.
=> make ArrayColumn.update return this.type instead of Unit

api/src/main/scala/quasar/api/datasource/DatasourceError.scala, connector/src/main/scala/quasar/connector/ResourceError.scala
`MalformedResource` intends to represent the case where a user tries to query something we can't parse into `Json`. This could be an image, some binary file or even a line-delimited JSON when we expected array JSON.
This is related ch#945. In order to implement what 945 specifies, I'll need to open two more PRs against `slamdata-backend` and `quasar-s3`.
=> Introduce MalformedResource to ResourceError

frontend/src/test/scala/quasar/std/StdLibSpec.scala, mimir/src/main/scala/quasar/mimir/MathLib.scala, mimir/src/main/scala/quasar/mimir/UnaryLib.scala, mimir/src/test/scala/quasar/mimir/MathLibSpecs.scala, mimir/src/test/scala/quasar/mimir/StringLibSpecs.scala
fix round for doubles
... removed round from MathLib because it's broken and we can use rint instead
(both Math.rint and round from sql2 use HALF_EVEN)
[ch1777]
=> fix round for doubles

project/Dependencies.scala
We were running into the `NoSuchMethodError` below because of https://github.com/scalaz/scalaz/pull/1790
```
java.lang.NoSuchMethodError: scalaz.NonEmptyList$.apply(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Lscalaz/NonEmptyList;
at quasar.frontend.logicalplan.Optimizer.<init>(Optimizer.scala:376)
at quasar.frontend.logicalplan.package$.preparePlan(package.scala:95)
at quasar.compile.package$.$anonfun$queryPlan$1(package.scala:150)
at cats.data.WriterT.$anonfun$flatMap$1(WriterT.scala:44)
```
[ch1794]
=> upgrade scalaz to 7.2.26

impl/src/main/scala/quasar/impl/table/PreparationsManager.scala, impl/src/test/scala/quasar/impl/table/PreparationsManagerSpec.scala
We already record durations for [ch1749], but they're expressed in seconds, not milliseconds.
=> OffsetDateTime toEpochSeconds returns seconds, not milliseconds

impl/src/main/scala/quasar/impl/datasources/DatasourceManagement.scala, impl/src/main/scala/quasar/impl/schema/SstConfig.scala, impl/src/main/scala/quasar/impl/schema/SstEvalConfig.scala, impl/src/main/scala/quasar/impl/schema/package.scala, impl/src/test/scala/quasar/impl/datasources/DatasourceManagementSpec.scala, impl/src/test/scala/quasar/impl/schema/ExtractSstSpec.scala, it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala, repl/src/main/scala/quasar/repl/Main.scala, run/src/main/scala/quasar/run/Quasar.scala, sst/src/main/scala/quasar/sst/compression.scala, sst/src/main/scala/quasar/sst/strings.scala, sst/src/test/scala/quasar/sst/CompressionSpec.scala, sst/src/test/scala/quasar/sst/StructuralTypeSpec.scala
Some low-hanging fruit to improve SST generation performance
1. Make preservation of string structure during compression optional, defaulting to not preserving structure.
2. Optimize computing an SST from a `Chunk` of data.
3. Leverage the fact that SST merging forms a commutative semigroup to divide and conquer, computing multiple chunks in parallel.
=> SST performance improvements

README.md, frontend/src/main/scala/quasar/frontend/data/DataCodec.scala, frontend/src/test/scala/quasar/frontend/data/DataCodecSpec.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
We no longer support keys that coincidentally share a name with a precise key.
=> Remove `$obj` from precise json.

qsu/src/main/scala/quasar/qsu/CoalesceUnaryMappable.scala, qsu/src/main/scala/quasar/qsu/InlineNullary.scala, qsu/src/main/scala/quasar/qsu/LPtoQS.scala, qsu/src/main/scala/quasar/qsu/MappableRegion.scala, qsu/src/test/scala/quasar/qsu/CoalesceUnaryMappableSpec.scala, qsu/src/test/scala/quasar/qsu/InlineNullarySpec.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala
Inlines nullary regions and coalesces unary ones prior to computing provenance to avoid having to create existentials due to "dynamic" project/injects.
Also appears to speed up compilation in general due to shrinking the size of the graph earlier on in the process.
=> Coalesce mappable regions before ApplyProvenance 

core/src/main/scala/quasar/compile/Compiler.scala, frontend/src/main/scala/quasar/std/structural.scala, frontend/src/test/scala/quasar/std/StdLibSpec.scala, mimir/src/main/scala/quasar/mimir/MapFuncCorePlanner.scala, qscript/src/main/scala/quasar/qscript/MapFunc.scala, qscript/src/main/scala/quasar/qscript/MapFuncCore.scala, qscript/src/main/scala/quasar/qscript/RenderQScriptDSL.scala
Heads up, @garyb. Publishing as snapshot version `68.2.0-31c90da` which is eviction compatible with 68.2.0. You should be able to test this within the launcher (by appending version directive `quasar:68.2.0-31c90da`).
@alissapajer I would mark this as ☠️ but github is being weird. Please review and merge asap.
[ch2071]
=> Implement CONTAINS_KEY

it/src/main/resources/tests/joins/staticOuterJoin.test, qscript/src/main/scala/quasar/qscript/MapFuncCore.scala, qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala, qscript/src/main/scala/quasar/qscript/rewrites/SimplifyJoin.scala, qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala
This fixes the old `SimplifyJoin` rewrite. The new integration test will catch this bug when we finally move this rewrite to QSU.
=> Avoid simplifying constant comparisons in outer joins

connector/src/main/scala/quasar/connector/QScriptEvaluator.scala, mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala, qscript/src/main/scala/quasar/qscript/rewrites/Optimize.scala, qscript/src/test/scala/quasar/qscript/rewrites/OptimizeSpec.scala
Sets the stage for where we'll perform qscript rewrites that we intend to keep as qscript rewrites and not eventually move to qsu.
This particular rewrite (elide no-op map) will allow us to more consistently match on the pattern
```
LeftShift
├─ ShiftedRead(/giraffe.json, _)
...
```
as currently in master this pattern often appears as
```
LeftShift
├─ Map
│  ├─ ShiftedRead(/giraffe.json, _)
│  ╰─ ○
...
```
We'll be matching this pattern as part of the parse-shift work, because we'll be rewriting certain qscript into an `ExtraShiftedRead`.
=> Adds an optimize qscript rewrite stage

connector/src/main/scala/quasar/connector/QScriptEvaluator.scala, mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala, qscript/src/main/scala/quasar/qscript/package.scala
Weeding through our implicit coproduct requirements, figuring out which ones are actually required.
=> Delete some unused implicits from the qscript evaluator

qsu/src/main/scala/quasar/qsu/LPtoQS.scala, qsu/src/main/scala/quasar/qsu/PruneSymmetricDimEdits.scala, qsu/src/test/scala/quasar/qsu/LPtoQSSpec.scala, qsu/src/test/scala/quasar/qsu/PruneSymmetricDimEditsSpec.scala
This resolves the issues of a single `Transpose` turning into two `LeftShift`s in `ApplyProvenance`. It appears we have an unrelated issue in `CollapseShifts` which has the same symptom.
[ch2113]
=> Prune Symmetric DimEdit Nodes Before ApplyProv

qscript/src/main/scala/quasar/qscript/provenance/Prov.scala, qscript/src/test/scala/quasar/qscript/provenance/ProvSpec.scala, qsu/src/main/scala/quasar/qsu/ApplyProvenance.scala, qsu/src/main/scala/quasar/qsu/CoalesceUnaryMappable.scala, qsu/src/main/scala/quasar/qsu/InlineNullary.scala, qsu/src/main/scala/quasar/qsu/LPtoQS.scala, qsu/src/main/scala/quasar/qsu/MappableRegion.scala, qsu/src/test/scala/quasar/qsu/ApplyProvenanceSpec.scala, qsu/src/test/scala/quasar/qsu/CoalesceUnaryMappableSpec.scala, qsu/src/test/scala/quasar/qsu/InlineNullarySpec.scala, qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala
Improves `CoalesceUnaryMappable` to coalesce source `Map`s into an `AutoJoin{2,3}`. This ended up requiring better provenance normalization for performance of computing provenance on large `MapFunc`s.
Also updated `InlineNullary` to be more performant as it didn't require the amount of traversing it was performing.
=> More thorough CoalesceUnaryMappable

it/src/main/resources/tests/joins/selfFullOuterJoin.test, it/src/main/resources/tests/joins/selfLeftOuterJoin.test, it/src/main/resources/tests/joins/selfRightOuterJoin.test, mimir/src/main/scala/quasar/mimir/EquiJoinPlanner.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala, yggdrasil/src/test/scala/quasar/yggdrasil/CogroupSpec.scala
Now includes rows when outer join key is undefined. This changes the results of left, right and full outer joins if there are undefined join keys.
Full outer joins were originally (that is, with the fix for left and right joins) multiplying rows with undefined keys, but are in ae96456 changed to be summing them instead.
=> include rows when outer join key is undefined

datagen/src/main/scala/quasar/datagen/dist.scala, datagen/src/test/scala/quasar/datagen/GenerateSpec.scala, frontend/src/main/scala/quasar/tpe/TypeF.scala, frontend/src/main/scala/quasar/tpe/normalization.scala, frontend/src/test/scala/quasar/tpe/TypeFArbitrary.scala, frontend/src/test/scala/quasar/tpe/TypeFSpec.scala, impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala, impl/src/main/scala/quasar/impl/schema/SstConfig.scala, impl/src/main/scala/quasar/impl/schema/package.scala, impl/src/test/scala/quasar/impl/schema/ExtractSstSpec.scala, repl/src/main/scala/quasar/repl/Evaluator.scala, run/src/main/scala/quasar/run/QuasarError.scala, sst/src/main/scala/quasar/sst/StructuralMerge.scala, sst/src/main/scala/quasar/sst/TypeStat.scala, sst/src/main/scala/quasar/sst/compression.scala, sst/src/main/scala/quasar/sst/strings.scala, sst/src/test/scala/quasar/sst/CompressionSpec.scala, sst/src/test/scala/quasar/sst/StringsSpec.scala, sst/src/test/scala/quasar/sst/StructuralTypeSpec.scala
Updates the array type representation to allow for both known indices of a specific type along with an optional type representing the LUB of the rest of the array, similar to how maps are represented.
Adds a new option to SST schema configuration to preserve a specified number of indices when compressing long arrays.
=> Ability to preserve array indices in SSTs

it/src/main/resources/tests/deep-giraffe-plus.data, it/src/main/resources/tests/shiftDeepGiraffeExcludeId.test, it/src/main/resources/tests/shiftDeepGiraffeIdOnly.test, it/src/main/resources/tests/shiftDeepGiraffeIncludeId.test, it/src/main/resources/tests/shiftDeepGiraffeIncludeIdAndField.test
Analogous tests as the ones added in #3834, this time with the shifts post-projection.
=> Add integration tests for shifting through object projections

it/src/main/resources/tests/joins/crossJoinWithOneSidedConditions.test
This tests returns results in a few seconds. The results are a very large number of rows each with `{"b":"CHICO"}`, like so:
```
{"b":"CHICO"}
{"b":"CHICO"}
{"b":"CHICO"}
...
```
=> Make join test pending instead of skipped

mimir/src/main/scala/quasar/mimir/evaluate/MimirQScriptEvaluator.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/Slice.scala, yggdrasil/src/test/scala/quasar/yggdrasil/table/SliceSpec.scala
The bug was being caused by a column which was part of the intermediate evaluation state, but subsequently got entirely "nulled out" and every value set to `undefined`.  This isn't really a problem for a JSON output, but CSV is a bit pickier. The solution is two-fold. First, we `materialize` every slice upon completion of evaluation. This is probably a good idea anyway. Or at least, I'm asserting without benchmarks that it is. Second, I modified `materialized` to remove any entirely empty columns, since we can do so efficiently at that point.
[ch2383]
=> Eliminate phantom empty columns in result sets

yggdrasil/src/main/scala/quasar/yggdrasil/TableModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/CPathPlate.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/IdsPlate.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/MaskPlate.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/PivotPlate.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/WrapPlate.scala, yggdrasil/src/test/scala/quasar/yggdrasil/table/TectonicParseInstructionSpec.scala, yggdrasilPerf/src/main/scala/quasar/yggdrasil/perf/TableConstructionBenchmark.scala
Had to move the plates out of mimir and into yggdrasil in order to keep `parseJson`'s implementation confined to that package. Ties the knot on everything mimir-related though.
=> Plate interpretation in Table.parseJson

impl/src/main/scala/quasar/impl/external/ExternalConfig.scala, impl/src/main/scala/quasar/impl/external/ExternalDatasources.scala
This is necessary to allow SDBE to specify a list of plugin files, rather than relying on the plugin directory included in the config. This *in turn* is extremely important because it allows the launcher to function reliably.
=> Added file case to ExternalConfig

yggdrasil/src/main/scala/quasar/yggdrasil/table/SlicePlate.scala, yggdrasil/src/test/scala/quasar/yggdrasil/table/SlicePlateSpec.scala
You'll notice that the unit test actually shows that we go one column *over* the limit. This is because we can't know that we've exceeded the column limit… until we actually exceed it. Fixing this in the current implementation would require undoing data that has already been put into columns and then re-doing that work against a new slice, which sounds hard, slow, and probably not worth it for right now. Ticketing for future improvement.
[ch2955]
[ch2350]
=> Added tests for tectonic slice breaking and fixed off-by-one issue

api/src/test/scala/quasar/api/table/MockTables.scala, frontend/src/main/scala/quasar/ParseInstruction.scala, frontend/src/test/scala/quasar/ParseInstructionSpec.scala, mimir/src/main/scala/quasar/mimir/RValueParseInstructionInterpreter.scala, mimir/src/test/scala/quasar/mimir/evaluate/RValueParseInstructionSpec.scala, qscript/src/main/scala/quasar/qscript/rewrites/RewritePushdown.scala, qscript/src/test/scala/quasar/qscript/rewrites/RewritePushdownSpec.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala, yggdrasil/src/main/scala/quasar/yggdrasil/table/PivotPlate.scala, yggdrasil/src/test/scala/quasar/yggdrasil/table/TectonicParseInstructionSpec.scala
```json
{ "a": 42, "b": true, "c": [1, 2, 3], "d": ["hi", "there"] }
```
with `b` and `d` retained and `c` pivoted will first be `Mask`ed, then be `Wrap`ed as so:
```json
{ "locus1": { "retain": { "b": true } }, "locus2": [1, 2, 3], "locus3": { "retain": { "d": ["hi", "there"] } } }
```
and then `Pivot`ed as so:
```scala
Pivot(Map((.locus1, ...), (.locus2, ...), (.locus3, ...)))
```
=> Generalize ParseInstruction.Pivot

foundation/src/main/scala/quasar/Disposable.scala, foundation/src/test/scala/quasar/DisposableSpec.scala
When interpreting a composite resource, the previous implementation would incorrectly dispose of the first resource on acquisition of the second. This corrects the behavior to only dispose if the subsequent acquisition fails.
=> Only dispose when subsequent acquisition fails

connector/src/main/scala/quasar/connector/datasource/SingletonDatasource.scala, connector/src/test/scala/quasar/connector/datasource/SingletonDatasourceSpec.scala
Fixes an issue where listing the parent path of the singleton resource would return the resource name typed as a prefix instead of a resource.
=> Singleton ds should list resource as a resource

foundation/src/main/scala/quasar/contrib/fs2/pipe.scala, repl/src/main/scala/quasar/repl/Evaluator.scala
This is part of [ch3352]. I verified that the mark is correctly handled by both Sublime Text and Safari.
=> Added UTF-8 byte-order mark to output streams from the REPL

qsu/src/main/scala/quasar/qsu/PruneSymmetricDimEdits.scala, qsu/src/main/scala/quasar/qsu/QSUGraph.scala, qsu/src/main/scala/quasar/qsu/RewriteGroupByArrays.scala, qsu/src/test/scala/quasar/qsu/PruneSymmetricDimEditsSpec.scala, qsu/src/test/scala/quasar/qsu/RewriteGroupByArraysSpec.scala
This was the issue with `replaceWithRename` that I referenced to @alissapajer 
[ch3067]
=> Fixed multi-path node removal/rename

qscript/src/main/scala/quasar/qscript/rewrites/Coalesce.scala, qscript/src/main/scala/quasar/qscript/rewrites/Normalizable.scala, qscript/src/main/scala/quasar/qscript/rewrites/Rewrite.scala, qscript/src/main/scala/quasar/qscript/rewrites/ThetaToEquiJoin.scala, qscript/src/main/scala/quasar/qscript/rewrites/Unirewrite.scala, qscript/src/test/scala/quasar/qscript/rewrites/RewriteSpec.scala, qscript/src/test/scala/quasar/qscript/rewrites/ThetaToEquiJoinSpec.scala
Depends on #3968 
What's remaining in `coalesceQC` are the rewrites that I'm expecting we'll need, along with the machinery to recurse into `FreeQS`. 
The plan forward (not in this PR) is threefold:
1) We can rewrite what is current `Coalesce` to act directly on `QScriptEducated`. This will remove the many lines of boilerplate machinery and make it easier to work within.
2) `Normalizable` is currently _also_ recursing into `FreeQS`, applying the entire `Rewrite` as well as `MapFunc` normalization (as well as possibly other rabbit hole atrocities). We need to centralize this recursion, and split out the `MapFunc` normalizations from the `Coalesce` normalizations. I think we'll be able to apply the `MapFunc` normalizations as a separate pass after we've coalesced nodes. Imagine two separate …
=> Delete unnecessary components of coalesceQC

impl/src/main/scala/quasar/impl/external/ExternalConfig.scala, project/Dependencies.scala, repl/src/main/scala/quasar/repl/Main.scala, repl/src/main/scala/quasar/repl/Paths.scala
With this you can start with plugins without any extracting into `~/.config/quasar/plugin`.
Just assemble the plugins with `datasourceAssemblePlugin`.
Example `repl/run` invocation from `sbt`:
`repl/run -P path-to/quasar-datasource-s3/datasource/target/scala-2.12/plugin-build/s3.plugin -P path-to/quasar-datasource-azure/datasource/target/scala-2.12/plugin-build/azure.plugin`
=> Allow plugin files to be specified in repl

yggdrasil/src/main/scala/quasar/yggdrasil/table/ColumnarTableModule.scala, yggdrasil/src/test/scala/quasar/yggdrasil/LeftShiftSpec.scala, yggdrasil/src/test/scala/quasar/yggdrasil/table/ColumnarTableModuleSpec.scala
The problem here is that we were computing the number of splits correctly (which should have really been more correctly named "number of output slices" or something like that), but the size of those splits was incorrect (we took the ceiling rather than the floor, for… no reason). This in turn meant that our rolling index offset drift off, and we could get negative slices out the other end.
[ch3773]
=> Alternative maths

.appveyor.yml, .travis.yml, build.sbt, foundation/src/test/scala/quasar/QuasarSpecification.scala, it/src/test/scala/quasar/regression/Sql2QueryRegressionSpec.scala, it/src/test/scala/quasar/regression/TestDirective.scala, project/plugins.sbt
Depends on #3997 
- Don't exclude typelevel scala dep
- Include `-Ybackend:GenBCode`
- Get rid of `isCIBuild` and `isIsolatedEnv` `BuildInfo`
=> Moar build cleanup

qsu/src/main/scala/quasar/qsu/minimizers/FilterToCond.scala, qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala
This does not close ch 366 since this doesn't introduce filtering `MapFunc`s. It simply uses `Typecheck` instead of `Cond` in `FilterToCond` when possible. To showcase what this does, consider the following query generated by the frontend:
```sql
SELECT c.c1 AS a, c.c2 AS b, c.c3 AS c, c.c4 AS d FROM ( 
SELECT p5.g7 AS c1, p5.g8  AS c2, p5.g9 AS c3, p5.g10 AS c4 
FROM (SELECT
(SELECT * FROM (SELECT ty.previous_addresses[_]{_} FROM `patients.data` AS ty) AS v WHERE type_of(v) = "string") AS g10, 
(SELECT * FROM (SELECT ty.previous_addresses[_].city FROM   `patients.data` AS ty) AS v WHERE  type_of(v) = "string") AS g7, 
(SELECT * FROM (SELECT ty.previous_addresses[_].state FROM   `patients.data` AS ty) AS v WHERE  type_of(v) = "string") AS g8, 
(SELECT * FROM (SELECT ty.last_visit FROM …
```
=> Use Typecheck instead of Cond when possible

qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala, qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala
Normally I would assign this to @jsantos17, but he's out and I'd like to get it in as soon as possible.
What this change does is build a recursive associativity rose trie grouping shifts at each level by parentage, and then subsequently by the linearized, de-`Guard`ed `FreeMap` which makes up the `struct`. We should probably adjust `elideGuards` to take `Typecheck` into account at some point, but I think it's probably still fine.
Once shift chains have been grouped together, the depth of the grouping check is incremented so we move *down* the chain (which is to say *up* the tree). We then perform the same operation at the next level. The concept behind this is you want to make sure that shifts are associated together at the top level if possible, but then if the next level separates them, …
=> Shift coalescence associativity.

qsu/src/main/scala/quasar/qsu/QScriptUniform.scala, qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala, qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala, run/src/test/scala/quasar/QScriptRegressionSpec.scala
Also note the extra change to the `QScriptRegressionSpec`: even before @wemrysi's rewrite lands, there are several queries which we can now push into tectonic which we previously could not.
[ch4703]
=> Fixed collapsing compatible shifts below the top tier

qsu/src/main/scala/quasar/qsu/minimizers/CollapseShifts.scala, qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala, run/src/test/scala/quasar/QScriptRegressionSpec.scala
The two conceptual changes here are:
- Use provenance's structural normalization and compare for compatibility based on `struct >> parent.repair` whenever relevant, rather than just using `struct`
- Account for the structural differences introduced by `IncludeIds` versus `IdOnly`/`ExcludeId` by "faking" a projection in the provenance prior to comparison
Note that both of these adjustments were only applied to `LeftShift`, ignoring `MultiLeftShift` altogether. This is true both for the collapse of zipping `LeftShift`s *and* when those shifts are direct descendants of a `MultiLeftShift`. These fixes are, at least theoretically, compatible with the `MultiLeftShift` structure, but in the interests of time we're ignoring that. Basically, once you get into `Multi`-land, you're hosed.
[ch4758]
=> Better identify compatible shifts

qsu/src/main/scala/quasar/qsu/ExpandShifts.scala
Not sure if we still need the `MonadCI` constraint since we no longer call `get` on it anywhere. Shall I remove that too?
=> Remove join-condition related side effects

common/src/main/scala/quasar/common/package.scala, qsu/src/main/scala/quasar/qsu/LPtoQS.scala
`WriterT` isn't a logger. It never was. The fact that we're calling `RenderTree` on giant qscripts in production code paths is… very broken.
[ch5234]
=> Made PhaseResults lazy (using Eval) to tree logging costs in production

impl/src/main/scala/quasar/impl/datasource/local/EvaluableLocalDatasource.scala, impl/src/main/scala/quasar/impl/datasources/SimpleCompositeResourceSchema.scala, impl/src/test/scala/quasar/impl/datasources/SimpleCompositeResourceSchemaSpec.scala, run/src/main/scala/quasar/run/Quasar.scala
Support for aggregated resource querying that does not return `source`. The child query results are simply concatenated.
Local datasource now excludes hidden files as resources. Otherwise .DS_Store prevents local datasource from working with aggregated resource querying.
[ch4298]
=> Prepare for aggregated resource querying

frontend/src/test/scala/quasar/ScalarStageSpec.scala
Adds new tests, as well as all three `IdStatus` cases for all the `Pivot`-only tests.
=> more scalar stages tests

frontend/src/test/scala/quasar/ScalarStageSpec.scala
No tests were actually deleted; they were only moved.
=> all the `Pivot . *` cases (Object/Array) (IncludeId/ExcludeId/IdOnly)

datagen/src/main/scala/quasar/datagen/Main.scala, datagen/src/main/scala/quasar/datagen/dist.scala, datagen/src/main/scala/quasar/datagen/generate.scala
Fixes for a couple issues in `datagen` uncovered by attempting to generate data from a real-world SST.
Also adds some rudimentary parallelism to help reduce generation time for large datasets.
[ch6234]
=> Fixes for datagen

foundation/src/main/scala/quasar/contrib/cats/boolean.scala, foundation/src/main/scala/quasar/contrib/cats/data/nonEmptySet.scala, qsu/src/main/scala/quasar/qsu/Graduate.scala, qsu/src/main/scala/quasar/qsu/ReifyIdentities.scala, qsu/src/main/scala/quasar/qsu/mra/Identities.scala, qsu/src/main/scala/quasar/qsu/mra/JoinKeys.scala, qsu/src/main/scala/quasar/qsu/mra/ProvImpl.scala, qsu/src/main/scala/quasar/qsu/mra/Uop.scala, qsu/src/test/scala/quasar/qsu/mra/IdentitiesSpec.scala, qsu/src/test/scala/quasar/qsu/mra/JoinKeysGenerator.scala, qsu/src/test/scala/quasar/qsu/mra/ProvImplSpec.scala, qsu/src/test/scala/quasar/qsu/mra/UopSpec.scala
We were representing `Uop` with a `List` to try and avoid needing an `Order` instance for `Identities`, however it turned out to be straightforward to implement the latter, so we can now use a `SortedSet` for `Uop` which results in better performance and fixing the issue with `Cogen`.
[ch7021]
=> Change Uop repr to a SortedSet

impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
Even under high load I'm unable to reproduce the flakiness in `DefaultResultPushSpec` locally. So I'm opening this PR to test with Travis directly.
=> Increase latchGet timeout

api/src/main/scala/quasar/api/destination/Destination.scala, api/src/main/scala/quasar/api/destination/Destinations.scala, api/src/main/scala/quasar/api/destination/ResultSink.scala, connector/src/main/scala/quasar/connector/DestinationModule.scala, impl/src/main/scala/quasar/impl/datasource/local/LocalDestination.scala, impl/src/main/scala/quasar/impl/datasource/local/LocalDestinationModule.scala, impl/src/main/scala/quasar/impl/destinations/DefaultDestinationManager.scala, impl/src/main/scala/quasar/impl/destinations/DefaultDestinations.scala, impl/src/main/scala/quasar/impl/destinations/DestinationManager.scala, impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala, impl/src/test/scala/quasar/impl/destinations/DefaultDestinationManagerSpec.scala, impl/src/test/scala/quasar/impl/destinations/DefaultDestinationsSpec.scala, impl/src/test/scala/quasar/impl/destinations/MockDestination.scala, impl/src/test/scala/quasar/impl/destinations/MockDestinations.scala, impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala, run/src/main/scala/quasar/run/Quasar.scala
[ch8932]
This also moves `ResultSink` and `Destination` from `quasar.connector` to `quasar.api.push`. This was in order to add `destinationOf` in `quasar.api.destination.Destinations`. In a subsequent PR I will use `destinationOf` to wire the result push HTTP API
=> Initialize destinations on first use

api/src/main/scala/quasar/api/push/RenderConfig.scala
Some destinations don't correctly handle the utf-8 byte order mark, so we need the ability to remove it.
=> Added BOM configuration parameter to RenderConfig.Csv

foundation/src/main/scala/quasar/numeric/NumericConversions.scala
Copied these over from https://github.com/slamdata/scion/blob/master/core/src/main/scala/scion/DataUtil.scala. I'm going to need access to them in the api datasource. Will delete the scion versions after this lands.
=> add numeric conversions

impl/src/main/scala/quasar/impl/parsing/ResultParser.scala, impl/src/test/scala/quasar/impl/datasource/CountBoolPlate.scala, impl/src/test/scala/quasar/impl/datasources/CompositeResourceSchemaSpec.scala, impl/src/test/scala/quasar/impl/datasources/SimpleCompositeResourceSchemaSpec.scala
[ch9430]
These additions will be deleted when new schema go into production, but in case data-based pagination lands before new schema, we include support for `Stateful` in old ssts.
This implementation is nearly identical to https://github.com/slamdata/scion/pull/200
=> handle QueryResult.Stateful in ssts

impl/src/main/scala/quasar/impl/datasource/local/LocalStatefulDatasource.scala, impl/src/main/scala/quasar/impl/parsing/ResultParser.scala, impl/src/test/scala/quasar/impl/datasources/CompositeResourceSchemaSpec.scala, impl/src/test/scala/quasar/impl/datasources/SimpleCompositeResourceSchemaSpec.scala
and ensure only one stateful plate is created in the sst stateful impl
**breaking** because the mimir integration tests fail against this patch (the mimir evaluator requires a change analogous to how ssts are changed here)
=> create the stateful plate within the effect in the local ds

foundation/src/main/scala/quasar/contrib/proxy/Search.scala
I have confirmed this works with the frontend. [Green frontend build here](https://travis-ci.com/slamdata/slamx/builds/131846875).
@djspiewak I have replaced the proxy-vole configuration with the defaults. Would you mind explaining the rationale used to pick the defaults we had before this PR?
=> Use default settings for ProxySearch

qsu/src/main/scala/quasar/qsu/mra/ProvImpl.scala, qsu/src/test/scala/quasar/qsu/mra/ProvImplSpec.scala, qsu/src/test/scala/quasar/qsu/mra/ProvenanceSpec.scala, qsu/src/test/scala/quasar/qsu/mra/VecsGenerator.scala
This preserves the provenance contributed by the injected values while curbing unbounded growth of the vector set in the presence of many operations on arguments which have overlapping provenance.
[ch10353]
=> Terminate provenance identity vectors when projecting non-matching injects

impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
The underlying stream of statuses being inspected only ever produced one element. If that element wasn't the matching one, then the stream errored. This wasn't the intent, instead we want to keep producing statuses as demanded and only error the stream if we timeout before seeing the element we're interested in.
[ch10816]
=> Fix flaky test in DefaultResultPushSpec

qsu/src/test/scala/quasar/qsu/ApplyProvenanceSpec.scala, qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala, sql/src/test/scala/quasar/sql/SqlParserSpec.scala
Reduces qsu/test compile times by ~90s locally.
=> Cache implicits in qsu tests to improve compile times

README.md, impl/src/main/scala/quasar/impl/CachedGetter.scala, impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala, impl/src/main/scala/quasar/impl/destinations/DefaultDestinations.scala, impl/src/main/scala/quasar/impl/scheduler/DefaultSchedulers.scala, impl/src/test/scala/quasar/impl/CachedGetterSpec.scala, impl/src/test/scala/quasar/impl/datasources/DefaultDatasourcesSpec.scala, impl/src/test/scala/quasar/impl/destinations/DefaultDestinationsSpec.scala, impl/src/test/scala/quasar/impl/destinations/MockDestination.scala, impl/src/test/scala/quasar/impl/scheduler/DefaultSchedulersSpec.scala
Fixes a bug in all the plugin managers that allowed unvalidated plugin refs to be saved when replacing an existing ref.
[ch10943]
=> Avoid persisting unvalidated plugin refs

impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
Previously, the examples that were testing conflict handling would start two pushes in sequence and expect the first to succeed and the second to fail. However, since starting is async, it was possible for the second job to win and the first to fail, causing unexpected build failures.
This remedies the situation by awaiting some output from the first job before starting the second.
[ch11255]
[ch11277]
=> Await first push when testing conflict handling for DefaultResultPush

build.sbt, project/Versions.scala
Add azure-core-http-netty dependency as workaround. If this dependency is not added then Azure cannot find any implementation of HttpClientProvider.
Part of ch11156
Marked as `breaking` because this PR is needed to get the Azure dependent datasources and destinations relying on https://github.com/precog/async-blobstore/pull/98 (upgrade to Azure SDK v12) working, so those plugins. At the same time plugin versions that are relying on Azure SDK v10 won't work anymore with this PR. 
So quasar and all the Azure dependent plugins need to support the same Azure SDK version.
=> Upgrade to Azure SDK v12

impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
```
...
[info] cancel all                                                                                                                                                                                                             pt_
[info]   o aborts all running pushes (0 ms)
[info] SKIPPED                                                                                                                                                                                                                pt_
[info]   o no-op when no running pushes (0 ms)
[info] SKIPPED                                                                                                                                                                                                                pt_
[info] Total for …
```
=> skip all tests in DefaultResultPushSpec

impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
Released as `177.0.1-ed3252c`
`datasourceRef` has `"<REDACTED>"` in credentials.
=> no need in sanitation when applying patch

impl/src/main/scala/quasar/impl/datasources/DefaultDatasources.scala
Due to how cached getter updates when read, it had a stale value post-replace. Accessing the getter after the replace causes it to update to the current state of the system.
=> Updated cached getter after datasource replace

foundation/src/main/scala/quasar/contrib/fs2/expect.scala, foundation/src/test/scala/quasar/contrib/fs2/ExpectSpec.scala
This is a tiny little utility which gives us the ability to assert that a stream should be a particular length and then recover (or produce an error) if it isn't, either because it's too small or too large. This can be used in the S3 connector, for example, to read the `Content-Range` header in the response and then assert that the `body` has the appropriate number of bytes. Or in a more advanced implementation, if the `body` does *not* have the appropriate number of bytes, rather than raising an error, it could simply make a new request to S3 using the `Range` header parameter, resuming exactly where the stream left off.
=> Added stream size expectation utility

api/src/main/scala/quasar/api/push/param/ParamError.scala, connector/src/main/scala/quasar/connector/destination/Constructor.scala, impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala, impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
Also renames `RedundantParams` to `ExcessiveParams` and changes param validation to accumulate errors for all params.
[ch11630]
=> Add ternary dest type constructor

connector/src/main/scala/quasar/connector/ResourceError.scala
This is the first PR implementing ch10728.
This is an error raised when Quasar asked for a seek, but we could not perform it. Before the introduction of CDC, we could handle pushdown evaluation errors by simply returning the unevaluated `ScalarStages` and letting Quasar handle evaluation. However, this is no longer appropriate when we're asked to seek and fail.
`version: breaking` because it needs handling in sdbe.
=> Add SeekFailed error

impl/src/main/scala/quasar/impl/storage/VoidStore.scala
I knew I forgot something! 🤦‍♂️ 
Fixes mimir's integration tests. 
Revision, since `mvstore/v1` hasn't propagated yet
=> VoidStore should be PrefixStore.SCodec

core/src/main/scala/quasar/compile/Compiler.scala, foundation/src/main/scala/quasar/contrib/iota/LazyEqualKMaterializer.scala, foundation/src/main/scala/quasar/contrib/matryoshka/LazyEqual.scala, foundation/src/main/scala/quasar/contrib/matryoshka/implicits.scala, qscript/src/main/scala/quasar/qscript/MapFuncCore.scala, qscript/src/main/scala/quasar/qscript/MapFuncDerived.scala, qsu/src/main/scala/quasar/qsu/ApplyProvenance.scala, qsu/src/test/scala/quasar/qsu/ExtractFreeMapSpec.scala, qsu/src/test/scala/quasar/qsu/GraduateSpec.scala, qsu/src/test/scala/quasar/qsu/LPtoQSSpec.scala, qsu/src/test/scala/quasar/qsu/MinimizeAutoJoinsSpec.scala, qsu/src/test/scala/quasar/qsu/PruneSymmetricDimEditsSpec.scala, qsu/src/test/scala/quasar/qsu/ReadLPSpec.scala, qsu/src/test/scala/quasar/qsu/ReifyAutoJoinsSpec.scala, qsu/src/test/scala/quasar/qsu/RewriteGroupByArraysSpec.scala
We need a trampolined monad to avoid SOE when compiling very large queries.
[ch11344]
[ch12247]
=> Replace all usage of scalaz.Need with cats.Eval

.versions.json, impl/src/main/scala/quasar/impl/Quasar.scala, impl/src/main/scala/quasar/impl/push/DefaultResultPush.scala, impl/src/test/scala/quasar/impl/push/DefaultResultPushSpec.scala
This allows us to independently decide how many datasets to load concurrently and how many to allow to be enqueued before blocking.
=> Separate configuration of push concurrency and total pushes

build.sbt, project/Versions.scala
Seems there may be a different issue with AHC client in the latest http4s, reverting back to Precog's version until we can fix upstream.
=> Revert http4s to Precog's 0.21.2

connector/src/main/scala/quasar/connector/render/RenderConfig.scala
We'll probably want something like `ColumnRender` for CSV rendering, but this will suffice for now.
Some destinations expect numeric values to confirm to the maximum allowed scale.
=> Add numeric scale to CSV rendering

build.sbt
... so that they match the versions used in Azure SDK. Part of ch12535
=> Bump netty and azure-core-http-netty

impl/src/main/scala/quasar/impl/cluster/Timestamped.scala, impl/src/main/scala/quasar/impl/storage/TimestampedStore.scala, impl/src/test/scala/quasar/impl/storage/AntiEntropyStoreSpec.scala, impl/src/test/scala/quasar/impl/storage/TimestampedStoreSpec.scala
When we want to use `TimestampedStore` in an unclustered server and aren't consuming the `updates` stream, the default bounded queue will eventually fill up and block modifications. To support this case, I've added a new variant of `TimestampedStore`, based on a circular buffer, that will never block modifications.
=> Variant of TimestampedStore that never blocks on modify

foundation/src/main/scala/quasar/RateLimiter.scala, foundation/src/main/scala/quasar/RateLimiterEffects.scala, foundation/src/test/scala/quasar/RateLimiterSpec.scala
This is the first piece required to support [Facebook rate limiting](https://developers.facebook.com/docs/graph-api/overview/rate-limiting/).
The main difference is that Facebook will provide us with a limit rather so we don't need to count the requests/events we make. This will be followed with another PR implementing the Facebook-specific code in the URL datasource.
[ch13331]
=> Support external window usage updates
